### ISSUE TITLE
Python Server API and H2/TLS framing

### ISSUE THREAD

**Issue by worenga** [nghttp2/nghttp2#1004]
I use the following python script to test some way of delivering my css interleaved with the HTML (just a fiddle).
https://gist.github.com/worenga/4c50468f143f11adb956f7063c9de887

However, using wireshark i noticed, that each HTTP/2 frame is put into a individual TLS segment, which (in this simple example) is quite wasteful since DATA frames are quite small + slow start. 

I was wondering whether there is an option to aggregate multiple HTTP/2 frames into bigger TLS frames as it is done by e.g. the h2o server.

**Comment by tatsuhiro-t** [comment]
Python implementation is not optimized yet.  https://github.com/nghttp2/nghttp2/blob/4be4c0cddc6edd87bd3f748e50cd60fd1497f012/python/nghttp2.pyx#L706 we write a frame to the transport object per frame.  If self.transport.write creates TLS record for each write, it leads to suboptimal small TLS record size.  It might be better to concatenate several frames before writing them into transport.  It costs extra copying, but probably reduces TLS overhead.

**Comment by tatsuhiro-t** [comment]
Closed since python bindings have been removed.
