### ISSUE TITLE
OCSP Stapling doesn't show in SSLlabs report or openssl

### ISSUE THREAD

**Issue by RobBelics** [nghttp2/nghttp2#1005]
I was happy I quickly got nghttpx working with one domain and default configuration on FreeBSD-RELEASE-11.1 so I plowed ahead to put two others over to nghttpx with h2o on the backend and all on the same IP. This all works but I went to ssllabs to do a check and it says OCSP stapling is not on. So I tried 

`openssl s_client -connect a.com:443 -tls1 -tlsextdebug -status`

and this says "no peer certificate available" and the SSL handshake does not work. Otherwise I get a A+ rating for everything else on all three of those sites.

I'm sure I'm doing something wrong. I tried adding `cacert=/usr/local/etc/letsencrypt/live/a.com/cacert.pem` because the doc talks about needing the cacert but that didn't help. So I don't know what I'm doing wrong.
```
backend=127.0.0.1,8080;a.com
backend=127.0.0.1,8081;b.com
backend=127.0.0.1,8082;c.com
backend=127.0.0.1,80

frontend=xxx.xxx.xxx.xxx,443

private-key-file=/usr/local/etc/letsencrypt/live/a.com/privkey.pem
certificate-file=/usr/local/etc/letsencrypt/live/a.com/fullchain.pem

subcert=/usr/local/etc/letsencrypt/live/b.com/privkey.pem:/usr/local/etc/letsencrypt/live/b.com/fullchain.pem
subcert=/usr/local/etc/letsencrypt/live/c.com/privkey.pem:/usr/local/etc/letsencrypt/live/c.com/fullchain.pem

#cacert=/usr/local/etc/letsencrypt/live/a.com/cacert.pem

# Logs
accesslog-file=/var/log/nghttpx-access.log
errorlog-file=/var/log/nghttpx-error.log

# Record where the requests came from
strip-incoming-x-forwarded-for=yes
add-x-forwarded-for=yes
strip-incoming-forwarded=yes
add-forwarded=by,for,host,proto

# Don't hash forwarded-for stuff, use the actual information
forwarded-by=ip
forwarded-for=ip
```
Now I missed this somehow, and haven't investigated yet, but in the error.log there is:
`WARN (shrpx_connection_handler.cc:610) ocsp query command for /usr/local/etc/letsencrypt/live/b.com/fullchain.pem failed: error=0, rstatus=100, status=1`

**Comment by tatsuhiro-t** [comment]
> openssl s_client -connect a.com:443 -tls1 -tlsextdebug -status

By default, nghttpx enables TLSv1.2 only.  -tls1 option forces openssl s_client to use TLSv1.0, and handshake fails because of no shared version.

As for "ocsp query command ... failed", `log-level=INFO` gives you full logging.  I think it can show more useful info.

This might not be related, but ocsp certificate verification is a bit flaky.  I'm considering to remove it.  If it is the cause of your issue, try `no-verify-ocsp=yes`

**Comment by RobBelics** [comment]
Thank you. Yes, I shouldn't have the -tls in there. Removing that and rerunning still does not give an OCSP response and adding the log level change does not give any new information. However, I just noticed that the install from FreeBSD ports has `--disable-python-bindings` in the Makefile. Since the fetch-ocsp-file program uses Python, I wonder if that's where the issue lies in this case, ignoring your concern about ocsp verification. I'll look into the Python issue.

**Comment by tatsuhiro-t** [comment]
Thank you for prompt reply.  I think --disable-python-bindings is not a problem.  fetch-ocsp-response is Python script, so you just need python interpreter to make OCSP work.

**Comment by RobBelics** [comment]
I found the issue and it was with the FreeBSD port. The Python script 'fetch-ocsp-response` was missing the `#!/usr/bin/env` on the first line of the file. By entering that, along with the proper python version, I was able to get ocsp stapling to work. 

I have reported it to the maintainer of the FreeBSD port and it should be fixed shortly.
