### ISSUE TITLE
gzip and brotli static files on back end server don't get passed through

### ISSUE THREAD

**Issue by RobBelics** [nghttp2/nghttp2#1007]
I set up nghttpx on the front end with h2o on the back end. (I'm still getting my feet wet with nghttp2.) Before I put h2o behind nghttpx, the static files served by h2o were sent to the browser as either a gz or br file previously compressed. When I look at how they're served with nghttpx on the front end, I get the original uncompressed static files such as html/css/js/etc. 

Where is the request for encoding getting lost?

**Comment by tatsuhiro-t** [comment]
As far as I know, nghttpx does not remove any accept-encoding header fields in HTTP request.
Using -LINFO option logs HTTP request from the client, and the 2nd request to the backend.  Can you find accept-encoding is missing in both requests?

**Comment by RobBelics** [comment]
In the conf file I use `log-level=INFO`. You can read that portion of a request to my personal web site here: `https://belics.com/nghttpx.txt`

**Comment by tatsuhiro-t** [comment]
Thank you.  I found that "Accept-Encoding: gzip, deflate, br" was correctly forwarded to the backend server.
In my local test setup, I can get gzipped content via nghttpx, so it should work.
Do you get compressed object by using the backend post request  in the log?  You can find it in the log after like `... [DCONN:0x28d25900] HTTP request headers. stream_id=15`.   Please remove `^M` which is 0x0d.

**Comment by RobBelics** [comment]
I don't know what you mean by your question. What I show is from the access log. The `^M` is also in the access log. If nghttpx is not inserting that, then there may be further issues with my FreeBSD version similar to what I found in my previous posting.

**Comment by RobBelics** [comment]
I found the issue and it was my fault. Somehow I deleted `file.send-compressed: on` from h2o.conf. Everything is working great now.
