### ISSUE TITLE
Reconnect automatically with nghttp2_asio

### ISSUE THREAD

**Issue by portsip** [nghttp2/nghttp2#1010]
Hi, when I created  the ghttp2::asio_http2::client::session, it will perform the connect automatically, and the session::on_connect and session::on_error will be triggered if connected or failed.

My question is: if failed to connect(for example, the network timeout), how can I let the session retry  to connect ? Must I delete the session and create a new session ?

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
