### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by portsip** [nghttp2/nghttp2#1011]
I would like to provide some suggestions for the nghttp2_asio.

1. It's good if there has a function "reconnect" to nghttp2::asio_http2::client::session, use it to re-connect to server if the connection is break.

Currently we can only perform the connect in the constructor. We have to delete the session and create it again if the connection is break(for example, the network connection is lost and resume after a while)

2. It's possible to add a status_code parameter to the response::on_data callback ?

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
