### ISSUE TITLE
h2load HTTP/2 --verbose is not showing any header out put compared to use with --h1 option

### ISSUE THREAD

**Issue by mkrug1981** [nghttp2/nghttp2#1015]
As we can see for a HTTP/2 test with '--verbose' mode is NOT showing any debug output like response header compared to use case with '--verbose --h1'
Not sure if I'm doing something wrong would it would be really good to see such output for HTTP/2 as well.
Besides that is there a way to print out as well request and response headers along with statistics into a file?

For testing I have picked a random domain
*** HTTP/2 request
h2load --client=1 --requests=1 https://int-cdn.drsddn.com/ --verbose
starting benchmark...
spawning thread #0: 1 total client(s). 1 total requests
TLS Protocol: TLSv1.2
Cipher: ECDHE-RSA-AES128-GCM-SHA256
Server Temp Key: ECDH P-256 256 bits
Application protocol: h2
progress: 100% done

finished in 597.71ms, 1.67 req/s, 359B/s
requests: 1 total, 1 started, 1 done, 1 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 1 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 215B (215) total, 148B (148) headers (space savings 30.84%), 0B (0) data
                     min         max         mean         sd        +/- sd
time for request:   151.02ms    151.02ms    151.02ms         0us   100.00%
time for connect:   445.13ms    445.13ms    445.13ms         0us   100.00%
time to 1st byte:        0us         0us         0us         0us     0.00%
req/s           :       1.68        1.68        1.68        0.00   100.00%

*** HTTP/1.1 request
h2load --client=1 --requests=1 https://int-cdn.drsddn.com/ --verbose --h1
starting benchmark...
spawning thread #0: 1 total client(s). 1 total requests
TLS Protocol: TLSv1.2
Cipher: ECDHE-RSA-AES128-GCM-SHA256
Server Temp Key: ECDH P-256 256 bits
Application protocol: http/1.1
progress: 100% done
HTTP/1.1 200 OK
Date: Tue, 19 Sep 2017 08:44:16 GMT
Content-Type: text/html
Content-Length: 0
Connection: keep-alive
Accept-Ranges: bytes
Server: Oracle-Application-Server-11g Oracle-Web-Cache-11g/11.1.1.3.0
Age: 42902
Last-Modified: Tue, 18 Aug 2015 07:40:48 GMT

finished in 607.96ms, 1.64 req/s, 452B/s
requests: 1 total, 1 started, 1 done, 1 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 1 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 275B (275) total, 224B (224) headers (space savings 0.00%), 0B (0) data
                     min         max         mean         sd        +/- sd
time for request:   148.09ms    148.09ms    148.09ms         0us   100.00%
time for connect:   458.44ms    458.44ms    458.44ms         0us   100.00%
time to 1st byte:        0us         0us         0us         0us     0.00%

**Comment by tatsuhiro-t** [comment]
There is no feature to write information in file.  You can redirect the output to the file, or do you want structured data like json?
