### ISSUE TITLE
any other way to mod http response other than mruby

### ISSUE THREAD

**Issue by humiaozuzu** [nghttp2/nghttp2#1021]
I need to hide mod http response code to prevent my ssl proxy server been detected.

My nghttpx backend is squid with http basic auth, and there is no way to modify the default behaviour in squid config. When someone connect to my nghttpx server with bad 'proxy-authorization' info, my server will response 407 so they know that this is a proxy server.

**Comment by tatsuhiro-t** [comment]
How about enabling client certificate authentication?
