### ISSUE TITLE
support header affinity load balance

### ISSUE THREAD

**Issue by ccl0326** [nghttp2/nghttp2#1024]
I know nghttp2 support client ip affinity for load balance.
But we want to use special header filed, we want to load balance the requests from same client to multiple upstreams with affinity.
Does nghttp2 has plan for it?

**Comment by tatsuhiro-t** [comment]
I didn't know this kind of affinity settings.  Is there any specification to make it work?

**Comment by ccl0326** [comment]
I think the sticky feature of session affinity for load balance in nginx is our requirement.

http://nginx.org/en/docs/http/ngx_http_upstream_module.html#server

**Comment by tatsuhiro-t** [comment]
Do you mean cookie based affinity?

**Comment by ccl0326** [comment]
@tatsuhiro-t yep~

**Comment by tatsuhiro-t** [comment]
#1036 adds cookie based session affinity.
@ccl0326 Could you test it out?

**Comment by ccl0326** [comment]
@tatsuhiro-t Sure~
