### ISSUE TITLE
Often get "short read" error in asio client example

### ISSUE THREAD

**Issue by Domain** [nghttp2/nghttp2#1026]
I use libnghttp2_asio to push message to iOS APN.
I use the code from here: [https://stackoverflow.com/questions/42837218/nghttp2-asio-connecting-to-apple-push-notification-times-out](https://stackoverflow.com/questions/42837218/nghttp2-asio-connecting-to-apple-push-notification-times-out)
But I often get "short read" error (80%), sometime is's OK (20%)

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
