### ISSUE TITLE
WebExtensions API in Firefox - Causes browser lockup with latest version of nghttpx

### ISSUE THREAD

**Issue by yegors** [nghttp2/nghttp2#1030]
We use nghttpx as a forwarding proxy, with squid + radius auth as the backend. We recently upgraded 1.9.1 to 1.26.0 which is causing unexpected behavior - it locks up the browser networking and requires a restart. 

This only occurs when using the WebExtensions API and does NOT occur with the old API which is being deprecated, nor does it occur in Chrome. 

The root cause appears to be when the proxy hostname is accessed directly, previously it returned a 400 error. Now the behavior has changed, and it returns a 407. This seems to cause an infinite loop, which locks up the networking component in Firefox 56, 57, 58 nightly. 

Is there a way to revert to old behavior, so it returns a 400 error? I realize this is a Firefox bug, but getting it fixed by Mozilla may take a while, and FF57 is being released in under 1 month, which deprecates the old API.

Response headers from 1.9.1

```
                            HTTP/1.1 400 Bad Request
                            Server: nghttpx nghttp2/1.9.2
                            Content-Length: 143
                            Date: Wed, 18 Oct 2017 18:56:22 GMT
                            Content-Type: text/html; charset=UTF-8
                            Connection: close
```

Response headers from 1.26.1

```
                           HTTP/1.1 407
                           status: 407
                           mime-version: 1.0
                           date: Wed, 18 Oct 2017 18:55:22 GMT
                           content-type: text/html;charset=utf-8
                           content-length: 12929
                           x-squid-error: ERR_CACHE_ACCESS_DENIED 0
                           vary: Accept-Language
                           content-language: en-us
                           proxy-authenticate: Basic realm="Web-Proxy"
                           server: squid/3.5.12
```

It seems before the requests never reached the backend, however now they do, which throws a 407 error and causes an infinite loop.

**Comment by tatsuhiro-t** [comment]
Could you tell me how to reproduce this?

**Comment by yegors** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1409858

1.26.1 - locks up the browser
```
function FindProxyForURL(url, host) {
                    return "HTTPS ro-003.windscribe.com";
}
```

1.9.1 - behaves correctly
```
function FindProxyForURL(url, host) {
                    return "HTTPS ro-002.windscribe.com";
}
```

**Comment by tatsuhiro-t** [comment]
There are too many changes between v1.9.1 and v1.26.0.  Could you find the exact version which introduced this issue?  Perhaps, bisecting nghttpx build?
