### ISSUE TITLE
Expose TLS-related variables to MRuby script

### ISSUE THREAD

**Issue by arcivanov** [nghttp2/nghttp2#1031]
NGINX exposes tons of SSL-related variables, which are generally also available in the lua scripts in openresty. No such variables are available in nghttpx except for `tls_used` and `tls_sni`.

Ideally all the variables from NGINX should be implemented but at a minimum an ability to see `ssl_client_fingerprint` and `ssl_client_i_dn` to see who is connecting should be available.

The use case is client TLS authentication.

https://nginx.org/en/docs/http/ngx_http_ssl_module.html#variables

**Comment by tatsuhiro-t** [comment]
#1037 adds SHA-256 client fingerprint, and client subject name to mruby Env object.

**Comment by tatsuhiro-t** [comment]
The following extra TLS related attributes are added to Env object:

* tls_client_fingerprint
* tls_client_subject_name
*  tls_cipher
*  tls_protocol
*  tls_session_id
*  tls_session_reused
*  alpn

**Comment by arcivanov** [comment]
I would appreciate a SHA-1 fingerprint as well.

**Comment by tatsuhiro-t** [comment]
I did.

**Comment by arcivanov** [comment]
Thanks so much! This is great!

**Comment by rpraveen** [comment]
@tatsuhiro-t this is awesome! Thanks for implementing this. Can we also add a 'tls_client_serial'? We use the client cert serial number in the backend to query the CA (the serial is better suited for lookup than the fingerprint). I'd be happy to send a patch if you prefer that.

**Comment by tatsuhiro-t** [comment]
@rpraveen #1060

**Comment by rpraveen** [comment]
Thanks a ton @tatsuhiro-t. That was fast! Appreciate your help!
