### ISSUE TITLE
okhttp client can not connect nghttp2 server

### ISSUE THREAD

**Issue by onesea** [nghttp2/nghttp2#1032]
it fails to connect via h2, seemed trying http 1.1. what is wrong?

**Comment by tatsuhiro-t** [comment]
What kind of error did you get?  Have you reported to okhttp project?

**Comment by onesea** [comment]
it turned out be okhttp/jdk's alpn problem

**Comment by tatsuhiro-t** [comment]
OK, let's close the issue.
