### ISSUE TITLE
Compiling on CentOS release 6.8 (Final) is failing

### ISSUE THREAD

**Issue by z180602** [nghttp2/nghttp2#1033]
Hi!
I will with h2load,but have some problem in install nghttp2:
./configure  PKG_CONFIG_PATH=/usr/local/lib/pkgconfig --prefix=/usr/local/nghttp2 --enable-app

configure: summary of build options:

    Package version: 1.27.0
    Library version: 28:0:14
    Install prefix:  /usr/local/nghttp2
    System types:
      Build:         x86_64-unknown-linux-gnu
      Host:          x86_64-unknown-linux-gnu
      Target:        x86_64-unknown-linux-gnu
    Compiler:
      C compiler:     gcc
      CFLAGS:         -g -O2
      LDFLAGS:        
      C++ compiler:   g++
      CXXFLAGS:       -g -O2
      CXXCPP:         g++ -E
      C preprocessor: gcc -E
      CPPFLAGS:       
      WARNCFLAGS:     
      WARNCXXFLAGS:   
      CXX1XCXXFLAGS:   -std=c++0x
      EXTRACFLAG:     -fvisibility=hidden
      LIBS:           
    Library:
      Shared:         yes
      Static:         yes
    Python:
      Python:         /usr/bin/python
      PYTHON_VERSION: 
      pyexecdir:      
      Python-dev:     no
      PYTHON_CPPFLAGS:
      PYTHON_LDFLAGS: 
      Cython:         
    Test:
      CUnit:          yes (CFLAGS='-I/root/CUnitHome/include/CUnit' LIBS='-L/root/CUnitHome/lib -lcunit')
      Failmalloc:     yes
    Libs:
      OpenSSL:        yes (CFLAGS='-I/usr/include/openssl' LIBS='-L/usr/lib -lssl -lcrypto')
      Libxml2:        yes (CFLAGS='' LIBS='-L/usr/local/lib -lxml2  ')
      Libev:          yes (CFLAGS='' LIBS='-lev')
      Libc-ares       yes (CFLAGS='-I/usr/local/include' LIBS='-L/usr/local/lib -lcares')
      Libevent(SSL):  yes (CFLAGS='-I/usr/local/libevent-2.0.22/include/' LIBS='-L/usr/local/libevent-2.0.22/lib/ -levent_openssl -levent')
      Spdylay:        no (CFLAGS='-I/usr/local/spdylay-1.3.2/include/spdylay' LIBS='-L/usr/local/spdylay-1.3.2/lib -lspdylay')
      Jansson:        yes (CFLAGS='-I/usr/local/include  ' LIBS='-L/usr/local/lib -ljansson  ')
      Jemalloc:       yes (LIBS='-ljemalloc')
      Zlib:           yes (CFLAGS='-I/usr/include' LIBS='-L/usr/lib -lz')
      Systemd:        no (CFLAGS='' LIBS='')
      Boost CPPFLAGS: 
      Boost LDFLAGS:  
      Boost::ASIO:    
      Boost::System:  
      Boost::Thread:  
    Third-party:
      http-parser:    yes
      MRuby:          no (CFLAGS='' LIBS='')
      Neverbleed:     no
    Features:
      Applications:   yes
      HPACK tools:    yes
      Libnghttp2_asio:no
      Examples:       yes
      Python bindings:no
      Threading:      no

  
The error it self during make

make  all-recursive
make[1]: Entering directory `/root/nghttp2'
Making all in lib
make[2]: Entering directory `/root/nghttp2/lib'
Making all in includes
make[3]: Entering directory `/root/nghttp2/lib/includes'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/root/nghttp2/lib/includes'
make[3]: Entering directory `/root/nghttp2/lib'
  CC       nghttp2_pq.lo
  CC       nghttp2_map.lo
  CC       nghttp2_queue.lo
  CC       nghttp2_frame.lo
  CC       nghttp2_buf.lo
  CC       nghttp2_stream.lo
  CC       nghttp2_outbound_item.lo
  CC       nghttp2_session.lo
  CC       nghttp2_submit.lo
  CC       nghttp2_helper.lo
  CC       nghttp2_npn.lo
  CC       nghttp2_hd.lo
  CC       nghttp2_hd_huffman.lo
  CC       nghttp2_hd_huffman_data.lo
  CC       nghttp2_version.lo
  CC       nghttp2_priority_spec.lo
  CC       nghttp2_option.lo
  CC       nghttp2_callbacks.lo
  CC       nghttp2_mem.lo
  CC       nghttp2_http.lo
  CC       nghttp2_rcbuf.lo
  CC       nghttp2_debug.lo
  CCLD     libnghttp2.la
make[3]: Leaving directory `/root/nghttp2/lib'
make[2]: Leaving directory `/root/nghttp2/lib'
Making all in third-party
make[2]: Entering directory `/root/nghttp2/third-party'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/root/nghttp2/third-party'
Making all in src
make[2]: Entering directory `/root/nghttp2/src'
Making all in includes
make[3]: Entering directory `/root/nghttp2/src/includes'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/root/nghttp2/src/includes'
make[3]: Entering directory `/root/nghttp2/src'
  CXX      libnghttpx_a-util.o
In file included from util.h:52,
                 from util.cc:25:
template.h:60: error: expected constructor, destructor, or type conversion before ‘std’
template.h:69: error: expected constructor, destructor, or type conversion before ‘size_t’
template.h:73: error: expected constructor, destructor, or type conversion before ‘size_t’
template.h:82: error: expected ‘;’ before ‘noexcept’
template.h:83: error: expected ‘;’ before ‘~’ token
template.h:85: error: expected nested-name-specifier before ‘ResultType’
template.h:85: error: using-declaration for non-member at class scope
template.h:85: error: expected ‘;’ before ‘=’ token
template.h:85: error: expected unqualified-id before ‘=’ token
template.h:87: error: a function call cannot appear in a constant-expression
template.h:87: error: template argument 1 is invalid
template.h:107: error: expected ‘;’ before ‘noexcept’
template.h:113: error: expected ‘;’ before ‘DList’
template.h:113: error: expected ‘;’ before ‘noexcept’
util.cc:1524: error: expected ‘;’ at end of input
util.cc:1524: error: expected ‘}’ at end of input
In file included from util.h:52,
                 from util.cc:25:
template.h: In constructor ‘nghttp2::DList<T>::DList()’:
template.h:102: error: class ‘nghttp2::DList<T>’ does not have any field named ‘head’
template.h:102: error: ‘nullptr’ was not declared in this scope
template.h:102: error: class ‘nghttp2::DList<T>’ does not have any field named ‘tail’
template.h:102: error: class ‘nghttp2::DList<T>’ does not have any field named ‘len’
template.h: At global scope:
template.h:102: error: expected unqualified-id at end of input
template.h:102: error: expected ‘}’ at end of input
make[3]: *** [libnghttpx_a-util.o] Error 1
make[3]: Leaving directory `/root/nghttp2/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/nghttp2/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/nghttp2'
make: *** [all] Error 2

**Comment by z180602** [comment]
how to do,think you

**Comment by z180602** [comment]
how to do,thank you

**Comment by z180602** [comment]
My installation process:

#[sphinx] 
yum install sphinx -y

#[zlib]
wget http://www.zlib.net/zlib-1.2.11.tar.gz
tar fx zlib-1.2.11.tar.gz
cd zlib-1.2.11
./configure  
sed -i 's/^CFLAGS/& -fPIC/g' Makefile
make -j&& make install 
cd ..

#[libtool]
wget http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz
tar fx libtool-2.4.6.tar.gz
cd libtool-2.4.6
./configure  --prefix=/usr/local/libtool-2.4.6 && make && make install
mv /usr/bin/libtool /usr/bin/libtool.bak -f
mv /usr/bin/libtoolize /usr/bin/libtoolize.bak -f
mv /usr/share/aclocal/libtool.m4 /usr/share/aclocal/libtool.m4.bak -f
mv /usr/share/aclocal/ltoptions.m4 /usr/share/aclocal/ltoptions.m4.bak -f
mv /usr/share/aclocal/ltversion.m4 /usr/share/aclocal/ltversion.m4.bak -f
ln -s /usr/local/libtool-2.4.6/bin/libtool /usr/bin/libtool -f
ln -s /usr/local/libtool-2.4.6/bin/libtoolize /usr/bin/libtoolize -f 
\cp  /usr/local/libtool-2.4.6/share/aclocal/libtool.m4 /usr/share/aclocal -f
\cp  /usr/local/libtool-2.4.6/share/aclocal/ltoptions.m4 /usr/share/aclocal -f
\cp  /usr/local/libtool-2.4.6/share/aclocal/ltversion.m4 /usr/share/aclocal -f
cd ..

#[openssl]
yum install openssl-devel -y
wget https://www.openssl.org/source/openssl-1.0.2l.tar.gz
tar xvf openssl-1.0.2l.tar.gz
cd openssl-1.0.2l
./config --prefix=/usr/local/openssl --openssldir=/etc/ssl --libdir=lib shared zlib-dynamic
make depend && make 
make install
mv /usr/bin/openssl{,.bak} -f
mv /usr/include/openssl{,.bak} -f
ln -s /usr/local/openssl/lib/libssl.so /usr/local/lib64/libssl.so -f
ln -s /usr/local/openssl/bin/openssl /usr/bin/openssl -f
ln -s /usr/local/openssl/include/openssl /usr/include/openssl -f
ln -s /usr/local/openssl/lib/pkgconfig/openssl.pc /usr/local/lib/pkgconfig/ -f
\cp /usr/local/openssl/lib/pkgconfig/libssl.pc /usr/local/lib/pkgconfig/ -f
\cp /usr/local/openssl/lib/pkgconfig/libcrypto.pc /usr/local/lib/pkgconfig/ -f
strings /usr/local/lib64/libssl.so |grep OpenSSL
echo "/usr/local/openssl/lib" >> /etc/ld.so.conf
ldconfig -v
cd ..

#[gmp]
wget https://gmplib.org/download/gmp/gmp-6.1.1.tar.bz2
tar fx  gmp-6.1.1.tar.bz2
cd gmp-6.1.1
./configure --prefix=/usr/local/gmp-6.1.1
make -j 4
make install
cd ..
 
#[mpfr] 
wget http://ftp.gnu.org/gnu/mpfr/mpfr-3.1.4.tar.bz2
tar fx mpfr-3.1.4.tar.bz2
cd mpfr-3.1.4
./configure --prefix=/usr/local/mpfr-3.1.4 --with-gmp=/usr/local/gmp-6.1.1/
make -j 4
make install
cd ..

#[mpc]
wget http://www.multiprecision.org/mpc/download/mpc-0.8.2.tar.gz
tar fx mpc-0.8.2.tar.gz
cd mpc-0.8.2
./configure --prefix=/usr/local/mpc-0.8.2 --with-gmp=/usr/local/gmp-6.1.1/ --with-mpfr=/usr/local/mpfr-3.1.4/
make -j 4
make install
echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/gmp-6.1.1/lib:/usr/local/mpfr-3.1.4/lib:/usr/local/mpc-0.8.2/lib" >> /root/.bash_profile
source ~/.bash_profile
cd ..

#[gcc]
wget ftp://ftp.gnu.org/gnu/gcc/gcc-4.9.0/gcc-4.9.0.tar.gz
yum install gcc-c++ -y
tar fx gcc-4.9.0.tar.gz
cd gcc-4.9.0
./configure --prefix=/usr/local/gcc-4.9.0 --enable-threads=posix --disable-checking --disable-multilib --enable-languages=c,c++ --with-gmp=/usr/local/gmp-6.1.1/ --with-mpfr=/usr/local/mpfr-3.1.4/ --with-mpc=/usr/local/mpc-0.8.2/
make -j 4
make install
echo "export  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/gcc-4.9.0/lib" >> /root/.bash_profile
source ~/.bash_profile
cd ..

#[autoconf]
wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
tar fx autoconf-2.69.tar.gz 
cd autoconf-2.69
./configure  --prefix=/usr/local/autoconf-2.69 && make && make install
mv /usr/bin/autoconf /usr/bin/autoconf.bak -f
mv /usr/bin/autoheader /usr/bin/autoheader.bak  -f
mv /usr/bin/autom4te /usr/bin/autom4te.bak -f
mv /usr/bin/autoreconf /usr/bin/autoreconf.bak -f
ln -f -s /usr/local/autoconf-2.69/bin/autoconf /usr/bin/autoconf -f
ln -f -s /usr/local/autoconf-2.69/bin/autoheader /usr/bin/autoheader -f
ln -f -s /usr/local/autoconf-2.69/bin/autom4te /usr/bin/autom4te -f
ln -f -s /usr/local/autoconf-2.69/bin/autoreconf /usr/bin/autoreconf -f
cd ..

#[automake]
wget http://ftp.gnu.org/gnu/automake/automake-1.15.tar.gz
tar fx automake-1.15.tar.gz 
cd automake-1.15
./configure --prefix=/usr/local/automake-1.15 && make && make install
mv /usr/bin/automake /usr/bin/automake.bak -f
mv /usr/bin/aclocal /usr/bin/aclocal.bak -f
ln -s /usr/local/automake-1.15/bin/automake /usr/bin/automake -f
ln -s /usr/local/automake-1.15/bin/aclocal /usr/bin/ -f
\cp  -rf /usr/local/libtool-2.4.6/share/aclocal/* `aclocal --print-ac-dir`
cd ..

#[cunit]
wget https://sourceforge.net/projects/cunit/files/CUnit/2.1-3/CUnit-2.1-3.tar.bz2
tar fx CUnit-2.1-3.tar.bz2 
cd CUnit-2.1-3
./bootstrap && make && make install
\cp ../CUnitHome/lib/pkgconfig/cunit.pc /usr/local/lib/pkgconfig/ -f
cd ..

#[libev]
wget https://fossies.org/linux/misc/libev-4.24.tar.gz
tar fx  libev-4.24.tar.gz
cd libev-4.24
./configure && make && make install 
cd ..

#[libc-ares]
wget https://c-ares.haxx.se/download/c-ares-1.13.0.tar.gz
tar fx c-ares-1.13.0.tar.gz
cd c-ares-1.13.0
./configure && make && make install
cd ..

#[libxml2]
wget ftp://xmlsoft.org/libxml2/libxml2-2.8.0.tar.gz
tar fx libxml2-2.8.0.tar.gz
cd libxml2-2.8.0
sed -i "s/\$RM \"\$cfgfile\"/# \$RM \"\$cfgfile\"/g"  configure
./configure --prefix=/usr/local/libxml-2.8.0 --with-zlib=/usr/local/lib/libz.a
sed -i 's/^CFLAGS/& -fPIC/g' Makefile
make 
make install
\cp /usr/local/libxml-2.8.0/share/aclocal/libxml.m4 /usr/local/automake-1.15/share/aclocal -f
\cp /usr/local/libxml-2.8.0/lib/pkgconfig/libxml-2.0.pc /usr/local/lib/pkgconfig/ -f
echo "export XML2_CONFIG=/usr/local/libxml-2.8.0/bin/xml2-config" >> ~/.bash_profile
source ~/.bash_profile
cd ..

#[boost]
wget https://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.bz2
tar fx boost_1_61_0.tar.bz2
cd boost_1_61_0
./bootstrap.sh
./bjam  stage --with-thread --with-date_time toolset=gcc --build-type=minimal variant=release link=shared threading=multi --with-system
cp boost -rf /usr/include
mkdir -p /usr/lib/boost 
\cp stage/lib/libboost_* /usr/lib/boost -f 
ldconfig
cd ..

#[libevent]
wget http://downloads.sourceforge.net/levent/libevent-2.0.22-stable.tar.gz
tar fx libevent-2.0.22-stable.tar.gz
cd libevent-2.0.22-stable
./configure --prefix=/usr/local/libevent-2.0.22
make 
make install
\cp libevent_openssl.pc /usr/local/libevent-2.0.22/lib/pkgconfig/ -f
\cp libevent_openssl.pc /usr/local/lib/pkgconfig/ -f
\cp /usr/local/libevent-2.0.22/lib/pkgconfig/libevent.pc /usr/local/lib/pkgconfig/ -f
cd ..

#[spdylay]
#
git clone https://github.com/tatsuhiro-t/spdylay.git && cd spdylay
sed -i "/#include \"shrpx.h\"/i\#define __STDC_LIMIT_MACROS" ./src/shrpx.cc
autoreconf -i -I/usr/share/aclocal/ 
automake
autoconf 
export ZLIB_CFLAGS="-I/usr/include" ZLIB_LIBS="-L/usr/lib -lz" OPENSSL_CFLAGS="-I/usr/include/openssl" OPENSSL_LIBS="-L/usr/lib -lssl -lcrypto" CUNIT_CFLAGS="-I/root/CUnitHome/include/CUnit" CUNIT_LIBS="-L/root/CUnitHome/lib -lcunit" LIBEVENT_OPENSSL_CFLAGS="-I/usr/local/libevent-2.0.22/include/" LIBEVENT_OPENSSL_LIBS="-L/usr/local/libevent-2.0.22/lib/ -levent_openssl -levent"
./configure --prefix=/usr/local/spdylay-1.3.2
make 
make install
cd ..
 
#[jansson]
wget http://www.digip.org/jansson/releases/jansson-2.7.tar.gz
tar -zxvf jansson-2.7.tar.gz && cd jansson-2.7
./configure 
make && make check && make install
cd ..

#[nghttp2]
git clone https://github.com/tatsuhiro-t/nghttp2.git
cd nghttp2
git submodule update --init 
autoreconf -i -I /usr/share/aclocal/ 
automake
autoconf
export  LIBSPDYLAY_CFLAGS="-I/usr/local/spdylay-1.3.2/include/spdylay" LIBSPDYLAY_LIBS="-L/usr/local/spdylay-1.3.2/lib -lspdylay"  OPENSSL_CFLAGS="-I/usr/include/openssl" OPENSSL_LIBS="-L/usr/lib -lssl -lcrypto" CUNIT_CFLAGS="-I/root/CUnitHome/include/CUnit" CUNIT_LIBS="-L/root/CUnitHome/lib -lcunit"  LIBEVENT_OPENSSL_CFLAGS="-I/usr/local/libevent-2.0.22/include/" LIBEVENT_OPENSSL_LIBS="-L/usr/local/libevent-2.0.22/lib -levent_openssl -levent" LIBCARES_CFLAGS="-I/usr/local/include" LIBCARES_LIBS="-L/usr/local/lib -lcares"
./configure  PKG_CONFIG_PATH=/usr/local/lib/pkgconfig --prefix=/usr/local/nghttp2 --enable-app
make
make install

**Comment by tatsuhiro-t** [comment]
I think the compiler is too old to compile c++ code.
It looks like you installed custom gcc-4.9.  Make sure that they are used in compilation.  For example, pass CC and CXX variables which points to the installed gcc and g++ to ./configure script.

**Comment by z180602** [comment]
Thank you, Is the problem solved

**Comment by tatsuhiro-t** [comment]
OK, let's close the issue.

**Comment by z180602** [comment]
Install success,but h2load  can't use.why?
[root@xdj ~]#/usr/local/nghttp2/bin/h2load -c 1000 -n 1000000 -m1 https://act.ahydnet.com/activity/deploy/ah/2017/hfp/images/tan_bg.png
/usr/local/nghttp2/bin/h2load: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/local/nghttp2/bin/h2load)
/usr/local/nghttp2/bin/h2load: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/local/nghttp2/bin/h2load)
/usr/local/nghttp2/bin/h2load: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.17' not found (required by /usr/local/nghttp2/bin/h2load)
/usr/local/nghttp2/bin/h2load: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by /usr/local/nghttp2/bin/h2load)
/usr/local/nghttp2/bin/h2load: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /usr/local/nghttp2/bin/h2load)
/usr/local/nghttp2/bin/h2load: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/local/nghttp2/bin/h2load)
/usr/local/nghttp2/bin/h2load: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /usr/local/nghttp2/bin/h2load)




[root@xdj ~]# mv /usr/lib64/libstdc++.so.6{,.bak}
[root@xdj ~]# cp /usr/local/lib64/libstdc++.so.6 /usr/lib64/libstdc++.so.6
[root@xdj ~]# /usr/local/nghttp2/bin/h2load -c 1000 -n 1000000 -m1 https://act.ahydnet.com/activity/deploy/ah/2017/hfp/images/tan_bg.png

**Comment by z180602** [comment]
Install success,but h2load can't use.why?

[root@xdj ~]#/usr/local/nghttp2/bin/h2load -c 1000 -n 1000000 -m1 

https://act.ahydnet.com/activity/deploy/ah/2017/hfp/images/tan_bg.png
/usr/local/nghttp2/bin/h2load: /usr/lib64/libstdc++.so.6: version GLIBCXX_3.4.20' not found (required by /usr/local/nghttp2/bin/h2load) /usr/local/nghttp2/bin/h2load: /usr/lib64/libstdc++.so.6: versionCXXABI_1.3.8' not found (required by /usr/local/nghttp2/bin/h2load)
/usr/local/nghttp2/bin/h2load: /usr/lib64/libstdc++.so.6: version GLIBCXX_3.4.17' not found (required by /usr/local/nghttp2/bin/h2load) /usr/local/nghttp2/bin/h2load: /usr/lib64/libstdc++.so.6: versionGLIBCXX_3.4.19' not found (required by /usr/local/nghttp2/bin/h2load)
/usr/local/nghttp2/bin/h2load: /usr/lib64/libstdc++.so.6: version GLIBCXX_3.4.18' not found (required by /usr/local/nghttp2/bin/h2load) /usr/local/nghttp2/bin/h2load: /usr/lib64/libstdc++.so.6: versionGLIBCXX_3.4.15' not found (required by /usr/local/nghttp2/bin/h2load)
/usr/local/nghttp2/bin/h2load: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /usr/local/nghttp2/bin/h2load)

[root@xdj ~]# mv /usr/lib64/libstdc++.so.6{,.bak}
[root@xdj ~]# cp /usr/local/lib64/libstdc++.so.6 /usr/lib64/libstdc++.so.6
[root@xdj ~]# /usr/local/nghttp2/bin/h2load -c 1000 -n 1000000 -m1 https://act.ahydnet.com/activity/deploy/ah/2017/hfp/images/tan_bg.png

Segmentation fault

**Comment by tatsuhiro-t** [comment]
It looks like no required glibc version is found.  Did you compile nghttp2 in that host?  Or did you just copy binaries from other servers which has the different glibc version?

**Comment by z180602** [comment]
Compile nghttp2 in that host

**Comment by starjun** [comment]
version `GLIBCXX_3.4.14' not found 两者是一个问题导致的：
c++标准库太老了.没有更新.
1：先查看 libstdc++.so.*
find / -name "libstdc++.so*"
2：一般存在目录 /usr/lib64 下（64位）；新安装的gcc 一般在 /usr/local/lib64/下
3：我们把最新的 libstdc++.so 复制到 /usr/lib64
4：删掉原来的 rm -rf libstdc++.so.6
5：重新创建链接 ln -s libstdc++.so.6.0.22 libstdc++.so.6（libstdc++.so.6.0.22 是你的最新版本）
6：ldconfig  一下
root 权限运行
