### ISSUE TITLE
Who compiled nghttp2_asio on Windows  successfully? 

### ISSUE THREAD

**Issue by zwl698** [nghttp2/nghttp2#1043]
Who compiled nghttp2_asio on Windows  successfully? Please share me the lib.

**Comment by pengweichu** [comment]
Please the #971

**Comment by zwl698** [comment]
Could you share me the lib?

**Comment by dvetutnev** [comment]
#1141 I`m use nghttp2_asio on Windows

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
