### ISSUE TITLE
Since spdycat is being deprecated, how to test nghttpx powered proxy servers? 

### ISSUE THREAD

**Issue by yegors** [nghttp2/nghttp2#1050]
New issue as per #1049

We operate 100s of proxy servers where nghttpx is used as a frontend for Squid. Currently we use spdycat to simulate a request in a similar fashion to what a browser would do to make sure everything is working. 

With spdycat being deprecated, is there any way to accomplish the same thing using other tools? I've been unsuccessful using CURL, even though it claims that it should work:  https://curl.haxx.se/libcurl/c/CURLOPT_HTTPPROXYTUNNEL.html

**Comment by tatsuhiro-t** [comment]
nghttp command line client replaced spdycat although their functionalities are not exactly the same.
nghttp does not support HTTPS proxy, but abusing -H option can make some requests:

```
$ nghttp -nv https://PROXY/ -H':scheme: http' -H':authority: example.com' -H':path: /'
```

**Comment by yegors** [comment]
This will do. Thanks.
