### ISSUE TITLE
TLS client certificate information in HTTP header

### ISSUE THREAD

**Issue by shotahino** [nghttp2/nghttp2#1054]
Similar to this feature in `HAProxy`: https://www.haproxy.com/blog/ssl-client-certificate-information-in-http-headers-and-logs/

In `nghttpx`, is there a way to extract TSL client certificate information and add to HTTP header?
This is incredibly useful feature and also very important to enable _authorization_.

I'm aware that `nghttpx` is expandable with `mruby` script, but I'm looking to see if there is already a support for this.

**Comment by tatsuhiro-t** [comment]
The development version of nghttpx has made several variables extracted from client certificate available to mruby.  https://nghttp2.org/documentation/nghttpx.1.html#Nghttpx::Env#tls_client_fingerprint_sha256

If you are in a hurry, and/or wants to do an experimentation, use mruby script, and set request header using the new variables (e.g., env.tls_client_fingerprint_sha256, env.tls_client_subject_name, etc).

**Comment by shotahino** [comment]
@tatsuhiro-t Thanks. It/specifically says that it requires `mruby`with C++ ABI enabled.

> C++ ABI
>By default, mruby uses setjmp/longjmp to implement its exceptions. But it doesn't release C++ stack object correctly. To support mrbgems written in C++, mruby can be configured to use C++ exception.
>When you mix C++ code, C++ exception would be enabled automatically. If you need to enable C++ exception explicitly add the following:
>conf.enable_cxx_exception

Is C++ ABI it really required for `mruby` script to work? 
It looks like C++ ABI comes into play only if we want to support `mrbgems` written in C++.

**Comment by shotahino** [comment]
@tatsuhiro-t Also, is this attribute always available?
I'm getting an error. 

>2017-11-14T02:20:17.075Z 6913 6922 cdd759c5 ERROR (shrpx_mruby.cc:92) Exception caught while executing mruby code: NoMethodError: undefined method 'tls_client_subject_name' for #>><Nghttpx::Env:0x7615be88>

**Comment by tatsuhiro-t** [comment]
It should work.  Note that the function is not included in v1.27.0.  Please make sure that you are using master branch.

**Comment by shotahino** [comment]
@tatsuhiro-t Ah, thanks for point that out. I was using `v1.27.0` release.
>This object is called app object. If app object defines on_req method, it is called with Nghttpx::Env object on request hook

In case of gRPC streaming, how often would this script be called? 
I think it is once per stream, but could you confirm?

Ideally, I would like this script to be called only once at the beginning of streaming (i.e. per connection as opposed to per request).

**Comment by tatsuhiro-t** [comment]
on_req is called when forwarding HTTP request when nghttpx received complete HTTP request header fields; so in HTTP/2 terms, yes, it is per Stream (HEADERS frame).
Does it answer your question?

**Comment by shotahino** [comment]
@tatsuhiro-t Yes, it is clear now. Thanks for your feedback every time. I greatly appreciate it.
