### ISSUE TITLE
Build errors over Debian 8 

### ISSUE THREAD

**Issue by bigboyq** [nghttp2/nghttp2#1055]
Build errors
```
Making all in examples
make[2]: Entering directory '/root/nghttp2-1.27.0/examples'
  CC       libevent-client.o
In file included from libevent-client.c:62:0:
/usr/include/event2/event.h:677:5: error: conflicting types for event_base_loopexit
 int event_base_loopexit(struct event_base *, const struct timeval *);
     ^
In file included from libevent-client.c:61:0:
/usr/local/include/event.h:164:5: note: previous declaration of event_base_loopexit was here
 int event_base_loopexit (struct event_base *base, struct timeval *tv);
     ^
In file included from libevent-client.c:62:0:
/usr/include/event2/event.h:913:5: error: conflicting types for event_base_once
 int event_base_once(struct event_base *, evutil_socket_t, short, event_callback_fn, void *, const struct timeval *);
     ^
In file included from libevent-client.c:61:0:
/usr/local/include/event.h:166:5: note: previous declaration of event_base_once was here
 int event_base_once (struct event_base *base, int fd, short events, void (*cb)(int, short, void *), void *arg, struct timeval *tv);
     ^
In file included from libevent-client.c:62:0:
/usr/include/event2/event.h:937:5: error: conflicting types for event_add
 int event_add(struct event *ev, const struct timeval *timeout);
     ^
In file included from libevent-client.c:61:0:
/usr/local/include/event.h:151:5: note: previous declaration of event_add was here
 int event_add (struct event *ev, struct timeval *tv);
     ^
In file included from libevent-client.c:62:0:
/usr/include/event2/event.h:982:5: error: conflicting types for event_pending
 int event_pending(const struct event *ev, short events, struct timeval *tv);
     ^
In file included from libevent-client.c:61:0:
/usr/local/include/event.h:155:5: note: previous declaration of event_pending was here
 int event_pending (struct event *ev, short, struct timeval *tv);
     ^
/usr/include/event2/event.h:1000:5: error: expected identifier or ( before const
 int event_initialized(const struct event *ev);
     ^
/usr/include/event2/event.h:1000:5: error: expected ) before -> token
 int event_initialized(const struct event *ev);
     ^
libevent-client.c: In function readcb:
libevent-client.c:455:25: warning: initialization makes pointer from integer without a cast
   unsigned char *data = evbuffer_pullup(input, -1);
                         ^
Makefile:612: recipe for target 'libevent-client.o' failed
make[2]: *** [libevent-client.o] Error 1
make[2]: Leaving directory '/root/nghttp2-1.27.0/examples'
Makefile:569: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/nghttp2-1.27.0'
Makefile:478: recipe for target 'all' failed
make: *** [all] Error 2
```

./configure result
```
configure: summary of build options:

    Package version: 1.27.0
    Library version: 28:0:14
    Install prefix:  /usr/local
    System types:
      Build:         x86_64-pc-linux-gnu
      Host:          x86_64-pc-linux-gnu
      Target:        x86_64-pc-linux-gnu
    Compiler:
      C compiler:     gcc
      CFLAGS:         -g -O2
      LDFLAGS:        
      C++ compiler:   g++
      CXXFLAGS:       -g -O2
      CXXCPP:         g++ -E
      C preprocessor: gcc -E
      CPPFLAGS:       
      WARNCFLAGS:     
      WARNCXXFLAGS:   
      CXX1XCXXFLAGS:   -std=c++11
      EXTRACFLAG:     -fvisibility=hidden
      LIBS:           
    Library:
      Shared:         yes
      Static:         yes
    Python:
      Python:         /usr/bin/python
      PYTHON_VERSION: 2.7
      pyexecdir:      ${exec_prefix}/lib/python2.7/dist-packages
      Python-dev:     yes
      PYTHON_CPPFLAGS:-I/usr/include/python2.7
      PYTHON_LDFLAGS: -L/usr/lib -lpython2.7
      Cython:         cython
    Test:
      CUnit:          yes (CFLAGS='' LIBS='-lcunit')
      Failmalloc:     yes
    Libs:
      OpenSSL:        yes (CFLAGS='' LIBS='-lssl -lcrypto ')
      Libxml2:        yes (CFLAGS='' LIBS='-lxml2 ')
      Libev:          yes (CFLAGS='' LIBS='-lev')
      Libc-ares       yes (CFLAGS='' LIBS='-lcares ')
      Libevent(SSL):  yes (CFLAGS='' LIBS='-levent_openssl -levent ')
      Spdylay:        no (CFLAGS='' LIBS='')
      Jansson:        yes (CFLAGS='' LIBS='-ljansson ')
      Jemalloc:       yes (LIBS='-ljemalloc')
      Zlib:           yes (CFLAGS='' LIBS='-L/usr/lib/x86_64-linux-gnu -lz ')
      Systemd:        yes (CFLAGS='' LIBS='-lsystemd ')
      Boost CPPFLAGS: 
      Boost LDFLAGS:  
      Boost::ASIO:    
      Boost::System:  
      Boost::Thread:  
    Third-party:
      http-parser:    yes
      MRuby:          no (CFLAGS='' LIBS='')
      Neverbleed:     no
    Features:
      Applications:   yes
      HPACK tools:    yes
      Libnghttp2_asio:no
      Examples:       yes
      Python bindings:yes
      Threading:      yes
```

Guess the problem related to libevent, but don't know how to resolve it, thanks everyone's attention

**Comment by tatsuhiro-t** [comment]
It looks like there are 2 different versions of libevent installed on your system.

/usr/include/event2/event.h and /usr/local/include/event.h

Have you installed libevent from source by yourself?

**Comment by bigboyq** [comment]
Thanks for your reply, I think you are right, I have manually compiled libevent, and apt-get installation also. I think this is key cause. 
I have reinstalled my system.
Then I have faced new situation. For I have compiled spdylay, which located in /usr/local/lib and /usr/local/include, but when I am doing ./configure under nghttp2 I got spdylay: no 

Even after ldconfig depmod, and system reboot

`configure: summary of build options:

    Package version: 1.28.0-DEV
    Library version: 28:0:14
    Install prefix:  /usr/local
    System types:
      Build:         x86_64-pc-linux-gnu
      Host:          x86_64-pc-linux-gnu
      Target:        x86_64-pc-linux-gnu
    Compiler:
      C compiler:     gcc
      CFLAGS:         -g -O2
      LDFLAGS:        -L/usr/local/lib
      C++ compiler:   g++
      CXXFLAGS:       -g -O2
      CXXCPP:         g++ -E
      C preprocessor: gcc -E
      CPPFLAGS:       -I/usr/local/include
      WARNCFLAGS:     
      WARNCXXFLAGS:   
      CXX1XCXXFLAGS:  
      EXTRACFLAG:     -fvisibility=hidden
      LIBS:           
    Library:
      Shared:         yes
      Static:         yes
    Python:
      Python:         /usr/bin/python
      PYTHON_VERSION: 2.7
      pyexecdir:      ${exec_prefix}/lib/python2.7/dist-packages
      Python-dev:     yes
      PYTHON_CPPFLAGS:-I/usr/include/python2.7
      PYTHON_LDFLAGS: -L/usr/lib -lpython2.7
      Cython:         cython
    Test:
      CUnit:          yes (CFLAGS='' LIBS='-lcunit')
      Failmalloc:     yes
    Libs:
      OpenSSL:        yes (CFLAGS='' LIBS='-lssl -lcrypto')
      Libxml2:        yes (CFLAGS='' LIBS='-lxml2')
      Libev:          yes (CFLAGS='' LIBS='-lev')
      Libc-ares       yes (CFLAGS='' LIBS='-lcares')
      Libevent(SSL):  yes (CFLAGS='' LIBS='-levent_openssl -levent')
      Spdylay:        no (CFLAGS='' LIBS='')
      Jansson:        yes (CFLAGS='' LIBS='-ljansson')
      Jemalloc:       yes (LIBS='-ljemalloc')
      Zlib:           yes (CFLAGS='' LIBS='-lz')
      Systemd:        no (CFLAGS='' LIBS='')
      Boost CPPFLAGS: 
      Boost LDFLAGS:  
      Boost::ASIO:    
      Boost::System:  
      Boost::Thread:  
    Third-party:
      http-parser:    yes
      MRuby:          no (CFLAGS='' LIBS='')
      Neverbleed:     no
    Features:
      Applications:   yes
      HPACK tools:    yes
      Libnghttp2_asio:no
      Examples:       yes
      Python bindings:yes
      Threading:      yes
` 

Any suggestions?Thanks

**Comment by bigboyq** [comment]
@tatsuhiro-t if ignored spdylay = no, continue the process, the nghttp2 works properly
The environment is Debian 9. The whole process from clean system is:
`
apt-get update && apt-get upgrade -y
apt-get install g++ make binutils autoconf automake autotools-dev libtool pkg-config zlib1g-dev libcunit1-dev libssl-dev libxml2-dev libev-dev libevent-dev libjansson-dev libc-ares-dev libjemalloc-dev cython -y
apt-get install python-setuptools -y
`
`
git clone https://github.com/tatsuhiro-t/spdylay
cd spdylay/
autoreconf -i
automake
autoconf
./configure
make
make install
ldconfig 
cd ~
git clone https://github.com/nghttp2/nghttp2
cd nghttp2
git submodule update --init
autoreconf -i
automake
autoconf
./configure
make
make install
`
Almost the success, only spdylay

**Comment by tatsuhiro-t** [comment]
Check config.log, which contains why spdylay is not detected.
You may have to give PKG_CONFIG_PATH=/usr/local/lib/pkgconfig to ./configure script.

**Comment by tatsuhiro-t** [comment]
BTW, spdylay support is disabled by default.  You have to enable it with --with-spdylay.
We are deprecating SPDY in the next release.

**Comment by bigboyq** [comment]
@tatsuhiro-t OK, uninstalled spdylay, in order to avoid next release modification. 
Thanks, all runs properly.
