### ISSUE TITLE
How to compile nghttp2_asio on Linux ?

### ISSUE THREAD

**Issue by pengweichu** [nghttp2/nghttp2#1056]
Hi, I have tried compile nghttp2_asio on Debian 9.2.1, I got below error, how to fix ?

`cmake .. -DENABLE_THREADS=ON -DENABLE_LIB_ONLY=ON -DENABLE_ASIO_LIB=ON -DJANSSON_INCLUDE_DIR=/home/pp/qh9/linux_include/jansson -DJANSSON_LIBRARY=/home/pp/qh9/linux_lib -DZLIB_INCLUDE_DIRS=/home/pp/3rd/zlib-1.2.11/ -DZLIB_LIBRARIES=/home/pp/qh9/linux_lib -DNGHTTP2_STATICLIB=ON -DOPENSSL_ROOT_DIR=/home/pp/3rd/openssl-1.0.2m/ -DOPENSSL_LIBRARIES=/home/pp/qh9/linux_lib`

Determining if the pthread_create exist failed with the following output:
Change Dir: /home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_881f6/fast"
/usr/bin/make -f CMakeFiles/cmTC_881f6.dir/build.make CMakeFiles/cmTC_881f6.dir/build
make[1]: Entering directory '/home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_881f6.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_881f6.dir/CheckSymbolExists.c.o   -c /home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_881f6
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_881f6.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_881f6.dir/CheckSymbolExists.c.o  -o cmTC_881f6 -rdynamic 
CMakeFiles/cmTC_881f6.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_881f6.dir/build.make:97: recipe for target 'cmTC_881f6' failed
make[1]: *** [cmTC_881f6] Error 1
make[1]: Leaving directory '/home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_881f6/fast' failed
make: *** [cmTC_881f6/fast] Error 2

File /home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_7987d/fast"
/usr/bin/make -f CMakeFiles/cmTC_7987d.dir/build.make CMakeFiles/cmTC_7987d.dir/build
make[1]: Entering directory '/home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_7987d.dir/CheckFunctionExists.c.o
/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_7987d.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.7/Modules/CheckFunctionExists.c
Linking C executable cmTC_7987d
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_7987d.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_7987d.dir/CheckFunctionExists.c.o  -o cmTC_7987d -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_7987d.dir/build.make:97: recipe for target 'cmTC_7987d' failed
make[1]: *** [cmTC_7987d] Error 1
make[1]: Leaving directory '/home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_7987d/fast' failed
make: *** [cmTC_7987d/fast] Error 2

Performing C SOURCE FILE Test C_FLAG__Wshorten_64_to_32 failed with the following output:
Change Dir: /home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_5c4cb/fast"
/usr/bin/make -f CMakeFiles/cmTC_5c4cb.dir/build.make CMakeFiles/cmTC_5c4cb.dir/build
make[1]: Entering directory '/home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_5c4cb.dir/src.c.o
/usr/bin/cc    -DC_FLAG__Wshorten_64_to_32   -Wshorten-64-to-32 -o CMakeFiles/cmTC_5c4cb.dir/src.c.o   -c /home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp/src.c
cc: error: unrecognized command line option '-Wshorten-64-to-32'
CMakeFiles/cmTC_5c4cb.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_5c4cb.dir/src.c.o' failed
make[1]: *** [CMakeFiles/cmTC_5c4cb.dir/src.c.o] Error 1
make[1]: Leaving directory '/home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_5c4cb/fast' failed
make: *** [cmTC_5c4cb/fast] Error 2

Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_FLAG__Wextended_offsetof failed with the following output:
Change Dir: /home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_9890a/fast"
/usr/bin/make -f CMakeFiles/cmTC_9890a.dir/build.make CMakeFiles/cmTC_9890a.dir/build
make[1]: Entering directory '/home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_9890a.dir/src.c.o
/usr/bin/cc    -DC_FLAG__Wextended_offsetof   -Wextended-offsetof -o CMakeFiles/cmTC_9890a.dir/src.c.o   -c /home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp/src.c
cc: error: unrecognized command line option '-Wextended-offsetof'; did you mean '-Winvalid-offsetof'?
CMakeFiles/cmTC_9890a.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_9890a.dir/src.c.o' failed
make[1]: *** [CMakeFiles/cmTC_9890a.dir/src.c.o] Error 1
make[1]: Leaving directory '/home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_9890a/fast' failed
make: *** [cmTC_9890a/fast] Error 2

Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_FLAG__Wlanguage_extension_token failed with the following output:
Change Dir: /home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_9a17a/fast"
/usr/bin/make -f CMakeFiles/cmTC_9a17a.dir/build.make CMakeFiles/cmTC_9a17a.dir/build
make[1]: Entering directory '/home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_9a17a.dir/src.c.o
/usr/bin/cc    -DC_FLAG__Wlanguage_extension_token   -Wlanguage-extension-token -o CMakeFiles/cmTC_9a17a.dir/src.c.o   -c /home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp/src.c
cc: error: unrecognized command line option '-Wlanguage-extension-token'
CMakeFiles/cmTC_9a17a.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_9a17a.dir/src.c.o' failed
make[1]: *** [CMakeFiles/cmTC_9a17a.dir/src.c.o] Error 1
make[1]: Leaving directory '/home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_9a17a/fast' failed
make: *** [cmTC_9a17a/fast] Error 2

Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_FLAG__Wmissing_variable_declarations failed with the following output:
Change Dir: /home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_34256/fast"
/usr/bin/make -f CMakeFiles/cmTC_34256.dir/build.make CMakeFiles/cmTC_34256.dir/build
make[1]: Entering directory '/home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_34256.dir/src.c.o
/usr/bin/cc    -DC_FLAG__Wmissing_variable_declarations   -Wmissing-variable-declarations -o CMakeFiles/cmTC_34256.dir/src.c.o   -c /home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp/src.c
cc: error: unrecognized command line option '-Wmissing-variable-declarations'; did you mean '-Wmissing-declarations'?
CMakeFiles/cmTC_34256.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_34256.dir/src.c.o' failed
make[1]: *** [CMakeFiles/cmTC_34256.dir/src.c.o] Error 1
make[1]: Leaving directory '/home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_34256/fast' failed
make: *** [cmTC_34256/fast] Error 2

Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_FLAG__Wunreachable_code_break failed with the following output:
Change Dir: /home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_272c5/fast"
/usr/bin/make -f CMakeFiles/cmTC_272c5.dir/build.make CMakeFiles/cmTC_272c5.dir/build
make[1]: Entering directory '/home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_272c5.dir/src.c.o
/usr/bin/cc    -DC_FLAG__Wunreachable_code_break   -Wunreachable-code-break -o CMakeFiles/cmTC_272c5.dir/src.c.o   -c /home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp/src.c
cc: error: unrecognized command line option '-Wunreachable-code-break'; did you mean '-Wunreachable-code'?
CMakeFiles/cmTC_272c5.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_272c5.dir/src.c.o' failed
make[1]: *** [CMakeFiles/cmTC_272c5.dir/src.c.o] Error 1
make[1]: Leaving directory '/home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_272c5/fast' failed
make: *** [cmTC_272c5/fast] Error 2

Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_FLAG__Wheader_guard failed with the following output:
Change Dir: /home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_b3d86/fast"
/usr/bin/make -f CMakeFiles/cmTC_b3d86.dir/build.make CMakeFiles/cmTC_b3d86.dir/build
make[1]: Entering directory '/home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_b3d86.dir/src.c.o
/usr/bin/cc    -DC_FLAG__Wheader_guard   -Wheader-guard -o CMakeFiles/cmTC_b3d86.dir/src.c.o   -c /home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp/src.c
cc: error: unrecognized command line option '-Wheader-guard'
CMakeFiles/cmTC_b3d86.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_b3d86.dir/src.c.o' failed
make[1]: *** [CMakeFiles/cmTC_b3d86.dir/src.c.o] Error 1
make[1]: Leaving directory '/home/pp/3rd/nghttp2/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_b3d86/fast' failed
make: *** [cmTC_b3d86/fast] Error 2

Source file was:
int main(void) { return 0; }

**Comment by tatsuhiro-t** [comment]
I'm not familiar with cmake, but it works for me.  I use cmake 3.9.3.

**Comment by tatsuhiro-t** [comment]
Have you tried autotools?

**Comment by pengweichu** [comment]
Yes, I've tried autotools and works fine.

Thanks

**Comment by pengweichu** [comment]
@tatsuhiro-t Hi, with autotools, how to specify the openssl  that i don't want it link to system installed openssl.

**Comment by tatsuhiro-t** [comment]
./configure --help shows some variables you can use:

```
  OPENSSL_CFLAGS
              C compiler flags for OPENSSL, overriding pkg-config
  OPENSSL_LIBS
              linker flags for OPENSSL, overriding pkg-config
```

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
