### ISSUE TITLE
Multiple messages

### ISSUE THREAD

**Issue by Gregory-Skurko** [nghttp2/nghttp2#1061]
I need to implement a live connection, the data through which will come from another socket (not ngntp2).
What I need:
1. Open http2 connection.
2. Expect the appearance of data in any buffer (or through synchronous work, it's not important).
3. Take this data and send it to.
4. Get a response and go back to the waiting state.

I have a problem with waiting. I'm using this example https://github.com/nghttp2/nghttp2/blob/master/examples/asio-cl2.cc

If I will send the several messages in session.on_connection callback, then in fact they sending after exiting of connection callback. If I try pass a session how param in another thread, then I catch seg fault
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4c63700 (LWP 16861)]
[New Thread 0x7ffff4462700 (LWP 16862)]
SEND TO https://nghttp2.org

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff4462700 (LWP 16862)]
nghttp2_submit_request (session=0x0, pri_spec=0x7fffe40008f0, nva=0x7fffe4000b50, nvlen=0, data_prd=0x7ffff4461c40, stream_user_data=0x63bf50)
    at nghttp2_submit.c:596
596	  if (session->server) {
```

1 way:
```
...
session.on_connect([&session, &uri](tcp::resolver::iterator endpoint_it) {
    ...
    auto req = session.submit(ec, httpMethod, uri);
    ...
    auto req = session.submit(ec, httpMethod, uri);
});
...
io_service.run();
```

2 way:
```
session.on_connect([&session, &uri](tcp::resolver::iterator endpoint_it) {
    ...
    setIsConnected();
    ...
});
...
std::thread thread([&session]() {
    while (true) {
        if (isConnected() && hasData() {
            ...
            auto req = session.submit(ec, httpMethod, uri);
            ...
        }
    }
});
io_service.run();
```

How to solve this problem?

**Comment by tatsuhiro-t** [comment]
It is correct that requests are sent after on_connect because everything is non-blocking.
With response callback set, you will get response eventually.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
