### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by shyjun** [nghttp2/nghttp2#1065]
Hi,  i am using nghttp2 client in an embedded system environment. i am measuring the available heap before and after a probe session(create a stream, send probe request, server will reply with 204, server will close the stream)

i could see a memory leak of 176bytes happening.

here is the log:

     1	-----------memory usage----------
     2	HeapBytesRemaining=112504
     3	---------------------------------
     4	
     5	SendProbeRequest: calling submit_request... waiting for stream_id
     6	nghttp2 malloc returning 2000e110, size=783
     7	nghttp2 malloc returning 2000cc80, size=96
     8	SendProbeRequest: Stream ID = 5
     9	
    10	nghttp2 malloc returning 2000e428, size=160
    11	nghttp2 free ptr=2000e110
    12	nghttp2 free ptr=2000cc80
    13	
    14	on_header_callback_fn:STREAM=5::-:status-:-204-
    15	nghttp2 malloc returning 2000e110, size=109
    16	nghttp2 malloc returning 2000cc80, size=48
    17	
    18	SendProbeRequest: status=204. stream_id=5
    19	
    20	on_stream_close_fn(), (err 0), stream 5
    21	nghttp2 free ptr=0
    22	nghttp2 free ptr=2000e428
    23	nghttp2 free ptr=0
    24	nghttp2 free ptr=0
    25	
    26	-----------memory usage----------
    27	HeapBytesRemaining=112328
    28	---------------------------------
    29	
    30	

see the line 21,23,24, free is called with 0 as the address..

am i supposed to free some allocation which nghttp2 lib did..?

Thanks
Shyju

**Comment by tatsuhiro-t** [comment]
I'm not sure it indicates memory leak.  It is completely fine to call free() with nullptr.

**Comment by shyjun** [comment]
that is true.. but "HeapBytesRemaining" shows 176bytes lesser... and if this probe session is run "n" times, the heap reduces by n*176 bytes..!!

**Comment by tatsuhiro-t** [comment]
nghttp2 by default keeps some closed streams in memory so that it can be still served as priority tree node.  It would be interesting if you create/close 10000 streams, and see how heap size grows.

**Comment by shyjun** [comment]
each open-close of a stream consumes exactly 176bytes. as i mentioned, mine is an embedded system with very limited memory, and there are other threads which need memory/resources... so system fails after running for an hour or so... is there a way i can free the complete memory used by a stream when stream is closed..??

**Comment by tatsuhiro-t** [comment]
Try https://nghttp2.org/documentation/nghttp2_option_set_no_closed_streams.html

**Comment by shyjun** [comment]
i tried it. but still same leak of 176bytes..!! code snipped copied below..

        setup_nghttp2_callbacks(callbacks);

        //rv = nghttp2_session_client_new(&avsHttp2Conn.session, callbacks, &avsHttp2Conn);
        nghttp2_option *opt;
        if(0!=nghttp2_option_new(&opt))
        {
            fatal("couldn't alloc option..\n");
        }
        nghttp2_option_set_no_closed_streams(opt,1);
        rv = nghttp2_session_client_new2(&avsHttp2Conn.session, callbacks, &avsHttp2Conn,opt);

        nghttp2_session_callbacks_del(callbacks);
        nghttp2_option_del(opt);

**Comment by tatsuhiro-t** [comment]
It could be HPACK related.  But have you actually tried to create lots of streams, and see it really causes out of memory?

**Comment by shyjun** [comment]
is there any chance of leak in HPACK...? in that case how do i debug it..??  my system sends a probe req every one minute. i could see the memory reduces to n*176 bytes..

**Comment by tatsuhiro-t** [comment]
By default HPACK buffer size is 4KiB buffers for each reception and transmission.
To change buffer size of transmission, use https://nghttp2.org/documentation/nghttp2_option_set_max_deflate_dynamic_table_size.html#synopsis
For reception, send NGHTTP2_SETTINGS_HEADER_TABLE_SIZE with value 0 using https://nghttp2.org/documentation/nghttp2_submit_settings.html

**Comment by shyjun** [comment]
will that really help..? as the leak seen is only 176bytes..!!

**Comment by tatsuhiro-t** [comment]
I'm not sure which purpose memory is allocated for, but HPACK 4KiB buffer is maximum size.  It will grow up to that size.  So if 176 bytes are spent for a part of HPACK, it will be there until it is evicted.

**Comment by shyjun** [comment]
if you see the log, memory allocated at line number 6 and 7 are freed at line number 11 and 12.. memory allocated at line10 is freed at line 22. but blocks allocated at line 15 and 16 are not freed..!! but their allocation size is 157, which is not matching with 176..!!  i can get some more info about the caller of these allocations and frees. but not really sure if it will be of any help.



 1	-----------memory usage----------
 2	HeapBytesRemaining=112504
 3	---------------------------------
 4	
 5	SendProbeRequest: calling submit_request... waiting for stream_id
 6	nghttp2 malloc returning 2000e110, size=783
 7	nghttp2 malloc returning 2000cc80, size=96
 8	SendProbeRequest: Stream ID = 5
 9	
10	nghttp2 malloc returning 2000e428, size=160
11	nghttp2 free ptr=2000e110
12	nghttp2 free ptr=2000cc80
13	
14	on_header_callback_fn:STREAM=5::-:status-:-204-
15	nghttp2 malloc returning 2000e110, size=109
16	nghttp2 malloc returning 2000cc80, size=48
17	
18	SendProbeRequest: status=204. stream_id=5
19	
20	on_stream_close_fn(), (err 0), stream 5
21	nghttp2 free ptr=0
22	nghttp2 free ptr=2000e428
23	nghttp2 free ptr=0
24	nghttp2 free ptr=0
25	
26	-----------memory usage----------
27	HeapBytesRemaining=112328
28	---------------------------------
29	
30

**Comment by shyjun** [comment]
hi, i did some further tests. if you see the log, the allocations are 783,96,160,109,48 sized buffers, and out of these, 783,96,160 are freed. So effectively, there are 2 allocations of size 109and48 which are not freed. I wrote a small test code which will just allocate 2 buffers of these sizes(109and48), and checked the heap usage, i could see that 176bytes reduced from heap. That means that the leak of 176bytes is caused by buffers of size 160and48. i will further debug and find out the caller of these allocations.

**Comment by shyjun** [comment]
hi, i debugged further. 

memory of size 109 bytes is allocated from here:
nghttp2_session_mem_recv->inflate_header_block->nghttp2_hd_inflate_hd_nv->nghttp2_rcbuf_new->nghttp2_mem_malloc

memory of size 48 bytes is allocated from here:
nghttp2_session_mem_recv->inflate_header_block->nghttp2_hd_inflate_hd_nv->hd_inflate_commit_indname->add_hd_table_incremental->nghttp2_mem_malloc

I went through the 48byte allocation path, 48bytes memory is allocated and updated in "nghttp2_hd_nv nv;" which is a local variable at "inflate_header_block".. but i could see it is not freed...  i am wondering if there is a leak in that path..!!

your help is highly appreciated...

**Comment by tatsuhiro-t** [comment]
Thanks.  I think they are stored in HPACK buffer which is connection scope.
So my advice is https://github.com/nghttp2/nghttp2/issues/1065#issuecomment-346041597

**Comment by shyjun** [comment]
Hi, i tried "NGHTTP2_SETTINGS_HEADER_TABLE_SIZE with value 0" but no change.. still leak of 176bytes...

**Comment by tatsuhiro-t** [comment]
It should.  If it doesn't work, then server might acknowledge SETTINGS, or does not encode TABLE SIZE update in HPACK.
Anyway, please check that you compiled source code successfully, and using the compiled binary.  Sometimes this kind of simple thing could cost many hours.
What kind of server are you using?

**Comment by shyjun** [comment]
Hi. the 48bytes memory chunk is allocated(from:nghttp2_session_mem_recv->inflate_header_block->nghttp2_hd_inflate_hd_nv->hd_inflate_commit_indname->add_hd_table_incremental->nghttp2_mem_malloc) and added at "session->hd_inflater->ctx->hd_table->buffer[idx]. but i could see that its not getting freed once the stream is closed. 

i see they are being maintained as a ring buffer. are these buffers required for future use.? can they be freed once the stream is closed.? please advise.

**Comment by tatsuhiro-t** [comment]
NGHTTP2_SETTINGS_HEADER_TABLE_SIZE with 0 is used, then HPACK should not consume extra memory.
It looks like the settings is not properly used.
It would be nice if you share the source code so that I can look at it.

**Comment by shyjun** [comment]
Hi, with the "nghttp2_option_set_max_deflate_dynamic_table_size" option, it is working fine. no memory leak seen... thank you for all your support and help.... i am copying the code here. let me know if any other changes are required... 

     1	
     2	nghttp2_option *opt;
     3	if(0!=nghttp2_option_new(&opt))
     4	{
     5	    fatal("couldn't alloc option..\n");
     6	}
     7	
     8	setup_nghttp2_callbacks(callbacks);
     9	
    10	nghttp2_option_set_no_closed_streams(opt,1);
    11	nghttp2_option_set_max_deflate_dynamic_table_size(opt, 0);
    12	
    13	rv = nghttp2_session_client_new2(&Http2Conn.session, callbacks, &Http2Conn,opt);
    14	
    15	nghttp2_session_callbacks_del(callbacks);
    16	nghttp2_option_del(opt);
    17	
    18	if (rv != 0) {
    19	    fatal("nghttp2_session_client_new failed");
    20	}
    21	
    22

**Comment by tatsuhiro-t** [comment]
It looks good to me.
