### ISSUE TITLE
nghttp2_hd_deflate_hd has incorrect documentation 

### ISSUE THREAD

**Issue by Lukasa** [nghttp2/nghttp2#1073]
The docs for this function say:

https://github.com/nghttp2/nghttp2/blob/ff200bfcf34044d364714d45f2227bb5dab55171/lib/includes/nghttp2/nghttp2.h#L4760-L4769

This is incorrect, however: the code returns the length of the encoded buffer on success.

https://github.com/nghttp2/nghttp2/blob/ff200bfcf34044d364714d45f2227bb5dab55171/lib/nghttp2_hd.c#L1504

**Comment by tatsuhiro-t** [comment]
It looks like doc for nghttp2_hd_deflate_hd_vec is also wrong in the same way.
