### ISSUE TITLE
Preserve client IP

### ISSUE THREAD

**Issue by truongdo** [nghttp2/nghttp2#1075]
I'm using nghttp2 as a load balancer for http2 (grpc) backend servers.
When I try to get client IP from the backend server, I can only the IP of the nghttp2 load balancer.
Would you please tell me if it is possible to get the client IP from the backend http2 servers?
I couldn't find such configuration in the document here: https://nghttp2.org/documentation/nghttpx.1.html

**Comment by truongdo** [comment]
It did work. I think it is for HTTP backend. I'm using http2.

**Comment by tatsuhiro-t** [comment]
It works for both HTTP/1 and HTTP/2 backend.

**Comment by truongdo** [comment]
I've managed to get the real user IP with gRPC backend.
The nghttp2 balancer forwards the IP via metadata with the X-Forwarded-* enabled.
Thanks @tatsuhiro-t  and @dalf .

**Comment by mxl123** [comment]
Hello, can I see your conf file? I have no effect after this setting
`strip-incoming-x-forwarded-for=yes
add-x-forwarded-for=yes
strip-incoming-forwarded=yes
add-forwarded=by,for,host,proto
forwarded-by=ip
forwarded-for=ip`

**Comment by truongdo** [comment]
@mxl123 
I only add the below configuration,
add-x-forwarded-for=yes
The client ip is stored in the gRPC metadata with name "x-forwarded-for"
