### ISSUE TITLE
nghttpx as a reverse proxy with Mutual TLS

### ISSUE THREAD

**Issue by matthewfarwell** [nghttp2/nghttp2#1087]
Hi,

I have two services running on the same machine, both of which will use Mutual TLS and grpc. My config file is something like:

```
frontend=0.0.0.0,8443;no-tls

backend=127.0.0.1,43001;/service1/;proto=h2;tls
backend=127.0.0.1,42001;/service2/;proto=h2;tls
backend=127.0.0.1,43001;/service1;proto=h2;tls
```

The idea is that I will be able to use grpc to connect to <ip>:8443/service1 and it will present the service1 certificate (which is managed by and comes from service1, and is not stored in nghttpx). Similarly with service2. However, nghttpx does not present any certificate, because I've got no-tls specified. If I specify tls, then I need a certificate which is specifc to nghttpx. I would like nghttpx to do passthrough of the TLS (no management at all). Is this possible at all?

I'm testing the above using a simple openssl command:

```
$ openssl s_client -connect localhost:43001
$ openssl s_client -connect localhost:8443/nxquery
```

The first presents a certificate, the second does not. Is there a way of doing what I want, or do I have to find another solution. Thanks.

**Comment by tatsuhiro-t** [comment]
nghttpx cannot do passthrough TLS connection.  It always terminates TLS, and forwards requests in L7.

**Comment by matthewfarwell** [comment]
Thanks. That is what I thought. Would this be easy to change? Would a PR be long and involved?

**Comment by tatsuhiro-t** [comment]
nghttpx is designed as pure L7 proxy, so I think adding passthrough (L4) is relatively large change.
If you just want L4 proxy, there is not much stuff that nghttpx is good at because its ability is concentrated in L7.  Perhaps, haproxy is a good choice for L4?

**Comment by matthewfarwell** [comment]
Cool. Thanks for the response.
