### ISSUE TITLE
dynamic private key certname hostname for nghttpx

### ISSUE THREAD

**Issue by mhf-ir** [nghttp2/nghttp2#1089]
I need to know a work flow for use nghttp2 as front of my whole http(s) services like load balancer i will user dns roundrobin as distribute request. but i need to is there any solution that nghttpx can use dynamic private key and cert file for request based on request.
It's will be many domains that can be added or removed from another app 

another require for my use case is reload the configuration without downtime like `nginx reload` that connection not reset but hold until new configuration

for my use case
`sub.domain.tld` private  and cert file is like `/ssl/sub.domain.tld/cert.pem` and `/ssl/sub.domain.tld/priv.pem`
`main-domain.io` private  and cert file is like `/ssl/main-domain.io/cert.pem` and `/ssl/main-domain.io/priv.pem`

and if other options depend on host name will be awesome like `backend` `port` and etc...

**Comment by tatsuhiro-t** [comment]
nghttpx supports multiple certificates using --subcert option.  To apply the changes, nghttpx must be reloaded (see below).

Graceful shutdown is supported.  See https://nghttp2.org/documentation/nghttpx.1.html#signals
In short, send SIGHUP to nghttpx.

At the moment, certificates for frontend connection, and backend servers are completely independent.
