### ISSUE TITLE
Can trafficserver work as a http/2 forward proxy?

### ISSUE THREAD

**Issue by CODES-HOSTING** [nghttp2/nghttp2#1097]
Hello, anyone can tell me can trafficserver work as a http/2 forward proxy alone without nghttp2 serving as its frontend? Just like below.
```
Client --(HTTP/2)--> trafficserver --(HTTP/1.1)--> Origin Server
```

**Comment by CODES-HOSTING** [comment]
@tatsuhiro-t 
Looking forward to your reply!

**Comment by tatsuhiro-t** [comment]
It is best to ask this to traffic server developer.
