### ISSUE TITLE
libnghttp2_asio: using example server with ssl

### ISSUE THREAD

**Issue by TurtleWithWheels156** [nghttp2/nghttp2#1100]
Hi all,

I am currently playing around with the example code on the website for the c++ server and am experiencing a problem where running the server code that enables ssl terminates and issues this error:

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  use_certificate_chain_file: No such file or directory

This does not occur when I ran the example that doesn't enable it (which also does not work when sending a request from the browser), so I was wondering what the problem might be. Thanks.

**Comment by tatsuhiro-t** [comment]
The error says that certificate file was not found on your local file system.  Check the path to server certificate pem file.

**Comment by TurtleWithWheels156** [comment]
Just realized I was missing one of the files I previously thought I had generated already.  Thanks.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
