### ISSUE TITLE
respond to pings after goaway received

### ISSUE THREAD

**Issue by baranov1ch** [nghttp2/nghttp2#1103]
grpc-go (and I guess other gRPC libs may do so), uses [peculiar server shutdown sequence](https://github.com/grpc/grpc-go/blob/master/transport/http2_server.go#L1092), where it sends GOAWAY, then PING, then waits for PING ACK, and finally sends one more GOAWAY. If PING is not received, shutdown hangs and exits only by deadline (1 minute) or by client connection close.

This kind of graceful shutdown is described in RFC BTW:
```
   A client that is unable to retry requests loses all requests that are
   in flight when the server closes the connection.  This is especially
   true for intermediaries that might not be serving clients using
   HTTP/2.  A server that is attempting to gracefully shut down a
   connection SHOULD send an initial GOAWAY frame with the last stream
   identifier set to 2^31-1 and a NO_ERROR code.  This signals to the
   client that a shutdown is imminent and that initiating further
   requests is prohibited.  After allowing time for any in-flight stream
   creation (at least one round-trip time), the server can send another
   GOAWAY frame with an updated last stream identifier.  This ensures
   that a connection can be cleanly shut down without losing requests.

```

Instead of just waiting some 'at least one round-trip time', gRPC server uses PING-PING_ACK pair.

But nghttp2 stops acking pings after it has sent or received GOAWAY.

**Comment by tatsuhiro-t** [comment]
Thank you for telling this.  It is a bit creative, but I think it is allowed.

**Comment by tatsuhiro-t** [comment]
#1104 fixes this issue.
