### ISSUE TITLE
libnghttp2_asio: How can the server send GOAWAY?

### ISSUE THREAD

**Issue by faure76** [nghttp2/nghttp2#1106]
Hello.

I want to modify asio-sv.cc and asio-cl.cc in examples dir.
My goal is simple. The server is sending a GOAWAY frame.
But I can not find a way to do this.

Anyone has an idea?

**Comment by tatsuhiro-t** [comment]
There is no API in libnghttp2_asio to send GOAWAY directly.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
