### ISSUE TITLE
libnghttp2_asio and HTTP/1

### ISSUE THREAD

**Issue by ckaminski** [nghttp2/nghttp2#1108]
Is there a best practice for using HTTP/1 with this library?  Say I wanted to integrate with Beast or cpp-netlib - is there a way to tell the library to delegate HTTP/1 connections to another library?

**Comment by tatsuhiro-t** [comment]
At the moment, libnghttp2_asio is standalone library, and only supports HTTP/2.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
