### ISSUE TITLE
Enable ALPN support in nghttpx

### ISSUE THREAD

**Issue by shotahino** [nghttp2/nghttp2#1111]
Do we need to do anything in `nghttpx.conf` to enable ALPN or give a special option in `./configure` step when compiling? 
From the doc, it does not seem we need to do anything so long as `openssl` version requirement  >= `1.0.2`. is met. But I would like to double check...

I am getting these logs on a device that supports only ALPN (Android 7 or newer).
Older Android works fine because they seem to support NPN.

```
Jan 17 05:39:54 daemon.info nghttpx[740]: [INFO] SSL/TLS handshake completed (shrpx_connection.cc:507)
Jan 17 05:39:54 daemon.info nghttpx[740]: [INFO] cipher=ECDHE-RSA-AES256-GCM-SHA384 protocol=TLSv1.2 resumption=no session_id= (shrpx_connection.cc:510)
Jan 17 05:39:54 daemon.info nghttpx[740]: [INFO] [CLIENT_HANDLER:0x7540e080] SSL/TLS handshake completed (shrpx_client_handler.cc:194)
Jan 17 05:39:54 daemon.info nghttpx[740]: [INFO] [CLIENT_HANDLER:0x7540e080] No protocol negotiated. Fallback to HTTP/1.1 (shrpx_client_handler.cc:561)


OpenSSL> version
OpenSSL 1.1.0f  25 May 2017
```

**Comment by shotahino** [comment]
Please ignore this.

**Comment by ameeshg** [comment]
@shotahino Do you happen to remember the fix for this issue? I am having the same problem after updating to openssl 1.0.2
