### ISSUE TITLE
How to ack for Settings Synchronization?

### ISSUE THREAD

**Issue by hellojaewon** [nghttp2/nghttp2#1115]
I'm implementing http/2 client.
Right after the connection was successfully established, The client sends settings frame with NGHTTP2_SETTINGS_ENABLE_PUSH to 0 by using nghttp2_submit_settings.
The client handle settings frame sent by the server for NGHTTP2_SETTINGS_MAX_CONCURRENT_STREAMS.
Other parameters are ignored.

After that, the client and server send application data well.
However, in some cases I received the GOAWAY frame from the server and the error_code was NGHTTP2_SETTINGS_TIMEOUT.

As I think, the settings synchronization are automatically performed by the nghttp2 library.
If I was wrong, is there a way that the application recognizes ACK flag and replies to the settings frame for an acknowledgement to prevent from receiving GOAWAY frame?

Thank you.

**Comment by tatsuhiro-t** [comment]
Yes, nghttp2 library handles synchronization of SETTINGS.  It will send back SETTINGS with ACK flag set to peer.  In order for it to being sent, nghttp2_session_send or nghttp2_session_mem_send must be called to serialize/send frames to the peer.   This means that you have to call either of these even after you get HTTP response from server.

**Comment by hellojaewon** [comment]
Thank you for the answer.
