### ISSUE TITLE
nghttp2 asio and strands

### ISSUE THREAD

**Issue by akonskarm** [nghttp2/nghttp2#1116]
Hi

I was wondering if anyone has successfully managed to convert the asio examples to using a single io_service and many threads doing io_service.run() through strand or if anyone has any thoughts on how hard it would be to convert current examples so that io_service is wrapped inside strand.

I've read these threads:
#491 
#395 
#797 
#506 

To my understanding, the current nghttp2 asio API uses the "1 io_service per thread" model (http://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/examples/cpp03_examples.html#boost_asio.examples.cpp03_examples.http_server_2) instead of the "1 io_service across threads with strand" (http://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/examples/cpp03_examples.html#boost_asio.examples.cpp03_examples.http_server_3).

The "1 io_service per thread" seems better for a web server application, where many short sessions are expected and thus many io_services can be triggered because of the number of connections, but not in the cases where a single client is expected whose connection persists for hours. The latter applies to my case and I've currently resorted to something akin to #395 

Thanks in advance

**Comment by brano543** [comment]
Hello @akonskarm,

this post helped me to solve the problem you had by reading the examples in #395 and also https://stackoverflow.com/questions/17648725/long-running-blocking-operations-in-boost-asio-handlers.  
```
void handle_report(const response &res, string report_name, vector<json> data, boost::filesystem::path download_folder, header_map headers)
{
	auto closed = std::make_shared<bool>();
	res.on_close([closed](uint32_t error_code) {
		if (error_code != 0)
		{
			*closed = true;
		}
});
        //handle any blocking call

        //in the end do 
if (*closed)
	{
		return;
	}

	//send response
	res.write_head(200, headers);
res.end(data);
}
void get_report(const request &req, const response &res)
{
	//get the response body
	vector<uint8_t> *msgpack_v = new vector<uint8_t>();
	req.on_data([&res, msgpack_v](const uint8_t *data, std::size_t len) {
		if (len > 0)
		{
			std::copy(data, data + len, std::back_inserter(*msgpack_v));
		}
		else if (len == 0)
		{
			//set the response headers correctly
			header_map headers;
			headers.emplace("content-type", header_value{"application/octet-stream", 0}); //non-sensitive
			headers.emplace("access-control-allow-origin", header_value{"*", 0});		  //non-sensitive
			try
			{
				//set temporary download dir
				boost::filesystem::path input_path(boost::filesystem::current_path());
				boost::filesystem::path folder("/download");
				boost::filesystem::path download_folder = input_path / folder;

				//first we need to get the report name
				json object = json::from_msgpack(*msgpack_v);
				string report_name = object["name"].get<string>();
				vector<json> data = object["data"];

				//cleanup memory
				delete msgpack_v;

				//run in separate thread
				boost::asio::io_service &request_service = res.io_service();
				shared_ptr<boost::asio::io_service::work> work(new boost::asio::io_service::work(request_service));
				boost::thread t(bind(static_cast<std::size_t (boost::asio::io_service::*)(void)>(&boost::asio::io_service::run), boost::ref(request_service)));
				t.detach();
				request_service.post(boost::bind(&handle_report, boost::ref(res), report_name, data, download_folder, headers));
			}
			catch (std::exception &e)
			{
				json error;
				error["err"] = e.what();
				vector<uint8_t> msgpack_response = json::to_msgpack(error);
				string msgpack_string = string(msgpack_response.begin(), msgpack_response.end());

				res.write_head(500, headers);
				res.end(msgpack_string);
			}
		}
	});
}
```
This code works, but I still have a question why @tatsuhiro-t recommended using the same io_service from response object,because for me also worked just spawning a thread just like this. There was some catch though with doing just this, I forgot now what it exactly did,because I have tried like every combination possible to get it working. I think it was that client timed out and dropped the connection and only after that the thread tried to send the response. It would help me if you could clarify it a bit more. My understanding is the reason why we had to do it like my example above is that there is some really heavy lifting behind the hood, that the asio service manages the whole loop and when we run new thread we need to create "event handler" for this, because the get_report function has finished its execution.
```
boost::thread t(bind(&handle_report,  boost::ref(res), data, download_folder, headers);
t.detach();
```

**Comment by akonskarm** [comment]
Hi

I went through the HTTP2 specification, parts of nghttp2 code and TCP network socket programming examples and I think I finally have a clear idea why threading is done per connection and not per message for HTTP2 servers.

- TCP sockets work with byte streams, ie. you need to chop up the buffer manually to get a message (called a frame in http2). The TCP socket doesn't know how many messages are in the buffer, that needs to be part of the application logic.
- There are few guarantees as to the order the frames arrive in, in a single connection, namely:
-- the TCP implementation allows us not to worry about reconstructing the segmented TCP messages, ie. the whole frame is going to be contiguous in the buffer.
-- an HTTP2 request (single stream id) is made up of 1 or more HEADER frames followed by a DATA frame. The last frame of the stream will have the endStream bit equal to 1, the last HEADER of the stream will have the endHeaders bit equal to 1.
-- However HTTP2 is a multiplexed protocol, so frames for different streams can be intermixed. The buffer will not contain all the frames of each stream in order. That's the key to HTTP2 being fast.
-- Furthermore the first message for each stream must be ordered - if the first HEADERS for stream id 7 is sent before the first HEADERS for stream id 5, the endpoint needs to deduce that stream id 5 is dead. it should not accept stream id later on

- As a result it makes sense that you can have at most 1 reader thread and 1 writer thread per connection, but I'm not sure that the speedup would be greater than the communication costs. There are so many demands for things to arrive in a certain order that I think the current implementation is spot on.
