### ISSUE TITLE
TLS cert expiration

### ISSUE THREAD

**Issue by shotahino** [nghttp2/nghttp2#1118]
Is it possible for nghttpx mruby extension to look into the expiration time of the client certificate and return a custom code to them if the cert is expired ? 

Or is there a way to do this some other way?

**Comment by tatsuhiro-t** [comment]
At the moment, it is not possible, but the future version will be able to do that.

**Comment by shotahino** [comment]
@tatsuhiro-t Thanks. Do you have a rough timeline for this feature's availability?

**Comment by tatsuhiro-t** [comment]
The release which has this fix will be available around the end of this month.
The patch will be available earlier than that.

**Comment by shotahino** [comment]
@tatsuhiro-t Thank you. It would be great if
- mruby extension can read the client cert expiration 
- return some custom code to the client to indicate that its cert is about to expire or already expired

**Comment by tatsuhiro-t** [comment]
That is the plan.

**Comment by shotahino** [comment]
@tatsuhiro-t I saw your PR. Thanks for quickly responding. 
Does the mruby script run only after TLS connection succeeds? 

In other words, if a client presents an expired cert, will the mruby script still run?

My hope would be that
1.  A client presents an expired cert
2. TLS still succeeds  <-- this requires a small change in `verify_callback()` in `shrpx_tls.cc` 
3. mruby script reads the cert expiration and return custom code to the client

Generally, I would like to have a way for clients to know TLS failure is due to expired cert.

**Comment by tatsuhiro-t** [comment]
If client certificate is expired, handshake fails because verification fails.
In fact, I missed that.  I'm not sure OpenSSL offers the knob to the application that only certificate expiration is excluded from verification error.

**Comment by shotahino** [comment]
@tatsuhiro-t 
I tried modifying, something like this worked and let TLS go through even with an expired cert.
Not sure if there is an easy option to configure Openssl to do this, however.
```
int verify_callback(int ok, X509_STORE_CTX *ctx) {
    int err = X509_STORE_CTX_get_error(ctx);
    X509 *err_cert = X509_STORE_CTX_get_current_cert(ctx);
    if (err == X509_V_ERR_CERT_HAS_EXPIRED)  {
        return ok;
    }
    return ok;
}
```

**Comment by tatsuhiro-t** [comment]
Thank you.
There may be multiple certificates in the chain.  For client certificate, I think we should allow expired only leaf client certificate if nghttpx is configured to do so.  What do you think?

**Comment by shotahino** [comment]
> For client certificate, I think we should allow expired only leaf client certificate if nghttpx is configured to do so

@tatsuhiro-t Yes, I totally agree.

**Comment by tatsuhiro-t** [comment]
Thank you.  #1126 does it.

**Comment by shotahino** [comment]
@tatsuhiro-t Thank you very much for accommodating my request so quickly!
