### ISSUE TITLE
v1.30 is crashed with inet_pton on windows 10, x64

### ISSUE THREAD

**Issue by pengweichu** [nghttp2/nghttp2#1128]
I'm using the v1.30 to send the PUSH notifications to Apple server.
but got the crash with util.cc, the function is inet_pton, 

Please see attached the screenshot.

OS: Windows 10, 64bit
Compiler: Visual studio 2015, VC++ 14
Boost: 1.65.1

**PS: If i use the old version (the PR #971 ) then no any problem.**

<img width="1063" alt="crash" src="https://user-images.githubusercontent.com/12697283/36068682-d40459c4-0f15-11e8-9cbd-b0acd0930559.png">

**Comment by tatsuhiro-t** [comment]
Thank you.  This is interesting.  Have microsoft implemented ient_pton in Windows 10 finally?  If so, we need some macro to detect this.

**Comment by tatsuhiro-t** [comment]
I think #1130 fixes this issue.
I'm not sure what happened exactly, but if header file contains the following line (which is true for mingw32):

```c
#define InetPtonA inet_pton
```

This kind of issue happens.

**Comment by pengweichu** [comment]
@tatsuhiro-t thank you, I will test the new version and report here if it has any issue.
BR
