### ISSUE TITLE
Flow control WINDOW_UPDATE

### ISSUE THREAD

**Issue by hhub2017** [nghttp2/nghttp2#1143]
Hi,
I'm using nghttp version 1.7.1, and having problem with it stalling, ie. not returning WINDOW_UPDATE.
The test is:
$ nghttp -v -m 1 -w 11 https://www.foo.com/10k.html   (ie. request for ~10kB file).

The trace consist of:
- nghttp sends SETTINGS - Initial Windows Size: 2047.
- Receive 1439 bytes DATA frame -> Send WINDOW_UPDATE 1439.
- Receive 1448 bytes DATA frame -> Send WINDOW_UPDATE 1448.  (for 3 times)
- Receive 1982 bytes DATA frame -> Send WINDOW_UPDATE 1982.
- Receive 905 bytes DATA frame -> Stall waiting for WINDOW_UPDATE from nghttp

Is this a known problem? Should I update to the latest version of nghttp?
I also have the same problem using h2load.

Thank you,
-Harry

**Comment by worenga** [comment]
i cannot reproduce this. Would you mind sharing a test URL?

**Comment by hhub2017** [comment]
Here you go. Thank you for looking at it.
-Harry

**Comment by tatsuhiro-t** [comment]
You still have 1142 (= 2047 - 905) credit to send bytes.  HTTP/2 does not require peer to send WINDOW_UPDATE for all received bytes.

**Comment by hhub2017** [comment]
Thank you so much for your prompt response.
Given that the client may or may not respond with WINDOW_UPDATE, what does a server supposed to do?
What is the common server implementation for this case, when WINDOW_UPDATE doesn’t always arrive in response to some DATA frames in a packet?

-Harry

**Comment by tatsuhiro-t** [comment]
Just send DATA as much as you can.  And wait for WINDOW_UPDATE when window credit is 0.

**Comment by hhub2017** [comment]
Got it! Thank you so much for your help.
