### ISSUE TITLE
nghttp2 processing requests sequentially when requests belong to same client session

### ISSUE THREAD

**Issue by davik** [nghttp2/nghttp2#1158]
Scenario: I am running a rest server(nghttp2) with two APIs with 4 threads.
1. /something : takes some time to process
2. /anything : takes no time to process

Now, in the client side I am creating one **session**(which is essentially one TCP connection) and making two async requests, first to /something and next to /anything consecutively. The behavior I notice is that server doesn't process the second request until the the first one is finished. In the packet capture I can see nice implementation of HTTP2 multiplexing. But isn't this head of line blocking? Or is it that my expectation that the requests should be processed parallely rather in a interleaving fashion even if they are from the same TCP connection is wrong?

Note: If I create two different session or TCP connection for each request then they are processed parallely.

**Comment by davik** [comment]
https://stackoverflow.com/questions/49732553/nghttp2-server-handle-multiple-requests-from-a-client-on-different-threads

Same problem!

**Comment by tatsuhiro-t** [comment]
This depends on how you implement server and also timing of request and readiness of resource.
Are you using libnghttp2_asio or libnghttp2?

There are several reasons why the request seems to be served sequentially.
When a server gets first request, and sends its response, it might not see second request.  If response body is small, it might finish before it actually process the second one.

**Comment by davik** [comment]
> Are you using libnghttp2_asio or libnghttp2?

I am using a libnghttp2_asio. 

> When a server gets first request, and sends its response, it might not see second request. If response body is small, it might finish before it actually process the second one.

In packet capture I can see that the requests are multiplexed. So both the requests land server at the same time. (.pcap attached)
[capture.zip](https://github.com/nghttp2/nghttp2/files/1890394/capture.zip)



My sample program looks like this. There are 2 GET apis defined in the server and client makes the request one by one, **_/one_** first followed by **_/two_**
**Observations:**
1. Single TCP connection for both the requests
2. Both the requests are served by the same thread and sequentially

Now my expectation is even if the requests belong to same TCP connection, they must be served parallely rather in different threads. (The first request should not block the second request)



 ##  server.cpp

```c++
  #include <nghttp2/asio_http2_server.h>
  #include <iostream>

  using namespace nghttp2::asio_http2;
  using namespace nghttp2::asio_http2::server;

  int main(int argc, char *argv[]) {
    boost::system::error_code ec;
    http2 server;
    server.num_threads(4);


    server.handle("/one", [](const request &req, const response &res) {
	res.write_head(200);
	int sec = 5;
	std::cout << "/one req start " << std::endl;

	for(int i=0; i< INT_MAX; i++);

	std::cout << "/one req end " << std::endl;
	res.end("ONE\n");
	});

    server.handle("/two", [](const request &req, const response &res) {
	res.write_head(200);
	std::cout << "/two req start" << "" << std::endl;

	std::cout << "/two req end" << "" << std::endl;
	res.end("TWO\n");
	});

     if (server.listen_and_serve(ec, "localhost", "3000")) {
      std::cerr << "error: " << ec.message() << std::endl;
    }
  }
```
## client.cpp

```c++
#include <nghttp2/asio_http2_client.h>
#include <iostream>

using boost::asio::ip::tcp;

using namespace nghttp2::asio_http2;
using namespace nghttp2::asio_http2::client;

int main(int argc, char *argv[]) {
  boost::system::error_code ec;
  boost::asio::io_service io_service;
  
  // connect to localhost:3000
  session sess(io_service, "localhost", "3000");
  
  
  sess.on_connect([&sess](tcp::resolver::iterator endpoint_it) {
    boost::system::error_code ec;
    
    
    auto reqOne = sess.submit(ec, "GET", "http://localhost:3000/one");
    std::cout << "One req made" <<std::endl;
    reqOne->on_response([](const response &res) {
      // print status code and response header fields.
      std::cout << "One response start" << std::endl;
      std::cerr << "HTTP/2 " << res.status_code() << std::endl;
      for (auto &kv : res.header()) {
	std::cerr << kv.first << ": " << kv.second.value << "\n";
      }
      std::cerr << std::endl;
      
      res.on_data([](const uint8_t *data, std::size_t len) {
	std::cerr.write(reinterpret_cast<const char *>(data), len);
	std::cerr << std::endl;
      });
      std::cout << "One response end" << std::endl;
    });
    
    reqOne->on_close([&sess](uint32_t error_code) {
      // shutdown session after first request was done.
      sess.shutdown();
    });
    
    auto reqTwo = sess.submit(ec, "GET", "http://localhost:3000/two");
    std::cout << "Two req made" <<std::endl;
    
    
    reqTwo->on_response([](const response &res) {
      // print status code and response header fields.
      std::cout << "Two response start" << std::endl;
      std::cerr << "HTTP/2 " << res.status_code() << std::endl;
      for (auto &kv : res.header()) {
	std::cerr << kv.first << ": " << kv.second.value << "\n";
      }
      std::cerr << std::endl;
      
      res.on_data([](const uint8_t *data, std::size_t len) {
	std::cerr.write(reinterpret_cast<const char *>(data), len);
	std::cerr << std::endl;
      });
      std::cout << "Two response end" << std::endl;
    });
    
    reqTwo->on_close([&sess](uint32_t error_code) {
      // shutdown session after first request was done.
      sess.shutdown();
    });
    
  });
  
  sess.on_error([](const boost::system::error_code &ec) {
    std::cerr << "error: " << ec.message() << std::endl;
  });
  
  io_service.run();
}

```

**One more question:**
When I start the server it starts 2 threads, one I can understand is for **listen_and_serve**. What the other thread is required for?

**Comment by tatsuhiro-t** [comment]
Unfortunately threading in libnghttp2_asio is not implemented in the way you want.
An HTTP/2 session over a single TCP connection is processed by 1 thread.
Multi threading is for multiple clients.  Single connection does not gain any advantage here.

**Comment by virendrasingh007** [comment]
I believe if we have separate fd for reading and writing for the single connection then there will be gain as reading and writing on the same connection may happen simultaneously.  
Now, my question is does  libnghttp2 supports simultaneous reading (RxThread) and writing (TxThread) on a nghttp2_session object?

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
