### ISSUE TITLE
nghttp2::asio_http2::client::session reconnect on connection failure

### ISSUE THREAD

**Issue by sukanyaray007** [nghttp2/nghttp2#1159]
When I created the nghttp2::asio_http2::client::session, it will perform the connect automatically, and the session::on_connect and session::on_error will be triggered if connected or failed.

My question is: if failed to connect(for example, the network timeout), how can I let the session retry to connect ? Must I delete the session and create a new session or I can reuse the same session for calling session::on_connect and session::on_error ?

**Comment by tatsuhiro-t** [comment]
client::session should not be reused in this case.  It should be recreated.

**Comment by akonskarm** [comment]
Hi

In terms of design, the approach that worked for me was:
a) have a thread that runs a client class, which owns the session/io_service and brings a thread up. Save a pointer to the object in a global var.
b) have a second thread with a second io_service that checks the state of the connection every X seconds. If the connection is down, construct a new client instance and replace the old one.

Best
A.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
