### ISSUE TITLE
Failed to submit the request, Unknown error code

### ISSUE THREAD

**Issue by pengweichu** [nghttp2/nghttp2#1164]
Hi, we are using the NGHTTP2_ASIO to send the PUSH notification to Apple server, but after the server running a few days, we got the error when submit POST request,  but the error message shows "Unknown error code", please see below code (we are using boost 1.65.1 and NGHTTP2 v1.31.0).

We are run it on Windows 10, x64.

> 
> 		json11::Json finalJson = ob;
> 		std::string finalMsg = finalJson.dump();
> 
> 		std::string hostname = "https://";
> 		hostname += mAPNServer;
> 		hostname += ":443";
> 		hostname += "/3/device/";
> 		hostname += p->mTokenOrRegId;
> 		const nghttp2::asio_http2::client::request *request = mSession->submit(e, "POST", hostname, finalMsg, headers);
> 		if (!e)
> 		{
> 			request->on_response(std::bind(&APNSession::onResponse, shared_from_this(), std::placeholders::_1));
> 			request->on_push(std::bind(&APNSession::onPush, shared_from_this(), std::placeholders::_1));
> 			request->on_close(std::bind(&APNSession::onRequestClose, shared_from_this(), std::placeholders::_1));
> 		}
> 		else
> 		{
>              // Here we got the error: unknown error code
> 			ErrLog(<< "Failed to submit the send request, error = " << e.message().c_str());
> 		}

**Comment by gaddalasuresh99** [comment]
Hi,

I am facing the similar issue, is the above issue resolved? If resolved, May i know what can be done to resolve it please. Thanks.

**Comment by akonskarm** [comment]
It's possible that you are running out of stream IDs. You need to handle this case in your application code. Do you count the number of requests?

BR
A.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
