### ISSUE TITLE
How does nghttp2_asio client can set SNI?

### ISSUE THREAD

**Issue by soumyakantiroychowdhury** [nghttp2/nghttp2#1172]
I tried this:

```
  boost::asio::ssl::context tls(boost::asio::ssl::context::tlsv12_client);
  tls.set_default_verify_paths();

  boost::asio::ssl::stream <boost::asio::ip::tcp::socket> socket(io_service, tls);
  SSL_set_tlsext_host_name(socket.native_handle(), "api.myserver.io");

  configure_tls_context(ec, tls);

  session sess(io_service, tls, "api.myserver.io", "443");
```

And this:
```
  boost::asio::ssl::context tls(boost::asio::ssl::context::tlsv12_client);
  tls.set_default_verify_paths();

  SSL* ssl = SSL_new(tls.native_handle());
  SSL_set_tlsext_host_name(ssl, "api.myserver.io");

  configure_tls_context(ec, tls);

  session sess(io_service, tls, "api.myserver.io", "443");

```
In both cases I get this error:

> error: sslv3 alert handshake failure

I understand that boost::asio does not give any support to set SNI and I need to do it via the native handle (https://stackoverflow.com/questions/35175073/boost-ssl-verifies-expired-and-self-signed-certificates) - but in this case libnghttp2_asio library expects ssl::context but not ssl::stream so I have no option to set the server name.

Is it a bug in nghttp2_asio client library or I am missing something?

Thanks in advance.

**Comment by ColaColin** [comment]
It might be interesting to see how curl is doing this, from what I understand curl uses nghttp2 and it works with SNI domains.

**Comment by soumyakantiroychowdhury** [comment]
In fact nghttp (the http/2 client) also sends SNI.

**Comment by tatsuhiro-t** [comment]
This is probably boot asio specific.  For nghttp client, I have SSL object, and know when it is created, but boost asio wraps it.
I think https://www.boost.org/doc/libs/1_67_0/doc/html/boost_asio/overview/ssl.html is a way to go.  To do this, I have to add these code to somewhere around https://github.com/nghttp2/nghttp2/blob/86fab997b4f5b6321cf9859a16eb7c11f7775fa5/src/asio_client_session_tls_impl.cc#L59

**Comment by tatsuhiro-t** [comment]
I think #1173 fixes this issue.

**Comment by soumyakantiroychowdhury** [comment]
Perhaps, or before the async_connect().

An example implementation here: https://github.com/boostorg/beast/blob/bfd4378c133b2eb35277be8b635adb3f1fdaf09d/example/http/client/sync-ssl/http_client_sync_ssl.cpp#L66

**Comment by soumyakantiroychowdhury** [comment]
Thanks you very much.
