### ISSUE TITLE
Does nghttpx forwards tcp keep-alive packets received from client to backend servers. If not , is there any work-around

### ISSUE THREAD

**Issue by vineetvyas** [nghttp2/nghttp2#1179]
Does nghttpx forwards tcp keep-alive packets received from client to backend servers. If not , is there any work-around

**Comment by vineetvyas** [comment]
@tatsuhiro-t : To re-confirm my understanding : Does this mean if client to front-end connection sends a TCP keep-alive , nghttpx will not send that to Back-end connection.

You confirmation on this would really help us close this thread.

**Comment by tatsuhiro-t** [comment]
nghttpx does not forward TCP keep-alive to backend.

**Comment by vineetvyas** [comment]
@tatsuhiro-t  : Thanks
