### ISSUE TITLE
Handling websockets in nghttp2

### ISSUE THREAD

**Issue by alyssawilk** [nghttp2/nghttp2#1181]
Envoy needs to handle websockets for any H2 hops (https://github.com/envoyproxy/envoy/issues/1630) which I think will require some changes to nghttp2.

The proposed solution Envoy-side is to implement https://tools.ietf.org/html/draft-mcmanus-httpbis-h2-websockets-02 which would require changes such as the new configurable option, ":protocol" support, and changes to current CONNECT validation*

I'd be happy to try alternate ways of having websocket survive an H2 upgrade and downgrade, implement the existing draft in nghttp2, or let someone more familar with the nghttp2 code base tackle it - please let me know what makes the most sense.

*https://nghttp2.org/documentation/programmers-guide.html#http-messaging
If ”:method” is “CONNECT”, the request headers must include ”:method” and ”:authority” and must omit ”:scheme” and ”:path”.

**Comment by tatsuhiro-t** [comment]
There is a branch which implements earlier draft https://github.com/nghttp2/nghttp2/tree/ws
I'll update and merge it into master when it becomes RFC.

**Comment by alyssawilk** [comment]
Would you consider to merging as is and having it off by default and warnings around the enabling?  I'm not sure how much longer it will take to be codified but I believe we'll need some sort of websocket support before it gets there and if possible I'd rather start with the draft and adapt the code as it changes than have to do some more hacky workaround.

**Comment by PiotrSikora** [comment]
@tatsuhiro-t we mostly care about being able to proxy:

1. WebSocket connections over HTTP/2, i.e.:

```
    client <---------> Envoy <-----------------> server
            WebSocket         HTTP/2 connection
            HTTP/1.1          :method = CONNECT
                              :protocol = websocket
```

```
    client <---------> Envoy <-----------------> Envoy <---------> server
            WebSocket         HTTP/2 connection         WebSocket
            HTTP/1.1          :method = CONNECT         HTTP/1.1
                              :protocol = websocket
```

2. TCP streams over HTTP/2, i.e.:

```
    client <---------> Envoy <-----------------> Envoy <---------> server
             raw TCP          HTTP/2 connection          raw TCP
                              :method = CONNECT
                              :protocol = bytestream
```

regardless of how the client connected to the proxy, so we're not blocked on [draft-ietf-httpbis-h2-websockets](https://tools.ietf.org/html/draft-ietf-httpbis-h2-websockets) being implemented by the browsers.

**Comment by alyssawilk** [comment]
We don't need this feature for client-server, we need it for server-server.   We've got a production set up 

client  --- H1 -- envoy --- H2 ---  envoy --- H1 --- [cloud VM] 

and we need WebSocket to be able to survive the H2 hop.  Using H1 on that hop doesn't work for a number of reasons and we can't implement H2 CONNECT without nghttp2 support.  Unfortunately it's been a month or two since I filed this and checking with Piotr he tells me it's still likely 6-8 weeks before an RFC is published.  We don't need this end-to-end websocket until roughly end of quarter so I can patch in your PR, get the Envoy PR ready, and wait 8 weeks, but it would be really helpful if we could avoid cutting it close.

**Comment by ksmurchison** [comment]
FYI, you CAN use an existing release of nghttp2 (or master branch) for WebSockets right now.  I am using it along with wslay using the following code snippits:

configure.ac:

         PKG_CHECK_MODULES([NGHTTP2], [libnghttp2 >= 1.5], [
                 AC_DEFINE(HAVE_NGHTTP2,[],
                         [Build HTTP/2 support into httpd?])
                AC_CHECK_DECLS([NGHTTP2_SETTINGS_ENABLE_CONNECT_PROTOCOL],
                        [], [], [[#include <nghttp2/nghttp2.h>]])
                 with_nghttp2=yes
                 ],
                 AC_MSG_NOTICE([httpd will not have support for HTTP/2.  Consider installing libnghttp2 >= 1.5]))


h2.c:

#if HAVE_DECL_NGHTTP2_SETTINGS_ENABLE_CONNECT_PROTOCOL
static int nghttp2_extended_connect = 1;
#else
#define NGHTTP2_SETTINGS_ENABLE_CONNECT_PROTOCOL 0x08
static int nghttp2_extended_connect = 0;
#endif

    nghttp2_settings_entry iv[] = {
        { NGHTTP2_SETTINGS_MAX_CONCURRENT_STREAMS, 100 },
        { NGHTTP2_SETTINGS_ENABLE_CONNECT_PROTOCOL, 1 }  /* MUST be last */
    };
    size_t niv = (sizeof(iv) / sizeof(iv[0]));

    if (!nghttp2_extended_connect) {
        /* Need to forcefully allow :scheme, :path, :protocol pseudo-headers
           (this version of libnghttp2 doesn't understand extended CONNECT) */
        nghttp2_option_set_no_http_messaging(ctx->options, 1);
    }

**Comment by alyssawilk** [comment]
Ah, cool.  This was enough for me to actually test against the branch @tatsuhiro-t linked but as he noted it's on an earlier draft so I can't really use it.  Thanks regardless, even if I'm back to waiting on the IETF to do its thing :-P

**Comment by ksmurchison** [comment]
FWIW, the Websocket over HTTP/2 spec is almost out of the RFC editor queue.  Its been assigned RFC 8441 and appears to only to be waiting on the author to sign off on any editorial changes.  So, the -07 draft is essentially the final spec.

**Comment by jasnell** [comment]
RFC 8441 has been published!

It would be excellent to have built in support for the `NGHTTP2_SETTINGS_ENABLE_CONNECT_PROTOCOL` setting and the `:protocol` pseudo-header without having to turn http messaging off.

By support, I mean very minimally:

* Include `NGHTTP2_SETTINGS_ENABLE_CONNECT_PROTOCOL` in the `nghttp2_settings_id` enum
* Allow `:protocol` as a pseudo-header when `:method` is `CONNECT` and `NGHTTP2_SETTINGS_ENABLE_CONNECT_PROTOCOL` is set to `1`.

**Comment by ksmurchison** [comment]
Presumably the 'ws' branch will be merged soon:
https://github.com/nghttp2/nghttp2/tree/ws

**Comment by jasnell** [comment]
Ah! excellent! I'd missed that branch entirely! Will definitely be watching for that to land :-)

**Comment by tatsuhiro-t** [comment]
I'll merge ws branch (except for nghttpx stuff) with a bit more check and make it available in the next release.

**Comment by jasnell** [comment]
Thank you very much @tatsuhiro-t!
