### ISSUE TITLE
nghttp2-asio: how user can set max concurrent stream and initial window size?

### ISSUE THREAD

**Issue by soumyakantiroychowdhury** [nghttp2/nghttp2#1186]
By default these two values are 100 and 65535, respectively for MAX_CONCURRENT_STREAM and INITIAL_WINDOW_SIZE for servers and clients developed using the nghttp2 asio library. Is there is any option to change the configuration?

**Comment by tatsuhiro-t** [comment]
There is no functionality to change MAX_CONCURRENT_STREAMS and INITIAL_WINDOW_SIZE for both server and client at the moment.

**Comment by soumyakantiroychowdhury** [comment]
Can this be put on your roadmap? If not, can you please provide tips on how I proceed to make the changes on my own??

**Comment by tatsuhiro-t** [comment]
Edit the following lines, and set settings as you wish.  Also refer to manual https://nghttp2.org/documentation/nghttp2_submit_settings.html:

- https://github.com/nghttp2/nghttp2/blob/e5b3f9addd49bca27e2f99c5c65a564eb5c0cf6d/src/asio_client_session_impl.cc#L393
- https://github.com/nghttp2/nghttp2/blob/e5b3f9addd49bca27e2f99c5c65a564eb5c0cf6d/src/asio_server_http2_handler.cc#L301

**Comment by soumyakantiroychowdhury** [comment]
Thank you.

**Comment by testillano** [comment]
Hi, is this still missing in nghttp2 API ?
I didn't found it, so I think so.
Then, we would need to patch the library ? Any other alternative ?

Thank you very much

**Comment by lukasmoellerch** [comment]
Hi! Is there any way we could make this part of the public API? Maybe there could be a constructor parameter taking C++ versions of the options which are then forwarded to the underlying C implementation?

Thanks!

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
