### ISSUE TITLE
libnghttp2_asio: TCP_NODELAY?

### ISSUE THREAD

**Issue by ColaColin** [nghttp2/nghttp2#1187]
I am working on an application that cares a lot about making few small requests that arrive at the target server as fast as possible.

I am wondering if TCP_NODELAY could help with it and want to enable it to test, but am not quite sure about the right way to do it. Is there a "right way" to do it when using the asio lib?

In general: Any other things one could configure for optimal speed in delivering few small requests at the best possible one way-delivery time?

**Comment by tatsuhiro-t** [comment]
As for TCP_NODELAY, it is enabled by default.

**Comment by ColaColin** [comment]
So code of this https://nghttp2.org/documentation/libnghttp2_asio.html#multiple-concurrent-requests style enables TCP_NODELAY automatically?

Cool, thank you.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
