### ISSUE TITLE
Callback "on_data" is called twice but with empty data.

### ISSUE THREAD

**Issue by davtorresg** [nghttp2/nghttp2#1190]
We are implementing a REST server with asio_nghttp2 1.31.0 and we are facing a strange behaviour.
The callback "**on_data**" is called twice when we send a PUT operation. It could be fine if the data (json) was sent in two chunks of data. The problem is that the second call doesn't have any data. If we print the data received in each call, we see that all the json is on the first one.

Please, could you clarify if this is an expected behaviour?

Thank you very much.

**Comment by tatsuhiro-t** [comment]
I think the second on_data indicates EOF (or end of stream) if the second parameter is 0.

**Comment by himanshu390** [comment]
@tatsuhiro-t I too facing the same problem,Any solution to fix this issue?

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
