### ISSUE TITLE
Does nghttpx v1.32.0 support TLS 1.3 if I compile it with the latest OpenSSL-1.1.1-pre8(TLS 1.3 Draft 28 included) ?

### ISSUE THREAD

**Issue by joeshae** [nghttp2/nghttp2#1191]
Hi tatsuhiro-t, 

Does nghttpx v1.32.0 support TLS 1.3 if I compile it with the latest OpenSSL-1.1.1-pre8(TLS 1.3 Draft 28 included) ?

(1) If it has already supported, how can I enabled this feature in the configs? Using _tls-min-proto-version_ and _tls-max-proto-version_?

(2) If it has not supported yet, do you have any plan to add this?

Thank you!

**Comment by tatsuhiro-t** [comment]
nghttpx enables TLSv1.3 by default if it is built with openssl 1.1.1.  No additional configuration is necessary.
If 0-RTT stuff is required, use tls13-early-data branch.

**Comment by joeshae** [comment]
Test successfully.
Thank you tatsuhiro-t.
