### ISSUE TITLE
BoringSSL not vendored

### ISSUE THREAD

**Issue by bratkartoffel** [nghttp2/nghttp2#1196]
Hi there,

I've built and run nghttp2 with boringssl for quite a while now and it works like a charm. You've made some changes in the past to make it work (#373), so thanks for your work.
I tried to create an alpine package for that, but the PRs are currently on hold:
https://github.com/alpinelinux/aports/pull/4676
https://github.com/alpinelinux/aports/pull/4677

The boringssl docs explicitly say, that the applications should vendor the specific version they run on. Is it possible to include boringssl, maybe within third-party? Why have you decided not to include it?
That way I could create an alpine package for nghttp2 as boringssl would be included somehow.

I successfully used boringssl commit d2f87a777955dd53d7768b236ec3804fe50462a7.

Thanks,
Simon

**Comment by tatsuhiro-t** [comment]
There is no plan to vendor boringSSL.  The primary TLS library is OpenSSL.  To fully use nghttp2 applications, OpenSSL is required.  boringSSL lacks several features.  Vendoring boringSSL might show a illusion that it is the best TLS library for this project, but the reality is not.

**Comment by bratkartoffel** [comment]
Sorry for leaving this issue open without response so long.

I see your point that this might show that boringssl is the best implementation to use, but this issue could be resolved quite easily (e.g. by adding one sentence to the readme).
Nevertheless, I've thought long about this issue the last few days, and I'll close it for other reasons. Nghttp2 doesn't compile against boringssl (latest master) without applying one or two ugly hacks. And this shows me once again, that this could happen any time when google decides to change stuff without any notice.

Thanks for your time for looking into this and thanks for the great software you wrote.

Simon
