### ISSUE TITLE
Add two accesslog-format variables $bytes_received and $bytes_sent for nghttpx

### ISSUE THREAD

**Issue by joeshae** [nghttp2/nghttp2#1207]
Could you please add two accesslog-format variables $bytes_received and $bytes_sent for nghttpx?
We need these two variables to calculate our users' traffics in realtime, and it seems there is no way to achieve this.
Thank you very much!

**Comment by tatsuhiro-t** [comment]
As for $bytes_sent, we already have $body_bytes_sent variable.

**Comment by joeshae** [comment]
Yes, I've noticed $body_bytes_sent.
Could you add $bytes_received and $bytes_sent for nghttpx? Just like nginx does: http://nginx.org/en/docs/stream/ngx_stream_log_module.html#log_format
It's very useful.

Thank you!

**Comment by tatsuhiro-t** [comment]
I understand that $byte_received and $bytes_sent include request/response header length.  Is that right?

**Comment by joeshae** [comment]
Yes, that's correct!

**Comment by tatsuhiro-t** [comment]
I have a difficulty to count up HTTP/2 header fields because they are compressed and we have no way to get the compressed header size from libnghttp2.

**Comment by joeshae** [comment]
Got it! That's all right.
Thank you!
