### ISSUE TITLE
multiple streams with body failed with rst_stream

### ISSUE THREAD

**Issue by liyangliu43** [nghttp2/nghttp2#1210]
I am using nghttpx.
When there were multiple streams on Http2Upstream, more than 8, with backends established not so quickly, the stream 9 or 10 with body received RST_STREAM by Http2Upstream.
I followed with code, and found that  downstream was pending and dconn_ was not established, so there were no places to upload the body.
pls help. is it possible to solve this problem？

**Comment by tatsuhiro-t** [comment]
Which endpoint sends RST_STREAM?  Client?

**Comment by liyangliu43** [comment]
No, sended by nghttpx， as server here.

**Comment by liyangliu43** [comment]
yes， we just use http2_proxy.
We have thought to specify larger value of this option, but still feel not so all OK.
Because,
the option limit the connections/streams(h2) numbers of  backend node, make it too large is not OK, and if it's small, may be not OK for frontends concurrent numbers.

**Comment by tatsuhiro-t** [comment]
Right.  I'll fix this by storing post data somewhere if dconn is not available.

**Comment by liyangliu43** [comment]
Thanks
