### ISSUE TITLE
h2load command support tlsv1.3?

### ISSUE THREAD

**Issue by khs1994** [nghttp2/nghttp2#1218]
I use h2load command test my website(TLSv1.3 enable),but output is tlsv1.2

```bash
starting benchmark...
spawning thread #0: 10 total client(s). 100 total requests
TLS Protocol: TLSv1.2
Cipher: ECDHE-RSA-AES256-GCM-SHA384
Server Temp Key: ECDH P-256 256 bits
```

**Comment by tatsuhiro-t** [comment]
I think you have to compile nghttp2 with latest openssl master branch or 1.1.1 pre-release to get TLSv1.3 support.
