### ISSUE TITLE
Can be static_table const?

### ISSUE THREAD

**Issue by Hadatko** [nghttp2/nghttp2#1225]
Hi,
currently it looks like this global variable is not const and it can be. Then linker can move it from rw section to ro section. I am right? Or are data in this global variable changed during communication. My very simple test looks fine when i changed it to const. File: **nghtt2_hd.c**

**Comment by tatsuhiro-t** [comment]
Thank you.  It is now const.  See dfc0f248c60140194626c526221e45b6ee0b3d45

**Comment by Hadatko** [comment]
Thank you too.

**Comment by tatsuhiro-t** [comment]
I got compile errors with the suggested changes.

**Comment by Hadatko** [comment]
Maybe you didn't change const everywhere. I change around 4 data types to const. But no other type of change. Maybe i can give a pull request.
