### ISSUE TITLE
Can be VALID_HD_VALUE_CHARS and VALID_HD_NAME_CHARS const?

### ISSUE THREAD

**Issue by Hadatko** [nghttp2/nghttp2#1226]
Global variable DOWNCASE_TBL is const, but others two are not and looks like they can/should be. This way this variables will be placed in RO instead of RW section.

**Comment by tatsuhiro-t** [comment]
Thanks.  These 2 tables are now const.  See a1ea1696becea1d3c3c2720d44acbf5dae759560

**Comment by Hadatko** [comment]
Thank you
