### ISSUE TITLE
libnghttp2_asio, error on connect, "parse tlsext"

### ISSUE THREAD

**Issue by ColaColin** [nghttp2/nghttp2#1228]
I am using the asio library to try and connect to api.hitbtc.com. However I am not getting far. This program:

```
boost::system::error_code ec;
boost::asio::io_service io_service;

boost::asio::ssl::context tls(boost::asio::ssl::context::tlsv12);
tls.set_options(boost::asio::ssl::context::default_workarounds |
				boost::asio::ssl::context::no_sslv2 |
				boost::asio::ssl::context::no_sslv3);
tls.set_default_verify_paths();
configure_tls_context(ec, tls);

std::cout << "Configured tls context: " << ec.message() << std::endl;

session sess(io_service, tls, "api.hitbtc.com", "443");

sess.on_connect([](tcp::resolver::iterator endpoint_it) {
    std::cout << "http2 session connected!" << std::endl;
});

sess.on_error([](const boost::system::error_code &ec) {
	std::cerr << "http2 error: " << ec.message() << std::endl;
});

std::thread thread = std::thread([&io_service]{
	io_service.run();
});
thread.detach();
```

Outputs:
```
Configured tls context: Success
http2 error: parse tlsext
```

Why does it hit the error handler like that? I have no idea what "parse tlsext" wants to tell me.

**Comment by ColaColin** [comment]
This continues to be a problem.

**Comment by ColaColin** [comment]
Maybe this just wants to tell me "http2 not supported", online test sites tell me that.

The error message could be easier to understand for sure in that case.

**Comment by ALTinners** [comment]
I believe the last comment by @ColaColin is correct - I'm running this now and I believe that a lack of HTTP2 support for the target server causes this message. It could be a lot more clear about the issue when this happens.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
