### ISSUE TITLE
asio client and response timeout

### ISSUE THREAD

**Issue by akonskarm** [nghttp2/nghttp2#1236]
Hi Tatsuhiro

Trying to implement a timeout on the client: Client sends request and, if no response is received in 3 seconds, then a timeout has occurred for this particular request.
I do have the code below, but I'm wondering, does the timer callback need to perform any cleaning on the nghttp2 objects? Or is it OK to handle everything in the application logic, like this?

Thanks in advance,
A.

```
auto req = sess.submit(..);
auto timer = std::make_shared<boost::asio::deadline_timer>(io_service, boost::posix_time::seconds(10));
timer->async_wait([](const boost::system::error_code &ec) {
    if (ec != boost::asio::error::operation_aborted) { 
        std::cerr << "Request timed out" << std::endl;
    }
});

req->on_response([timer](const nghttp2::asio_http2::client::response &res) {
    if (timer->expires_at() > boost::asio::deadline_timer::traits_type::now()) {
        std::cerr << "Response arrived in time" <<std::endl;
        timer->cancel();
    } else {
        std::cerr << "Response arrived too late" << std::endl;
    }
}
```

Edit: fixed the code so that it actually works

**Comment by akonskarm** [comment]
This gives a core dump sometimes. Maybe needs req->on_close(/*cancel timer*/);?

**Comment by ranjithpp** [comment]
i have same question. requirement is server wants to silently drop request in some specific scenario after all the headers are received. 
can server don't do anything with respect to this particular stream? and after some time, client may cancel the stream using rst_stream, in that case, do server need to ignore this stream?

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
