### ISSUE TITLE
nghttp2 1.34.0 fails to build under macOS 10.13.6

### ISSUE THREAD

**Issue by Schamschula** [nghttp2/nghttp2#1240]
While building nghttp2 1.34.0 under macOS 10.13.6 with Xcode 10 cli tools, I get the following error:

> /usr/bin/clang++ -DHAVE_CONFIG_H -I. -I..  -DPKGDATADIR='"/opt/local/share/nghttp2"' -I../lib/includes -I../lib/includes -I../lib -I../src/includes -I../third-party -I/opt/local/include/libxml2 -I/opt/local/include/openssl -I/opt/local/include -DHAVE_CONFIG_H   -I/opt/local/include  -std=c++11 -pipe -Os -stdlib=libc++ -arch x86_64 -MT libnghttpx_a-tls.o -MD -MP -MF .deps/libnghttpx_a-tls.Tpo -c -o libnghttpx_a-tls.o `test -f 'tls.cc' || echo './'`tls.cc
> shrpx.cc:662:16: error: use of overloaded operator '<<' is ambiguous (with operand types 'shrpx::Log' and 'unsigned long')
>                << sizeof(addr.un.sun_path);
>                ^  ~~~~~~~~~~~~~~~~~~~~~~~~
> ./shrpx_log.h:103:8: note: candidate function
>   Log &operator<<(int16_t n) { return *this << static_cast<int64_t>(n); }
>        ^
> ./shrpx_log.h:104:8: note: candidate function
>   Log &operator<<(int32_t n) { return *this << static_cast<int64_t>(n); }
>        ^
> ./shrpx_log.h:105:8: note: candidate function
>   Log &operator<<(int64_t n);
>        ^
> ./shrpx_log.h:106:8: note: candidate function
>   Log &operator<<(uint16_t n) { return *this << static_cast<uint64_t>(n); }
>        ^
> ./shrpx_log.h:107:8: note: candidate function
>   Log &operator<<(uint32_t n) { return *this << static_cast<uint64_t>(n); }
>        ^
> ./shrpx_log.h:108:8: note: candidate function
>   Log &operator<<(uint64_t n);
>        ^
> ./shrpx_log.h:109:8: note: candidate function
>   Log &operator<<(float n) { return *this << static_cast<double>(n); }
>        ^
> ./shrpx_log.h:110:8: note: candidate function
>   Log &operator<<(double n);
>        ^
> ./shrpx_log.h:111:8: note: candidate function
>   Log &operator<<(long double n);
>        ^
> ./shrpx_log.h:112:8: note: candidate function
>   Log &operator<<(bool n);
>        ^
> shrpx.cc:1150:10: warning: 'daemon' is deprecated: first deprecated in macOS 10.5 - Use posix_spawn APIs instead. [-Wdeprecated-declarations]
>   return daemon(0, 0);
>          ^
> /usr/include/stdlib.h:298:6: note: 'daemon' has been explicitly marked deprecated here
> int      daemon(int, int) __DARWIN_1050(daemon) __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_0, __MAC_10_5, __IPHONE_2_0, __IPHONE_2_0, "Use posix_spawn APIs instead.") __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
>          ^

See https://gist.github.com/Schamschula/8015e8df4a0a9a70b6eae77f9d79ba38 for full log

**Comment by DomT4** [comment]
I can reproduce this on 10.14 with Xcode 10 FWIW. `git bisect` blames https://github.com/nghttp2/nghttp2/commit/9c824b87fe647c4d587fe365d9bd63704ec826fe.

**Comment by Schamschula** [comment]
Thanks!

Works for me!

https://github.com/macports/macports-ports/commit/28d336b5d14bea9ff6c46c5ac4173a7e1b2874f6

**Comment by DomT4** [comment]
Works for me as well, thanks!
