### ISSUE TITLE
Getting 502 Bad Gateway with tls-enabled backend

### ISSUE THREAD

**Issue by HeavenDuke** [nghttp2/nghttp2#1241]
I'm using nghttpx as a reverse proxy with Apache as backend server. Here is my configuration:
```
frontend=151.101.72.133,443
backend=151.101.72.133,15443;;tls
accesslog-file=/var/log/nghttpx/access.log
errorlog-file=/var/log/nghttpx/error.log
no-ocsp=yes
private-key-file=/etc/ssl/private/ssl-cert-snakeoil.key
certificate-file=/etc/ssl/certs/ssl-cert-snakeoil.pem
```
In this case, fetching resources directly from Apache is okay, but accessing through nghttpx results in `502 Bad Gateway`, with nothing showed up in both nghttpx & Apache's error log.

Any ideas on why this happens? Thanks!

**Comment by tatsuhiro-t** [comment]
Is the certificate of apache self signed?  If so you have to specify the certificate with --cacert option, or use -k to disable certificate verification as a last resort.
