### ISSUE TITLE
autotools check for boost-system is broken when using C++14 or C++17

### ISSUE THREAD

**Issue by jktjkt** [nghttp2/nghttp2#1242]
I want to use `libnghttp2_asio` from an application which uses C++17. Due to some incompatible changes in Boost-system between C++11, C++14 and C++17 where some low-level implementation details were moved away resulting in symbols `boost::system::detail::generic_category_instance` and `boost::system::detail::system_category_instance` ceasing to exist, it is important to build all of Boost, nghttp2 and the end application using the same C++ standard. (See also https://github.com/boostorg/system/issues/26 and https://github.com/boostorg/system/issues/24, for example.) However, this is hard to achieve with current autotools setup.

Even though I'm invoking `./configure` with a `CXXFLAGS=-std=c++17` env var, I'm still getting a non-descriptive error:
```
checking whether the Boost::ASIO library is available... yes
Could not find a version of the library!
```
I ended removing the `configure.ac` checks for Boost-ASIO and I just force-it to available:
```patch
diff --git a/configure.ac b/configure.ac
index efc0c297..e12c67b3 100644
--- a/configure.ac
+++ b/configure.ac
@@ -454,23 +454,7 @@ if test "x${request_jemalloc}" = "xyes" &&
 fi
 
 # Check Boost Asio library
-have_asio_lib=no
-
-if test "x${request_asio_lib}" = "xyes"; then
-  AX_BOOST_BASE([1.54.0], [have_boost_base=yes], [have_boost_base=no])
-
-  if test "x${have_boost_base}" = "xyes"; then
-    AX_BOOST_ASIO()
-    AX_BOOST_SYSTEM()
-    AX_BOOST_THREAD()
-
-    if test "x${ax_cv_boost_asio}" = "xyes" &&
-       test "x${ax_cv_boost_system}" = "xyes" &&
-       test "x${ax_cv_boost_thread}" = "xyes"; then
-      have_asio_lib=yes
-    fi
-  fi
-fi
+have_asio_lib=yes
 
 # The nghttp, nghttpd and nghttpx under src depend on zlib, OpenSSL,
 # libev, and libc-ares.
```

The upstream for the autotools' boost support [has abandoned the project in 2009](http://www.randspringer.de/boost/index.html). I am getting reasonable luck just building these with GCC-8 on x86_64 and also with GCC-7.2 via devtoolset packaging on RHEL7. Doing fancier stuff such as using the ARM Linaro toolchain (GCC 7) for corss-builds to ARM or using clang 6 on RHEL7 is currently broken -- but it can be solved by just not letting autotools perform its broken checks.

**Comment by kennymalac** [comment]
Is this still valid? Would like to use with C++17.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
