### ISSUE TITLE
Automatic Port on asio_http2 server

### ISSUE THREAD

**Issue by promgamer** [nghttp2/nghttp2#1252]
Hi,

Are you interested in a automatic port attribution when using asio_http2 server? Right now, we need to tell the server a port to listen. But asio supports not defining a port (and ask the operating system for a random available port).  This allows one to start a server without defining a port (asio will search for the next available port) and have a function that returns what port is it listening.

I think this could be a nice addition. If you're ok with this, I can send a PR.

Let me know.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
