### ISSUE TITLE
h2load fails on some 1xx intermediary responses in H1

### ISSUE THREAD

**Issue by wtarreau** [nghttp2/nghttp2#1259]
Hi,

we've recently implemented Early-Hints (https://tools.ietf.org/html/rfc8297) in HAProxy and tested it using h2load. I noticed some strange errors when doing it using H1 : 

    $ h2load-134  -n 10000 -c 1 -m 1 --h1 http://127.0.0.1:4445/
    (...)
    progress: 100% done
    h2load-134: h2load_http1_session.cc:88: int h2load::{anonymous}::htp_msg_completecb(http_parser*): Assertion `req_stat' failed.
    Aborted

It happens at least on 1.16.1 and 1.34. I took captures of this and figured that the problem is that h2load seems to consider the 103 message as a final one, then it sends a new request (thus it creates some pipelining), and at some point it gets more responses than the configured amount of requests and fails. I did a quick script that I passed on the tcpdump's ASCII output and it indeed shows that the request count grows as fast as the sum of 103+200.

This doesn't happen at all in H2, it works fine. I suspect that on H2 it simply uses the ES bit on the frame to detect the end and doesn't care about status codes, which would make sense.

If anyone is interested in trying to reproduce this, here's the configuration I'm using on haproxy (latest master from https://github.com/haproxy/haproxy, or 1.9-dev7 and above, not yet released) : 

    global
        log stdout format raw daemon
        stats socket /tmp/sock1 mode 666 level admin
        stats timeout 1h
        tune.ssl.default-dh-param 1024

    defaults
        mode http
        timeout connect 4s
        timeout client 6s
        timeout server 20s

    listen EH103
        bind :4442 name HTTP1-TLS ssl crt rsa+dh2048.pem npn http/1.1
        bind :4443 name HTTP2-TLS ssl crt rsa+dh2048.pem npn h2 alpn h2
        bind :4445 name HTTP1-CLR
        bind :4446 name HTTP2-CLR proto h2

        http-request early-hint link "</blah.css>; rel=preload; as=style"
        http-request early-hint link "</blah.js>; rel=preload; as=script"

        server srv 127.0.0.1:8000

A local server must run on port 8000 here, but you can also replace the server line with "redirect location /" if you don't have any at hand. I can easily run some tests now if that helps.

It's not blocking for me at all, as I could validate the behaviour I needed, thus please see this bug as low priority. However if the same code is shared with the nghttp client or with nghttpx, you could be interested in checking how it will deal with 1xx and particularly 103.

**Comment by tatsuhiro-t** [comment]
It looks like h2load does not do any special handling of non final response.  Will fix it.

**Comment by tatsuhiro-t** [comment]
As for code reuse, this HTTP/1 non-final response handling is specific to h2load.

**Comment by tatsuhiro-t** [comment]
Fix committed.  If you still have this issue, please reopen.

**Comment by wtarreau** [comment]
Just built and tested, I can confirm the fix works fine for me! Thanks!
