### ISSUE TITLE
2 API Wishlist/Considerations

### ISSUE THREAD

**Issue by jwaterloo** [nghttp2/nghttp2#126]
This is specifically regarding the high level C++ ASIO api but could apply to any. I feel three/four methods need adding for normal web development and to take advantage of HTTP/2 server push features.

1) Need to be able to call the server, submit requests and receive responses, from inside and outside of client requests. This facilitates the efficient generation of content/including without having to go outside of the application through sockets.

1a) the request class, as in "std::shared_ptr<request> req", could use a method vector<response> submitRequest(std::shared_ptr<request> newRequest). This is so web developer can compose responses by aggregating other responses. While similar to a client this would not involve any socket calls.

1b) The http2 server class could use a method vector<response> submitRequest(std::shared_ptr<request> newRequest). Similar need as in 1a) but doesn't require a client to have initiated a request. A background task in the same process as the web server may ask for html that it will use to create an email or convert to PDF. Since all of this is in-process these should not involve any socket based client calls.

2) Most have been underestimated the value of server push to the developer community. HTTP has long been considered defective for its lack of post redirects. This has led some to store post data in a database or session temporarily when the next redirect will immediate fetch the data. This limits the scalability of ones web pages as they are no longer stateless. This led to the creation of flash scope memory which is a short lived session that last between requests. HTTP/2 server push now allow redirected content, which is dependent upon the context, to be pushed with the redirect. Web development now become easier and web site scalability increases with the reverting back to stateless architecture. I noticed the "req->push("GET", "/my.css");" loses the ability to vary based on the context , the reason for the resource dependency. I would recommend adding one or both families of overloads.

2a) req->push("GET", "/my.css", actual_content_stream_string_byte_array);
2b) req->push("GET", "/my.css", shared_ptr<void >application_specific_context_available via the req);

Consider this common use case:
A client posts data to server.
Most good websites uses PRG, post redirect get, to preserve the back buttons.
Unfortunate there was a problem with the posted data.
The posed data or data derived from the posted data and additional error messages need to be sent back as part of the redirect.
Since post data can't be sent in a redirect, hence the historical defect, server push is used to send the form that generated the post pre-populated with the posted data and any error messages and redirect to this context specific server pushed resource. Your current API is a little wanting in differentiating between initial display of the form the generates a post and the populated version with error message.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
