### ISSUE TITLE
ASIO load balancing question

### ISSUE THREAD

**Issue by finkandreas** [nghttp2/nghttp2#1262]
I'm having a question considering load balancing of the ASIO high-level interface. It seems that for each thread there is a separate boost::asio::io_service. I was trying this program:
```
#include <nghttp2/asio_http2_server.h>
#include <iostream>

using namespace nghttp2::asio_http2;
using namespace nghttp2::asio_http2::server;

int main(int argc, char *argv[]) {
  boost::system::error_code ec;
  boost::asio::ssl::context tls(boost::asio::ssl::context::sslv23);
  tls.use_private_key_file("server.key", boost::asio::ssl::context::pem);
  tls.use_certificate_chain_file("server.crt");
  nghttp2::asio_http2::server::configure_tls_context_easy(ec, tls);
  http2 server;
  server.num_threads(2);
  server.handle("/sleep", [&server](const request &, const response &res) {
    std::cerr << "Starting to sleep" << std::endl;
    sleep(60);
    res.write_head(200);
    res.end("sleep\n");
  });
  server.handle("/quick", [](const request &, const response &res) {
    std::cerr << "Starting quick handler" << std::endl;
    res.write_head(200);
    res.end("quick\n");
  });
  server.listen_and_serve(ec, tls, "localhost", "4000");
  return 0;
}
```
Here I have a very slow handler, and a quick one. I start the server, Call the slow handler with curl, and then I try to call the quick handler with other curl instances.
It seems, that every second quick handler call is stuck. I think it is because it will be in the worker queue for the io_service which currently handles the slow handler.
Is there a reason, why there is an io_service instance per thread? If I understand [this article](https://theboostcpplibraries.com/boost.asio-scalability) correctly boost can take care of load balancing, if you create multiple threads for the same io_service.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
