### ISSUE TITLE
questions on encapsulating asio library with C-API

### ISSUE THREAD

**Issue by sandylss** [nghttp2/nghttp2#1263]
Hi, I'm implementing an HTTP2 server and integrating it with a large C project. I plan to encapsulate asio-library with C-API because in that way I/O part(such as lib-event) can be saved. I will save time on caring about multiple connections on a server because it seems the example of C-server with libevent just forwards data? 

The main problem is that in C++, we can use **lambda function and closure** to capture temporary variables like `req.on_data([&req, &res](const uint8_t *data, std::size_t len) {...}` but if I encaps with C-API, how do I capture `response`?

I've made some effort. I defined a new callback function with `response` as its parameter.
~~~c++
typedef std::function<void(nghttp2::asio_http2::server::response &, const uint8_t *, std::size_t)> data_cb_with_rsp;

// register callback function to the smart pointer
void request_impl::on_data_with_rsp(data_cb_with_rsp cb) { on_data_cb_with_rsp_ = std::move(cb); }

// execute the function when there is data
void request_impl::call_on_data(nghttp2::asio_http2::server::response &rsp, const uint8_t *data, std::size_t len) {
  if (on_data_cb_) {
    on_data_cb_(data, len);
  } else if (on_data_cb_with_rsp_) {
    on_data_cb_with_rsp_(rsp, data, len);
  }
}

// in function "int on_data_chunk_recv_callback", find the response automatically
strm->request().impl().call_on_data(strm->response(), data, len);
~~~
In this way I'm trying to fill the response by referring to the stream so that C program can use asio-library. 

Now I can compile and run the program. The callback function can be waken up when a chunk of data arrives. But though I respond the client, the client receives a null reply.

So I wonder is it possible to use the response in this way? Or I should just use nghttp2 C-API?

Thanks a lot.

**Comment by sandylss** [comment]
The problem is at I set status_code 204, which forbids response body. Now it works.
Hope this might help. May close the issue.

**Comment by tatsuhiro-t** [comment]
Looks like you made it.  FTR, I think boost ASIO is too much complicated and I don't recommend to use it with C.  My recommendation is just use plain libnghttp2 and use libev or libevent.  It performs best.
