### ISSUE TITLE
How to get statistics from nghttpx 

### ISSUE THREAD

**Issue by zdenek-pizl** [nghttp2/nghttp2#1268]
Greetings,

 is there any way how to get statistics of i.e. 
- data transferred, 
- time to serve a request, 
- number of requests served per second 
- number of errors, success, ...

Optimal way would be to provide some standard interface for collectd/statsd/other_collector. But it would be nice to have at least something in log file for example.

Is there any plan to extend functionality like this? Thank you, .zp.

**Comment by tatsuhiro-t** [comment]
There is no direct way to get them from nghttpx at the moment. I think it would be very handy if it is available.
The workaround is calculate them from access log.  We have number of variables available to access log: see https://nghttp2.org/documentation/nghttpx.1.html#cmdoption-nghttpx-accesslog-format

**Comment by zdenek-pizl** [comment]
Thanks, it looks using custom access.log format together with i.e. collectd's plugin tail is feasible way.
