### ISSUE TITLE
epoll server example with no tls/ssl

### ISSUE THREAD

**Issue by kunalekawde** [nghttp2/nghttp2#1281]
Hi,

I'm interested in using nghttp2 with following model, external epoll (application) on a single threaded app with nghttp2 (w/o any threads) and without TLS. Is there any example of epoll server without TLS ?

Thanks,
Kunal

**Comment by iwontsahreit** [comment]
> Hi,
> 
> I'm interested in using nghttp2 with following model, external epoll (application) on a single threaded app with nghttp2 (w/o any threads) and without TLS. Is there any example of epoll server without TLS ?
> 
> Thanks,
> Kunal

Were you able to write such a server? Really need help.

**Comment by kunalekawde** [comment]
> 
> 
> > Hi,
> > I'm interested in using nghttp2 with following model, external epoll (application) on a single threaded app with nghttp2 (w/o any threads) and without TLS. Is there any example of epoll server without TLS ?
> > Thanks,
> > Kunal
> 
> Were you able to write such a server? Really need help.

Yes, basically the server part of epoll on single thread is independent of this. The place of integration would be when data is read from socket or written. nghttp2 callbacks should be registered during the connection establishment or initialization and when the epoll socket is triggered, the respective server application - receive functionality  should be invoked which in-turn should invoke the nghttp2 callback to read and process the incoming data, it would then invoke the application registered callbacks which can then process the L7 data.
