### ISSUE TITLE
Update httpbin server

### ISSUE THREAD

**Issue by jeroen** [nghttp2/nghttp2#1290]
See https://nghttp2.org/blog/2014/05/27/httpbin-for-http-slash-2-clients/

The httpbin server running on https://nghttp2.org/httpbin/ is quite old and has some bugs. Would it be possible to upgrade to the latest version?

Deployment instructions: https://github.com/requests/httpbin#officially-deployed-at

**Comment by tatsuhiro-t** [comment]
Updated httpbin to the latest version.
