### ISSUE TITLE
Documentation is unclear about compiler requirements when not using C++

### ISSUE THREAD

**Issue by gdt** [nghttp2/nghttp2#1293]
README.rst says that for C++ parts of nghttp2, C++14 and gcc>=6|clang>=6 is needed.  It is unclear what the requirements are when not including asio or tools.  On NetBSD 7, with gcc 4.8, the build appears to succeed, with a C compiler but not C++ compiler available.  I am guessing that for the C-only part, supporting C99 is good enough.

**Comment by tatsuhiro-t** [comment]
C source code is pretty much conservative and I think gcc 4.8 is good enough.  I'm not sure the bare minimum version, but it is not probably good idea to find the lower gcc version because old ones might contain bugs.

**Comment by gdt** [comment]
Thanks.   If it's "conservative" then 4.5 should be fine :-)   So perhaps add to the readme:

For the C parts, a C99 compiler is required.  gcc 4.8 is known to be adequate.

**Comment by tatsuhiro-t** [comment]
@gdt Thank you for suggestion.  Added the text to README, see de85b0fda592934a64886ba6a584424b777e97ac

@akonskarm gcc 4.9.4 might work.  I don't have old compilers anymore, so don't know how it works.
