### ISSUE TITLE
nghttp2 core dumps with c++ asio

### ISSUE THREAD

**Issue by akonskarm** [nghttp2/nghttp2#1299]
Hi Tatsuhiro

I've experienced two cases of core dumps. My best solution right now is to add more checks in the asio code:

a) request_impl::cancel on the asio_client was producing core dump sometimes when it tried to cancel a request that we deemed as "timed out". I can provide this PR on asio_client_request_impl.cc:
```
 void request_impl::cancel(uint32_t error_code) {
-  auto sess = strm_->session();
-  sess->cancel(*strm_, error_code);
+  if (strm_ != nullptr) {
+      auto sess = strm_->session();
+      if (sess != nullptr) {
+          sess->cancel(*strm_, error_code);
+      }
+   }
 }
```

b) on asio_server, I sometimes get a core dump when a  client is disconnected for a few minutes and then reconnects. Then it's the call to response_impl::io_service() that fails (asio_server_response_impl.cc)

```
boost::asio::io_service &response_impl::io_service() {
  return strm_->handler()->io_service();                                                                                                                                     
}
```

Maybe this should also be changed to return pointer to io_service or nullptr?

**Comment by zvasilev** [comment]
Hello Tatsuhiro, 

I'm using client asio library and hit that segfault too.
Still not sure that use the library incorrectly, or I missed some documentation but cannot find a solution without that check.

There is also segfault in session_impl::shutdown if the session is nullptr.
This happens only if the io_service has more than one thread.

void session_impl::shutdown() {
  valid_for_use_ = false;
  if (stopped_) {
    return;
  }

  + if(session_) {
    nghttp2_session_terminate_session(session_, NGHTTP2_NO_ERROR);
    signal_write();
  + }
}

And thank you for the great library!

**Comment by akonskarm** [comment]
Would anyone have any ideas for this?

**Comment by zvasilev** [comment]
Hello,

Had similar problems. 
After reread core C library docs, there is written that nghttp should be called from the same thread.
I've made additional io_service with just one thread. Still does not observe any crash.

**Comment by akonskarm** [comment]
Thank you for your answer

I have multiple threads posting to a single io_service and a separate thread is running the io_service (server.num_threads(1);). Do you think this is the source of the problems above?

**Comment by zvasilev** [comment]
I'm using the same architecture. 
Posting HTTP task from different threads to a single io_service.

I do a few things different than the example.
First, initialize error and connect callbacks, and after that call resolve.
Like https://github.com/nghttp2/nghttp2/pull/1313
Also, I do not call cancel but sess_ptr->shutdown(); when the connection is no more needed.

**Comment by akonskarm** [comment]
Thank you very much!
I had forgotten about that detail.

In terms of asio client, have you managed to implement a timeout?
I have another thread here: 
https://github.com/nghttp2/nghttp2/issues/1236

**Comment by zvasilev** [comment]
I still don't implement a timeout for http2, because of move to ngttp2 recently from my custom implementation.
For other types of connections IMAP/SMTP I'm implementing timeout a bit different because I want to shut down connection if took too much time waiting read/write. For example, iOS will terminate that app if it doesn't close on the phone lock.

I call reschedule_timeout_timer on each phase , connect , resolve, read ...
my code looks like this

void reschedule_timeout_timer(handler_type_t const& handler) {

            std::error_code ec_timer;
            _deadline.cancel(ec_timer);

            _deadline.expires_from_now(std::chrono::seconds(is_in_background_mode()?25:45));
            _deadline.async_wait(std::bind(&raw_connection::check_deadline, this, std::placeholders::_1, handler));
        }

        void check_deadline(std::error_code const&ec, handler_type_t const& handler) {

            if(ec == asio::error::operation_aborted) {
                return;
            }
        
            if(!base::is_closed()) {
            
                if (_deadline.expires_at() <= std::chrono::high_resolution_clock::now()) {

                    std::error_code ec_timer;
                    _deadline.cancel(ec_timer);
                
                    std::error_code ignored_ec;
                    socket_.lowest_layer().close(ignored_ec);
                    base::set_closed();

                    base::_strand.dispatch(
                        asio::detail::bind_handler(
                            handler, std::error_code(errors::operation_timeout, errors::error_category())), _allocator);
                }
                else {
                    _deadline.async_wait(std::bind(&raw_connection::check_deadline, this, std::placeholders::_1, handler));
                }
            }
        }

**Comment by akonskarm** [comment]
Unfortunately it's required to have a timeout because of the way http2 concurrent streams work.
Ie. you can run out of throughput because of old outstanding requests.

**Comment by ranjithpp** [comment]
@akonskarm did you write an API to clean up the resource?

**Comment by akonskarm** [comment]
I don't have any code that I trust tbh

**Comment by ranjithpp** [comment]
is there a clean up required at nghttp2 if not to send reset stream @akonskarm

**Comment by gaddalasuresh99** [comment]
Hello all,

I see many people running io_service in one thread and passing the requests from multiple different threads. Are you also getting the response for each request and how you are handling it.

Actually, my client code calls multiple requests which have to be submitted to server(using session) and then get the result for each request and send it back toclient. all the requests and responses should be asynchrnous here. Can someone please advise. thanks.

**Comment by ranjithpp** [comment]
as per documentation session object should be protected, you can find more information in api documentation

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
