### ISSUE TITLE
Is the ":authority" header of PUSH_PROMISE frames validated?

### ISSUE THREAD

**Issue by nicolas-grekas** [nghttp2/nghttp2#1307]
The RFC says it MUST be validated, so maybe that's already done by default?

**Comment by tatsuhiro-t** [comment]
nghttp2 does not validate :authority.  The application is responsible for doing it.

**Comment by nicolas-grekas** [comment]
Thanks for the confirmation!

**Comment by bagder** [comment]
@tatsuhiro-t, so in the case the push is attempted with a bad/wrong `:athority`, what error code should the push callback return to trigger the PROTOCOL_ERROR for the stream that the spec mandates?

**Comment by tatsuhiro-t** [comment]
@bagder https://nghttp2.org/documentation/types.html#c.nghttp2_on_header_callback
If you find bad authority in on_header_callback, call nghttp2_submit_rst_stream with the desired error code, and then return NGHTTP2_ERR_TEMPORAL_CALLBACK_FAILURE.

**Comment by bagder** [comment]
Thanks a lot @tatsuhiro-t !
