### ISSUE TITLE
Violation in HTTP messaging rule

### ISSUE THREAD

**Issue by f0rtung** [nghttp2/nghttp2#1316]
Hi!
I create a stream using nghttp2_submit_headers, and then in on_frame_send_callback I send data that relates to the request. I plan to send headers each time using nghttp2_submit_headers, and then the data. After the first such request, the data is successfully processed by the server, but during the second attempt the server does not accept headers (-532 error, NGHTTP2_ERR_HTTP_MESSAGING), on_begin_headers_callback is called, but control is not transferred to on_header_callback.
Tell me what am I doing wrong?
Headers that I post first:
: method
: scheme
: authority
: path
x-payload-size
x-payload-type
And second:
x-payload-size
x-payload-type

[id=1] [  4.821] send SETTINGS frame <length=6, flags=0x00, stream_id=0>
          (niv=1)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
[id=1] [  4.822] recv SETTINGS frame <length=6, flags=0x00, stream_id=0>
          (niv=1)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
[id=1] [  4.822] recv (stream_id=1) :method: POST
[id=1] [  4.822] recv (stream_id=1) :scheme: https
[id=1] [  4.822] recv (stream_id=1) :authority: localhost:8080
[id=1] [  4.822] recv (stream_id=1) :path: /
[id=1] [  4.822] recv (stream_id=1) x-payload-type: 2
[id=1] [  4.822] recv (stream_id=1) x-payload-size: 38
[id=1] [  4.822] recv HEADERS frame <length=46, flags=0x04, stream_id=1>
          ; END_HEADERS
          (padlen=0)
          ; Open new stream
[id=1] [  4.822] recv DATA frame <length=38, flags=0x00, stream_id=1>
[id=1] [  4.822] recv (stream_id=1) x-payload-type: 0
[id=1] [  4.822] recv (stream_id=1) x-payload-size: 4
[  4.822] [INVALID; error=Violation in HTTP messaging rule] recv HEADERS frame <length=8, flags=0x04, stream_id=1>
          ; END_HEADERS
          (padlen=0)
[id=1] [  4.822] recv SETTINGS frame <length=0, flags=0x01, stream_id=0>
          ; ACK
          (niv=0)
[id=1] [  4.822] send SETTINGS frame <length=0, flags=0x01, stream_id=0>
          ; ACK
          (niv=0)
[id=1] [  4.822] send RST_STREAM frame <length=4, flags=0x00, stream_id=1>
          (error_code=PROTOCOL_ERROR(0x01))
[id=1] [  4.822] stream_id=1 closed

**Comment by tatsuhiro-t** [comment]
That's because you didn't set END_STREAM flag set in 2nd HEADERS frame which contains trailer fields in HTTP semantics that terminates stream.

**Comment by f0rtung** [comment]
@tatsuhiro-t  Could you explain in more detail? I would like to use the same stream, without closing it, to exchange messages (header + data), how is it necessary in this case to specify the flags?

**Comment by f0rtung** [comment]
If I set the END_STREAM flag, then I do not receive the data that follows the second header.

**Comment by tatsuhiro-t** [comment]
You cannot use HTTP/2 in that way.
HTTP/2 still use HTTP semantics defined in RFC 7230 to 7225.
Read https://tools.ietf.org/html/rfc7540#section-8.1 to know what HTTP message is.
