### ISSUE TITLE
Design of the C++ API

### ISSUE THREAD

**Issue by brjoha** [nghttp2/nghttp2#1317]
This excerpt is from the Programmer's guide...

"Not doing I/O makes embedding nghttp2 library in the existing code base very easy. Usually, the existing applications have its own I/O event loops. It is very hard to use nghttp2 in that situation if nghttp2 does its own I/O".

...and I fully agree with this.  However, the experimental C++ API appears to break this paradigm by encapsulating the ASIO event loop.  I would strongly recommend looking at how Boost::Beast has provided an HTTP/1.x protocol layer using ASIO without doing this.  It is integrated alongside ASIO rather than over it.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
