### ISSUE TITLE
nghttp2_session_send sending frames sequentially whereas mem_send sends in one transfer

### ISSUE THREAD

**Issue by kunalekawde** [nghttp2/nghttp2#1322]
Hi All,

I'm trying HTTP/2 transfer for multiple GET requests with nghttp2 integrated echo server.
The observation is that if client uses nghttp2_session_send, the HEADER frames are sent in sequence, so if there are 3 requests, HEADER(1) would be sent, response received then HEADER(3) - response received and so on. Whereas, if nghttp2_session_mem_send is used, I see all 3 HEADER frames are sent in single transfer itself.

Initially I saw this in libcurl and later tried same using nghttp2 examples libevent-client/client and libevent-server. client.c example uses mem_send and libevent-client uses send, observed the behavior here.

My main concern here is that if dependency and priority is specified, since in one case, requests are in sequence, dependency information is not valid, libcurl is sending dependent streamid as 0 - may be since its already complete.

Please let me know if this observation is valid/invalid or if anyone has seen similar. 

Thanks

**Comment by kunalekawde** [comment]
My earlier test with libevent-client were not correct as it was sending multiple requests separately on new connection and hence seen separately, I retested with libevent-client sending over same connection, its sending both HEADER frames in same HTTP/2 transfer. Then, the only reason I see this in libcurl could be on how the I/O is performed.

**Comment by kunalekawde** [comment]
As a generic HTTP/2 behavior, if client sends request in separate transfers  e.g HEADER(1) first then HEADER(3) followed by HEADER(5) with 3(weight=20) & 5(weight=80) depending on 1, the server would process HEADER(1) first -- pass it to application then HEADER(3) -- pass it to application, basically it wont process the stream dependency & priority right ? 
So it is correct to say that for server to process the stream dependency & priority it needs to receive the HEADERS at same instant (in single http/2 transfer i.e HEADER(1), HEADER(3), HEADER(5) - single row in pcap)  ?

**Comment by tatsuhiro-t** [comment]
The priority mechanism of nghttp2 works when wring DATA frames.  The order of passing data to application is not covered by the library.

**Comment by kunalekawde** [comment]
Thanks for the information @tatsuhiro-t 

Oh ok, which means when the server application sends response and nghttp2 layer is creating the DATA frames, at that time priority and dependency information is used..?

If you could also below once, it would be helpful, these tests i did using nghttp2/examples/client.c and libevent-server.c
1.	When dependency is specified, order in which response is received does gets changed although not as expected.
So I did 2 tests with priority same=16 as exclusive dependency is in sequence:
a.	Expected (1, 3, 7, 5) Client got response in order (1, 5, 3, 7) and in same order streams were ended
b.	Expected (1, 5, 3, 7) Client got response in order (1, 3, 5, 7) and in same order streams were ended

2.	When priority information is specified with common dependency
e.g. 3(weight=5), 5(weight=20), 7(weight=70) depends on 1
Client received DATA in order 1, 3, 5, 7 but end stream was received as expected 1, 7, 5, 3 

As per your earlier comment, I see that #2 is possible now, any inputs on #1 above please ?

**Comment by tatsuhiro-t** [comment]
It is not clear to me the dependency tree you make here.  Could you elaborate more?
As far as I know, examples/client only issues 1 request.  How do you send multiple requests with it?

**Comment by kunalekawde** [comment]
yeah sure.
In client.c in loop(struct connection* conn) function, I updated to:
`
  nghttp2_priority_spec pri_spec;
  nghttp2_priority_spec_default_init(&pri_spec);
  if (send_request(conn, conn->req, pri_spec) != 0) {
    rv = -1;
    goto fail;
  }

  nghttp2_priority_spec_init(&pri_spec, 1, 16, 1);
  if (send_request(conn, conn->req, pri_spec) != 0) {
    rv = -1;
    goto fail;
  }

  nghttp2_priority_spec_init(&pri_spec, 7, 16, 1);
  if (send_request(conn, conn->req, pri_spec) != 0) {
    rv = -1;
    goto fail;
  }

  nghttp2_priority_spec_init(&pri_spec, 3, 16, 1);
  if (send_request(conn, conn->req, pri_spec) != 0) {
    rv = -1;
    goto fail;
  }
`

**Comment by kunalekawde** [comment]
Please let me know if I should share the entire client.c

**Comment by tatsuhiro-t** [comment]
I could not find send_request in examples/client.c.
I guess that requests are sent to server in its own packet, and libevent-server processes each of them sequentially before it sees multiple requests.  As far as I know, HTTP/2 priority specifies share of the resource and does not dictate about the particular order of responses.

**Comment by kunalekawde** [comment]
I'm not which version I updated but here is the complete file: https://justpaste.it/2puqp
Here, basically I'm verifying the dependency as the priority is kept to default=16.  libevent-server processing them sequentially is still fine as you earlier clarified that prioritization/dependency is handled when sending the response - DATA to client. But I had expected the server follow the dependency order provided to it. 
Following was observation as specified earlier:
a. Expected (1, 3, 7, 5) Client got response in order (1, 5, 3, 7) and in same order streams were ended
b. Expected (1, 5, 3, 7) Client got response in order (1, 3, 5, 7) and in same order streams were ended

Thanks @tatsuhiro-t for checking on this. Your clarification would be really helpful.

**Comment by kunalekawde** [comment]
@tatsuhiro-t , sorry to bother you again on this, but did you get chance to check this ? Or do you think the test is incorrect ?

**Comment by tatsuhiro-t** [comment]
For case a, stream 5 depends on stream 7.  Then stream 7 gets open.  When processing this, nghttp2 first removes stream 7 from dependency tree which makes stream 5 depend on root.  Since stream 1 and 5 has equal priority now, 5 is sent before 3 and 7.
Using idle stream (which is not created stream yet, as you do making stream 5 depend on stream 7) as anchor is interesting, but nghttp2 expects anchor stream will not open.

**Comment by kunalekawde** [comment]
@tatsuhiro-t , thanks for the explanation but its not very clear to me still. nghttp2 at server would get stream 7 also right at the time its processing 1 & 3 , because client is first creating all requests and then sending.
let me take one more example:
- Stream 3 depends on 1
- Stream 5 depends on 1
- Stream 7 depends on 1
- Stream 9 exclusively depends on 1
         1
         9
   3    5    7

Does it mean that 9 will be removed from dependency tree, so nghttp2 would serve response as 1 , 3, 5, 7 , 9 ?

**Comment by kunalekawde** [comment]
@tatsuhiro-t , thanks for the explanation but its not very clear to me still. nghttp2 at server would get stream 7 also right at the time its processing 1 & 3 , because client is first creating all requests and then sending.
let me take one more example:
- Stream 3 depends on 1
- Stream 5 depends on 1
- Stream 7 depends on 1
- Stream 9 exclusively depends on 1
         1
         9
   3    5    7

Does it mean that 9 will be removed from dependency tree, so nghttp2 would serve response as 1 , 3, 5, 7 , 9 ?

**Comment by tatsuhiro-t** [comment]
It depends on how dependency is made.  If no idle stream is involved (in other words, all stream dependency is made on stream creation), no stream is removed from tree.

And as I wrote earlier, the order of response does not matter.  HTTP/2 prioritization distributes resources over streams.  Some disruption of ordering is acceptable.

**Comment by kunalekawde** [comment]
Ok got some more clarity on this, thanks a lot.
