### ISSUE TITLE
Sending response after server handler has completed?

### ISSUE THREAD

**Issue by alanmcguinn** [nghttp2/nghttp2#1325]
I'm looking to implement an asynchronous response handler and I'm looking for the best way to do it.

I have Rest request coming from a client. The nghttp2_asio handler processes the request and then sends an asynchronous request to another down stream service. So, at this point it does not call response.end() and does not send a response. The client is still waiting, but the server handler has completed.

Sometime later, when the downstream service returns its answer in a separate thread (legacy epoll stuff), I need to formulate a Rest response and send it back to the waiting client.

So far, I've tried registering a lambda with the response captured and calling response.end() in this. Note: This is happening in a different thread (not the original server handler thread).

Question 1: Is it possible to send a response later like this using nghttp2_asio?
Question 2: If so, would I need to do it on the original server handler threads io_service?
Question3: Or do I have to "wait" in the server handler for the downstream response and send from there? (This is probably what I'm going to do for now).

**Comment by alanmcguinn** [comment]
`void end(generator_cb cb) const;`

I guess this could be the answer here?

**Comment by akonskarm** [comment]
take a look at examples/asio-sv.cc and the "delay" example in particular

**Comment by joconnor-openet** [comment]
@akonskarm thanks, that example helped a lot.

>  Question 2: If so, would I need to do it on the original server handler threads io_service?

turns out you need to call response.end() on the original io_service thread. Otherwise the stream could be closed underneath you at any moment if e.g. the client closes the connection.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
