### ISSUE TITLE
Behaviour of nghttp2 when client sends repeated stream id successively in the same connection

### ISSUE THREAD

**Issue by RekhaBalasu** [nghttp2/nghttp2#1328]
Hi,

What is the behaviour of nghttp2 library when the client  sends the same stream id for successive stream.
For example: client sends a request with stream ID 5 and yet again sends another request with the same stream ID of 5. 

Does nghttp2 library responds with error or is it upto the application that uses this library to handle this scenario?

**Comment by akonskarm** [comment]
the nghttp2 library will handle it

**Comment by RekhaBalasu** [comment]
Hi,
Can you please tell me precisely what callbacks will be invoked in this scenario? Is there any documentation available where this information is available?

**Comment by akonskarm** [comment]
I don't think there is an application level callbcak - this should be handled internally in the library.

**Comment by tatsuhiro-t** [comment]
It is handled by library as connection error. on_invalid_frame_recv will be called.
