### ISSUE TITLE
nghttp2 handling for stream identifier reuse

### ISSUE THREAD

**Issue by RekhaBalasu** [nghttp2/nghttp2#1330]
As per RFC 7540, Section 5.1.1. mentions that stream identifiers cannot be reused. 

If a client reuses any stream-id at any point in the connection, how will the nghttp2 library handle it? What callbacks will be invoked for handling this scenario.

**Comment by tatsuhiro-t** [comment]
It is treated as connection error and on_invalid_frame_recv_callback is called.
If the library cannot determine that it is invalid because the necessary information has been lost, it just ignores the stream.
