### ISSUE TITLE
Please cut a patch release

### ISSUE THREAD

**Issue by lovesegfault** [nghttp2/nghttp2#1339]
nghttp2 1.38.0 fails to build under Boost 1.70, as reported in #1320. Although the fix has been merged, it did not make it into the last release, and as such I'd like to ask for a new release to be cut containing the fix.

**Comment by tatsuhiro-t** [comment]
Is it possible to apply the patch to fix build problem for your build?  I think the distribution generally has a facility to apply their own patch to fix this kind of build problem.

**Comment by lovesegfault** [comment]
1.39.1 builds again.

Cheers!
