### ISSUE TITLE
h2load output interpretation

### ISSUE THREAD

**Issue by kunalekawde** [nghttp2/nghttp2#1343]
Apologies if this is a trivial question but Im not able to co-relate the output from h2 load.

$ ./.build/nghttp2/BUILD/nghttp2-1.36.0/install/bin/h2load -D1 -t1 -c1 -m1  http://10.15.10.158:80/workerApp/TestMsg?H2async1
starting benchmark...
spawning thread #0: 1 total client(s). Timing-based test with 0s of warm-up time and 1s of main duration for measurements.
Warm-up started for thread #0.
progress: 100% of clients started
Warm-up phase is over for thread #0.
Main benchmark duration is started for thread #0.
Application protocol: h2c
Main benchmark duration is over for thread #0. Stopping all clients.
Stopped all clients for thread #0

finished in 1.00s, 1312.00 req/s, 239.81KB/s
requests: 1312 total, 1313 started, 1312 done, 1312 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 1312 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 239.81KB (245563) total, 16.83KB (17238) headers (space savings 94.68%), 199.88KB (204672) data
                     min         max         mean         sd        +/- sd
time for request:      474us     16.03ms       758us       800us    97.48%
time for connect:       65us        65us        65us         0us   100.00%
time to 1st byte:    12.44ms     12.44ms     12.44ms         0us   100.00%
req/s           :    1311.65     1311.65     1311.65        0.00   100.00%

Finished line shows 1312 request and req/s shows max ~1312 so matching

Now: with only change of **client to 2**
$ ./.build/nghttp2/BUILD/nghttp2-1.36.0/install/bin/h2load -D1 -t1 -c2 -m1  http://10.15.10.158:80/workerApp/TestMsg?H2async1
starting benchmark...
spawning thread #0: 2 total client(s). Timing-based test with 0s of warm-up time and 1s of main duration for measurements.
Warm-up started for thread #0.
progress: 50% of clients started
progress: 100% of clients started
Warm-up phase is over for thread #0.
Main benchmark duration is started for thread #0.
Application protocol: h2c
Main benchmark duration is over for thread #0. Stopping all clients.
Stopped all clients for thread #0

finished in 1.00s, 2073.00 req/s, 379.01KB/s
requests: 2073 total, 2075 started, 2073 done, 2073 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 2073 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 379.01KB (388108) total, 26.69KB (27332) headers (space savings 94.66%), 315.81KB (323388) data
                     min         max         mean         sd        +/- sd
time for request:      397us     38.86ms       960us      1.30ms    97.35%
time for connect:       85us       119us       102us        24us   100.00%
time to 1st byte:    11.29ms     11.89ms     11.59ms       427us   100.00%
req/s           :    1031.37     1040.44     1035.90        6.41   100.00%

Finished show 2073, ideally expectation was ~1312 *2 ? and req/s show 1032 , since this count is across all clients, shouldn't it have been like 1312*2 ?

**Comment by tatsuhiro-t** [comment]
My wording might not be correct, but req/s is calculated per client.  So 1031.37 is not that bad.

**Comment by kunalekawde** [comment]
Thanks @tatsuhiro-t , it is clear now although I've another question:
**h2load -D1 -t1 -c1 -m1**
Here, the request per sec was not mentioned but h2load shows 1312 , does it mean that h2load will try sending maximum requests on 1 thread over a period of 1 sec with 1 connection using only 1 stream concurrently ? 
Is there some way i can configure like threads=x , connections=y, RPS(req/sec)=z duration=d, so RPS will continue for duration d ?

**Comment by kunalekawde** [comment]
closing this old ticket.
