### ISSUE TITLE
Trying to create a callback request on the client side.

### ISSUE THREAD

**Issue by RCorsin** [nghttp2/nghttp2#1344]
Hello everyone, I'm working actually on a server/client to send/receive images from a 360 camera to an mounted headset as a project for my master, I'm using your nghttp2 asio and I'm already able to send two images at the same time, but I wanted to create a callback function, my point is : I want the main thread to fuse two images, one in low and one in high resolution, to obtain a high resolution field of view and a low resolution background everywhere else. To do so I'm seeing two options : 
- create a callback function which will loop the client request (which is not working for the moment but I don't understand why).
- Push from the server but I need the coordinate of the client side (the field of view of the HDM) and I don't know if it's possible to send from the client this coordinates while the server is pushing from itself.

**Comment by RCorsin** [comment]
The second solution would be the best but at a moment or another I will again have the need to callback my request to have my HDM coordinates

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
