### ISSUE TITLE
Is it possible to know when a connection has been broken? (asio lib)

### ISSUE THREAD

**Issue by samuxiii** [nghttp2/nghttp2#1351]
Hi,
In the scenario where an established connection is interrupted by a network outage, is it possible to get the error code? It seems the on_error callback is not being called and I would like to recover the error_code/information and manage it.

Also I've seen a ping is being sent recursively whereas a session is alive using

     _session_impl::handle_ping (const boost::system::error_code &ec)_ 

but this function doesn't return or process the error it gets from _nghttp2_submit_ping_ .
 
Thank you so much in advance

**Comment by akonskarm** [comment]
What does handle_ping have to do with it?
the session class has the on_error method.

Best,
A.

**Comment by pgit** [comment]
*bump* @samuxiii says explicitly that `on_error()` is NOT called, and that is something I have been seeing as well. The session gets broken for yet unknown reasons (timeout? network outage w/o TCP reset) and does not report it via the callback.

Any subsequent requests result in an "unknown error".

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
