### ISSUE TITLE
fetch-ocsp-response: Succeeding, but nghttp2 refuses the result

### ISSUE THREAD

**Issue by bratkartoffel** [nghttp2/nghttp2#1354]
Hi,

the fetch-ocsp-response command succeeds (exits with 0 code) with the following debug info:
```
nghttpx_1     | fetch-ocsp-response (using OpenSSL 1.1.1b  26 Feb 2019)
nghttpx_1     | sending OCSP request to http://ssl-ca2.fraho.eu/ca.ocsp
nghttpx_1     | /etc/nghttpx/ssl/ctf.home/server.crt: good
nghttpx_1     |         This Update: May 30 07:32:42 2019 GMT
nghttpx_1     |         Next Update: May 30 11:32:42 2019 GMT
nghttpx_1     |
nghttpx_1     | verifying the response signature
nghttpx_1     | verify OK (used: [u'-VAfile', u'/tmp/tmpWI2nn3/issuer.crt'])
```

But nghttpx refuses to take the ocsp response with the following error:
```
nghttpx_1     | 2019-05-30T07:32:42.368Z 7 7 e31ec905 ERROR (shrpx_tls.cc:1937) OCSP_basic_verify failed: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error
```

I'm unsure where the error may be (the ocsp responder is my implementation), but it looks that nghttpx is to restrictive when checking the response. OpenSSL already said that it's ok (and verified the signature), so why nghttpx complains about it?

I've uploaded the certificate and chain for testing

[cert-and-chain.zip](https://github.com/nghttp2/nghttp2/files/3235971/cert-and-chain.zip)

What I've found out so far:
* this does not happen when compiling / using nghttp2 with libressl
* it seems that it's basically working (tested with a letsencrypt cert)

Although it seems that my ocsp responder is not working correctly, why openssl is fine with the response and nghttp2 is not?

**Comment by tatsuhiro-t** [comment]
Is your CA private? I mean it is not installed in browsers or OS?
If it isn't, I think nghttpx couldn't build trusted path to a trusted root CA.
What happens if you specify your CA using --cacert option?

As for openssl ocsp command verification, it omits above check for provided chain certificate.

**Comment by bratkartoffel** [comment]
Yes, the CA is private and self-hosted.
After some more tests I found out that using nghttpx 1.36.0 (linked against boringssl) works.
Using nghttpx 1.38.0 (linked against openssl-1.1.1b) fails.

Using the following openssl command succeeds:
```
# openssl ocsp -issuer chain.crt -cert server.crt -url http://ssl-ca2.fraho.eu/ca.ocsp --CA chain.crt -verify_depth 10
Response verify OK
server.crt: good
        This Update: May 30 16:16:42 2019 GMT
        Next Update: May 30 20:16:42 2019 GMT
# echo $?
0
```
