### ISSUE TITLE
:path header field value must start with "/" and does not accept empty?

### ISSUE THREAD

**Issue by zergscut2017** [nghttp2/nghttp2#1360]
When client sends request with path as empty, nghttp2 server sends RST_STREAM complaining PROTOCOL ERROR. When  client sends request with path "/", there is no such complain.
From the nghttp2_http.c, I got such description:
/* For "http" or "https" URIs, OPTIONS request may have "*" in :path
   header field to represent system-wide OPTIONS request.  Otherwise,
   :path header field value must start with "/".  This function must
   be called after ":method" header field was received.  This function
   returns nonzero if path is valid.*/
And I checked rfc3986(https://tools.ietf.org/html/rfc3986#section-3.3), it seems like that either empty or "/" is legal. 
   If a URI contains an authority component, then the path component
   must either be empty or begin with a slash ("/") character.
My understanding is, when the URI contains authority(e.g. http://abcdef.service.com:80):
For client, it could send either empty or "/" as PATH 
For server, it should accept the request with header path as either "/" or empty.

**Comment by tatsuhiro-t** [comment]
Please read RFC 7540 regarding :path pseudo header field:
https://tools.ietf.org/html/rfc7540#section-8.1.2.3
