### ISSUE TITLE
is there a difference in the performance of nghttp2 and libnghttp2_asio?

### ISSUE THREAD

**Issue by Suicosmos** [nghttp2/nghttp2#1362]
Hello, does anyone know if there is a noticeable difference in performance for libnghttp2_asio and the nghttp2 normal C code. I am having difficulties understanding nghttp2 and was contemplating trying the libnghttp2_asio version, would i lose anything performance-wise?

**Comment by akonskarm** [comment]
I've tested this and the answer is no, you get the same performance with both C and C++ bindings.

Best,
A.

**Comment by Anilkumardev** [comment]
> I've tested this and the answer is no, you get the same performance with both C and C++ bindings.
> 
> Best, A.

Can you please send me sample code for sending POST request concurrently ?

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
