### ISSUE TITLE
libnghttp2_asio file not getting created even after passing --enable-asio-lib to configure script

### ISSUE THREAD

**Issue by codewithrajranjan** [nghttp2/nghttp2#1367]
I am running the configure command with

`
   ./configure --prefix=/opt/ng-http2 --enable-asio-lib
`

Boost is already installed.

**Comment by self-tuts** [comment]
OK I got the answer we need to use --with-boost flag 

`
    ./configure --prefix=/opt/ng-http2/ --with-boost=/opt/boost --enable-asio-lib=yes
`

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
