### ISSUE TITLE
Usage of nghttp2 library

### ISSUE THREAD

**Issue by cmirajkar87** [nghttp2/nghttp2#1370]
Hello Tatsuhiro,

I am trying to implement http2 using nghttp2 library which needs to be scalable.
In transmit direction I am using "nghttp2_submit_request" for submitting data to library,
the header/values are submitted with flags NGHTTP2_NV_FLAG_NO_COPY_NAME/ NGHTTP2_NV_FLAG_NO_COPY_VALUE.
And then I call "nghttp2_session_mem_send" to send out http2 frames on line.
Please note that I am maintaining the data till it is not sent out by the library.

In the reverse direction I am using "nghttp2_session_mem_recv" when I receive any frames from 
peer.

Now w.r.t to above usage scenario I have few questions

1) Can the transmit and receive be on two different threads? i.e "nghttp2_submit_request & nghttp2_session_mem_send" on let's say tx thread and "nghttp2_session_mem_recv" on rx thread?

2) If the above is possible then do I need to have locks to allow only one thread to be in control 
of nghttp2_session handle while data(tx or/and rx) is being processed? 

3)What is the best possible way to submit data( in tx direction) to library? Can I submit let's say
10k(assuming 20k as max concurrent streams possible) request by calling "nghttp2_submit_request" and then go for "nghttp2_session_mem_send" till it exhausts of all the data? Or something like below

while(1)
{
nghttp2_submit_request(); //submit one http request.

 while(1) //transmit it, wait till mem_send produces all the data pertaining to this request
      nghttp2_session_mem_send();
}

Any help would be really appreciated.

Thanks,
Chetan

**Comment by tatsuhiro-t** [comment]
You can use nghttp2_session from different thread but only one thread can access it at any time.  You  need a lock.

nghttp2_session_mem_send will send frames as much as possible.  It is most likely that socket buffer becomes full and you have to wait.

**Comment by cmirajkar87** [comment]
Thankyou, appreciate your help.
