### ISSUE TITLE
What is the correct usage pattern of nghttp2_hd_inflate_hd2()

### ISSUE THREAD

**Issue by yzhao1012** [nghttp2/nghttp2#1379]
I am using nghttp2_hd_inflate_hd2() to parse HTTP2 headers sniffed from the network. But I am seeing it constantly return negative return code.

The way I am using this API is as follows:
- Collect a list of payload from network packages from one TCP connection for HTTP2 traffic.
- Concatenate these payload into one sequential buffer.
- Parse the above buffer into multiple HTTP2 frames.
- Stitch together frames of the same stream, i.e., with the same stream ID according to HTTP2 framing protocol
- Concatenate the HEADERS and CONTINUATION frames, and parse the payload with nghttp2_hd_inflate_hd2().

Was the above usage pattern incorrect?

**Comment by yzhao1012** [comment]
nghttp2_hd_inflate_hd2() is defined here:
https://github.com/nghttp2/nghttp2/blob/f6644a92af289e3ebeb8c37be8128f33573c1e15/lib/includes/nghttp2/nghttp2.h#L5229

**Comment by tatsuhiro-t** [comment]
I think it is fine.  Make sure that only payload is fed into nghttp2_hd_inflater.  It does not parse frame header.
