### ISSUE TITLE
cmake and nghttp2_asio

### ISSUE THREAD

**Issue by bgemmill** [nghttp2/nghttp2#1383]
Hello,

I'm trying to integrate nghttp2 into a cmake project, and I'm noticing some strange behavior around the configure step. I'm adding nghttp2 as an external project like so:
```
set(NGHTTP2_VERSION "1.39.2")
set(NGHTTP2_ROOT "${CMAKE_BINARY_DIR}/nghttp2-${NGHTTP2_VERSION}")

    ExternalProject_Add(
            dependency-nghttp2
            URL https://github.com/nghttp2/nghttp2/releases/download/v${NGHTTP2_VERSION}/nghttp2-${NGHTTP2_VERSION}.tar.xz
            URL_HASH SHA256=a2d216450abd2beaf4e200c168957968e89d602ca4119338b9d7ab059fd4ce8b
            UPDATE_COMMAND ""
            CONFIGURE_COMMAND ./configure --prefix=${NGHTTP2_ROOT} --enable-lib-only --with-boost=${BOOST_ROOT} --enable-static --disable-shared --enable-asio-lib
            #CONFIGURE_COMMAND ${CMAKE_COMMAND} -DCMAKE_INSTALL_PREFIX:PATH=${NGHTTP2_ROOT} -DCMAKE_BUILD_TYPE=Release -DENABLE_LIB_ONLY=ON -DBOOST_ROOT=${BOOST_ROOT} -DENABLE_STATIC_LIB=ON -DENABLE_SHARED_LIB=OFF -DENABLE_ASIO_LIB=ON
            BUILD_COMMAND $(MAKE) install
            BUILD_IN_SOURCE true
            INSTALL_COMMAND ""
            INSTALL_DIR ${NGHTTP2_ROOT}
    )
```

If I use `./configure`, everything builds fine.

If I translate those arguments to cmake and use that to configure (the commented out line), the nghttp2 library builds successfully, but the nghttp2_asio library compilation fails:
```
In file included from /dependency-nghttp2/src/http2.cc:25:
/home/docker/dev/trading/cmake-build-debug/dependency-nghttp2-prefix/src/dependency-nghttp2/src/http2.h:36:10: fatal error: 'nghttp2/nghttp2.h' file not found
```

This is strange because it looks like the CMakelists.txt next to that file uses `include_directories` to mention `"${CMAKE_CURRENT_SOURCE_DIR}/includes"` for that target.

Is there something else I should be doing to make cmake build successfully, or should I just stick with ./configure?

ubuntu 18.04
cmake 3.15.1
clang 8.0.1

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
