### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [nghttp2/nghttp2#1384]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the destructor for the class “ConnectionHandler”](https://github.com/nghttp2/nghttp2/blob/42e8ceb65629389b37129356d4f31ad79be0d048/src/shrpx_connection_handler.cc#L162 "Update candidate").

**Comment by tatsuhiro-t** [comment]
Thank you.  Fix committed via f2fde180cdcca1f0a1c12d097c92510a887f6500

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/nghttp2/nghttp2/commit/f2fde180cdcca1f0a1c12d097c92510a887f6500 "Remove redundant null check before delete").
