### ISSUE TITLE
h2load multi uri

### ISSUE THREAD

**Issue by vunhatminh241191** [nghttp2/nghttp2#1385]
Hi guys,

I am trying to use h2load with multiple URIs with options -i for the input file. My file look like this:
`https://10.11.0.121:9091`
`https://10.11.0.121:9092`

H2load supposed to send connection to these address but it only sends for the first URI. Does anyone know how h2load works with multiple uri?

Thanks

**Comment by tatsuhiro-t** [comment]
```
  -i, --input-file=<PATH>
              Path of a file with multiple URIs are separated by EOLs.
              This option will disable URIs getting from command-line.
              If '-' is given as <PATH>, URIs will be read from stdin.
              URIs are used  in this order for each  client.  All URIs
              are used, then  first URI is used and then  2nd URI, and
              so  on.  The  scheme, host  and port  in the  subsequent
              URIs, if present,  are ignored.  Those in  the first URI
              are used solely.  Definition of a base URI overrides all
              scheme, host or port values.
```

in particular:

> The  scheme, host  and port  in the  subsequent
              URIs, if present,  are ignored.  Those in  the first URI
              are used solely.

**Comment by vunhatminh241191** [comment]
I think I did the wrong the connection here. Thanks for helping out @tatsuhiro-t
