### ISSUE TITLE
Suggestion: To support path parameters in asio server serve mux 

### ISSUE THREAD

**Issue by amitjain04** [nghttp2/nghttp2#1398]
Currently the handle function registers static API url. Internally it is stored in a map. When the request is received, the request URL string is matched against the map (in a loop finding the longest match). This is good when there are static routes.

In case of APIs, the request URL may have a dynamic part in the request URL. So during the handle function there should be option to register the API supporting path parameters. 
for e.g.
/api/v1.0/users/**{userId}**/tickets
or 
/api/v1.0/users/**:userId**/tickets

When the request is received, the request URL will be
/api/v1.0/users/**John**/tickets

Any plans to support this use case in asio server serve mux?

Regards,
Amit Jain

**Comment by akonskarm** [comment]
This would probably require for the library to use regular expressions.
What's the added value? You can handle ".../users" and handle John in your callback.

Best,
A.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
