### ISSUE TITLE
Why I can't send RESPONSE for POST

### ISSUE THREAD

**Issue by liuzhuo-bj** [nghttp2/nghttp2#1427]
Dear experts,

I am tring use c++ and nghttp2 for a project. 
My software requirement is very simple, client send POST to server, server send response to client with state 200 or other.
Don't need SSL function. but must use HTTP2.

I built client and server two software and do some basic test, but server can't send response to client ALWAYS.

client --> server
server can receive frame from client, but when I tried to send response, it is always fail. Checked wireshark log, no response frame was sent.

About server code related 'reponse send': 
   1, on_frame_recv_callback never find hd.type== DATA or HEADER, it is always 4 SETTING, so I can't expect send response in on_request_recv.
   2, I tried to send response in session_recv when conditions meet: STREAM_END flag is true, and frame type is HEADER or DATA.
  3, Before I call nghttp2_submit_response, I checked stream_data = nghttp2_session_get_stream_user_data(session, streamid); the state is OK, then I call nghttp2_submit_response(session_data->session, tmpFrameNode->streamID, hdrs1, ARRLEN(hdrs1), NULL), there no error return, but on_frame_not_send_callback shown the error is 510 -- the stream closed.

client code and server code please refer following comments.
If possible give a sample？ or point what is my fault?

Thanks a lot,

**Comment by liuzhuo-bj** [comment]
Client codes:

uint8_t userData[] = "test data body";
nghttp2_data_provider data_prd;
request_t req;

static http2_stream_data *create_http2_stream_data(const char *uri,	struct http_parser_url *u) {
	http2_stream_data *stream_data = (http2_stream_data*)malloc(sizeof(http2_stream_data));
	return stream_data;
}

static void delete_http2_stream_data(http2_stream_data *stream_data) {
	free(stream_data);
}

static http2_session_data * create_http2_session_data(struct event_base *evbase) {
	http2_session_data *session_data = (http2_session_data*)malloc(sizeof(http2_session_data));
	memset(session_data, 0, sizeof(http2_session_data));
	return session_data;
}

static int on_header_callback(nghttp2_session *session,	const nghttp2_frame *frame, const uint8_t *name,
	size_t namelen, const uint8_t *value, size_t valuelen, uint8_t flags, void *user_data) 
{
	http2_session_data *session_data = (http2_session_data *)user_data;
	(void)session;
	(void)flags;

	switch (frame->hd.type) 
	{
	case NGHTTP2_HEADERS:
		if (frame->headers.cat == NGHTTP2_HCAT_RESPONSE &&
			session_data->stream_data->stream_id == frame->hd.stream_id) 
		{
			/* Print response headers for the initiated request. */
			print_header(stderr, name, namelen, value, valuelen);
			break;
		}
	}
	return 0;
}

static int on_begin_headers_callback(nghttp2_session *session,	const nghttp2_frame *frame,	void *user_data) 
{
	http2_session_data *session_data = (http2_session_data *)user_data;
	(void)session;

	switch (frame->hd.type) {
	case NGHTTP2_HEADERS:
		if (frame->headers.cat == NGHTTP2_HCAT_RESPONSE && session_data->stream_data->stream_id == frame->hd.stream_id) 
		{
			printf("Response headers for stream ID=%d:\n",	frame->hd.stream_id);
		}
		break;
	}
	return 0;
}

static int on_frame_recv_callback(nghttp2_session *session,	const nghttp2_frame *frame, void *user_data) 
{
	http2_session_data *session_data = (http2_session_data *)user_data;
	(void)session;

	switch (frame->hd.type) 
	{
	case NGHTTP2_HEADERS: //1
		if (frame->headers.cat == NGHTTP2_HCAT_RESPONSE && session_data->stream_data->stream_id == frame->hd.stream_id) 
		{
			fprintf(stderr, "All headers received\n");
		}
		break;
	}
	return 0;
}

static int on_data_chunk_recv_callback(nghttp2_session *session, uint8_t flags,
	int32_t stream_id, const uint8_t *data,	size_t len, void *user_data) 
{

	http2_session_data *session_data = (http2_session_data *)user_data;
	(void)session;
	(void)flags;

	if (session_data->stream_data->stream_id == stream_id) 
	{
		printf("%s in on_data_chunk_recv_callback\n", data);
	}
	return 0;
}

static int on_stream_close_callback(nghttp2_session *session, int32_t stream_id, uint32_t error_code, void *user_data) 
{
	http2_session_data *session_data = (http2_session_data *)user_data;
	int rv;

	if (session_data->stream_data->stream_id == stream_id) 
	{
		fprintf(stderr, "Stream %d closed with error_code=%u\n", stream_id,	error_code);
		rv = nghttp2_session_terminate_session(session, NGHTTP2_NO_ERROR);
		if (rv != 0) {
			return NGHTTP2_ERR_CALLBACK_FAILURE;
		}
	}
	return 0;
}

static void initialize_nghttp2_session(http2_session_data *session_data) {
	nghttp2_session_callbacks *callbacks;
	nghttp2_session_callbacks_new(&callbacks);
	nghttp2_session_callbacks_set_send_callback(callbacks, send_callback);
	nghttp2_session_callbacks_set_on_frame_recv_callback(callbacks,	on_frame_recv_callback);
	nghttp2_session_callbacks_set_on_data_chunk_recv_callback(	callbacks, on_data_chunk_recv_callback);
	nghttp2_session_callbacks_set_on_stream_close_callback(	callbacks, on_stream_close_callback);
	nghttp2_session_callbacks_set_on_header_callback(callbacks,	on_header_callback);
	nghttp2_session_callbacks_set_on_begin_headers_callback(callbacks, on_begin_headers_callback);
	nghttp2_session_client_new(&session_data->session, callbacks, session_data);
	nghttp2_session_callbacks_del(callbacks);
}

static void send_client_connection_header(http2_session_data *session_data) 
{
	nghttp2_settings_entry iv[1] = {
		{NGHTTP2_SETTINGS_MAX_CONCURRENT_STREAMS, 100} };
	int rv = nghttp2_submit_settings(session_data->session, NGHTTP2_FLAG_NONE, iv,	ARRLEN(iv));
	if (rv != 0) {
		errx(1, "Could not submit SETTINGS: %s", nghttp2_strerror(rv));
	}
}

ssize_t data_prd_read_callback( nghttp2_session *session, int32_t stream_id, uint8_t *buf, size_t length,
	     uint32_t *data_flags, nghttp2_data_source *source, void *user_data)
{
	   struct request_t *req =(struct request_t*) source->ptr;
	   memcpy(buf, req->data, req->data_len);
	 * data_flags |= NGHTTP2_DATA_FLAG_EOF;
	   return req->data_len;
}

static void submit_request(http2_session_data *session_data) 
{
	int32_t stream_id;
	http2_stream_data *stream_data = session_data->stream_data;

	char dataLenStr[4];
	sprintf(dataLenStr, "%d", strlen((const char*)userData));
	req.data = userData;
	req.data_len = strlen((const char*)userData);

	char schemeData[] = "http";
	char methodData[] = "POST";
	char pathData[] = "./test.txt";
	char authorityData[] = "192.168.3.222:8482";
	char contenttypeData[] = "multipart/related;";
	nghttp2_nv hdrs[] =	{
		MAKE_NV(":scheme", schemeData,strlen(schemeData)),
		MAKE_NV2(":method", methodData),
		MAKE_NV2(":path", pathData),
		MAKE_NV2("content-type", contenttypeData),
		MAKE_NV("authority", "5gcore.huawei.com",strlen("5gcore.huawei.com")),
		MAKE_NV("content-length", dataLenStr,strlen(dataLenStr))
	};

	data_prd.source.ptr = (void*)&req;
	data_prd.read_callback = data_prd_read_callback;

	stream_id = nghttp2_submit_request(session_data->session, NULL, hdrs, ARRLEN(hdrs), &data_prd, stream_data);
	if (stream_id < 0)
	{
		printf("---exit submit_request with error---\n");
		errx(1, "Could not submit HTTP request: %s", nghttp2_strerror(stream_id));
	}
	stream_data->stream_id = stream_id;
}

static int session_send(http2_session_data *session_data) {
	int rv;
	rv = nghttp2_session_send(session_data->session);
	return 0;
}

static void eventcb(struct bufferevent *bev, short events, void *ptr) 
{
	http2_session_data *session_data = (http2_session_data *)ptr;
	if (events & BEV_EVENT_CONNECTED)
	{
		int fd = bufferevent_getfd(bev);
		int val = 1;

		setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, (char *)&val, sizeof(val));
		initialize_nghttp2_session(session_data);
		send_client_connection_header(session_data);

		printf("call submit_request in eventcb \n");
		submit_request(session_data);

		if (session_send(session_data) != 0) 
		{
			delete_http2_session_data(session_data);
		}
		return;
	}
	if (events & BEV_EVENT_EOF) {
		warnx("Disconnected from the remote host");
	}
	else if (events & BEV_EVENT_ERROR) {
		warnx("Network error");
	}
	else if (events & BEV_EVENT_TIMEOUT) {
		warnx("Timeout");
	}
	delete_http2_session_data(session_data);
}

static void initiate_connection(struct event_base *evbase, const char *host, uint16_t port, http2_session_data *session_data) 
{
	int rv;
	struct bufferevent *bev;
	struct sockaddr_in servAddr;

	servAddr.sin_family = AF_INET;// AF_UNSPEC;
	servAddr.sin_addr.s_addr = inet_addr(host);
	servAddr.sin_port = htons(port);
	printf("inet_ntoa ip = %s\n", inet_ntoa(servAddr.sin_addr));

	if (inet_pton(AF_INET, host, &servAddr.sin_addr) <= 0)
		return;

	bev = bufferevent_socket_new(evbase, -1, BEV_OPT_DEFER_CALLBACKS | BEV_OPT_CLOSE_ON_FREE);
	bufferevent_setcb(bev, readcb, writecb, eventcb, session_data);
	int i = bufferevent_enable(bev, EV_READ | EV_WRITE);

	rv = bufferevent_socket_connect(bev, (sockaddr*)&servAddr, sizeof(servAddr));
	session_data->bev = bev;
}

/* Get resource denoted by the |uri|. The debug and error messages are
   printed in stderr, while the response body is printed in stdout. */
static void run(const char *uri) 
{
	struct http_parser_url u;
	char host[] = "192.168.3.228";
	uint16_t port = 5555;

	struct event_base *evbase;
	http2_session_data *session_data;

	evbase = event_base_new();
	session_data = create_http2_session_data(evbase);
	session_data->stream_data = create_http2_stream_data(uri, &u);

	initiate_connection(evbase, host, port, session_data);
	event_base_dispatch(evbase);
	event_base_free(evbase);
}

int main(int argc, char **argv) 
{
	struct sigaction act;
	memset(&act, 0, sizeof(struct sigaction));
	act.sa_handler = SIG_IGN;
	sigaction(SIGPIPE, &act, NULL);

	run(NULL);
	return 0;
}

**Comment by liuzhuo-bj** [comment]
server codes:

static void start_listen(struct event_base *evbase, const char *service, app_context *app_ctx)
{
	int rv;
	struct addrinfo hints;
	struct addrinfo *res, *rp;

	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_INET;//AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;
#ifdef AI_ADDRCONFIG
	hints.ai_flags |= AI_ADDRCONFIG;
#endif /* AI_ADDRCONFIG */

	rv = getaddrinfo(NULL, service, &hints, &res);
	if (rv != 0) {
		errx(1, "Could not resolve server address");
	}

	for (rp = res; rp; rp = rp->ai_next) {
		struct evconnlistener *listener;
		listener = evconnlistener_new_bind(	evbase, acceptcb, app_ctx, LEV_OPT_CLOSE_ON_FREE | LEV_OPT_REUSEABLE| LEV_OPT_THREADSAFE,	16, rp->ai_addr, (int)rp->ai_addrlen);
		if (listener) 
		{
			freeaddrinfo(res);
			printf("start_listen OK \n");
			return;
		}
	}
	errx(1, "Could not start listener");
}
static int on_frame_recv_callback(nghttp2_session *session,	const nghttp2_frame *frame, void *user_data) 
{
	http2_session_data *session_data = (http2_session_data *)user_data;
	http2_stream_data *stream_data;

	switch (frame->hd.type) {
	case NGHTTP2_DATA:
	case NGHTTP2_HEADERS:
		printf("frame->hd.flags is %d in on_frame_recv_callback", frame->hd.flags);
		if (frame->hd.flags & NGHTTP2_FLAG_END_STREAM) {
			stream_data =(http2_stream_data*) nghttp2_session_get_stream_user_data(session, frame->hd.stream_id);
			if (!stream_data) {
				printf("stream is NOT still ALIVE in on_frame_recv_callback\n");
				return 0;
			}
			return on_request_recv(session, session_data, stream_data);
		}
		break;
	default:
		break;
	}

	return 0;
}
static int session_recv(http2_session_data *session_data) 
{
	struct evbuffer *input = bufferevent_get_input(session_data->bev);
	unsigned int datalen = evbuffer_get_length(input);
	unsigned char *data = evbuffer_pullup(input, -1);
	unsigned int handledLen = 0;
	http2_stream_data *stream_data;
	nghttp2_nv hdrs1[] = {
		MAKE_NV2(":status", "204")
	};
	int rv;

	int readlen = nghttp2_session_mem_recv(session_data->session, data, datalen);//用这个会触发 framecallback，on-header-callbck;
	if (readlen < 0) {
		warnx("Fatal error: %s", nghttp2_strerror((int)readlen));
		return -1;
	}

	do {
		handledLen += parserHttp2Packet(data + handledLen, datalen, &tmpFrameNode, session_data->session);
		if ((isCompletedStream) &&
			((tmpFrameNode->frameType == FRAME_HEADER) || (tmpFrameNode->frameType == FRAME_DATA))
			)
		{
			stream_data = (http2_stream_data*)nghttp2_session_get_stream_user_data(session_data->session, tmpFrameNode->streamID);
			/* For DATA and HEADERS frame, this callback may be called after on_stream_close_callback. Check that stream still alive. */
			if (!stream_data) {
				printf("stream is NOT still ALIVE in on_frame_recv_callback\n");
				return 0;
			}
			rv = nghttp2_submit_response(session_data->session, tmpFrameNode->streamID, hdrs1, ARRLEN(hdrs1), NULL);
			if (rv != 0) {
				printf("Fatal error: %s in traffic_send_response\n", nghttp2_strerror(rv));
				return -1;
			}
			isCompletedStream = false;
		}
	} while (handledLen < datalen);

	if (evbuffer_drain(input, (size_t)readlen) != 0) {
		warnx("Fatal error: evbuffer_drain failed");
		return -1;
	}
	if (session_send(session_data) != 0)
	{
		printf("Fatal error: session_send failed");
		return -1;
	}

	return 0;
}

**Comment by liuzhuo-bj** [comment]
seems nghttp2_submit_response return ok, but no frame was sent to client side. 

frameType = 1  frameFlag = 1; stream-id = 1 in session_recv
enter on_request_recv
nghttp2_submit_response OK
frame->hd.type is 4  in on_frame_send_callback
frame->hd.type is 3  in on_frame_send_callback
enter on_stream_close_callback
enter on_frame_not_send_callback error_code is -510

**Comment by liuzhuo-bj** [comment]
solved. close.

**Comment by Nishant-3795** [comment]
@liuzhuo-bj Can you let here know how you fixed it or if possible provide access to your repository. I am facing the similar issue. Any help will be appreciated.
