### ISSUE TITLE
nghttp2 on_data callback function giving length of data twice in one request only from client

### ISSUE THREAD

**Issue by himanshu390** [nghttp2/nghttp2#1436]
Hello,I am running a client server model using libnghttp2_asio.When server is receiving data inside on data callback function i am checking the length of data received from the client inside on data callback function.But inside on_data callback function length is being checked 2 times,First time it is giving correct length and second time it is giving length as zero.Moreover when length of data is zero,it is making 40 threads internally,not when length of received data is correct in first checking. I am sending only one  PUT request from client to server and i am not using any loop inside on data callback function.
Can anyone help me in this regard and explain why this is happening inside on_data callback function on server?

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
