### ISSUE TITLE
PING interval is not configurable in asio nghttp2 client library

### ISSUE THREAD

**Issue by srikanta00** [nghttp2/nghttp2#1437]
We are using asio nghttp2 client library as HTTP/2 implementation of our 5G Network Functions (NFs). 3GPP 5G specification (TS 29.500) mandates the minimum PING interval of 60 seconds. But the PING interval in nghtt2 client library is 30 seconds and apparently non-configurable. If this interval is configurable or defaults to 60 seconds, then this library will be suitable for 5G core network . I'd request you to make it configurable.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
