### ISSUE TITLE
proxyproto V2 support

### ISSUE THREAD

**Issue by humiaozuzu** [nghttp2/nghttp2#1452]
Can you add proxyproto V2 support as most common products such as NGINX and AWS Elastic Load Balancing has already support it.

Really appreciate your help and thank you for making this wonderful project.

**Comment by tatsuhiro-t** [comment]
Here is the WIP branch of nghttpx proxy protocol v2 support https://github.com/nghttp2/nghttp2/tree/proxyprotov2
