### ISSUE TITLE
how to set nghttp2_option_set_no_closed_streams option in asio_client

### ISSUE THREAD

**Issue by kylejan** [nghttp2/nghttp2#1462]
the default asio client session has the memory leak issue for closed streams.

how can i set nghttp2_option_set_no_closed_streams option for the asio client.

**Comment by nescafey** [comment]
I have the same problem about the memory leak issue for closed streams,it seemed 208 bytes losted after stream closed every time,I add code below to try fix the problem
                nghttp2_option *option;
 
		nghttp2_option_new(&option);  
		nghttp2_option_set_no_closed_streams(option, 1);
		 	 
                rv = nghttp2_session_client_new2(&n->session, callbacks, n, option);

		nghttp2_option_del(option);

but memory leak still exist,i don't know how to fix the memory leak,now no memory to alloc after a long time loop.

**Comment by kylejan** [comment]
yep, i still stuck in this memory leak issue

**Comment by akonskarm** [comment]
guys, how do you reproduce this?

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
