### ISSUE TITLE
Problem with h2o and h2load with volume.

### ISSUE THREAD

**Issue by rperper** [nghttp2/nghttp2#1469]
I've built h2o master branch and configured it for http/3 and all is well.  I can run the lsquic http_client program against it in volume and everything works just fine.  However, if I then build h2load (quic branch) and run more than one request against it, I get failures like this:
```I01534686 0x82c30c0b3b135f6e pkt packet has incorrect reserved bits
I01534686 0x82c30c0b3b135f6e pkt could not decrypt packet payload
I01534883 0x82c30c0b3b135f6e con recv packet len=1018
I01534883 0x82c30c0b3b135f6e pkt rx pkn=3574480305 dcid=0x008bbde81b18b9ed scid=0xc7ef90bcf602346ede type=Initial(0x00) len=145 k=0
I01534883 0x82c30c0b3b135f6e pkt packet has incorrect reserved bits
I01534883 0x82c30c0b3b135f6e pkt could not decrypt packet payload
I01535279 0x82c30c0b3b135f6e con recv packet len=449
I01535279 0x82c30c0b3b135f6e pkt rx pkn=2371164212 dcid=0x008bbde81b18b9ed scid=0xc7ef90bcf602346ede type=Initial(0x00) len=145 k=0
I01535279 0x82c30c0b3b135f6e pkt packet has incorrect reserved bits
I01535279 0x82c30c0b3b135f6e pkt could not decrypt packet payload
I01536071 0x82c30c0b3b135f6e con recv packet len=893
I01536071 0x82c30c0b3b135f6e pkt rx pkn=214 dcid=0x008bbde81b18b9ed scid=0xc7ef90bcf602346ede type=Initial(0x00) len=20 k=0
```
I can't tell if it's an h2o problem or an h2load problem, but I'm opening issues with both.  Any questions, feel free to let me know:
Bob Perper
rperper@litespeedtech.com
Thanks so much.

**Comment by tatsuhiro-t** [comment]
Thank you for telling me.  h2load works with ngtcp2 server.  Does h2load work with lsquic server?

**Comment by rperper** [comment]
It does.

**Comment by rperper** [comment]
h2load command line:```root@test10g:/opt/h2bench/Benchmark/051820-151110/h2o# h2load  --npn-list=h3-27 -n 100000 -c 100 -t 1 -T 30 -m 10 -H  'Accept-Encoding: gzip,deflate' https://benchmark.com/1knogzip.jpg 
starting benchmark...
spawning thread #0: 100 total client(s). 100000 total requests
TLS Protocol: TLSv1.3
Cipher: TLS_AES_128_GCM_SHA256
Server Temp Key: ECDH P-256 256 bits
Application protocol: h3-27
progress: 10% done
progress: 20% done
progress: 30% done
progress: 40% done
progress: 50% done
progress: 60% done
progress: 70% done
progress: 80% done
progress: 90% done
progress: 100% done

finished in 8.69s, 11511.14 req/s, 11.37MB/s
requests: 100000 total, 100000 started, 100000 done, 100000 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 100000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 98.80MB (103594500) total, 392.38KB (401800) headers (space savings 91.27%), 97.66MB (102400000) data
                     min         max         mean         sd        +/- sd
time for request:     1.04ms       3.02s     77.18ms    123.69ms    94.86%
time for connect:    14.28ms       1.57s    196.81ms    379.64ms    93.00%
time to 1st byte:   167.54ms       2.29s    447.93ms    529.20ms    87.00%
req/s           :     115.29      165.88      126.80       10.36    77.00%
```
http_server command line:```./http_server -s 192.168.0.212 -c benchmark.com,/root/server.crt,/root/server.key -r /var/www/html```

**Comment by rperper** [comment]
With h2o both sides don't do much and the -v option in h2load gives the messages I opened this problem about.
Thanks,
Bob Perper

**Comment by tatsuhiro-t** [comment]
Thanks.  It looks like removing header protection failed, which means that both side didn't agree with encryption keys.  At the moment, I have no idea why it happened.

**Comment by kazuho** [comment]
> ```
> I01534883 0x82c30c0b3b135f6e pkt rx pkn=3574480305 dcid=0x008bbde81b18b9ed scid=0xc7ef90bcf602346ede type=Initial(0x00) len=145 k=0
> ```

Am I correct to interpret that these lines suggest ngtcp2 failing to decrypt "Initial packets" that quicly sends? If that is the case, could it be related to the handling of coalesced packets within ngtcp2? The issue could be on the quicly side, though I haven't heard of any other implementation complaining.

**Comment by tatsuhiro-t** [comment]
@kazuho Yes, ngtcp2 as a client failed to decrypt Inital packet from h2o/quicly.  ngtcp2 should be able to handle coalesced packets since we extensively utilize it.

I tried to reproduce this with minimum currency and the number of requests.
2 clients per each 1 request can reproduce this.  It looks like a client received Initial packet which was sent to another client.  Note that h2load creates independent socket per client.

```
I01534883 0x82c30c0b3b135f6e pkt rx pkn=3574480305 dcid=0x008bbde81b18b9ed scid=0xc7ef90bcf602346ede type=Initial(0x00) len=145 k=0
```

The above log says that Initial packet with DCID 0x008bbde81b18b9ed  is received by client whose SCID is  0x82c30c0b3b135f6e.

Will check I did messed up packet handling.

**Comment by kazuho** [comment]
@tatsuhiro-t Thank you for the analysis. So it's is packets being routed to a wrong connection, happening on either endpoint. That explains well why we are not seeing it in the interops.

I would look into if there's anything wrong on our side.

**Comment by rperper** [comment]
How are you doing on this?  Please let me know when you have something to test.
Thanks!

Bob Perper
rperper@litespeedtech.com

**Comment by kazuho** [comment]
During last weekend, we did figure out that it was a bug in h2o. It was fixed as https://github.com/h2o/h2o/pull/2349. I confirmed using h2load that there is no loss is observed (from the server-side point of view).

Thanks to @rperper for identifying the issue, and thanks to @tatsuhiro-t for the diagnosis.

**Comment by rperper** [comment]
Thanks so much!

**Comment by rperper** [comment]
When I try the new version of h2o with the draft-27 version of h2load I get nothing but timeouts:
```
root@test10g:/opt/h2bench/Benchmark/060920-162434/h2o# h2load -v --npn-list=h3-27  https://benchmark.com/100M.bin
starting benchmark...
spawning thread #0: 1 total client(s). 1 total requests
I00000000 0xccb817d01097dded pkt tx pkn=0 dcid=0x4a73c8779fe621a3 scid=0xccb817d01097dded type=Initial(0x00) len=0 k=0
I00000000 0xccb817d01097dded frm tx 0 Initial(0x00) CRYPTO(0x06) offset=0 len=512
I00000000 0xccb817d01097dded frm tx 0 Initial(0x00) PADDING(0x00) len=693
I00000000 0xccb817d01097dded rcv loss_detection_timer=1591734670078880256 last_tx_pkt_ts=1591734668578880256 timeout=1500
I00001502 0xccb817d01097dded rcv loss detection timer fired
I00001502 0xccb817d01097dded rcv pto_count=1
I00001502 0xccb817d01097dded rcv loss_detection_timer=1591734671578880256 last_tx_pkt_ts=1591734668578880256 timeout=3000
I00001502 0xccb817d01097dded pkt tx pkn=1 dcid=0x4a73c8779fe621a3 scid=0xccb817d01097dded type=Initial(0x00) len=0 k=0
I00001502 0xccb817d01097dded frm tx 1 Initial(0x00) CRYPTO(0x06) offset=0 len=512
I00001502 0xccb817d01097dded frm tx 1 Initial(0x00) PADDING(0x00) len=693
I00001502 0xccb817d01097dded rcv loss_detection_timer=1591734673081059072 last_tx_pkt_ts=1591734670081059072 timeout=3000
I00004506 0xccb817d01097dded rcv loss detection timer fired
I00004506 0xccb817d01097dded rcv pto_count=2
I00004506 0xccb817d01097dded rcv loss_detection_timer=1591734676081059072 last_tx_pkt_ts=1591734670081059072 timeout=6000
I00004506 0xccb817d01097dded pkt tx pkn=2 dcid=0x4a73c8779fe621a3 scid=0xccb817d01097dded type=Initial(0x00) len=0 k=0
I00004506 0xccb817d01097dded frm tx 2 Initial(0x00) CRYPTO(0x06) offset=0 len=512
I00004506 0xccb817d01097dded frm tx 2 Initial(0x00) PADDING(0x00) len=693
I00004506 0xccb817d01097dded rcv loss_detection_timer=1591734679084367104 last_tx_pkt_ts=1591734673084367104 timeout=6000
I00010512 0xccb817d01097dded rcv loss detection timer fired
I00010512 0xccb817d01097dded rcv pto_count=3
I00010512 0xccb817d01097dded rcv loss_detection_timer=1591734685084367104 last_tx_pkt_ts=1591734673084367104 timeout=12000
I00010512 0xccb817d01097dded pkt tx pkn=3 dcid=0x4a73c8779fe621a3 scid=0xccb817d01097dded type=Initial(0x00) len=0 k=0
I00010512 0xccb817d01097dded frm tx 3 Initial(0x00) CRYPTO(0x06) offset=0 len=512
I00010512 0xccb817d01097dded frm tx 3 Initial(0x00) PADDING(0x00) len=693
I00010512 0xccb817d01097dded rcv loss_detection_timer=1591734691090734848 last_tx_pkt_ts=1591734679090734848 timeout=12000
```
When I run the same h2load 
against litespeed it works.  h2o works with http 1.1 and http/2.  The lsquic client times out as well.  This is using the branch:
```
root@xdp2:~/http2benchmark/http3/src/h2o# git show
commit 01e22cea8129c5083f2d02a8ddc89b9a0ce5ad02 (HEAD -> master, origin/master, origin/HEAD)
Merge: e69471b8 c39cdd15
Author: Kazuho Oku <kazuhooku@gmail.com>
Date:   Sat Jun 6 17:22:22 2020 +0900

    Merge pull request #2350 from h2o/kazuho/h3-misc-fixes
    
    [http3] update quicly (incorporating the PTO improvement), also fix occasional crash

```
I may have done something wrong building it, if so, please let me know.  I'm building it on Ubuntu 20.04.  Thanks!

Bob Perper
rperper@litespeedtech.com

**Comment by rperper** [comment]
We've tested it with 29 and all is well.  Closing.
