### ISSUE TITLE
Can we install just nghttp2 c library without including libnghttp2_asio?

### ISSUE THREAD

**Issue by amulyaprasad** [nghttp2/nghttp2#1471]
I am trying to install nghttp2 and I am getting this error.

error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

In requirements section , its mentioned that

Compiling libnghttp2 C source code requires a C99 compiler. gcc 4.8 is known to be adequate. In order to compile the C++ source code, gcc >= 6.0 or clang >= 6.0 is required. C++ source code requires C++14 language features

So is there anyway we can just install c library without c++ dependencies. My GCC version is 4.8.5.

**Comment by amulyaprasad** [comment]
I am trying to install nghttp2 and I am getting this error.

` error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.`

In requirements section , its mentioned that

> Compiling libnghttp2 C source code requires a C99 compiler. gcc 4.8 is known to be adequate. In order to compile the C++ source code, gcc >= 6.0 or clang >= 6.0 is required. C++ source code requires C++14 language features

So is there anyway we can just install c library without c++ dependecies. My GCC version is 4.8.5

**Comment by akonskarm** [comment]
if you follow the steps in README it will not compile asio parts. you specifically need to ./configure with some flag to enable asio C++ compilation. At least GCC 4.9.4 is required for C++ compilation

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
