### ISSUE TITLE
building libnghttp2_asio on Windows and how to supply the openssl build path?

### ISSUE THREAD

**Issue by skuskusku** [nghttp2/nghttp2#1486]
Hello everyone, this is probably a noob question:

how do I build libnghttp2_asio on Windows? I built nghttp2.lib using the sequence of 

cmake .
cmake --build  .

from a Visual Studio 2017 command prompt. However this doesn't build libnghttp2_asio for me. The output of calling "cmake ." also tells me 

   Features:
      ....
      Libnghttp2_asio:OFF

How do I go about building this library on Windows? The docs tell me sth. about the --enable-asio-lib configure flag, but what would be its synonym for a Windows build?

Along the lines I read in the "cmake ." output something like this:

-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) (Required is at least version "1.0.1")

How do I supply the path to my OpenSSL build to the cmake build command on Windows? I have the latest 1.0.2 version as a local build available, in case that matters. 

Thanks in advance,

-- 
Stefan

**Comment by qugang** [comment]
Have you found a solution?

**Comment by skuskusku** [comment]
It's been a while, but from what I can see in my sources, it is just not necessary to supply the path to openssl. The windows service of mine that is consuming nghttp2.lib simply links against libssl.lib and libcrypto.lib and that's that.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
