### ISSUE TITLE
Memory leak with server

### ISSUE THREAD

**Issue by cmirajkar87** [nghttp2/nghttp2#1491]
Hello Tatsuhiro,

We have used the C implementation of the nghttp2 library in our applications, functionality wise we have what we needed
till now, but one problem we are facing is very high consumption of memory on the SERVER end, just to make sure 
that it was not our application which was leaking memory, I had created a simple application which just uses the nghttp2 
library, so with this also I see very huge memory consumption only on server end, client side memory is constant.

I am doing around 15k requests per second, i get the reply back for every requests there is no problem here but the 
memory consumption hits 1.5 - 2 Gb within 1 hour of tests.

I did one experiment just to know whether the leak happens while processing the request or sending the response
and i found that it happens while the responses are being sent.

For this I dropped every requests on server end and on client end I would generate rst_stream when the message would timeout. so with this memory consumption for the same load after 1 hr was 100 mb on server end and client would remain
at 10mb(this is always constant).

I came across nghttp2_option_set_no_closed_streams api and used this on server end (during initialization) to see if made any difference but it didn't help. 

Framework wise, in the server code i read the data from socket repeatedly, the data is then passed to nghttp2 stack using "nghttp2_session_mem_recv"

I have registered the following callbacks

nghttp2_session_callbacks_set_on_begin_headers_callback
nghttp2_session_callbacks_set_on_header_callback
nghttp2_session_callbacks_set_on_frame_recv_callback
  @@nghttp2_session_callbacks_set_on_stream_close_callback
nghttp2_session_callbacks_set_on_data_chunk_recv_callback

for sending response i call nghttp2_submit_response.
Please note that in my tests the response only has 200OK as the status, no other headers or message body is sent.

So can you please give me some pointers on what can be done here or is there anything which i have not done or done incorrectly.

Thanks,
chetan

**Comment by akonskarm** [comment]
you can also try
nghttp2_option_set_max_deflate_dynamic_table_size(option, 0);

**Comment by cmirajkar87** [comment]
I tried this but the memory consumption is still the same. I FORGOT to mention this in my original issue but in my tests I am creating only one connection and sending the same request from client again and again, so w.r.t this I think this dynamic table size 
shouldn't matter right

**Comment by akonskarm** [comment]
idk, either run it through valgrind/massif or post the code.

**Comment by cmirajkar87** [comment]
Found the issue upon debugging the nghttp2 code, the stream memory is not freed up until max concurrent streams is reached. In my case the max concurrent streams was 1<<32.

**Comment by ranjithpp** [comment]
is there a way to locally drop the stream at server? @cmirajkar87
