### ISSUE TITLE
How to keep sending retry requests after "sess.on_error" is invoked using "libnghttp2_asio"

### ISSUE THREAD

**Issue by jiteshm17** [nghttp2/nghttp2#1492]
Hi
I just started using the `libnghttp2_asio` library and ran the example client and server mentioned at [this](https://nghttp2.org/documentation/libnghttp2_asio.html#client-api) link. However, I am facing a small issue. What if my server is down for a few seconds and then comes back up? I suppose I should keep making requests for a max duration right? So, I added this piece of code in the `sess.on_error` callback in the client code

```
sess.on_error([](const boost::system::error_code &ec){
    std::cerr << " error : " << ec.message() << std::endl;
    boost::asio::io_service io_service;
    int num_retries = 100;
    for(int  i = 0; i < num_retries; i++){
        this_thread::sleep_for(std::chrono::milliseconds(1000));
        cout << "retry attempt "<< i+1 << endl;
        session sess(io_service, "localhost", "3000");
   }
});
```
Despite doing this, I find that the `sess.on_connect` is not being invoked after an initial failure, i.e. to test this, I first run the client without starting the server, but then, later even after starting the server, the connection isn't established. 
```
error: Connection refused
retry attempt 1
retry attempt 2
retry attempt 3
retry attempt 4
retry attempt 5
retry attempt 6
...
retry attempt 100
```
Any help would be appreciated.
Thanks!

**Comment by akonskarm** [comment]
Your code can't work. You can do this by updating an external variable in the "on_error" callback, detecting the failure and recreating the session outside the callback

**Comment by jiteshm17** [comment]
Yeah, doing that worked, thanks
