### ISSUE TITLE
Using an nghttp2::asio_http2::client::session object from multiple threads

### ISSUE THREAD

**Issue by skuskusku** [nghttp2/nghttp2#1497]
Hello everyone,

I am using nghttp2::asio client functionality in order to send payloads to APNS. APNS requires a long standing connection with PING frames within 60s as outlined in the following ticket: #847

My application itself gets incoming requests via its own server functionality on arbitrary threads and for each request it has to send some payload to APNS using the single session to APNS created upfront.

So my application has a dedicated worker thread whose sole purpose is to create this connection upfront. Now I want incoming requests to my application to use this single connection and submit data to the APNS endpoint. Those incoming requests to my application come from secondary threads, so I am wondering how to use the one session created in my worker thread. My current solution simply stores the address of the nghttp2::asio_http2::client::session object created upfront in my worker thread in a global variable of type nghttp2::asio_http2::client::session *. Threads that handle incoming requests to my application now use this pointer and perform the submit method of nghttp2::asio_http2::client::session on it. I wonder if this is a safe approach to the problem or if there are any pitfalls to it. Is it required to wrap each call to the submit method in a mutex so no two threads for two concurrent incoming requests are performed simultaneously? Or is this all just an insane idea of mine and there are better solutions to the problem?

Some pseudo code to illustrate my current solution with lots of omissions, but I hope you get the idea:

```
/// the global pointer to the session:
nghttp2::asio_http2::client::session *g_pHttp2Session = NULL;


/// the worker thread:
UINT __stdcall APNSThread(LPVOID lp)
{
    boost::system::error_code ec;
    boost::asio::io_service io_service;
    std::string uri = g_szAPNSPushUrl;
    std::string scheme, host, service;

    if (host_service_from_uri(ec, scheme, host, service, uri))
    {
        // std::cerr << "error: bad URI: " << ec.message() << std::endl;
        LogMessage(g_dwTlsSlot, L"Error bad URI: %S", ec.message().c_str());
        return (DWORD)E_UNEXPECTED;
    }
    boost::asio::ssl::context tls_ctx(boost::asio::ssl::context::sslv23);
    /// ...more ssl setup stuff....
    nghttp2::asio_http2::client::session sess = scheme == session(io_service, tls_ctx, host, service);

    sess.on_connect([&sess, &uri, pAPNSThreadData](tcp::resolver::iterator
        endpoint_it)
    {
        g_pHttp2Session = &sess;
    }

    sess.on_error([](const boost::system::error_code &ec)
    {
        ec;
        LogMessage(g_dwTlsSlot, L"Error: %S", ec.message().c_str());

        // std::cerr << "error: " << ec.message() << std::endl;
    });

    io_service.run();

    /// io_service now running...
}

/// now the function to handle incoming requests, this will execute on an arbitrary 
/// thread and there can be multiple of them executing simultaneously:

static DWORD PushAPNSInternal(....)
{
    DWORD dwLastError = 0;
    if (g_pHttp2Session)
    { /// start if (g_pHttp2Session)
        boost::system::error_code ec;

        // Generate a crazy filename
        boost::uuids::uuid uuid = boost::uuids::random_generator()();

        nghttp2::asio_http2::header_map headers;

        nghttp2::asio_http2::header_value hv = { boost::uuids::to_string(uuid),
            false };
        headers.emplace("apns-id", hv);
        hv = { "0", false };
        /// more header setup stuff....

        const nghttp2::asio_http2::client::request *req =
            g_pHttp2Session->submit(ec, "POST", uri + "/3/device/" + strDeviceToken,
                szPayload);

        if (ec)
        {
            // std::cerr << "error: " << ec.message() << std::endl;
            return (DWORD)E_UNEXPECTED;
        }

        req->on_response([](const response &res)
        {
            for (auto &kv : res.header())
            {
                kv;
                LogMessage(g_dwTlsSlot, L"Header %S is %S", kv.first.c_str(), 
                    kv.second.value.c_str());
                // std::cerr << kv.first << ": " << kv.second.value << "\n";
            }
            // std::cerr << std::endl;

            res.on_data([](const uint8_t *data, std::size_t len)
            {
                data; len;
                LogMessage(g_dwTlsSlot, L"Data received: %lu bytes", (DWORD)len);
                    // std::cerr.write(reinterpret_cast<const char *>(data), len);
                // std::cerr << std::endl;
            });// end of lambda res.on_data
        }); // end of lambda req->on_response
    } /// end if (g_pHttp2Session)

    return dwLastError;
}

```

Is this approach of mine reasonable and safe? What other options do I have for my problem?

Any help appreciated,

-- 
Stefan

**Comment by akonskarm** [comment]
let the threads submit work items to a queue and let the thread that manages the connection take the items from the queue and send them. queue should have a mutex.

check https://github.com/nghttp2/nghttp2/issues/1216

**Comment by skuskusku** [comment]
Thank you very much akonskarm, I have looked at the ticket you mentioned and have set up and debugged the code example in this ticket that was suggested by Tatsuhiro ("..unify thread1 and thread2..."). I have one question though: The code in Tatsuhiros example schedules repeated invocations of the submit_request with a timer. So a queueing solution would simply look inside the submit_request function if there is something to dequeue from the queue and if so submit a new request followed by a new timer rescheduling operation and if there is nothing to dequeue, it would merely reschedule the timer? So we have a polling solution with the polling interval governed by the timer frequency? Is that right? Or do I miss the point and the dequeueing operation would take place somewhere else?

Again, thanks for your response.

**Comment by akonskarm** [comment]
Yeah so the idea is that every X milliseconds or seconds or whatever submit requests is invoked and you check the queue and take items out and submit them. If there are few items and you finish quickly, then you schedule the timer and wait for its expiration. If there are a lot of items and it takes you longer than the wait time, then I think the timer will expire immediately, but I'm not 100% sure. It's also easy to implement some sort of rate control (for example only do up to X requests every Y milliseconds to have an upper rate limit of Z requests per second).

Best,
Alexandros

**Comment by skuskusku** [comment]
Hi Alexandros,

wouldn't it be a better strategy to dequeue no more than one item per submit_request call, but, while dequeueing, look at the size of the queue and adjust the timer interval accordingly? My idea is: If an item gets dequeued and the size before dequeueing is greater than one, than there are more items waiting after dequeueing, so the timer interval is set to zero (so the next waiting item gets dequeued immediately). If, however, the size of the queue is exactly one in the moment of dequeueing, the timer interval for the next invocation of submit_request can be set to a larger interval, say 100ms or 1000ms, because after dequeueing the queue will be empty. Does that make sense to you? I think the quandary is that attempting to dequeue in the highest possible frequency will make the system as fast as possible, but will unnecessarily burn CPU cycles and drain the battery or consume energy needlessly. 

Thanks for your insights,

-- 
Stefan

**Comment by akonskarm** [comment]
Sorry I don't remember the code on the ticket I liked to exactly. In my code I'm now doing something like

```
void submit_requests() {
  int size= queue.get_size();
  for (int i=0; i<size; i++) {
    dequeue and submit to session
  }
  timer->expire_at...
  timer->async_wait...
}
}
```

but I'm doing this because in the algorithm I sometimes need to reinsert an item to the queue for later - this way I don't try an item more than once per cycle.

I think your strategy/algorithm will depend on your application, if you value latency, if you are working with limited hardware etc. I need it to be as fast as possible and with a 200ms timer I can do 10-15k requests per second at 8kb payload with 1 thread and 1 tcp connection, which is plenty for me.

Best
Alexandros

**Comment by skuskusku** [comment]
Thanks Alexandros!
