### ISSUE TITLE
making asio_client_session_impl more robut

### ISSUE THREAD

**Issue by akonskarm** [nghttp2/nghttp2#1500]
Hi Tatsuhiro

I'm thinking of the following change to asio_client_session_impl.cc

const request *session_impl::submit(boost::system::error_code &ec,
                                    const std::string &method,
                                    const std::string &uri, generator_cb cb,
                                    header_map h, priority_spec prio) {
  ec.clear();

  if (stopped_) {
    ec = make_error_code(static_cast<nghttp2_error>(NGHTTP2_INTERNAL_ERROR));
    return nullptr;
  }

  **if (nghttp2_session_check_request_allowed(session_) == 0) {
    ec = make_error_code(static_cast<nghttp2_error>(NGHTTP2_INTERNAL_ERROR));
    call_error_cb(ec);
    stop();
    return nullptr;
  }**

  http_parser_url u{};
  // TODO Handle CONNECT method
  if (http_parser_parse_url(uri.c_str(), uri.size(), 0, &u) != 0) {
    ec = make_error_code(boost::system::errc::invalid_argument);
    return nullptr;
  }

If you agree it will make it more robust, then I can make a pull request.

Best
Alexandros

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
