### ISSUE TITLE
Is it possible to set time-out for requests

### ISSUE THREAD

**Issue by atari83** [nghttp2/nghttp2#1512]
Hello!

So, I'm writing a client application with nghttp2_asio, and I would like to know if it is possible set time-out for REST requests ?
Say, I want to abort waiting for requests that takes more than 3 seconds from server to response.

Thanks,

**Comment by atari83** [comment]
It seems it has to be controlled in application logic. :)

**Comment by akonskarm** [comment]
could you share your logic?
