### ISSUE TITLE
Crash : http server asynchrous response - segmentation fault (nghttp2  version 1.35.1)

### ISSUE THREAD

**Issue by siddhartha-biswas** [nghttp2/nghttp2#1519]
void local_server::send_response(unsigned int req_id, unsigned int status_code, std::string &data, nghttp2::asio_http2::header_map &nghttp_header_map) {

    io_service_->post([req_id, status_code, data, nghttp_header_map]() {

        const nghttp2::asio_http2::server::response *res;

        auto rsp_it = stream_map_.find(req_id);
        if(!nghttp_header_map.empty()) {
            rsp_it->second.rsp_.write_head(status_code, nghttp_header_map);
        } else {
            rsp_it->second.rsp_write_head(status_code);
        }

        if(!data.empty()) {
            rsp_it->second.rsp_end(data);
        } else {
            rsp_it->second.rsp_end("");
        }
    });
}

The above code stores the reference to nghttp2::asio_http2::server::response against a unique generated request id, in a map. The request is handled in a callback on_request. The response is generated asynchronously for the given request id and sent through send_response.

The objective is to handle multiple parallel streams where the request is handled in a separate thread which also generates the response and sends it. The response is sent in the context of the io_service_.

The issue I am facing is that sometimes the code is crashing after executing a few 100s of request/response with segmentation fault in nghttp2 library. I have no clue why this is happening.

Any help will be appreciated.

The segmentation fault and call stack :-

Program terminated with signal SIGSEGV, Segmentation fault.
#0  nghttp2_map_find (map=0x0, key=-465260576) at nghttp2_map.c:163
163     nghttp2_map.c: No such file or directory.
[Current thread is 1 (Thread 0x7f5ef9ffb700 (LWP 18348))]
(gdb) bt
#0  nghttp2_map_find (map=0x0, key=-465260576) at nghttp2_map.c:163
#1  0x00007f5f0aba15d9 in nghttp2_session_get_stream (session=<optimized out>, stream_id=<optimized out>) at nghttp2_session.c:283
#2  0x00007f5f0aba6876 in nghttp2_session_resume_data (session=<optimized out>, stream_id=<optimized out>) at nghttp2_session.c:7283
#3  0x00007f5f0e5d53aa in nghttp2::asio_http2::server::http2_handler::resume (this=0x7f5ee4459d30, strm=...) at asio_server_http2_handler.cc:428
#4  0x00007f5f0e5d8e53 in nghttp2::asio_http2::server::response_impl::end(std::function<long (unsigned char*, unsigned long, unsigned int*)>) (
    this=this@entry=0x7f5ee444aff0, cb=...) at asio_server_response_impl.cc:81
#5  0x00007f5f0e5d8ef7 in nghttp2::asio_http2::server::response_impl::end (this=0x7f5ee444aff0, data="") at asio_server_response_impl.cc:66
#6  0x00007f5f0e5d7e9e in nghttp2::asio_http2::server::response::end (this=<optimized out>, data=...) at asio_server_response.cc:45
#7  0x0000000000493a52 in local_server::send_response(this=0x1c7efb0, req_id=3858, status_code=200, data=..., nghttp_header_map=...)

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
