### ISSUE TITLE
How to correctly modify string_generator function from asio_common.cc for a byte array (uint8_t)

### ISSUE THREAD

**Issue by CaesarOG** [nghttp2/nghttp2#1531]
My sordid and grimy attempt at doing so is below:
What I don't understand is if I send an argument that is a uint8 array say `uint8_t value[]` with a simple short c-string of characters (since it's unsigned char anyway) terminated by '\0', it prints CORRECTLY within this function `bytes_generator` if I place the print out before the body of the callback. But if I move the print out one line down to inside the body of the callback, I get this string of hex characters which doesn't even convert back to the corresponding ASCII. Example `const uint8_t body[] = {'o', 'l', 's', 'd', 'j', 'a', '\0'};` when printed in server code's `req.on_data` callback using `reinterpret_cast<const char *>` it appears as something like `xe2\xcb\x9f`. I only see the regular print out of the chars on the top line of the `bytes_generator` function if I print before entering the body of the callback. My thinking is: perhaps I'm doing something egregiously wrong with `move` that can't be done with a pointer which CAN be done with an object such as string like in the example `string_generator` function from `asio_common.cc` ? But doing it without `move` produced the same result, leaving me further confused. Pls advise.

```cpp
nghttp2::asio_http2::generator_cb bytes_generator(const uint8_t * data, size_t sz) {
  std::cout << "SIZE DATA: " << sz << std::endl;
  const size_t copy_sz = sz;
  const auto size = std::make_shared<size_t>(copy_sz);
  auto byteio = std::make_shared<std::pair<const uint8_t *, size_t>>(std::move(data), sz);
  return [byteio, size](uint8_t * buf, size_t len, uint32_t * data_flags) -> generator_cb::result_type {
    auto &data = byteio->first;
    auto &left = byteio->second;
    auto n = std::min(len, left);
    std::cout << "len: " << len << std::endl;
    std::cout << "size N: " << n << std::endl;
    std::cout << "left: " << left << std::endl;
    std::cout << "data size: " << byteio->second << std::endl;
    std::cout << "DATA PRINT OUT" << std::endl;
    std::cerr.write(reinterpret_cast<const char *>(data), left); cout << endl;
    std::copy_n(data + (*size) - left, n, buf);
    left -= n;
    if (left == 0) {
      *data_flags |= NGHTTP2_DATA_FLAG_EOF;
    }
    return n;
  };
}
```

**Comment by CaesarOG** [comment]
@tatsuhiro-t I feel like you will be able to spot the problem within a minute, will gratefully appreciate any pointers *pun intended*

**Comment by akonskarm** [comment]
You can't move a pointer like this, it does nothing. Who is controlling the memory of the "data" argument?

Consider doing it like this (shared_ptr could be unique_ptr depending on your needs and your compiler version)

```
struct Payload {
	uint32_t size;
	uint32_t remaining_size;
	std::shared_ptr<char> buffer;
};

nghttp2::asio_http2::generator_cb request_payload_generator(std::shared_ptr<Payload> && payload) {
    return [strio = std::move(payload)](uint8_t *buf, size_t len, uint32_t *data_flags) {
        auto &data = strio->buffer;
        const auto &total = strio->size;
        auto &left = strio->remaining_size;
        auto n = std::min(len, static_cast<std::size_t>(left));
        std::copy_n(data.get() + total - left, n, buf);
        left -= n;
        if (left == 0) {
            *data_flags |= NGHTTP2_DATA_FLAG_EOF;
        }
        return n;
    };
}
```

**Comment by CaesarOG** [comment]
> You can't move a pointer like this, it does nothing. Who is controlling the memory of the "data" argument?
> 
> Consider doing it like this (shared_ptr could be unique_ptr depending on your needs and your compiler version)
> 
> ```
> struct Payload {
> 	uint32_t size;
> 	uint32_t remaining_size;
> 	std::shared_ptr<char> buffer;
> };
> 
> nghttp2::asio_http2::generator_cb request_payload_generator(std::shared_ptr<Payload> && payload) {
>     return [strio = std::move(payload)](uint8_t *buf, size_t len, uint32_t *data_flags) {
>         auto &data = strio->buffer;
>         const auto &total = strio->size;
>         auto &left = strio->remaining_size;
>         auto n = std::min(len, static_cast<std::size_t>(left));
>         std::copy_n(data.get() + total - left, n, buf);
>         left -= n;
>         if (left == 0) {
>             *data_flags |= NGHTTP2_DATA_FLAG_EOF;
>         }
>         return n;
>     };
> }
> ```

This worked! Update, when I switched from this basic example of a uint8_t literal array ie. `uint8_t arr[] = {'o', 'h', 't', '\0'}; uint8_t * arrayPtr = arr;` to using protocol buffers with FlatBuffers library, I was able to use `std::shared_ptr<uint8_t *> buffer = make_shared<uint8_t *>(arrayPtr);` to store the pointer. Nothing else worked with make_shared. 
Otherwise with the original example uint8_t literal array, I had to directly use shared_ptr to create to make it work without turning the input to garbage, this also worked for protocol buffers, but ONLY this creating with shared_ptr worked for the literal array. So --> `std::shared_ptr<uint8_t> buffer = std::shared_ptr<uint8_t>(arrayPtr, std::default_delete<uint8_t[]>())` And then immediately afterwards STILL had to run following to make it work `std::copy_n(arrayPtr, sizeBuff, payload_val.buffer.get())`. Interesting learning experience.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
