### ISSUE TITLE
worker clear mcpool when livecheck using mcpool, maybe cause crash

### ISSUE THREAD

**Issue by lianhansheng** [nghttp2/nghttp2#1543]
base on 1.42.0
livecheck's wb_ and conn_ use mcpool, connection's tls.wbuf and tls.rbuf also use mcpool.
source code:
wb_(worker->get_mcpool()),
conn_(loop, -1, nullptr, worker->get_mcpool()
tls{DefaultMemchunks(mcpool), DefaultPeekMemchunks(mcpool).

ClientHandler destructor will call schedule_clear_mcpool to start mcpool_clear_timer_ when worker_stat->num_connections ==0, mcpool_clear_cb callback call worker->get_mcpool()->clear() to clear mcpool. but now, livecheck is running and using mcpool, will visit wild pointer. especially, livecheck's connection writev_clear fail, not to do tls.wbuf.drain(nwrite). when disconnect function do tls.wbuf.reset(), next = mb->next will visit wild pointer.

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.   #1544 fixes this issue.
