### ISSUE TITLE
nghttp2 adaptable to Boost::Beast and another concurrent lib?

### ISSUE THREAD

**Issue by patlecat** [nghttp2/nghttp2#1549]
I see you use boost asio just like the beast lib does. But could you adapt it to beast too or make it easier to use with beast so no overlapping occurs and the networking lib can be switched transparently? @madmongo1 from the beast team would be happy to help as he said.
I ask because I think also switching to another threading lib would be good idea. Something like Taskflow (https://github.com/taskflow/taskflow) for ex where each request could defined as a task that is then processed in a defined order.

Apparently HTTP/2 messaging is the hardest part and your lib covers that already. While other libs do offer the other 2 features I mentioned.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
