### ISSUE TITLE
Concurrent processing for requests received on nghttp2::asio_http2::server

### ISSUE THREAD

**Issue by testillano** [nghttp2/nghttp2#1554]
Hi,

I have implemented an http2 asio server (server_) following the usual examples (configuration, handler, listen and serve).
My lambda for **req.on_data** dispatchs the message received in a FIFO queue initialized with an arbitrary number of working threads (the queue is similar to [this](https://github.com/embeddedartistry/embedded-resources/blob/master/examples/cpp/dispatch.cpp)):
```
void MyServer::setHandler()
{
    server_.handle("/", rootHandler());
}

nghttp2::asio_http2::server::request_cb MyServer::rootHandler()
{
    return [&](const nghttp2::asio_http2::server::request & req,
               const nghttp2::asio_http2::server::response & res)
    {
        req.on_data([&res, &req, this](const uint8_t* data, std::size_t size)
        {
            queue_dispatcher_.dispatch([&] { receive(req, res); });
        });
    };
}
```

The '**receive()**' method pretends to do the work in a separate thread, including the _**res.write_head()**_ and **_res.end()_**.
I even simulate delays following the _non-blocking_ method detailed at asio sv [example](https://github.com/nghttp2/nghttp2/blob/master/examples/asio-sv.cc).

When launching `h2load -n10000 -c1 -m1 <uri> -d <post file>`, and also with more concurrent streams, my server crashes.

**I would like to know if my pretension to have concurrent processing is a nonsense and offers nothing.**
**I would also know how I can use req/res in my separate thread (this seems to be the cause of the problem).**

Thank U very much

**Comment by testillano** [comment]
Probably, this is what I'm looking for:
https://gist.github.com/tatsuhiro-t/ba3f7d72d037027ae47b
I will test it

**Comment by sptrakesh** [comment]
@testillano were you able to get the above approach to work?  I have some issues with handling input data (post, put etc).  I believe it is a timing issue with the thread pool not potentially having started processing a request, while the `on_data` callback is in play.  In my tests, I was getting the user input data very inconsistently.

**Comment by testillano** [comment]
Yes I did it following the mentioned gist.
My concrete problem is that in my implementation, my threads was using a different io_context but you have to use the one provided by tatsuhiro. So, the stream is constructed with res.io_context:
https://gist.github.com/tatsuhiro-t/ba3f7d72d037027ae47b#file-asio-sv3-cc-L81

You can see my own implementation in my wrapper library (https://github.com/testillano/http2comm), where I achieve to manage concurrent processing in two different ways:
* creating threads on demand to process the request with their own lifecycle (detached)
* using pre-inititlized threads in a FIFO queue
The key is to do the stream commit posting over nghttp2 io_context:
https://github.com/testillano/http2comm/blob/master/src/Stream.cpp#L128

I'm working on a private repository still not public but it will be in few weeks (not ready the minimum implementation), using that wrapper library (https://github.com/testillano/http2comm). If you have any doubt don't hesitate to contact.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
