### ISSUE TITLE
MSVC/Windows compile problems with "ssize_t" as return type for callback functions

### ISSUE THREAD

**Issue by ghesketh** [nghttp2/nghttp2#1555]
For example:

>`typedef ssize_t (*nghttp2_data_source_read_callback)(nghttp2_session *session, int32_t stream_id, uint8_t *buf, size_t length, uint32_t *data_flags, nghttp2_data_source *source, void *user_data);`

MSVC/Windows does not define `ssize_t`, but it seems like a fix could be to use `int` as the return type, since it is either a value from `enum nghttp2_error` or "By default, ... limited to 16KiB" — and `int` fits these semantics (especially the `enum` case)

**Comment by noloader** [comment]
On Windows use `SSIZE_T`. See [Windows Datatypes](https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types) in MSDN.

**Comment by tatsuhiro-t** [comment]
v1.60.0 introduced nghttp2_ssize API.  One can get rid of ssize_t completely if wanted.
