### ISSUE TITLE
running nghttp2 server (c++ asio) handling large traffic

### ISSUE THREAD

**Issue by atari83** [nghttp2/nghttp2#1556]
Hello!
I've implemented nghttp2 server with boost asio, it is pretty much looks like the tutorial implementation.  
So, basically I'm using "nghttp2::asio_http2::server::http2"  and using "num_threads" to give it more threading resources.

The logic on server is very straight forward, it receives REST-JSON requests and after processing the requests it'd log them into the database. 

I didn't push so many traffics on the server, yet. But I wanted to know your insight that what preparations needs to be done to make the server more responsive in case of heavy incoming traffic.

Should I actually need to use separated thread-pool (not the server threadpool), to queue incoming requests and process them there ? Does it make sense ?

Thanks,

**Comment by sptrakesh** [comment]
See issue 1554 for some context.

**Comment by atari83** [comment]
Thanks.
