### ISSUE TITLE
Segfault when calling shutdown on a session which is still connecting

### ISSUE THREAD

**Issue by janoszakarias** [nghttp2/nghttp2#1563]
Hi,

I've received a segfault when calling shutdown on a session was still connecting and has not yet called either on_connect() or on_error().
It seems the issue is that the session ptr is not checked against a nullptr in nghttp2_session.c - session_terminate_session() which is called by session_impl::shutdown() :

```
static int session_terminate_session(nghttp2_session *session,
                                     int32_t last_stream_id,
                                     uint32_t error_code, const char *reason) {
  int rv;
  const uint8_t *debug_data;
  size_t debug_datalen;

  if (session->goaway_flags & NGHTTP2_GOAWAY_TERM_ON_SEND) {
    return 0;
  }
```

Since nghttp2_session *session_ is initialized as nullptr in constructor and has not yet been set to a valid object, the code crashes.

**Comment by DrAlexx** [comment]
Hello,
Seems I have made a pull request with the fix
https://github.com/nghttp2/nghttp2/pull/1576
