### ISSUE TITLE
h2load should provide the stats in structured data

### ISSUE THREAD

**Issue by Seraphime** [nghttp2/nghttp2#1566]
Hi,

We're using h2load for benchmarking and optimization purposes.
Because the stats h2load outputs are in an unstructured format, we had to write some tooling to parse it.

I think the community would benefit from having a structured representation of the stats.

I'm thinking about Json, but even csv could do the trick.

**Comment by jasnell** [comment]
+1, this would definitely be useful. In Node.js we had to write some parsing logic for it also.

**Comment by Seraphime** [comment]
I propose the following schema

```
{
    "connections": 1,       //  (int) How many connections did h2load create to the server
    "total_requests": 500,  //  (int) How many requests were requested from h2load to make
    "failed_requests": 5,   //  (int) How many requests failed due to connection problems/RST_STREAM
    "concurrent_streams": 10,  //  (int) Concurrent requests per connection
    "total_time_us": 1788900,  //   (int64) Total time for all requests to complete in microseconds
    "throughput_kbs": 5730.000,   //   (double) throughput in kilobytes per second
    "requests_per_second": 40.30, //    (double) requests per second
    "requests_stats": {           // Provide min/max/med/sd stats in microseconds
           "min_outlier": 178890000,        // (int64) minimal outlier
           "max_outlier": 178890000,        // (int64) maximal outlier
           "median": 178890000,             // (int64) median
           "std_deviation": 0               // (int64) standard deviation
     },
    "connect_stats": {             // Provide min/max/med/sd stats in microseconds
           "min_outlier": 178890000,         // (int64) minimal outlier
           "max_outlier": 178890000,         // (int64) maximal outlier
           "median": 178890000,              // (int64) median
           "std_deviation": 0                // (int64) standard deviation
     },
    "first_byte_stats": {           // Provide min/max/med/sd stats in microseconds
           "min_outlier": 178890000,         // (int64) minimal outlier
           "max_outlier": 178890000,         // (int64) maximal outlier
           "median": 178890000,              // (int64) median
           "std_deviation": 0                // (int64) standard deviation
     }
}
```

Bellow is my reading of the stats that h2load provides currently. 

```
finished in 724.36ms, 690.27 req/s, 52.01KB/s
requests: 500 total, 500 started, 500 done, 500 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 500 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 37.67KB (38577) total, 2.00KB (2047) headers (space savings 94.07%), 26.86KB (27500) data
                     min         max         mean         sd        +/- sd
time for request:     7.52ms    178.11ms     28.82ms     42.89ms    92.00%
time for connect:       78us        78us        78us         0us   100.00%
time to 1st byte:     7.64ms      7.64ms      7.64ms         0us   100.00%
req/s           :     690.44      690.44      690.44        0.00   100.00% 	
```

The first line

```
finished in 724.36ms, 690.27 req/s, 52.01KB/s
```

gives

- total time of the benchmark
- approximation of how many requests were executed per second
- throughput in kilobytes.

The second line

```
requests: 500 total, 500 started, 500 done, 500 succeeded, 0 failed, 0 errored, 0 timeout
```

gives an overview of the requests executed

- total requests
- how many started
- how many completed
- how many received a success error code
- how many failed (RST_STREAM/connection failure)
- how many received a 400/500 error code
- how many timed out

The third line

```
status codes: 500 2xx, 0 3xx, 0 4xx, 0 5xx
```

gives the repartition of status codes

The fourth line

```
traffic: 37.67KB (38577) total, 2.00KB (2047) headers (space savings 94.07%), 26.86KB (27500) data
```

provides insight on how many bytes were transferred and to what they correspond

- Total bytes transferred
- Total header bytes transferred 
- Space saving from compression
- Total data bytes transferred

The next line

```
time for request:     7.52ms    178.11ms     28.82ms     42.89ms    92.00%
```

gives

- Minimal time for stream completion (outlier)
- Maximal time for stream completion (outlier)
- Median time for stream completion
- Standard deviation for stream completion

The next two lines provide the same information but respectively for the time to connect and the time for the first byte.

```
time for connect:       78us        78us        78us         0us   100.00%
time to 1st byte:     7.64ms      7.64ms      7.64ms         0us   100.00%
```

And the last line provides the same statistics as the  3 lines above for requests per second, but this metric is only meaningful for multiple client request as we already have it noted in the summary above.

**Comment by tatsuhiro-t** [comment]
The proposed schema looks good.
