### ISSUE TITLE
rps option dose not limit of request rate

### ISSUE THREAD

**Issue by drfunjohn** [nghttp2/nghttp2#1584]
Hi.
when I run next h2load with next values: 
`h2load --rps=70 --h1 -t1 -c50 -D20s`
I get correct rps:
`finished in 20.01s, 3497.50 req/s, 403.03KB/s
requests: 69950 total, 70000 started, 69950 done, 69950 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 69950 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 7.87MB (8254100) total, 5.40MB (5665950) headers (space savings 0.00%), 136.62KB (139900) data
                     min         max         mean         sd        +/- sd
time for request:      703us     18.96ms      3.69ms      1.33ms    66.71%
time for connect:        5us       325us       167us       108us    52.00%
time to 1st byte:     2.89ms      4.65ms      3.68ms       751us    38.00%
req/s           :      69.94       69.95       69.94        0.00    60.00%`

but when I encrease rps to 78 (per client) I get:

`h2load --rps=78 --h1 -t1 -c50 -D20s`

`finished in 20.01s, 11506.50 req/s, 1.29MB/s
requests: 230130 total, 230180 started, 230130 done, 230130 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 230130 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 25.90MB (27155340) total, 17.78MB (18640935) headers (space savings 0.00%), 449.48KB (460270) data
                     min         max         mean         sd        +/- sd
time for request:      254us     20.98ms      2.76ms      1.64ms    73.02%
time for connect:       32us       284us       183us        64us    66.00%
time to 1st byte:     1.75ms      4.59ms      3.91ms       624us    88.00%
req/s           :     165.99      661.60      230.12       93.95    92.00%`

This test run in the container with Alpine image. Tool was compiled from source without any custom parameters.
h2load nghttp2/1.44.0-DEV

**Comment by tatsuhiro-t** [comment]
I could not reproduce this so far.

**Comment by drfunjohn** [comment]
so when you try it it works as expected? Thanx. I will try to find more details about reproducing.
