### ISSUE TITLE
Does nghttp2_session_close_stream (and nghttp2) allow reentrancy?

### ISSUE THREAD

**Issue by mdouglass** [nghttp2/nghttp2#1590]
Hello,

I am investigating an issue in node.js (see https://github.com/nodejs/node/issues/38964 for the gory details) which is caused because it is calling `nghttp2_session_close_stream` reentrantly from inside `session->callbacks.on_stream_close_callback`. The reentrant call ends up causing a crash (or an ASAN-violation if that is turned on) because the inner calls destroys the stream and then the outer call tries to access the stream.

I am not clear from the nghttp2 documentation if this is supposed to work or not and it would help me in solving the node.js issue to know.

Thanks!

**Comment by tatsuhiro-t** [comment]
Some functions are known to cause crash when they are called from callback functions: https://nghttp2.org/documentation/programmers-guide.html#remarks

From the thread, it looks like nodejs tried to send something from callback, which means to call  nghttp2_session_mem_send or nghttp2_session_send?  That might cause crash.

**Comment by mdouglass** [comment]
Thanks! I missed that comment in the docs.
