### ISSUE TITLE
Can the quic branch be merged instead of rebased?

### ISSUE THREAD

**Issue by bneradt** [nghttp2/nghttp2#1604]
This is a process request. We use the `quic` branch for HTTP/3 development for [proxy-verifier](https://github.com/yahoo/proxy-verifier). Functionally I'm pleased with how well this works. But on a proxy-verifier release basis we pin the various HTTP libraries we use (ngtcp2, openssl quic, nghttp2, nghttp3). The desire is to be able to reproduce a release in the future by checking out the proxy-verifier version and rebuild it. However, this does not work because the quic branch in nghttp2 is rebased periodically, which rewrites history and removes the pin that we would like to use. I deal with this periodically by updating the pin. I appreciate the work that goes into keeping these branches up to date. Instead of rebasing the nghttp2 quic branch periodically, can the nghttp2 quic branch instead be merged from the main branch? Keeping the quic branch free from events that rewrite history will immensely help those (like myself) who are using this branch.

Thank you for your work on this project!

**Comment by bneradt** [comment]
@ messaging the lead quic developer in case that is helpful: @tatsuhiro-t

**Comment by tatsuhiro-t** [comment]
Thank you for suggestion.  I'll try to minimize the disruption by merging master to quic branch.

**Comment by tatsuhiro-t** [comment]
quic branch was merged into master.

**Comment by bneradt** [comment]
Confirmed: the https://github.com/nghttp2/nghttp2/commit/19cf303828eca4653130e1aaf27aa57319e3b819 commit still exists and has not been removed via a history rewrite. Thank you!
