### ISSUE TITLE
[libnghttp2_asio] - Get Thread ID's PID of thread

### ISSUE THREAD

**Issue by mohsenomidi** [nghttp2/nghttp2#1606]
Dear contributors,

For higher resolution log process needs to get the PID(Thread ID)  the value returns by `gettid()` for each listener threads, ​for example if you have 5 thread in on on listener/port, is there any way to get these threads PID's. 

Regards,

**Comment by JackyYin** [comment]
Hi,
I am trying to help here.
Not sure if this helps but, currently you can use `gettid()` anytime from your server handler callback:
```
    server.handle("/", [](const request &req, const response &res) {
      std::cout << "tid in cb: " << gettid() << std::endl;
      res.write_head(200, {{"foo", {"bar"}}});
      res.end("hello, world\n");
    });
```

**Comment by mohsenomidi** [comment]
This works only when you receive the request and return result per request, I need to gettid when server start serving before processing any request, and after that the monitoring system can watch to each thread, also per request gettid() add processing overhead and impact on system performance even if checking the variable if it been set before or not (conditions overhead, takes cpu time and pulse) for large amounts of request and more TPS it will impact performance

**Comment by JackyYin** [comment]
Thanks for your explanation, I will try to add an interface to get all thread IDs.
