### ISSUE TITLE
-ljemalloc: applications were requested (--enable-app) but dependencies are not met

### ISSUE THREAD

**Issue by PengXuu** [nghttp2/nghttp2#1616]
log as follow:
checking for library containing malloc_stats_print... -ljemalloc
configure: error: applications were requested (--enable-app) but dependencies are not met.
And i already installed jemalloc:
ls /usr/local/lib
cmake             libjemalloc.a          libssl.so
engines-1.1       libjemalloc_pic.a      libssl.so.1.1
libcrypto.a       libjemalloc.so         libwebsockets.a
libcrypto.so      libjemalloc.so.2

**Comment by JackyYin** [comment]
Hello,
I think it's not bacause of the `jemalloc`.
you should also check `zlib` and `libev` and `libcares` in your environment.

```
if test "x${request_app}" != "xno" &&
   test "x${have_zlib}" = "xyes" &&
   test "x${have_openssl}" = "xyes" &&
   test "x${have_libev}" = "xyes" &&
   test "x${have_libcares}" = "xyes"; then
  enable_app=yes
fi
```
