### ISSUE TITLE
GOAWAY exchange

### ISSUE THREAD

**Issue by khlebnikov** [nghttp2/nghttp2#1617]
Hello,

the HTTP/2 spec suggests (from my reading) that both endpoints should exchange `GOAWAY` frames during graceful shutdown.  Specifically, I refer to this clause:

> A GOAWAY frame might not immediately precede closing of the
   connection; **a receiver of a GOAWAY that has no more use for the
   connection SHOULD still send a GOAWAY frame before terminating the
   connection**.
   
(emphasis mine)

A different decision have been made for nghttp2 it seems.  Specifically, `nghttp2_session_want_read` will return `0` if we've *sent* a `GOAWAY` frame and no streams remain open even though a "response" `GOAWAY` frame hasn't been received.  

Could you please clarify why such decision has been made?  Is it because the wording uses `SHOULD` instead of something like `MUST`?  Is it true of most HTTP/2 peers that they don't respond with a `GOAWAY` of their own if they receive one?

**Comment by tatsuhiro-t** [comment]
If I understand the relevant part of RFC correctly, RFC does not require both endpoints to exchange GOAWAY.  No such requirement exists.  The rule is very simple: if an endpoint is willing to close the connection, it should send GOAWAY even if it has already received GOAWAY.

**Comment by khlebnikov** [comment]
Oh, I see.  Thank you for clarification!
