### ISSUE TITLE
On Windows ssize_t is defined in config.h

### ISSUE THREAD

**Issue by nacho** [nghttp2/nghttp2#1633]
If you have a library or an application like libsoup that uses nghttp2.h you should expect that the api types are accessible. Instead it exposes api wth the ssize_t which is not defined by default with msvc on Windows. Instead of having the type generated and defined in config.h you should have it defined (if not yet defined in nghttp2.h) for those libraries or apps that make use of it.

**Comment by hrxi** [comment]
I also hit this while packaging libnghttp2 for wrapdb: https://github.com/mesonbuild/wrapdb/pull/1221.

**Comment by tatsuhiro-t** [comment]
v1.60.0 introduced nghttp3_ssize API.  One can get rid of ssize_t if wanted.
