### ISSUE TITLE
h2load cannot set max_frame_size

### ISSUE THREAD

**Issue by robaho** [nghttp2/nghttp2#1639]
If the default frame size of 16k is too small for high throughput transfers.

There is no way to set the receiver frame size using h2load.

**Comment by robaho** [comment]
added https://github.com/nghttp2/nghttp2/pull/1640 to enable this

**Comment by robaho** [comment]
I think the documentation [here](https://nghttp2.org/documentation/h2load-howto.html#flow-control) needs to be updated as well.

**Comment by tatsuhiro-t** [comment]
Why?  The size of frame is irrelevant to flow control.

**Comment by robaho** [comment]
Because it is a guide, and the section is not the help, but is offered with "and it may affect benchmarking results".

The frame size will affect the benchmarking results for large transfers by 5x-10x and I think it should be noted (and probably also discussed why - e.g. reduces contention in concurrency by reducing the number of frames needed to be processed).

**Comment by tatsuhiro-t** [comment]
Could you give me the evidence that the large frame size offers 10x performance increment?  with the detailed client and server setup and configurations.

**Comment by robaho** [comment]
The full discussion can be found [here](https://groups.google.com/d/msgid/golang-nuts/89926c2f-ec73-43ad-be49-a8bc76a18345n%40googlegroups.com).

In general, as compared to Http1, the framing of Http2 is overhead. By increasing the frame size you lower the overhead per byte transmitted for large transfers.

It may be difficult to detect the overhead unless you are working on a very fast network. In lieu of that, running the client and server on the same machine using local networking will get you close (although with modern networks the CPU overhead of running both may be worse).

Using an iMac with i7 quad-core processor, I obtained the following results:

> Using a Go server with default frame size (16k):
> 
> Go client:  900 MB/s
> Java client: 1300 MB/s
> curl: 1500 MB/s
> 
> Using a Java server with default frame size (16k):
> 
> Go client: 670 MB/s
> Java client: 720 MB/s
> curl: 800 M/s
> 
> Using Go server using 256k client max frame size:
> 
> Go client: 2350 MB/s
> Java client: 2800 MB/s
> h2load: 4300 MB/s
> 
> Using Java server using 256k client max frame size:
> 
> Go client: 2900 MB/s
> Java client: 2800 MB/s
> h2load: 3750 MB/s

**Comment by robaho** [comment]
So, in the above case, it is not quite 10x, closer to 5x from worst to best using Go. This is representative because the overhead of frame handling in the Go implementation is higher than in h2load.

I would guess though that if tests were run using h2load with multiple concurrent streams you might see similar effects.

**Comment by tatsuhiro-t** [comment]
Thanks.  I'm not sure it is due to the issue for the particular implementations (Go and Java), but if you insist on adding the documentation, it would go to the separate section.

**Comment by robaho** [comment]
I don't disagree, but the fact is that many implementations will have overhead in frame processing and a larger frame size amortizes this cost.

I wasn't able to duplicate using nghttpd and h2load - but mainly because the only disk I had with a file larger than 2GB was external and the transfer rate was the limiting factor.

**Comment by robaho** [comment]
Actually, it didn't make full sense to me so I retested. The issue is that nghttpd is not properly supporting the larger frames requested by the client - that is most likely why there is no difference. I am going to file another issue.
