### ISSUE TITLE
Build fails on gcc because of bpf

### ISSUE THREAD

**Issue by Shaac** [nghttp2/nghttp2#1641]
Hello,

Since 1.45.0 (more exactly commit f0d1e50d5a4b10992893933ff9972d27b2970579), build is broken when compiling with bpf support (which was introduced in 1.45.0) and using gcc as compiler.

There are two issues here:

- The first one is that bpf support is forced on CMake build. With autoconf, the flag `--with-libbpf` is required to activate the feature, but with CMake it is sneakily activated if libbpf is installed (which will be the case if you have qemu installed for example). And there is no way to deactivate it, I’d argue that it should be like other options in `CMakeOptions.txt`, and deactivated by default.
- The second is the build failure itself. The compile command for `reuseport_kern.o` contains `-target bpf`, but gcc has no such option. It will exit with error `gcc: error: unrecognized command-line option ‘-target’`. I believe clang has this option, that’s probably how it was tested. I believe gcc now has bpf support, but I don’t know what option should be passed.

However those issues are fixed, the most important from my point of vue, it that `cmake . && cmake --build .` should work right of the box. It did on 1.44.0, and now it does not. This is particularly problematic as nghttp2 is a dependency for curl with http2 support in https://github.com/Microsoft/vcpkg, and vcpkg uses cmake builds, making now curl[http2] in vcpkg broken if you have libbpf installed on your machine (and gcc as default compiler as most linux distributions have).

**Comment by tatsuhiro-t** [comment]
dec233b9ef19d0cd81ea9edaa545a2723566a3f8 disables detection of libbpf by default.
For now, building ePBF program needs clang.  It is optional even if HTTP/3 is enabled, and curl does not need it.

**Comment by Shaac** [comment]
Great thanks, that fixes the issues for me! Thanks for the fast fix.

Once 1.47 is released, nghttp2 will be able to be upgraded on vcpkg and the rest of the issues will be done.

I would still suggest that a warning is issued if someone wants to build ePBF and clang is not the selected compiler in case someone encounters the same kind of issues in the future.
