### ISSUE TITLE
Continuation frame question

### ISSUE THREAD

**Issue by peve** [nghttp2/nghttp2#1649]
Hi,
I'm running a test http2 server using `nghttpd --no-tls --verbose 8000`. Then I'm running a simple node js script that fires two identical requests in parallel to the same server endpoint using the same http2 connection.

The first request is responded with a `HEADERS` frame with the End Headers flag set, followed by the `DATA` frame etc. However, the second request is responded with a `HEADERS` frame _without_ the End Headers flag set, then followed by a `CONTINUATION` frame with the End Headers flag set, then finally the `DATA` frame.

My question is why a `CONTINUATION` frame is used for the second request. The requests are trivial GET requests without any custom headers, and so are the responses. The same `HEADERS` data is returned by the server for both requests, but for the second request it's for some reason split up into a `HEADERS` + `CONTINUATION` frame.

I would appreciate if someone could explain this behavior to me. I've attached a wireshark packet capture of the requests/responses.

[continuation-frame-capture.zip](https://github.com/nghttp2/nghttp2/files/7577172/continuation-frame-capture.zip)

**Comment by tatsuhiro-t** [comment]
It looks like you used very old version.  Could you try the latest version?

**Comment by peve** [comment]
Thanks for the quick repsonse.

I tried with the latest version but am still seeing the same thing.
The HEADER frame now contains the `server: nghttpd nghttp2/1.46.0` header, so should be on the latest. Could it be something on the client side?

Attaching a new packet capture.
[continuation-frame-capture-2.zip](https://github.com/nghttp2/nghttp2/files/7580711/continuation-frame-capture-2.zip)

**Comment by tatsuhiro-t** [comment]
Could you share the client code to reproduce this issue?

**Comment by peve** [comment]
Sure.

http2client.js:
```
const http2 = require('http2')

const run = async () => {
  const session = http2.connect('<nghttp2 server>');
  session.on('error', (err) => console.error("error", err))

  const sendRequest = (path) => {
    const req = session.request({':path': `/${path}`})
    req.end()

    let data = ''
    req.on('data', (chunk) => {
      data += chunk
    })

    req.on('end', () => {
      console.log(`${data}`)
    })
  };

  sendRequest("test.txt");
  sendRequest("test.txt");

  await new Promise((r) => {
    setTimeout(r, 1000)
  });
  session.close();
};

run().then(() => {
  console.log("done");
})
```

Running using ` node .\http2client.js` with node v14.16.1.

**Comment by peve** [comment]
Interesting. I'm not able to reproduce this on localhost either.

That SETTINGS frame is odd indeed. It's not connecting directly to the nghttpd server, there's a number of hops in between. Maybe some intermediary box that intercepts and injects the SETTINGS frame as well as splitting the second request's HEADER into a CONTINUATION frame.
