### ISSUE TITLE
nghttp2_session_set_local_window_size results in increase memory usage

### ISSUE THREAD

**Issue by kunalekawde** [nghttp2/nghttp2#1655]
Hello,

This is not an issue but clarification.
As part of server, we added nghttp2_session_set_local_window_size(32 MB) which fixed the window related issue. As a side effect though this API is reflecting in memory profiling. Does using this API will implicitly result in more memory usage or there would be some API invocation missing in application as part of clean-up w.r.t. use of this API ?

Thanks

**Comment by tatsuhiro-t** [comment]
I do not think the function directly increases memory usage.  Increasing window size means that a remote endpoint can send more amount of data at a time and if application code buffers them, it might use more memory as a result.
