### ISSUE TITLE
How can  I set the local port for backend HTTPS traffic?

### ISSUE THREAD

**Issue by bhushanwankhede** [nghttp2/nghttp2#1656]
Hello,

I am using nghttpx as proxy on ubuntu,
I have  configured **forntend to 127.0.0.1:8443;no-tls** and  **backend to destination server [url,port;proto=h2;tls;dns].**
and https traffic is working fine, **but all https traffic going via ephemeral port to destination server**.
destination server https traffic going via ephemeral port so for every request client port is different, 
and I want local port (fix port) for https traffic on nghttpx. 
Is there any configuration to configured local port or bind local port  (fix port) for  backend https traffic.

I need help in this.
thanks.

**Comment by chengyechun** [comment]
You do not display all nghttpx configurations. so I do not know whether you are a forward proxy or a reverse proxy. According to your description, it should be a reverse proxy. The port of the server should be specified by the backend server and configured in the nghttpx.conf file.
