### ISSUE TITLE
Divergent interpretation of RFC7541 when using small HPACK dictionaries

### ISSUE THREAD

**Issue by wtarreau** [nghttp2/nghttp2#1660]
Hello Tastuhiro!

We're discussing here (https://github.com/haproxy/haproxy/issues/1498) with a user who noticed that the nghttp client fails to communicate with haproxy when the dictionary size is set to zero in nghttp. But haproxy doesn't use the dictionary. The user found that modifying haproxy to first emit an HPACK table size update of zero is sufficient to fix the issue. However based on my reading of the spec it should not be needed, as the defaut size ought to be the negotiated one in the settings until adjusted otherwise in HPACK.

Specifically, the HPACK spec says:
```
   Protocols that use HPACK determine the maximum size that the encoder
   is permitted to use for the dynamic table.  In HTTP/2, this value is
   determined by the SETTINGS_HEADER_TABLE_SIZE setting (see
   Section 6.5.2 of [HTTP2]).
```

The spec also says that the sender may choose to reduce the size to a lower or equal value, and that it has to be advertised using a table size update:
```
   An encoder can choose to use less capacity than this maximum size
   (see Section 6.3), but the chosen size MUST stay lower than or equal
   to the maximum set by the protocol.

   A change in the maximum size of the dynamic table is signaled via a
   dynamic table size update (see Section 6.3).  This dynamic table size
   update MUST occur at the beginning of the first header block
   following the change to the dynamic table size.  In HTTP/2, this
   follows a settings acknowledgment (see Section 6.5.3 of [HTTP2]).
```

But in this case if the H2 SETTINGS frame indicates zero, the only permitted value is zero and there's no size change to be performed.

That's why my reading of the spec tells me that it ought not to be required to send this initial dynamic table size update, and that maybe nghttp assumes 4kB by default unless stated otherwise by this. This seems to be supported by the tests that show that any header table value between 0 and 4095 triggers the problem. But it is also possible that we're having a different interpretation of the spec that would need to be sorted out with the HTTP WG. Please note that I'm absolutely not against modifying haproxy to systematically send that table size update (at least to allow the client to free unused memory) but I'd like to do it for a valid reason and here it seems not necessary.

Here's a simple reproducer:
Start haproxy with this small test config:
```
frontend test
        bind :8080
        mode http
        timeout client 5s
        http-request return status 200 string "Hello" content-type "text/plain"
```
Launch it this way:
```
$ haproxy -db -f test.cfg
```

In another terminal start nghttp and see the COMPRESSION_ERROR being sent:
```
$ nghttp -v --header-table-size=0 http://localhost:8080
[  0.000] Connected
[  0.000] send SETTINGS frame <length=18, flags=0x00, stream_id=0>
          (niv=3)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
          [SETTINGS_HEADER_TABLE_SIZE(0x01):0]
[  0.000] send PRIORITY frame <length=5, flags=0x00, stream_id=3>
          (dep_stream_id=0, weight=201, exclusive=0)
[  0.000] send PRIORITY frame <length=5, flags=0x00, stream_id=5>
          (dep_stream_id=0, weight=101, exclusive=0)
[  0.000] send PRIORITY frame <length=5, flags=0x00, stream_id=7>
          (dep_stream_id=0, weight=1, exclusive=0)
[  0.000] send PRIORITY frame <length=5, flags=0x00, stream_id=9>
          (dep_stream_id=7, weight=1, exclusive=0)
[  0.000] send PRIORITY frame <length=5, flags=0x00, stream_id=11>
          (dep_stream_id=3, weight=1, exclusive=0)
[  0.000] send HEADERS frame <length=38, flags=0x25, stream_id=13>
          ; END_STREAM | END_HEADERS | PRIORITY
          (padlen=0, dep_stream_id=11, weight=16, exclusive=0)
          ; Open new stream
          :method: GET
          :path: /
          :scheme: http
          :authority: localhost:8080
          accept: */*
          accept-encoding: gzip, deflate
          user-agent: nghttp2/1.46.0
[  0.000] recv SETTINGS frame <length=12, flags=0x00, stream_id=0>
          (niv=2)
          [SETTINGS_ENABLE_CONNECT_PROTOCOL(0x08):1]
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
[  0.000] recv SETTINGS frame <length=0, flags=0x01, stream_id=0>
          ; ACK
          (niv=0)
[  0.000] send GOAWAY frame <length=8, flags=0x00, stream_id=0>
          (last_stream_id=0, error_code=COMPRESSION_ERROR(0x09), opaque_data(0)=[])
Some requests were not processed. total=1, processed=0
```

Note that I could reproduce it with both nghttp 1.46.0 and 1.35.0 so I suspect it has always worked like this.

**Comment by tatsuhiro-t** [comment]
This is a bit complicated topic and I had some discussions in the past:

- https://lists.w3.org/Archives/Public/ietf-http-wg/2015OctDec/0088.html
- https://github.com/nghttp2/nghttp2/issues/396

My understanding is that encoder must send dynamic table size change if SETTINGS_HEADER_TABLE_SIZE changes the maximum size it uses, including the change to the initial value 4096.  In this particular case, client (decoder) sends SETTINGS_HEADER_TABLE_SIZE = 0, which changes maximum table size from 4096 to 0 on server (encoder) side, server must send dynamic table size change.

**Comment by wtarreau** [comment]
Very interesting, thanks for the link, it seems I missed this conversation by then!

What I'm seeing there is that Cory, Martin and I all have the same understanding of the spec (i.e. no need to advertise an update if there is no change), which you seemed to agree with. As mentioned by Cory, here the client's setting was already ACKed by the server by the SETTINGS ACK frame, and does not need to be reflected a second time at the HPACK layer since nothing ever changes in HPACK (i.e. it starts at zero as instructed by the SETTINGS frame and stays at zero thus never changes).

Thus I think that as long as the SETTINGS frame was not rejected, there is no reason for expecting that the peer would use a different value than the negotiated one, and that as such your received-side HPACK dictionary ought to be sized according to the advertised size.

**Comment by tatsuhiro-t** [comment]
SETTINGS_HEADER_TABLE_SIZE = 0 changes the maximum size of dynamic table from 4096 to 0.  Even though haproxy does not use dynamic table, in protocol spec, the change must be signaled in dynamic table update as per:

```
   A change in the maximum size of the dynamic table is signaled via a
   dynamic table size update (see Section 6.3).
```

The text uses "A change in the maximum size of the dynamic table", not the amount of the actual memory used by encoder.

And also there is no text in RFC that SETTINGS ACK can be used as an implicit dynamic table update.

Perhaps, we do not agree whether the first SETTINGS_HEADER_TABLE_SIZE = 0 changes  the maximum size of the dynamic table or not.  In my opinion, it is a change to the initial value 4096 because if SETTINGS_HEADER_TABLE_SIZE is missing, the maximum size stays at 4096 bytes.

**Comment by wtarreau** [comment]
But no change is performed from the initial size that is already set by SETTINGS_HEADER_TABLE_SIZE, it's only undergone. I totally agree that SETTINGS_HEADER_TABLE_SIZE changes the initial value from 4096 to this value, but at the HPACK layer it's not changed again, it remains at the value imposed by the client.

With this said, I think we both agree that the spec is ambiguous around this, and the fact that it's split between H2 and HPACK doesn't help.

I'm more than willing to update haproxy to emit that 0x20 byte at the beginning, at least to improve interoperability with deployed nghttp clients and to also possibly help other clients save a bit of resource, but given that even the spec's author thinks this is not needed, and Cory said this would break several of his implementations, I really think that nghttp remains overly strict on this specific one and probably ought to be slightly relaxed. By then you seemed to agree with this in the end: https://lists.w3.org/Archives/Public/ietf-http-wg/2015OctDec/0107.html

**Comment by tatsuhiro-t** [comment]
My understanding is that at the HPACK layer, the initial value is 4096, and then changed to 0 when encoder side receives and acks SETTINGS_HEADER_TABLE_SIZE = 0.

I wrote I found the relevant discussion in ML but unfortunately no reference was made there, so there is no way to know what I read at that time.
I think I agreed that if the maximum size does not change, encoder does not need to send dynamic table update.

About interoperability, after fixing #396, no bug is reported for 6 years except for this issue.  It works with google, cloudflare, ats, nginx, etc.

I think it would be better to bring the topic to httpwg to get the definitive answer.

**Comment by wtarreau** [comment]
Yep that's what I anticipated, as usual in such circumstances. I'll send a thread there. Do you want me to CC you are are you still subscribed ?

**Comment by tatsuhiro-t** [comment]
Thanks.  I'm still subscribing to the ML.

**Comment by tatsuhiro-t** [comment]
https://lists.w3.org/Archives/Public/ietf-http-wg/2021OctDec/0235.html

The correct interpretation of RFC is send dynamic table update when the maximum table size changes, so this is not a bug of nghttp2.  Some servers need to be fixed for their latent bug.  It would be nice to add a test case to h2spec so that new implementation does not fall into this trap.

**Comment by wtarreau** [comment]
Hi Tatsuhiro!

I agree that it's when it changes, but the different interpretations are clearly "when it changes from what?". It seems that for some clients it's "when it changes from the initial value documented in the H2 spec" and that for some servers it's "when it changes from the initial value imposed by the client using the H2 SETTINGS frame" (which is *exactly* what is written in RFC7541: `In HTTP/2, this value is determined by the SETTINGS_HEADER_TABLE_SIZE setting`). There is no default value for the HPACK spec, which is where the ambiguity comes from.

In any case as you've seen, we're trying with Martin to figure how to best address this in the spec so that there is a single possible interpretation that everyone agrees on. There's a slight opportunity to place some words in h2bis about it to resolve the problem. Right now I'm particularly concerned about what happens when large sizes are advertised and servers do not want to change and do not send anything back, I guess that some clients will expect 4k while others will expect the advertised large size, that can easily lead to corruption!

**Comment by tatsuhiro-t** [comment]
And now we know the correct answer, no?  Just then tell broken server vendors to fix it.

**Comment by wtarreau** [comment]
Tastuhiro, you seem to be unilateraly deciding that all of them are broken when they strictly apply what they read in the HPACK spec, but till now we only know *one* client that breaks with all of them due to a different interpretation. If most implementers understand a spec one way, it's not just a matter of fixing code. At the very least a spec has to be updated and impacts estimated.

**Comment by wtarreau** [comment]
closed ?

**Comment by tatsuhiro-t** [comment]
I did not intend to offend anyone.  RFC needs some clarification, yes.  Let's do it.  So one client is nghttp, right?  If I would read the spec in another way, then you discovered no problem and are happy now with one less byte on wire, but I think this incident would be rather nice because we detected this discrepancy even after 6 years and shed light on this grey area.  HTTP/3 is around the corner, but HTTP/2 persists for long time to the future, so fixing and clarifying the ambiguous RFC is good thing.

This issue was closed because nghttp2 implementation follows the correct interpretation.

**Comment by wtarreau** [comment]
Oh yes, don't get me wrong, that's also what I said on the WG, seeing such tiny issues 6 years after initial implementations is also a good indication that after all everything is not that bad :-)

Regarding "the correct" as I mentioned there are two correct ones due to the spec. Let's say it follow "a correct interpretation", which I totally agree with :-)

**Comment by tatsuhiro-t** [comment]
I do not think there are two correct ones.

**Comment by wtarreau** [comment]
In the HPACK spec you see it never mentions 4096, it only mentions the size learned from H2 via the SETTINGS parameter. So from a pure HPACK perspective, HPACK is instantiated properly configured and there is never any change of value. And it is particularly visible in code because on the server side we have to violate some layers to implement it the other way, by having HPACK know that the initial value is not the default one.

Again I'm not saying you're wrong, I'm saying that depending on what side you're implementing, the spec strongly confirms each approach. For me the HPACK rules are pretty clear that I do not have to emit an update for something that didn't change. And the fact that we'll possibly update it in the H2 spec is a hint that the trouble is on the boundary between the two.

**Comment by tatsuhiro-t** [comment]
It is unfortunate that RFC 7540 and 7541 were published separately and emits illusion that they are completely separated, but as far as I remember that correctly, the initial plan was to merge them into one document on publication, but for some reason, they were just left as is.
https://github.com/httpwg/http2-spec/pull/1003 clarifies the rules and you seemed to agree with it.
I do not understand why you are still insisting there are 2 correct ways.  Just because RFC is ambiguous and one can read it differently, that does not mean there are multiple correct interpretations.  There is just one correct interpretation and others which are wrong due to the misinterpretation.

**Comment by wtarreau** [comment]
> the initial plan was to merge them into one document on publication

They were split when gzip was dropped for header compression, and work had to begin on a replacement. Hervé and Roberto had good proposals each on their side and they found their methods sufficiently orthogonal to be merged to become HPACK, but all that fairly new work definitely deserved an independent document so that it could evolve till the last minute and was easy to replace later if needed.

>  Just because RFC is ambiguous and one can read it differently, that does not mean there are multiple correct interpretations

The simple fact that on a quick test in 5 minutes I could find 5 different implementations that all understood it the same way, and that this interpretation is supported word-for-word by the text, in a different way that the one that you understand is what I mean by "there are two correct ways to implement it", depending on how one understands it.

There's nothing wrong with that, it's a sad situation, but claiming that X or Y has to be fixed is not the right approach, neither nghttp nor the 5 disagreeing servers has to be "fixed", we just need to see what consensus is found in the WG about this and how we can deal with the possibly resulting incompatibilities (which arguably are quite tiny).

**Comment by tatsuhiro-t** [comment]
Once https://github.com/httpwg/http2-spec/pull/1003 is approved and merged, those implementations that do not conform to the spec should be fixed.  I feel this thread does not produce constructive result, I'll lock this issue.
