### ISSUE TITLE
Continuation or non-HTTP traffic issue

### ISSUE THREAD

**Issue by olcydvt** [nghttp2/nghttp2#1670]
Hi,

I tried to make a client request to http server and faced  **Continuation or non-HTTP traffic** error.
I can make a curl request to this  server but not with nghttp2 client.

It seems like at  first onconnect callback is proceeded and after that  immediatelly onclosed callback is also called and session is being shutdowned.

Note:1: Server side is pistache lib. based.
Note: It seems that we are not able to make a http1.1 request from this lib. right ?

![ws](https://user-images.githubusercontent.com/25078232/151673239-308098cd-628b-4f37-b2bf-eca95ef68bc2.PNG)

**Comment by Nishant-3795** [comment]
Are you able to capture HTTP/2 logs by executing _nghttp -nv https://nghttp2.org_. If Yes, kindly let me know how can I get it, so that I can close my issue.

**Comment by tatsuhiro-t** [comment]
nghttp client does not support HTTP/1.1.

**Comment by olcydvt** [comment]
thank you
