### ISSUE TITLE
Fails logging HTTP2 traces on wireshark

### ISSUE THREAD

**Issue by Nishant-3795** [nghttp2/nghttp2#1673]
I was trying to capture the logs using WireShark but it fails to capture for HTTP2. On terminal, I am getting the status code 200 when executing command _nghttp -nv https://nghttp2.org_ but  if I check the .pcap file, then the HTTP2 logs are missing and rest are present.

I am very new to this and is learning HTTP/2. Any help would be appreciated.

Command to store the traces: **_sudo tcpdump -i any -w http2.pcap_**

**Comment by wangwenqin123** [comment]
Maybe you can use Chrome and set  "SSLKEYLOGFILE",then you can see them on wireshark

**Comment by Nishant-3795** [comment]
This way it works but I was sending the client request from the terminal and in this case, it fails to update the keylog file. Unfortunately some priority task arrive and I moved from this task.

Today I got the time, and after trying out few things, I am now able to generate the SSLKEYLOGFILE from terminal also without sending any CURL request.

Hence, closing the ticket.
