### ISSUE TITLE
nghttp2 does not support header"keep-alive" but browser supports

### ISSUE THREAD

**Issue by zgjsxx** [nghttp2/nghttp2#1674]
We have a proxy service , when we visit **https://thesource.jfs.ohio.gov/NeosuranceEmployer/Account/Login?Language=en-US&Language=en-US**, it will face the below error.

`SESS=1051, error code: -531:Invalid HTTP header field was received, msg: Invalid HTTP header field was received: frame type: 1, stream: 7, name: [keep-alive], value: [timeout=3, max=993] `

It seems that nghttp2 does not allow header **keep-alive** happen on the response header, but browser will allow. 
I did the test on browser for the url  https://thesource.jfs.ohio.gov/NeosuranceEmployer/Account/Login?Language=en-US&Language=en-US, it does not show any error message.
Could we rethink about the header "keep-alive"?

**Comment by chengyechun** [comment]
HTTP/2 is multiplexed, and there is no need to use the keepalived field.
