### ISSUE TITLE
Excessively strict enforcement of Connection-Specific Header Fields

### ISSUE THREAD

**Issue by Natris** [nghttp2/nghttp2#1678]
Presence of Upgrade header causes NGHTTP2_ERR_HTTP_HEADER and thus http2 protocol error.

IMO it is excessively strict; please check 
[8.1.2.2](https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.2).
in paragraph 3:
 This means that an intermediary transforming an HTTP/1.x message to
   HTTP/2 will need to remove any header fields nominated by the
   Connection header field, along with the Connection header field
   itself.  Such intermediaries SHOULD also remove other connection-
   specific header fields, such as Keep-Alive, Proxy-Connection,
   Transfer-Encoding, and Upgrade, even if they are not nominated by the
   Connection header field.

This IMO implies that headers not nominated by the Connection header may be present in case an intermediary converts http1 to http2; it is only a http2 endpoint that must not generate such message. Enforcement of presence of these headers should depend on content of Connection header field.

This can be found in the wild, see 
nghttp --verbose https://holandske-drevaky.cz/
Both Chrome and Firefox display this page (with Firefox not showing the header in developer tools)

**Comment by tatsuhiro-t** [comment]
Here is new wording in http2bs:

https://httpwg.org/http2-spec/draft-ietf-httpbis-http2bis.html#section-8.2.2

> HTTP/2 does not use the Connection header field ([Section 7.6.1](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-semantics-18#section-7.6.1) of [[HTTP](https://httpwg.org/http2-spec/draft-ietf-httpbis-http2bis.html#HTTP)]) to indicate connection-specific header fields; in this protocol, connection-specific metadata is conveyed by other means. An endpoint MUST NOT generate an HTTP/2 message containing connection-specific header fields. This includes the Connection header field and those listed as having connection-specific semantics in [Section 7.6.1](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-semantics-18#section-7.6.1) of [[HTTP](https://httpwg.org/http2-spec/draft-ietf-httpbis-http2bis.html#HTTP)] (that is, Proxy-Connection, Keep-Alive, Transfer-Encoding, and Upgrade). Any message containing connection-specific header fields MUST be treated as [malformed](https://httpwg.org/http2-spec/draft-ietf-httpbis-http2bis.html#malformed) ([Section 8.1.1](https://httpwg.org/http2-spec/draft-ietf-httpbis-http2bis.html#malformed)).
>
> The only exception to this is the TE header field, which MAY be present in an HTTP/2 request; when it is, it MUST NOT contain any value other than "trailers".
>
> An intermediary transforming an HTTP/1.x message to HTTP/2 MUST remove connection-specific header fields as discussed in [Section 7.6.1](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-semantics-18#section-7.6.1) of [[HTTP](https://httpwg.org/http2-spec/draft-ietf-httpbis-http2bis.html#HTTP)], or their messages will be treated by other HTTP/2 endpoints as [malformed](https://httpwg.org/http2-spec/draft-ietf-httpbis-http2bis.html#malformed) ([Section 8.1.1](https://httpwg.org/http2-spec/draft-ietf-httpbis-http2bis.html#malformed)).

**Comment by Natris** [comment]
Thanks for the info; then it does not make much sense to fix it. But in general, it is unfortunate that IMO fully RFC 7540 compliant web pages break for a library where they work for normal browsers. These issues are unfortunately very hard to solve in practice.
