### ISSUE TITLE
Server cuts connection too early if multiple response headers followed by GOAWAY are submited

### ISSUE THREAD

**Issue by Natris** [nghttp2/nghttp2#1684]
I have several test cases where server very rarely does not properly send response before shutting down. Instead typically a single provisional response (probably followed by some incomplete frame?) is sent, afterwards server does no longer want to read/write.

I have been attempting to reproduce this issue with full debug logs for more than a week but I was not able; it seems to be extremely timing dependent.

For instance, after receiving request, from the "on frame callback" I schedule 5x send of 102 provisional response:
nghttp2_submit_headers(session, NGHTTP2_FLAG_NONE, frame->hd.stream_id,
                                                              nullptr, e.options.prov_res_nva, e.options.prov_res_nvlen, 0);
followed by a final response without data
nghttp2_submit_headers(session, NGHTTP2_FLAG_NONE, frame->hd.stream_id, nullptr,
                                                           e.options.res_nva, e.options.res_nvlen, 0);
followed by trailer
nghttp2_submit_trailer(session, frame->hd.stream_id, e.options.trail_nva, e.options.trail_nvlen);

and by GOAWAY marking the response stream as the last stream
nghttp2_submit_goaway(session, NGHTTP2_FLAG_NONE, frame->hd.stream_id, 111, nullptr, 0);

All these calls succeed.

I observe that in this case 48 bytes are written to the socket by the server before nghttp2_session_want_read and nghttp2_session_want_write return false and thus I stop the server.

Of these 48 bytes, probably 13 are a single provisional response containing status 102 (these I deserialize on the other side); I have no idea what the remaining bytes are, but it seems it is not a complete frame, or some "unimportant" frame I do not log (settings, window changes etc.)

Here is the definition of messages:
`        SimpleEndpoint se;
        se.client = false;
        nghttp2_nv res_nva[] = {MAKE_NV(":status", "200")};
        se.options.res_nva = res_nva;
        se.options.res_nvlen = sizeof(res_nva) / sizeof(res_nva[0]);
        se.options.send_goaway = true;

        se.options.send_trailer = true;
        nghttp2_nv trail_nva[] = {MAKE_NV("trail", "aaa")};
        se.options.trail_nva = trail_nva;
        se.options.trail_nvlen = sizeof(trail_nva) / sizeof(trail_nva[0]);

        se.options.send_prov_response = true;
        const auto PROV_RESPONSE_COUNT = 5;
        se.options.prov_response_count = PROV_RESPONSE_COUNT;
        nghttp2_nv prov_res_nva[] = {MAKE_NV(":status", "102")};
        se.options.prov_res_nva = prov_res_nva;
        se.options.prov_res_nvlen = sizeof(prov_res_nva) / sizeof(prov_res_nva[0]);`

I will be continuing trying to reproduce this with nghttp2 debug logs, but I am not sure if that is even possible. Unfortunately trying to reduce this to snippet leads to thousands of successes of this test, I can only somewhat reproduce this on our teamcity build servers. I have multiple similar tests that fail; the common denominator of them is the fact that I submit GOAWAY on the server side in all of them.

I have been going through the code, but aside from the TODO in nghttp2_session_add_item for header concerning queues (which may be relevant as I the messaging I am scheduling is far from typical) I have come out empty.

**Comment by tatsuhiro-t** [comment]
Could you make sure that nghttp2_session is manipulated in a single thread at time?  If it is a timing dependent, then it might be a race condition which might corrupt the session object state.

**Comment by Natris** [comment]
I have a special thread in which the server runs
`struct pollfd fds[1];
    fds[0].fd = e.fd;
    for (;;) {
        if (!nghttp2_session_want_read(session) && !nghttp2_session_want_write(session)) {
            avu_log_debug("test_http2", "process of simple endpoint finished (client %d)", e.client);
            return;
        }
        fds[0].events = 0;
        if (nghttp2_session_want_read(session)) {
            fds[0].events |= POLLIN;
        }
        if (nghttp2_session_want_write(session)) {
            fds[0].events |= POLLOUT;
        }
        int res = poll(fds, 1, 120*1000000);
        if (res < 0) {
            throw std::system_error(errno, std::system_category(), "process: poll");
        } else if (res == 0) {
            throw std::runtime_error("process: poll timeout");
        }
        if ((res = nghttp2_session_recv(session))) {
            avu_log_error("test_http2", "nghttp2_session_recv returned %d; want_read = %d, client %d", res, (fds[0].events & POLLIN) != 0, e.client);
            return;
        }
        if ((res = nghttp2_session_send(session))) {
            avu_log_error("test_http2", "nghttp2_session_send returned %d; want_write = %d, client %d", res, (fds[0].events & POLLOUT) != 0, e.client);
            return;
        }
    }`
    The only manipulation is from "on frame finished" when the request is received.

**Comment by Natris** [comment]
Immediately before read and write return 0 I see the client side writing 9 bytes; this may be connected with request's data window updates. But without debug logs of nghggp2 I have no clue :( 
In this case client sends request data; the scheduling of the responses is done from frame callback that finishes request stream- if (frame->hd.flags & NGHTTP2_FLAG_END_STREAM)

**Comment by tatsuhiro-t** [comment]
As long as there are open streams, nghttp2_session_want_read should return zero.  At the moment, I have no idea why it returned 0 in your test case.

**Comment by tatsuhiro-t** [comment]
BTW, those 9 bytes, HTTP/2 frame header is 9 bytes.  It has no payload, it is probably an empty DATA frame.
