### ISSUE TITLE
h2load shows all failed requests

### ISSUE THREAD

**Issue by hrexha28** [nghttp2/nghttp2#1691]
Hi,
I was trying to run h2load against a local webserver but at the end the result shows all failed requests like:
h2load -n100 https://localhost:8081/

![image](https://user-images.githubusercontent.com/96107415/161225113-33e98203-b677-4a7d-bd6f-2ef8e19b0f0e.png)
I have running a nghttpd server listening on that port.
Any idea why it's happening?
Thanks.

**Comment by chengyechun** [comment]
![image](https://user-images.githubusercontent.com/57088250/181176159-bc283550-e88b-4718-a60d-279638907c18.png)
I ran into the same problem as you, don't know if I use the error, this is only a simple test, for the nghttp2 code has not read.
