### ISSUE TITLE
h2load ngtcp2_conn_read_pkt: ERR_DRAINING

### ISSUE THREAD

**Issue by easycoderwei** [nghttp2/nghttp2#1692]
This issue is the same as https://github.com/ngtcp2/ngtcp2/issues/139.
Is there any solution?

**Comment by tatsuhiro-t** [comment]
When I last checked nginx source code, it has some kind of 'flooding' protection against QUIC packets or frames that I think did not work as intended.  I think it is a potential bug of nginx.

**Comment by whitehatboxer** [comment]
@tatsuhiro-t Did you have a solution of it? I faced same problem and was trying to solve it. :-)
