### ISSUE TITLE
http stopping server - boost::exception_detail::clone_impl ...

### ISSUE THREAD

**Issue by bojanHub** [nghttp2/nghttp2#1696]
We have a problem that in some situations TCP (HTTP2) connections stay in CLOSE-WAIT state and we don't know where is the cause of the problem. We see that our server sends HTTP2 reply (res.end) but don't see FIN from server side that I guess should happen inside nghttp2 code (or asio). We see TCP FIN from client but server sometimes does not send it. And mostly it continues in the way that after some time "acceptor" does not detect new connections anymore. It looks like all http2 threads stuck.

Till we don't know the root of the problem we want to implement some mechanism that we will detect CLOSE-WAIT states and restart HTTP2 server.

In our application we call this to stop server (server is defined as - http2 server;):
```
server.stop();
server.join();
```

And in many cases it works ok but sometimes we get:
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  set_option: Bad file descriptor
/usr/local/bin/scripts/start_smf.sh: line 18: 253819 Aborted                 (core dumped) ./smf
```

We tested this with 1.42 and 1.47 nghttp2 version but we get the same result.

Core file shows:
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f7461f497f1 in __GI_abort () at abort.c:79
#2  0x00007f746259e957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f74625a4ae6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f74625a4b21 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f74625a4ada in std::rethrow_exception(std::__exception_ptr::exception_ptr) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f7464137b53 in std::__basic_future<unsigned long>::_M_get_result (this=0x5569231f8e60) at /usr/include/c++/7/future:719
#7  std::future<unsigned long>::get (this=0x5569231f8e60) at /usr/include/c++/7/future:796
#8  nghttp2::asio_http2::io_service_pool::join (this=<optimized out>) at asio_io_service_pool.cc:74
#9  0x00005569213e4f57 in main (argc=1, argv=0x7ffe2afaaff8) at 
```

I put printfs in asio code and it looks like `acceptor.close()` triggers `acceptor.async_accept()` where error_code e is set, so if (!e) is not called but in problematic cases `acceptor.is_open` is still true so start_accept is called and it looks that this causes "Bad file descriptor" that soon follows with crash.

Why is acceptor.is_open still true even I call acceptor.close? Some thread priorities problem?

```
void server::stop() {
  for (auto &acceptor : acceptors_) {
    acceptor.close();   <- this call triggers acceptor.async_accept but it looks that acceptor.is_open() is sometimes still TRUE
  }
  io_service_pool_.stop();
}

void server::start_accept(tcp::acceptor &acceptor, serve_mux &mux) {

  if (!acceptor.is_open()) {
    return;
  }

  auto new_connection = std::make_shared<connection<tcp::socket>>(
      mux, tls_handshake_timeout_, read_timeout_,
      io_service_pool_.get_io_service());

  acceptor.async_accept(
      new_connection->socket(), [this, &acceptor, &mux, new_connection](
                                    const boost::system::error_code &e) {
        if (!e) {
          new_connection->socket().set_option(tcp::no_delay(true));
          new_connection->start_read_deadline();
          new_connection->start();
        } 
        if (acceptor.is_open()) {  <- when is problem this is still TRUE despite we call server.stop (acceptor.close())
          start_accept(acceptor, mux);
        }
      });
}
```

Any idea how to solve this?

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
