### ISSUE TITLE
No response from http2 server for SETTINGS frame with nghttp2 asio

### ISSUE THREAD

**Issue by priyankamazumdergithub** [nghttp2/nghttp2#1700]
Sometimes the http2 server does not respond to any http2 request from the client. Looks like the server is stuck. All the new TCP connection remains in CLOSE-WAIT state which is used to send a http2 packet to the server.

From packet capture it is found that the http2 client does not receive any response from the server for SETTINGS frames.

Here is the packet flow:
![image](https://user-images.githubusercontent.com/104984171/166920682-f96ffe51-2daf-41cc-a9e1-b8b82007641b.png)

Here is the SETTING frame.
![image](https://user-images.githubusercontent.com/104984171/166920901-50282314-fc2d-4651-8ca5-5c27512b91b8.png)

Using nghttp2 version 1.30.0 
OS is RHEL 7.9
Boost version 1.66

**Comment by akonskarm** [comment]
I think client should not send 2 SETTINGS frames consecutively.

**Comment by chengyechun** [comment]
I think the problem is not caused by the number of SETTINGS frames, because the maximum number of SETTINGS frames is 32, which is far greater than 2. This information is insufficient to reproduce the problem.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
