### ISSUE TITLE
nghttp2-asio: segmentation fault in conan-cmake-based project

### ISSUE THREAD

**Issue by lukasmoellerch** [nghttp2/nghttp2#1721]
I am using the ngthttp2 asio interface for a project of mine and have been having issues with segmentation faults appearing. This issue is reproducible when compiling the client example from the documentation. Other boost asio based executables work fine.

An attempt at a minimal reproduction can be found here: https://github.com/lukasmoellerch/nghttp2-alpine-test

When compiled with `cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build . -- example` in an alpine based docker container with gcc running the resulting executable results in a segmentation fault. I was able to extract the following stacktrace, but it is not very helpful.

![image](https://user-images.githubusercontent.com/4623046/171875524-5ec79493-487b-4870-a708-42b659da0aa0.png)

Any suggestions / pointers are greatly appreciated. It might very well be the case that this is a problem with the conan distribution of nghttp2.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
