### ISSUE TITLE
proxyproto is broken on v1.48.0

### ISSUE THREAD

**Issue by hshh** [nghttp2/nghttp2#1746]
nghttpx listen with frontend=*,12345;proxyproto. It works on 1.47.0.

nghttpx[93431]: [INFO] [LISTEN:0x7f614ae83180] Accepted connection from 127.0.0.1, fd=18 (shrpx_connection_handler.cc:476)
nghttpx[93431]: [INFO] Dispatch connection to worker #0 (shrpx_connection_handler.cc:520)
nghttpx[93431]: [INFO] [WORKER:0x7f614af21000] WorkerEvent: client_fd=18, addrlen=16 (shrpx_worker.cc:478)
nghttpx[93431]: [INFO] [WORKER:0x7f614af21000] CLIENT_HANDLER:0x7f6149a45500 created  (shrpx_worker.cc:505)
nghttpx[93431]: [INFO] [CLIENT_HANDLER:0x7f6149a45500] PROXY-protocol: Started (shrpx_client_handler.cc:1289)
nghttpx[93431]: [INFO] [CLIENT_HANDLER:0x7f6149a45500] PROXY-protocol-v1: Finished, 51 bytes read (shrpx_client_handler.cc:1468)
nghttpx[93431]: [INFO] tls: handshake is still in progress (shrpx_connection.cc:705)
nghttpx[93431]: [INFO] tls: handshake libssl error 5 (shrpx_connection.cc:697)
nghttpx[93431]: [INFO] [CLIENT_HANDLER:0x7f6149a45500] Deleting (shrpx_client_handler.cc:531)
nghttpx[93431]: [INFO] [CLIENT_HANDLER:0x7f6149a45500] Deleted (shrpx_client_handler.cc:555)

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue, and yes, it has been broken since v1.48.0 release.  I'm working on fixing it.
