### ISSUE TITLE
checking for nghttp2 version >= 1.2.1... FAILED in solaris 10

### ISSUE THREAD

**Issue by suhas9727** [nghttp2/nghttp2#1757]
**Hi Team, can someone please help me here. I m getting the below error while configuring httpd in solaris 10. please help,**

checking for nghttp2... checking for user-provided nghttp2 base directory... none
checking for nghttp2 version >= 1.2.1... FAILED
configure: WARNING: nghttp2 version is too old
no
checking whether to enable mod_http2... no (disabled)
checking whether to enable mod_proxy_http2... no
  adding "-I$(top_srcdir)/modules/md" to INCLUDES
checking whether to enable mod_md... checking dependencies
checking for OpenSSL... (cached) yes
  setting MOD_LDFLAGS to "-L/opt/app/bea/apache24_54/openssl/lib -R/opt/app/bea/apache24_54/openssl/lib -lssl -lcrypto -luuid -lsendfile -lrt -lsocket -lnsl -lpthread"
  setting MOD_CFLAGS to "-I/opt/app/bea/apache24_54/openssl/include"
checking for jansson... checking for user-provided jansson base directory... none
FAILED
no
configure: WARNING: libjansson not found
checking for curl... checking for user-provided curl base directory... none
checking curl/curl.h usability... no
checking curl/curl.h presence... no
checking for curl/curl.h... no
checking for curl version >= 7.29... FAILED

**Comment by suhas9727** [comment]
Can someone please check this?

**Comment by chengyechun** [comment]
I think the nghttp2 version is too old for the httpd version.

**Comment by suhas9727** [comment]
@chengyechun can we install updated nghttp2?

**Comment by chengyechun** [comment]
> @chengyechun can we install updated nghttp2?
Is there any impact on installing a new version, e.g. 1.45.x stable branch
