### ISSUE TITLE
cmake: Build broken for Xcode generator, add ENABLE_DOC option.

### ISSUE THREAD

**Issue by FractalGiraffe** [nghttp2/nghttp2#1765]
Hi,

May [PR #1596](https://github.com/nghttp2/nghttp2/pull/1596) be merged please? Our team at Amazon has implemented such a change in our internal mirror as the issue was preventing us from doing a library only build using your build system, on devices that use XCode generator. As in our case, there are cases where documentation doesn't need to be generated. Furthermore, the code in doc/CMakeLists.txt triggers a bug that is relevant to all generators, even though the new XCode is currently the only one that reports an error (https://github.com/glennrp/libpng/issues/344). Nevertheless, this should be irrelevant to us as we don't need to generate documentation. It would be very helpful if the PR was merged.

**Comment by tatsuhiro-t** [comment]
#1596 has been merged.
