### ISSUE TITLE
about  Usage of nghttp/nghttpd

### ISSUE THREAD

**Issue by chengyechun** [nghttp2/nghttp2#1767]
I run the nghttpd -v --no-tls 8093 command to start an HTTP2 service and use the nghttp to access the service. According to the packet, the communication is normal, but files cannot be uploaded or downloaded, for example, nghttp -O http://localhost:8093/index.html . Can someone take a look at it?

**Comment by chengyechun** [comment]
Do I need to rely on libjansson to download files from the server?

**Comment by tatsuhiro-t** [comment]
```
  -O, --remote-name
              Save  download  data  in  the  current  directory.   The
              filename is  derived from  URI.  If  URI ends  with '/',
              'index.html'  is used  as a  filename.  Not  implemented
              yet.
```

nghttp -O has not been implemented yet.  nghttpd does not store any uploaded resources.
