### ISSUE TITLE
Abnormal Parameters in the nghttpd Command

### ISSUE THREAD

**Issue by chengyechun** [nghttp2/nghttp2#1774]
hello，I use the nghttpd command line to start an HTTP/2 server. However, I find that if an abnormal parameter, for example, nghttpd --no-tls 8093 -v -n -1, appears in the command line, a coredump occurs. This parameter should be verified during parameter reading.
![image](https://user-images.githubusercontent.com/57088250/183588152-a5ea528e-c03e-459e-a841-ffee441b8463.png)
![image](https://user-images.githubusercontent.com/57088250/183588243-c84435cf-3f4a-4e03-8af1-7c9ef280cf8d.png)

**Comment by tatsuhiro-t** [comment]
#1775 fixes this particular issue.  The maximum value depends on the settings on OS and we have no validation about it in general.

**Comment by eaglegai** [comment]
> The maximum value depends on the settings on OS and we have no validation about it in general.
if we have no validation on the maximum value .we still have coredumps easily. 
for -n parameter, 128 is enough ,or 256 ?, we can show a valid range in man page, for example [1,256]
@tatsuhiro-t

**Comment by tatsuhiro-t** [comment]
I think that is the misuse of the option.

**Comment by eaglegai** [comment]
okay, maybe libev should exit gracefully, instead of abort
