### ISSUE TITLE
Build fails on systems without systemd

### ISSUE THREAD

**Issue by Baerbeisser** [nghttp2/nghttp2#1776]
OS: Artix with dinit
Source: AUR, as dependency of wget2
Error message:

```
shrpx.cc:60:12: critical error: systemd/sd-daemon.h: File or folder not found
   60 | #  include <systemd/sd-daemon.h>
```

**Comment by chengyechun** [comment]
Check whether your compilation configuration does not match your environment. This seems to require libsystemd.
