### ISSUE TITLE
How Asio client is aware of server terminating connection via GOAWAY with error code 0

### ISSUE THREAD

**Issue by soumyakantiroychowdhury** [nghttp2/nghttp2#1777]
When a http/2 server closes the connection gracefully by sending GOAWAY frame with error code 0, how does the asio http2 client can communicate this to the upper layer? The `on_error` callback of the `session` class is not called in this scenario, which is expected.

**Comment by atari83** [comment]
I faced same issue. 
Have you find any solution to address this problem ? asio is not getting maintained anymore ..

**Comment by soumyakantiroychowdhury** [comment]
There is another project nghttp2/nghttp2-asio to track nghttp2-asio. I logged the same issue there https://github.com/nghttp2/nghttp2-asio/issues/4 but no response yet.

**Comment by fesily** [comment]
At `req->on_close()` the `error_code == NGHTTP2_REFUSED_STREAM` is returned

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
