### ISSUE TITLE
signed releases

### ISSUE THREAD

**Issue by hyder365** [nghttp2/nghttp2#1785]
Hi. Would it be possible to include a detached PGP signature for the release tarballs? I see git tags are signed, but some tooling only works with static artifacts.

**Comment by tatsuhiro-t** [comment]
No, but it can check the integrity of tar balls with sha256sum.  This is not exactly what you wanted, but provides similar purpose.

**Comment by tatsuhiro-t** [comment]
Now asc files contain pgp signatures.  I hope I have done it properly.
