### ISSUE TITLE
./nghttpx: symbol lookup error: ./nghttpx: undefined symbol: nghttp2_option_set_server_fallback_rfc7540_priorities

### ISSUE THREAD

**Issue by jsntit** [nghttp2/nghttp2#1788]
hi   
     os ubuntu 20.04
     from nghttpx 1.48，used configure --enable-app && make && make install
     /usr/local/bin/nghttpx -v  
     error
     ./nghttpx: symbol lookup error: ./nghttpx: undefined symbol: nghttp2_option_set_server_fallback_rfc7540_priorities

**Comment by jsntit** [comment]
resolved

**Comment by zhangyijun0518** [comment]
Hi
Is this issue solved? I have the same issue when I tried to uplift from1.47 to 1.48~1.50

**Comment by jsntit** [comment]
最新版本没问题的

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年11月29日 14:16
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [nghttp2/nghttp2] ./nghttpx: symbol lookup error: ./nghttpx: undefined symbol: nghttp2_option_set_server_fallback_rfc7540_priorities (Issue #1788)


Hi
Is this issue solved? I have the same issue when I tried to uplift from1.47 to 1.48~1.50

―
