### ISSUE TITLE
Please cut a 1.50.0 release asap

### ISSUE THREAD

**Issue by dradetsky** [nghttp2/nghttp2#1796]
I independently ran across issue #1786 with newsboat (which uses libcurl and thus nghttp2), described here: https://github.com/newsboat/newsboat/pull/2177.

I have confirmed that at least curl is fixed by using the tip of master for nghttp2 (it's more complicated to verify for newsboat). Therefore, it would be desirable to make a bugfix release now. This would be easier for package managers, which typically consume release versions.

Or, I mean, since you seem to have chosen 1.50.0 for the next release, you could just release the tip now as 1.50.0, that's fine too I guess. The source code of curl already refers to the next version of nghttp2 as 1.50.0, and I don't see why we need to confuse people.

**Comment by tatsuhiro-t** [comment]
We do not add new API function in a patch release, the next release which contains the relevant API will be 1.50.0.  ETA is still unknown.

**Comment by dradetsky** [comment]
You're right, that shouldn't be a patch release, I was wrong.

I still suggest a new release should be made soon, unless that's particularly complicated, or if there are other release process considerations I don't know about. The RFC 9113 thing is causing a lot issues due to widespread h2 misimplementation (not your fault, but still), so making a release would be good. You can always make another release whenever you would have otherwise next made one.

**Comment by dradetsky** [comment]
In any case, it now seems clear that curl is not going to do a special release to address this issue (which I don't necessarily disagree with). In which case, their next release is due in 43 days. Thus nghttp2 should do a release in 42 days or less to ensure that those packaging the latest upstream releases deliver this fix. According to the release schedule, you were otherwise planning to do a release in about 13 days. If that happens, everything should go reasonably well. However, if you just straight up skipped that release in favor of the next one, packagers would probably deliver a libcurl to users with the same issues, and might not fix it quickly.

Assuming @tatsuhiro-t thinks the release will go as planned (or close enough) he can close this. Or I guess close it when the release is actually made, idk.

**Comment by dradetsky** [comment]
> it  now seems clear that curl is not going to do a special release to address this issue

See https://github.com/curl/curl/discussions/9479

**Comment by runout-at** [comment]
All software using libsoup is affected too.
https://gitlab.gnome.org/GNOME/libsoup/-/issues/300

I stumbled over this after upgrading the Evolution Groupware (CalDAV/WebDAV) in Debian  Bookworm

**Comment by tatsuhiro-t** [comment]
nghttp2 v1.50.0 will be available in this week.

**Comment by tatsuhiro-t** [comment]
v1.50.0 is out.
