### ISSUE TITLE
Fails to compile with http3 support on Fedora 36

### ISSUE THREAD

**Issue by JorgeCarousel** [nghttp2/nghttp2#1808]
Hey guys,

I'm following the instructions from this page: https://nghttp2.org/documentation/package_README.html#build-http-3-enabled-h2load-and-nghttpx but when I run the configure line for nghttp2 I get: 

`configure: error: C compiler cannot create executables`

The config.log file doesn't tell me much and the command doesn't tell me what I'm missing, I installed the development tools group before running the commands and installed libbpf-devel before too, so i don't know what I can be missing.

Any ideas?

**Comment by JorgeCarousel** [comment]
I should have added that I'm compiling it using OpenSSL-3.0.5+quic (not v1.1+quic) and the master version of nghttp2, not the versions in the page.

**Comment by tatsuhiro-t** [comment]
config.log should have something to look at. I think if you follow the instruction as is, it uses clang-12.  If your system does not have clang-12 and clang++-12 compilers, configure will fail.  Check the clang version installed in your system.

**Comment by JorgeCarousel** [comment]
You are correct, clang-12 is not on Fedora 36, only clang-14, for clang-12 there are only libraries and devel packages.

**Comment by JorgeCarousel** [comment]
After installing clang-12 and libbfp-0.8.1 to Ubuntu Server 22.04 (it comes with 0.5) it was finally able to configure and make, thanks for the tip, but you using a newer version of clang should be considered so other systems can have it.

**Comment by tatsuhiro-t** [comment]
clang-14 also works.  The availability of compilers varies among Linux distributions.  Even compiler command name could be different.  I think I should review README and update it based on Ubuntu 22.04 LTS.  Thank you for your suggestion.
