### ISSUE TITLE
Clarification on when nghttp2_on_frame_recv_callback can be called on a "closed" stream?

### ISSUE THREAD

**Issue by b-spencer** [nghttp2/nghttp2#1815]
There's a warning in the docs for `nghttp2_on_frame_recv_callback()`:

> For `HEADERS`, `PUSH_PROMISE` and `DATA` frames, this callback may be called after stream is closed (see `nghttp2_on_stream_close_callback`). The application should check that stream is still alive using its own stream management or `nghttp2_session_get_stream_user_data()`.

I'm having trouble understanding precisely what this means.

What does it mean for a stream to be "closed"?  Is it:

  - we submitted a `RST_STREAM`?
  - we received a `RST_STREAM`?
  - we returned a stream-fatal result from a callback?
  - we returned a session-fatal result from a callback?
  - nghttp2 invoked the stream closed callback?
  - something else?
  - some mix of the above?

What does it mean for a stream to be "still alive"?  Is it:

  - `nghttp2_session_get_stream_user_data()` returns non-NULL (when we had set it previously)?
  - `nghttp2_session_find_stream()` returns non-NULL (for a non-zero stream ID)?
  - just the opposite of whatever "closed" is?
  - something else?

I don't understand when or _why_ nghttp2 would deliver `HEADERS`, `PUSH_PROMISE`, or `DATA` frames to the application after it knows the stream is "closed" or "closing".  I don't know which application-visible states the stream can be in when this happens.

Experimentation shows, for example, that when I return a stream-fatal result from `nghttp2_on_header_callback()`, I do _not_ receive a `ngttp2_on_frame_recv_callback()` callback for the `HEADERS` frame that was being processed.

For example, do I really need to mark my own stream objects with "close in progress" whenever I return a stream-fatal result from a callback, _just_ so that I can then _ignore_ a future `nghttp2_on_frame_recv_callback()` that might happen before the future `nghttp2_on_stream_close_callback()`?

It certainly would be easier for my application if as soon as I submit a `RST_STREAM`, or return a stream- or session-fatal result from a callback, I knew that I would not have my receive frame callback invoked again.  (I've been unable to create a test case where my receive frame callback _is_ actually called after such things, BTW.)

I also don't see a similar warning on any of the other callbacks.  Why does this warning only apply to the receive frame callback?

I'd appreciate any clarifications that can be provided here.  Thanks!

**Comment by tatsuhiro-t** [comment]
It looks like the documentation is outdated. After https://github.com/nghttp2/nghttp2/commit/0fa4779d38d68aeacf4a4c2442685a4e98c9db30, on_frame_recv_callback is not called for a closed stream.
I'll fix the documentation.  Thank you for pointing this out.
