### ISSUE TITLE
Compiling statically linked binary of h2load

### ISSUE THREAD

**Issue by bharatkrishna** [nghttp2/nghttp2#1825]
nghttp2 version: 1.50.0 downloaded from https://github.com/nghttp2/nghttp2/releases/tag/v1.50.0
Operating System: Ubuntu 18.04.4 LTS

I am trying to build a static binary of h2load and using these options to ./configure:

`./configure --enable-app --enable-static --disable-shared `

And in the end of the configre's output:

```
    Library:
      Shared:         no
      Static:         yes

   Libs:
      OpenSSL:        yes (CFLAGS='' LIBS='-lssl -lcrypto')
      Libxml2:        yes (CFLAGS='-I/usr/include/libxml2' LIBS='-lxml2')
      Libev:          yes (CFLAGS='' LIBS='-lev')
      Libc-ares:      yes (CFLAGS='' LIBS='-lcares')
      libngtcp2:      no (CFLAGS='' LIBS='')
      libngtcp2_crypto_openssl: no (CFLAGS='' LIBS='')
      libngtcp2_crypto_boringssl: no (CFLAGS='' LIBS='')
      libnghttp3:     no (CFLAGS='' LIBS='')
      libbpf:         no (CFLAGS='' LIBS='')
      Libevent(SSL):  yes (CFLAGS='' LIBS='-levent_openssl -levent')
      Jansson:        yes (CFLAGS='' LIBS='-ljansson')
      Jemalloc:       yes (CFLAGS='' LIBS='-ljemalloc')
      Zlib:           yes (CFLAGS='' LIBS='-lz')
      Systemd:        no (CFLAGS='' LIBS='')
```
When I run make and copy over the h2load binary it created on to another linux machine, I get missing .so file error:
`./h2load: error while loading shared libraries: libev.so.4: cannot open shared object file: No such file or directory`

What would be the way to build a completely statically linked binary?

**Comment by tatsuhiro-t** [comment]
There are several ways to link third-party library statically.  One solution is use `-l:` notation to specify the library.
For example, in order to link libev statically, pass `LIBEV_LIBS="-l:libev.a"` to the configure script.
You also need `LIBTOOL_LDFLAGS="-static-libtool-libs"` to statically link the libtool libraries (e.g., libnghttp2).

**Comment by bharatkrishna** [comment]
I am still getting this message when I run make: 
`/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libev.a(ev.o): relocation R_X86_64_32 against .rodata' can not be used when making a PIE object; recompile with -fPIC
`

I tried configure as follows:

- `./configure --enable-apo LIBEV_LIBS="-l:libev.a" LIBTOOL_LDFLAGS="-static-libtool-libs"`
- `./configure --enable-app --enable-static LIBEV_LIBS="-l:libev.a" LIBTOOL_LDFLAGS="-static-libtool-libs"`
- `./configure --enable-app --enable-static --disable-shared LIBEV_LIBS="-l:libev.a" LIBTOOL_LDFLAGS="-static-libtool-libs"`

**Comment by tatsuhiro-t** [comment]
It works for me.
Perhaps, https://github.com/nghttp2/nghttp2/blob/bea6cae0d560be305f01825a27a214967e38c24a/docker/Dockerfile#L49-L61 might be useful which creates mostly statically linked binary.

**Comment by tatsuhiro-t** [comment]
If the compiler you use produces pie binary and libev.a is not compiled with -fPIC, the error would occur.  Try LDFLAGS=-no-pie to  produce non-pie binary.
