### ISSUE TITLE
Question: How to handle received NGHTTP2_WINDOW_UPDATE frame as a client 

### ISSUE THREAD

**Issue by akhabali** [nghttp2/nghttp2#1842]
Hello,

Could someone please clarify how NGHTTP2_WINDOW_UPDATE  frame type should be handled **by the client** when received in the [nghttp2_on_frame_recv_callback ](https://nghttp2.org/documentation/types.html#c.nghttp2_on_frame_recv_callback)

Does the client need to ack the window update somehow or is it handled automatically by the nghttp2 library?

I couldn't find any documentation explaining how it works.

```C
static int on_frame_recv_callback(nghttp2_session *session, const nghttp2_frame *frame, void *user_data)
{

    switch (frame->hd.type)
    {
    case NGHTTP2_WINDOW_UPDATE:
        // What to do with this?
        break;

      case NGHTTP2_GOAWAY:
      case NGHTTP2_DATA:
      case NGHTTP2_HEADERS:
      case NGHTTP2_RST_STREAM:
        break;

    }
    return 0;
}
```

Thank you very much.

**Comment by tatsuhiro-t** [comment]
It is handled by the library, and application does not need to do anything with it.
