### ISSUE TITLE
Multiplexing over one nghttp2_session

### ISSUE THREAD

**Issue by victorstewart** [nghttp2/nghttp2#1876]
imagine i want to send 4 requests to the same endpoint at the same time, then parse the responses as they come.

`on_data_chunk_recv_callback` and `on_stream_close_callback` provide the `stream_id`, so that i can refer back to each request individually, but `on_header_callback` does not provide the `stream_id` and thus it's impossible to simply accumulate the response headers for each.

firstly wondering why `on_header_callback` does not include `stream_id`?

and secondly, in this scenario where i send 4 requests to the same endpoint in a given sequence, is it guaranteed that by the time `on_stream_close_callback` is called, all headers and data segments have been received for that stream AND NONE for the next, so that i can use this callback as a watermark to transition to the next request?

**Comment by victorstewart** [comment]
but you could also imagine a situation where a load balancer maintains a connection to a client, and then load balances requests over machines... now there is no guaranteeing response sequence.

so without the stream_id it seems impossible to do have multiple outstanding requests in flight per `nghttp2_session`.

**Comment by tatsuhiro-t** [comment]
You can get stream_id via frame->hd.stream_id.

**Comment by victorstewart** [comment]
thanks!!!
