### ISSUE TITLE
[python] use CFFI for bindings

### ISSUE THREAD

**Issue by bbangert** [nghttp2/nghttp2#188]
nghttp2 uses cython to bind to the C layer. Unfortunately this isn't portable for use in pypy. It would be nice if the binding worked with asyncio under pypy as its substantially faster (pypy 2.5 has some features that also help performance with objects passed between pypy and C).

**Comment by methane** [comment]
FYI, PyPy 2.5 doesn't support asyncio, since PyPy3 2.5 has not released yet.
I don't know PyPy3 2.5 can run asyncio or not.

**Comment by tatsuhiro-t** [comment]
I'm totally new to cffi, but it is promising to move from cython to cffi, although pypy still does not support asyncio (I guess they eventually support it, right?).  As always, patches are welcome.

**Comment by bbangert** [comment]
PyPy won't support asyncio until PyPy supports Python 3.3 or later unfortunately. Sorry about the inaccuracy in my original report. If there was a cffi binding though, then I would be able to use nghttp2 as a server under pypy+twisted/tornado. In my tests, I've been able to hold open over 140k connections using pypy+twisted, while cpython would be lucky to handle 50k connections. Since HTTP/2 has such long lived connections, the huge increase in performance and efficiency is important for larger production uses.

I can take a look into writing a binding soon.

**Comment by tatsuhiro-t** [comment]
It looks like asyncio coroutine does not work in cython compiled code since inspect issue.
cffi would be promising in this respect.

**Comment by tatsuhiro-t** [comment]
Closed since python bindings have been removed.
