### ISSUE TITLE
How to merge frame to one request?

### ISSUE THREAD

**Issue by sumous** [nghttp2/nghttp2#1882]
Hi,
I found that the frame of Magic, SETTINGS, WINDOW_UPDATE post in seperate request, However chromium is in one request.
How to merge the three requests in to one?

this is in nghttp2
![image](https://user-images.githubusercontent.com/1303581/224466319-1ad4c8b5-61c3-4d6d-b86b-476d004a67fe.png)

this is in chromium
![image](https://user-images.githubusercontent.com/1303581/224466335-38f99da5-3d19-4f5b-a1cf-112dc1c90262.png)

**Comment by tatsuhiro-t** [comment]
Assemble those frames in one temporary buffer and write it.
