### ISSUE TITLE
Updating nghttp2 to use OpenSSL 3.1.0

### ISSUE THREAD

**Issue by lalithalakshmi** [nghttp2/nghttp2#1894]
Hi,
We are using nghttp2 1.41 in our project. And we are updating to OpenSSL 3.1.0. I get link errors since the library and seems it is dependent on Open SSL 1.1.0. 
Can I configure nghttp2 to use with OpenSSL 3.1.0 when building it?

/root/5gran/du/../rumHdlrIntf/build//lib/libnghttp2_asio.so: undefined reference to `SSL_get_error@OPENSSL_1_1_0'
/root/5gran/du/../rumHdlrIntf/build//lib/libnghttp2_asio.so: undefined reference to `ERR_reason_error_string@OPENSSL_1_1_0'
/root/5gran/du/../rumHdlrIntf/build//lib/libnghttp2_asio.so: undefined reference to `SSL_CTX_get_default_passwd_cb_userdata@OPENSSL_1_1_0'
/root/5gran/du/../rumHdlrIntf/build//lib/libnghttp2_asio.so: undefined reference to `EVP_sha256@OPENSSL_1_1_0'

Thanks,
-Lalitha

**Comment by GrahamCampbell** [comment]
You are using a super old version of this library. I have compiled 1.53.0 with OpenSSL 3.0.9 LTS without issue (which would be the recommended version to go since 3.1.x is not LTS).
