### ISSUE TITLE
undefined symbol: nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation / Increment SO Version

### ISSUE THREAD

**Issue by hansingt** [nghttp2/nghttp2#1922]
Version 1.50.0 of nghttp2 added a new function called `nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation` to the interface (https://github.com/nghttp2/nghttp2/pull/1792).

Actually, as I understand the libtool guidelines (https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html), this would have required to increment the "current" version and the "age" as a new interface had been added and executables linking against this version and actually using this new interface might otherwise fail if using an older version at runtime:

> Programs using the previous version may use the new version as drop-in replacement, but programs using the new version may use APIs not present in the previous one. In other words, a program linking against the new version may fail with “unresolved symbols” if linking against the old version at runtime: set revision to 0, bump current and age.

This is exactly, what currently happens with libcurl: New version use this new interface method, but still link against the library  version `14`. This results in "unresolved symbol" errors during runtime, if an older version of nghttp2 is found in library path.

See e.g. https://bugs.launchpad.net/ubuntu/+source/curl/+bug/2018342.

Thus, this change would have required to update the library "current" version to `15`. This issue suggest to do so now, to solve this problem for new versions.

**Comment by hansingt** [comment]
Ah I see. Sorry, my fault. I've thought, that the `14` in SO major version would directly correspond to the libtool "current" version.

But I still don't see, what's wrong than.. 
According to the guideliens, as stated above, incrementing the current and age should avoid programs from linking to older versions during runtime, to avoid this "undefined symbol" error. Or do I get this wrong as well?

**Comment by tatsuhiro-t** [comment]
Yes, linker should take care of that and in runtime the correct so file should be linked.
There may be some issues in build process of the network manager, which I do know well.
Running ldd will report the shared libraries that it uses.  I am not sure that is possible but is there any possibilities that network manager links to old libnghttp2 located in somewhere not in standard location?

**Comment by hansingt** [comment]
Don't know about NetworkManager. For me, the same Problem arises with libcurl.

But I think, the problem might more be, that libcurl links against `libnghttp.so.14` but than requires features only added by `14.24`. Thus, I'd guess, that the problem is within libcurl (any maybe NetworkManager), but I'm not sure, whether the linker can be told to link against a so with Major and Minor version?

As you've incremented the current and age version just as suggested by libtool, I think, the problem must be somewhere else. Thinking again about this, it does make sense, that the major version remains stable, as the interface is backward compatible, but not forward comaptible. Thus, the minor version needs to be incremented, just as libtool did. But then, programs using these new functionalities, require to link against version `14.24`, because in other `14.x` (`x < 24`) these functions do not exist yet.

Regarding this, I think the problem must be in libcurl not specifying it's dependencies correctly, but I'd have to check that.

**Comment by tatsuhiro-t** [comment]
I think linker records minor version as well, as you wrote, the API is backward compatible, but has new function available.  Those programs that depend on new function should link to the appropriate so file with major and minor versions.

**Comment by tatsuhiro-t** [comment]
It looks like I was wrong about minor version, which is not recorded anywhere in the current build process.
So libcurl is build with say libnghttp2.14.24.1, dynamic linker happily links  libnghttp2.14.20.0, for example.
Ubuntu should provide the correct dependencies, otherwise it is very hard to use.

When I booted ubuntu:23.04 using docker, curl just works fine.

**Comment by hansingt** [comment]
Yeah, problem (in my case) is not ubuntu not providing the correct dependencies, but having multiple versions of the libnghttp2 on my Systems `LD_LIBRARY_PATH`.  I know, this is a rare case.

But I'm still not sure, whether there is something wrong in the build tools.. I get the feeling, that having multiple versions of the same lib is simply not a usecase for libtool and the linkers..

Anyway, thanks for the support. I don't think, that there is an issue with libnghttp2 and thus, we can close this issue.
