### ISSUE TITLE
Support for Webtransport SETTINGS

### ISSUE THREAD

**Issue by martenrichter** [nghttp2/nghttp2#1933]
I would like to implement the http2-wrapped Web transport protocol on node.js . (https://datatracker.ietf.org/doc/draft-ietf-webtrans-http2/)
As node.js sits on top of nghttp2, it also depends on nghttp2 capabilities.

In principle, it is an easy task to do this, as node.js and nghttp2 support already the extended connect settings frame.
However, the protocol needs also  SETTINGS_WEBTRANSPORT_MAX_SESSIONS set on the server and client side to indicate support of the protocol. Section 9.1 also defines other settings, but these can also be set using the capsule protocol, which is independent of nghttp2 and node.js and can be made in javascript. (One thing which is puzzling, is that the id in the draft is 32-bit as it should be only 16-bit. I ask the work group about this).

So I would like to ask you, if you may consider adding this setting, even if it is still in draft status?

As I have the impression, that more protocols may come along (in connection to the capsule protocol and extended connect), that require additional settings. I am wondering, if adding the setting as additional parameters to the API is a good idea, or if a more generic API is eventually needed.

I have also asked the node.js people about the issue:
https://github.com/nodejs/node/issues/48962#issuecomment-1656905447

**Comment by tatsuhiro-t** [comment]
You can send arbitrary settings via nghttp2_submit_settings.

**Comment by martenrichter** [comment]
Thanks, I was not aware, that this is already possible. I had looked in at the old commits for the extended commit and it was not immediately clear.

**Comment by martenrichter** [comment]
In the meantime, I have successfully implemented the http/2 webtransport/capsule protocol.
I have also landed a patch into node.js to support sending initial settings based on your advice.
Now, as I understand the protocol more in detail, the missing initial flow control window values can be a major issue and may generate failing ir stalled connections (except if the values are guessed right on both sides). 
So I think also receiving unknown SETTINGS would be good.

Would you be open to a PR that allows to register settings values (may be limited to a certain number of settings), which are processed and stored via a separate array/structure?
Or is there already a structure I can process without a change to the library? I currently have the impression that all unknown settings are dropped.

**Comment by tatsuhiro-t** [comment]
I think unknown settings are not dropped and are reported in nghttp2_on_frame_recv_callback.  Will check.

**Comment by martenrichter** [comment]
Thank you very much! This is the pointer I needed. My first look into the source code suggests that I can get the settings there.

**Comment by martenrichter** [comment]
Already fixed in node.js
