### ISSUE TITLE
add-response-header does not allow custom headers?

### ISSUE THREAD

**Issue by romanrm** [nghttp2/nghttp2#1952]
Hello,

Using nghttp2/1.43.0. I have a line in my config:

`add-response-header="Strict-Transport-Security: max-age=15768000"`

Starting the server fails:
```
2023-09-21T17:47:17.568Z 7359 7359 df18f28b ERROR (shrpx_config.cc:3182) add-response-header: invalid header field: "Strict-Transport-Security: max-age=15768000"
2023-09-21T17:47:17.568Z 7359 7359 df18f28b FATAL (shrpx.cc:2889) Failed to load configuration from /etc/nghttpx/nghttpx.conf
```

It is very puzzling what is the reason, does this config option have a whitelist of headers that it allows adding? If so, that is extremely unexpected, typically such option would allow adding any header whatsoever, even absolutely non-standard ones. But in this case it doesn't even allow a standards-defined header.

**Comment by romanrm** [comment]
I tried lowercase, but did not try removing quotes, because documentation also shows quotes are specified for the value.

**Comment by romanrm** [comment]
`Example: --add-response-header="foo: bar"`

**Comment by tatsuhiro-t** [comment]
Double quotes are needed when specified in command-line, which are processed by command-line parser.  They are not needed in config files.

**Comment by romanrm** [comment]
I would suggest to have them ignored if possible, when also specified in config file, not cause a fatal error. Thanks

**Comment by tatsuhiro-t** [comment]
I have no plan to do that.
