### ISSUE TITLE
issue with 1.57.0 on RHEL 7

### ISSUE THREAD

**Issue by rkhalloran** [nghttp2/nghttp2#1971]
unable to build the current 1.57.0 package on RHEL7; the provided gcc 4.8 (yes I know..) throws any number of errors: assuming these are related to how old the g++ compiler is

make[3]: Entering directory `/hosting/tmp/workspace/nghttp2-1.57.0/src'

  CXX      util.o

In file included from util.h:56:0,

                 from util.cc:25:

template.h: In constructor ‘nghttp2::DList<T>::DList(nghttp2::DList<T>&&)’:

template.h:93:14: error: ‘exchange’ is not a member of ‘std’

       : head{std::exchange(other.head, nullptr)},

              ^

template.h:94:14: error: ‘exchange’ is not a member of ‘std’

         tail{std::exchange(other.tail, nullptr)},

              ^

template.h:95:13: error: ‘exchange’ is not a member of ‘std’

         len{std::exchange(other.len, 0)} {}

             ^

template.h: In member function ‘nghttp2::DList<T>& nghttp2::DList<T>::operator=(nghttp2::DList<T>&&)’:

template.h:101:12: error: ‘exchange’ is not a member of ‘std’

     head = std::exchange(other.head, nullptr);

            ^

template.h:102:12: error: ‘exchange’ is not a member of ‘std’

     tail = std::exchange(other.tail, nullptr);

            ^

template.h:103:11: error: ‘exchange’ is not a member of ‘std’

     len = std::exchange(other.len, 0);

           ^

template.h: In function ‘std::unique_ptr<char []> nghttp2::strcopy(InputIt, InputIt)’:

template.h:185:14: error: ‘make_unique’ is not a member of ‘std’

   auto res = std::make_unique<char[]>(last - first + 1);

              ^

template.h:185:31: error: expected primary-expression before ‘char’

   auto res = std::make_unique<char[]>(last - first + 1);

                               ^

….

template.h:376:7: note:   candidate expects 1 argument, 2 provided

template.h:376:7: note: constexpr nghttp2::StringRef::StringRef(nghttp2::StringRef&&)

template.h:376:7: note:   candidate expects 1 argument, 2 provided

make[3]: *** [util.o] Error 1

make[3]: Leaving directory `/hosting/tmp/workspace/nghttp2-1.57.0/src'

make[2]: *** [all-recursive] Error 1

make[2]: Leaving directory `/hosting/tmp/workspace/nghttp2-1.57.0/src'

make[1]: *** [all-recursive] Error 1

make[1]: Leaving directory `/hosting/tmp/workspace/nghttp2-1.57.0'

make: *** [all] Error 2

------

Loading in the optional gcc11 package and retrying, I'm getting a different set of errors for TLS_{client, server}_method:

make[3]: Entering directory `/hosting/tmp/workspace/nghttp2-1.57.0/src'

  CXX      util.o

  CXX      http2.o

  CC       timegm.o

  CXX      app_helper.o

  CC       nghttp2_gzip.o

  CXX      nghttp.o

nghttp.cc: In function ‘int nghttp2::{anonymous}::communicate(const string&, const string&, uint16_t, std::vector<std::tuple<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, nghttp2_data_provider*, long int, int> >, const nghttp2_session_callbacks*)’:

nghttp.cc:2292:27: error: ‘TLS_client_method’ was not declared in this scope; did you mean ‘DTLS_client_method’?

2292 |     ssl_ctx = SSL_CTX_new(TLS_client_method());

      |                           ^~~~~~~~~~~~~~~~~

      |                           DTLS_client_method

make[3]: *** [nghttp.o] Error 1

-----

Assuming *these* are due to the OpenSSL 1.0.1 version in the base RHEL 7.

Will this latest package even build given the old OpenSSL package present there?  Your assistance is appreciated.

**Comment by tatsuhiro-t** [comment]
gcc 4.8 is too old to build nghttp2.

**Comment by rkhalloran** [comment]
Thanks for the feedback, but still getting those header-related issues when
I go to GCC 11. Is OpenSSL 1.0.2 in RHEL 7 *also* too old?

**Comment by tatsuhiro-t** [comment]
Yes, it is tool old.

**Comment by rkhalloran** [comment]
Appreciate the feedback

**Comment by xl32** [comment]
@rkhalloran at codeit.guru repo, we build it with quictls successfully for EL7:
Please check openssl-quictls* and nghttp2* packages here (SRPMS are also available):
https://repo.codeit.guru/packages/centos/7/x86_64/
