### ISSUE TITLE
1.57 new file lib/nghttp2_time.c builds fail on Cygwin and Mingw 

### ISSUE THREAD

**Issue by BrianInglis** [nghttp2/nghttp2#1976]
New file in *1.57* `lib/nghttp2_time.c` builds fail on *Cygwin* and *Mingw* cross as both `GetTickCount64`() and `clock_gettime`() are defined, and recent fix #1963 *Fix build error when both clock_gettime and GetTickCount64 are available* for #1962 *compilation error on *Windows* with *MSYS2* : undefined reference to `time_now_sec`* does not handle the issue comprehensively; we want to use the *POSIX* interface for *Cygwin* builds, but the *Windows* interface for *Mingw* (cross-)builds. 
The patch below resolves the issue for *Cygwin* and *Mingw* cross, and hopefully also other *POSIX* and *Windows*/*Msys2*, but I don't have build environments to test those: additional `!`/`defined()`s *may* be needed after review:
[nghttp2-1.57-nghttp2_time-c-time_now_sec-cygwin-mingw-defines.patch](https://github.com/nghttp2/nghttp2/files/12931873/nghttp2-1.57-nghttp2_time-c-time_now_sec-cygwin-mingw-defines.patch)

Please also consider including the effects of the additional patches below in some way after review: to `configure` *C++* `-std=gnu...` for use with stricter feature test macro settings; and to use static lib in `Makefile` for building tests; these have been used since before I adopted maintaining *nghttp2* for *Cygwin* & *Mingw* cross under *Cygwin*:
[configure-ac-cxx-ext.patch](https://github.com/nghttp2/nghttp2/files/12932784/configure-ac-cxx-ext.patch)
[tests-Makefile-am-staticlib.patch](https://github.com/nghttp2/nghttp2/files/12932853/tests-Makefile-am-staticlib.patch)

**Comment by tatsuhiro-t** [comment]
Could you create a patch based on https://github.com/nghttp2/nghttp2/pull/1963? I am not sure what is missing in #1963.

**Comment by BrianInglis** [comment]
The first attachment is the required patch on top of #1963:
[nghttp2-1.57-nghttp2_time-c-time_now_sec-cygwin-mingw-defines.patch](https://github.com/nghttp2/nghttp2/files/12931873/nghttp2-1.57-nghttp2_time-c-time_now_sec-cygwin-mingw-defines.patch)

**Comment by tatsuhiro-t** [comment]
Thank you for the patch.  Does #1977 work for you?

**Comment by BrianInglis** [comment]
Your patch #1977 works great for both *Cygwin* and *Mingw* cross builds of `lib/nghttp2_time.c` and all tests pass as usual. Hontou ni arigatou gozaimasu!
