### ISSUE TITLE
nghttp2 1.57.0 limits responses to 33 per second

### ISSUE THREAD

**Issue by awfulhak** [nghttp2/nghttp2#1984]
After updating to 1.57.0, I see that performance tests against my server are now limited to 33 queries per second (with the initial pool of 1000) due to the recent https://github.com/nghttp2/nghttp2/pull/1961.
This seems to show up as ```nghttp2_session_want_write()``` and ```nghttp2_session_want_read()``` both returning 0.
By calling ```nghttp2_option_set_stream_reset_rate_limit(ngopt, 10000, 10000);``` on the server side, it can survive bursts of a few thousand queries.
Note, all of these queries are responded to - nothing is being canceled.

Is it possible to either change ```libnghttp2``` so that responses don't contribute to the reset rate limit or to add an option to enable this behaviour?

**Comment by tatsuhiro-t** [comment]
The mitigation only counts incoming RST_STREAM frame from client.  If it hits, that means client somehow sends RST_STREAM.

**Comment by awfulhak** [comment]
Thanks @tatsuhiro-t.  I'll look into what the client side is doing to cause this.

**Comment by awfulhak** [comment]
Yes, I can confirm that our client was sending a ``RST_STREAM`` after receiving a response, causing the bad behaviour.  Removing this addresses the issue.
Thanks again for your help.
