### ISSUE TITLE
nghttp2-1.58.0/lib/nghttp2_time.c fails to compile on HP-UX

### ISSUE THREAD

**Issue by rgh-sas** [nghttp2/nghttp2#1994]
The recent changes to lib/nghttp2_time.c introduced with release nghttp2-1.58.0 have broken building nghttp2 on HP-UX.
HP-UX does have the routine "clock_gettime()"; however, it does not support the clock CLOCK_MONOTONIC which is now required by nghttp2_time.c if your OS supports "clock_gettime()".  Probably a configure test is required to determine if CLOCK_MONOTONIC is supported and if not set a define indicating it isn't supported and then add logic to nghttp2_time.c to account for this. 
A simple hack I made is as follows based off the released code nghttp2-1.58.0/lib/nghttp2_time.c:
```
35c35
< #if !defined(HAVE_GETTICKCOUNT64) || defined(__CYGWIN__) || defined(__hpux)
---
> #if !defined(HAVE_GETTICKCOUNT64) || defined(__CYGWIN__)
49c49
< #elif defined(HAVE_CLOCK_GETTIME) && !defined(__hpux)
---
> #elif defined(HAVE_CLOCK_GETTIME)
60c60
< #else  /* (!HAVE_CLOCK_GETTIME || __CYGWIN__ || __hpux) && !HAVE_GETTICKCOUNT64 */
---
> #else  /* (!HAVE_CLOCK_GETTIME || __CYGWIN__) && !HAVE_GETTICKCOUNT64 */
```

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.  #1995 fixes it.
