### ISSUE TITLE
Cannot download libnghttp2 because of Content-Length in the server's response

### ISSUE THREAD

**Issue by VyhyrynskyiOleksii** [nghttp2/nghttp2#2003]
We're constantly getting this error for 1 day:
`error: Cannot download getPackage/libnghttp2-1.33.0-5.el8_9.x86_64.rpm: All mirrors were tried; Last error: Interrupted by header callback: Server reports Content-Length: 78564 but expected size is: 78568`
We cleared the cache from our side (and it's actually building during CI/CD so there is no cache - it installs packages from scratch on each run).
Maybe it can be related to some caching from your side or some wrong way of zipping/uploading the package...
The Content-length differs only for 4 bytes which happens quite often if such an error exists (even for other packages due to the search results on Google)

Example of similar issue: https://github.com/openresty/openresty-packaging/issues/75#issue-1166485812
The root cause and fix: https://github.com/openresty/openresty-packaging/issues/75#issuecomment-1068182170
Maybe you can do the same clearing of cache on your side to fix the issue.

**Comment by VyhyrynskyiOleksii** [comment]
The temporary workaround for this (if anyone will came here from the internet) is to pin to the previous version with making excludes from microdnf or whatever package installer you're using.
Example of fixing it in dockerfile with usage of microdnf:

> RUN     microdnf install libnghttp2-1.33.0-3.el8_2.1
RUN     printf "[main]\nexcludepkgs=libnghttp2" > /etc/dnf/dnf.conf
RUN     microdnf -y update

For other package installers --exclude flag on both update and upgrade commands should work but it doesn't exist for microdnf, so we put `excludepkgs` param to `[main]` section of `/etc/dnf/dnf.conf` which is dnf package installer config file  (it didn't exist though we wrote to that file with  `>` (if file exists it would override it, I believe, so be careful with such solution).

**Comment by xorpaul** [comment]
This is also affecting our internal yum.oracle.com repository mirror:
```
[MIRROR] libnghttp2-1.33.0-5.el8_9.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 78564 but expected size is: 78568
[MIRROR] libnghttp2-1.33.0-5.el8_9.i686.rpm: Interrupted by header callback: Server reports Content-Length: 85120 but expected size is: 85124
[MIRROR] libnghttp2-1.33.0-5.el8_9.i686.rpm: Interrupted by header callback: Server reports Content-Length: 85120 but expected size is: 85124
[MIRROR] libnghttp2-1.33.0-5.el8_9.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 78564 but expected size is: 78568
[FAILED] libnghttp2-1.33.0-5.el8_9.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
[MIRROR] libnghttp2-1.33.0-5.el8_9.i686.rpm: Interrupted by header callback: Server reports Content-Length: 85120 but expected size is: 85124
[FAILED] libnghttp2-1.33.0-5.el8_9.i686.rpm: No more mirrors to try - All mirrors were already tried without success
```

**Comment by dolfinus** [comment]
Does anyone going to fix that? It affected all my docker images on CentOS 8 as well

**Comment by xorpaul** [comment]
For me the package and it's metadata was fixed upstream in the yum.oracle.com repository last Friday.

**Comment by tatsuhiro-t** [comment]
I do not host those files and cannot do anything about it.
