### ISSUE TITLE
To QUIC or not?

### ISSUE THREAD

**Issue by patlecat** [nghttp2/nghttp2#2004]
Now that OpenSSL announced to support QUIC how about nghttp? Does it support QUIC already or is it planned?

[QUIC with OpenSSL 3.2](https://github.com/openssl/openssl/discussions/22806)

**Comment by tatsuhiro-t** [comment]
OpenSSL 3.2 QUIC is useless for nghttp2.

**Comment by patlecat** [comment]
> OpenSSL 3.2 QUIC is useless for nghttp2.

How so?
