### ISSUE TITLE
Question about pause a stream for long operations

### ISSUE THREAD

**Issue by micheleselea** [nghttp2/nghttp2#2045]
Hi, I'm using example libevent-server.c and I'm able to have an http2 server running.
When the on_frame_recv_callback is called an so the on_request_recv (so basically a new request is ready to be served) I can reply to client. Because the server is single thread if the on_request_recv take long time to process all other streams/connections are blocked by that operation.
Is there a way to PAUSE current request, do the long request without blocking the other connections, and when the data are ready resume and send reply to the client?

**Comment by tatsuhiro-t** [comment]
You do not need to do everything inside the callback.  Just return from it, and do whatever you want along in a manner that it does not block event loop outside the callback, and then submit response.

**Comment by micheleselea** [comment]
Ah ok, so I just need to reply with 0, and then I can do the _write and send_response whenever I have data ready? Can I call send_response from different thread?

**Comment by micheleselea** [comment]
So if I understand right, just some pseudocode:

```
in on_request_recv
{

if short_request
  send_response()
if long_request
{
 spawn a different thread and just return 0
   {
        doing my long stuff
        protect somehow nghttp2_session
        send_response
   }
}

}
```

is it correct from you point of view? or there a smart way to do that?

**Comment by tatsuhiro-t** [comment]
Something like that.  But I do not recommend to use thread because you need to place locks around every invocation of nghttp2 API, not just in this callback.

**Comment by micheleselea** [comment]
I understand, but if the process to obtain data to send back to client call takes 10 seconds I can't wait that amount of time in that function because I'll block all other connections, so I do not see any other mode to do that. I'm just try to use a SIGNAL to led do the nghttp2_session  operation on the main thread. Let see if I can do the job
