### ISSUE TITLE
libevent-server.c possible leak?

### ISSUE THREAD

**Issue by micheleselea** [nghttp2/nghttp2#2048]
In libevent-server.c I think there's a possible leak.
If you connect to server session_data is created here
`session_data = create_http2_session_data(app_ctx, fd, addr, addrlen);`
if you than trigger the software close, session_data is never deleted because is never trigger any code line
` delete_http2_session_data(session_data);`
in that example is not a big deal because the software will terminate, but in a scenario with the software is just restarted (with an external main loop) you can end up with a session_data leak . Do you know which is the best way to deal with? Now I'm tracking all created/deleted session_data to be able to close the "not deleted" one on event loop exit

**Comment by tatsuhiro-t** [comment]
The example is written for its own.  If you mind those sessions, you should remember them somewhere and delete them when everything is done.

**Comment by micheleselea** [comment]
Ok thankyou, I thought that exiting leabevent loop will trigger closing all the socket/bufferevent associated. So I'm already doing the "remember" stuff
thanks
