### ISSUE TITLE
Static library always built with identical lib name as shared causing linking errors

### ISSUE THREAD

**Issue by jonaski** [nghttp2/nghttp2#2088]
As you have removed the ``if(HAVE_CUNIT OR ENABLE_STATIC_LIB)`` condition in version 1.60.0, it's always building the static library, even though I explicitly have been disabling it with ``ENABLE_STATIC_LIB=OFF``, and since 1.60.0 with ``BUILD_STATIC_LIBS=OFF``. ``STATIC_LIB_SUFFIX`` is never set, but is used here: https://github.com/nghttp2/nghttp2/blob/c5e087b1038b9b0a972ca07748a525b8f58139d9/lib/CMakeLists.txt#L74
But without ``STATIC_LIB_SUFFIX`` being set, the static library is using identical lib name as the shared lib causing linking errors, as you can see here: https://github.com/strawberrymusicplayer/strawberry-msvc-dependencies/actions/runs/8115697967/job/22184102638?pr=370
This means the user has to configure CMake with ``STATIC_LIB_SUFFIX`` to avoid the conflict when building a shared library.
The ``if(BUILD_STATIC_LIBS)`` line should be moved so it does not only apply to the install, but building too.
And ``STATIC_LIB_SUFFIX`` should probably be CMake option defaulting to "static" so it does create conflicts when building both shared and static.

**Comment by tatsuhiro-t** [comment]
`if(HAVE_CUNIT OR ENABLE_STATIC_LIB)` was removed because CUnit dependency is dropped and the unit tests are always built which requires static lib if I understand it correctly.
Would you mind submitting a patch to fix the issue you described?

**Comment by jmckenna** [comment]
Initially reported (and a fix) through https://github.com/nghttp2/nghttp2/pull/2051#issuecomment-1973837157

**Comment by jmckenna** [comment]
We should probably notify all packagers of 1.60.0 that the `if` statement needs to be moved (specific line at https://github.com/nghttp2/nghttp2/pull/2051#issuecomment-1973837157 )

**Comment by jmckenna** [comment]
@jonaski do you want to submit a pull request?  It seems your solution is more detailed than mine :) Mine is a quick fix for 1.60.0 packagers, but it sounds like you have the proper way.  thanks.

**Comment by jmckenna** [comment]
Also, I think we should be testing for this (I'm not familiar with the CI for windows for this project), on each commit, to prevent such a breaking change occurring in a release again.

**Comment by jonaski** [comment]
I can do it.
