### ISSUE TITLE
Version 1.60.0 signed with new GPG key

### ISSUE THREAD

**Issue by egtvedt** [nghttp2/nghttp2#2089]
Hello,

I noticed nghttp2 version 1.60.0 is signed with a different GPG key compared to previous releases, the tag is also signed with a different key.

Have you updated your key @tatsuhiro-t ? Do you have an official place for fetching it?

It would be nice if signing changes was mentioned in release notes.

**Comment by tatsuhiro-t** [comment]
I created new subkey for signing, yes, and it looks like release tooling picked up new key.  It is unexpected, but it should work.  I uploaded keys to https://keyserver.ubuntu.com/

**Comment by egtvedt** [comment]
Thank you for the quick answer, yes I see an RSA 4096-bit key as a sub key now

```
pub   dsa1024/7E8403D5D673C366 2009-02-21 [SC]
      F4F3B91474D1EB29889BD0EF7E8403D5D673C366
uid                 [ unknown] Tatsuhiro Tsujikawa <tatsuhiro.t@gmail.com>
sub   rsa4096/5339A2BE82E07DEC 2024-02-20 [S]
```

I suspect your release tool prefers the stronger RSA over DSA.

Again thank you for confirming the change so fast.
