### ISSUE TITLE
Compilation error redefinition of typedef 'nghttp2_data_provider_wrap' in 1.60.0 for old gcc

### ISSUE THREAD

**Issue by rainerjung** [nghttp2/nghttp2#2096]
When compiling nghttp2 1.60.0 on old linux systems, eg RHEL 6 or SLES11, using gcc 4.4.5 or 4.3.4, I get the following fatal compilation error:

In file included from nghttp2_session.c:42:
nghttp2_submit.h:34: error: redefinition of typedef 'nghttp2_data_provider_wrap'
nghttp2_outbound_item.h:49: note: previous declaration of 'nghttp2_data_provider_wrap' was here
make[3]: *** [nghttp2_session.lo] Error 1

File nghttp2_session.c includes nghttp2_session.h, which in turn includes nghttp2_outbound_item.h which defines

 39 typedef struct nghttp2_data_provider_wrap {
 40   int version;
 41   union {
 42     struct {
 43       nghttp2_data_source source;
 44       void *read_callback;
 45     };
 46     nghttp2_data_provider v1;
 47     nghttp2_data_provider2 v2;
 48   } data_prd;
 49 } nghttp2_data_provider_wrap;

Later file nghttp2_session.c includes nghttp2_submit.h, which has

 34 typedef struct nghttp2_data_provider_wrap nghttp2_data_provider_wrap;

Both have been added recently in 93c4d8bc340438460bce20c939a357fbfae05350. Newer GCC version do not seem to complain.

Best regards,

Rainer

**Comment by tatsuhiro-t** [comment]
Please use the recent version of gcc or clang.

**Comment by rainerjung** [comment]
Sure, I know that using modern gcc works. The whole point of this issue here is, that it does not work on old versions of distributions (which come with old GCC compilers). I am fine, if libnghttp2 does not want to support them, but before up until 1.59.0 one could compile the lib even with old compilers. So if we do not fix the issue, we should state what the supported gcc versions for building libnghttp2 are.

**Comment by tatsuhiro-t** [comment]
Currently, README says:

> Compiling libnghttp2 C source code requires a C99 compiler. gcc 4.8 is known to be adequate.

It is a bit hard to find the minimum because we do not have time to check every (or bisect) version of compiler to see which one works.  Also linux distros typically tweak their compiler package and one can work and others do not.

**Comment by rainerjung** [comment]
Thank you, then lets close this issue. If I find a simple but clean code workaround I can always create a new one. Thanks!

**Comment by ryandesign** [comment]
Please reopen. Redefinition of typedefs is a C11 feature; a conforming C99 compiler need not allow that. gcc 4.2 for example does not.

**Comment by rainerjung** [comment]
Reopened as suggested by @ryandesign.
