### ISSUE TITLE
Possibly memory leak and assertion failure in nghttp2_session_pack_data

### ISSUE THREAD

**Issue by Jeevhi** [nghttp2/nghttp2#2104]
I am using libnghttp2 to send APN2 notification. The basic code was taken from https://github.com/nghttp2/nghttp2/blob/master/examples/client.c 

The difference is that I keep connection open for sending multiple notifications, but one at a time. Hence I do not call `nghttp2_session_terminate_session` from `on_stream_close_callback`. Instead I call `nghttp2_session_del` when connection is closed by the server. 

This worked so far. However, recently our usage increased and I started getting assertion here in `nghttp2_session_pack_data` function. 

https://github.com/nghttp2/nghttp2/blob/master/lib/nghttp2_session.c#L7737

```
/* Current max DATA length is less then buffer chunk size */
  assert(nghttp2_buf_avail(buf) >= datamax);
```

Do you think this due to I am not calling `nghttp2_session_terminate_session`. What would be right way to handle this?

Thanks

**Comment by Jeevhi** [comment]
I see many unanswered issues here so wondering if issues here are watched or do we need to post in some other forum. thanks

**Comment by tatsuhiro-t** [comment]
Watched but the issue like this is hard to deal with because it may be a bug in your program.  Most likely you are calling nghttp2_session from multiple threads or something.  There are many users, but the person that answers their countless questions is just me.

**Comment by Jeevhi** [comment]
I understand and appreciate. thanks for answering.

I can again check for thread contention but it is being called from a thread pool and each thread has it's own instance and hence the session is not used from multiple threads simultaneously. 

In addition, if you can guide me here, does calling `nghttp2_session_del` releases all the resourses if `nghttp2_session_terminate_session` not called at all?

**Comment by tatsuhiro-t** [comment]
> In addition, if you can guide me here, does calling nghttp2_session_del releases all the resourses if nghttp2_session_terminate_session not called at all?

Yes.  Calling nghttp2_session_terminate_session is optional.
