### ISSUE TITLE
Upcoming security release

### ISSUE THREAD

**Issue by tatsuhiro-t** [nghttp2/nghttp2#2121]
The upcoming security release is scheduled at 2024/4/4.
We cannot answer any questions about the details for this security advisory.

**Comment by BrianInglis** [comment]
Details are now available on the OSS-Sec list https://seclists.org/oss-sec/2024/q2/22

**Comment by micheleselea** [comment]
Do you think will be released a new version of nghttp2 lib?

**Comment by tatsuhiro-t** [comment]
https://github.com/nghttp2/nghttp2/security/advisories/GHSA-x6x3-gv8h-m57q
