### ISSUE TITLE
Not able to bundle apache with nghttp2 1.60.0 version

### ISSUE THREAD

**Issue by jvyas24** [nghttp2/nghttp2#2123]
Bundling apache with following components gives error:
httpd -2.4.58
nghttp2 - 1.60.0
openldap - 2.5.17
openssl - 3.0.13
pcre2 - 10.43

While its working fine with below components:
httpd -2.4.58
nghttp2 - 1.59.0
openldap - 2.5.17
openssl - 3.0.13
pcre2 - 10.43

Attached error in screenshot:
![MicrosoftTeams-image](https://github.com/nghttp2/nghttp2/assets/148332324/59f77f6a-1ac7-4047-b16f-6550592b73f6)

**Comment by tatsuhiro-t** [comment]
It would be better to ask apache developer about this.

**Comment by jvyas24** [comment]
but there is no change in Apache side, it is working fine with older version.
