### ISSUE TITLE
zip 1.60.0 package munit missing

### ISSUE THREAD

**Issue by micheleselea** [nghttp2/nghttp2#2130]
In zip package the folder test/munit is empty and cmake fail to configure window solution

**Comment by tatsuhiro-t** [comment]
Do not use archive generated by github.  They do not work.

**Comment by micheleselea** [comment]
I downloaded from 
https://github.com/nghttp2/nghttp2/releases/tag/v1.60.0

**Comment by tatsuhiro-t** [comment]
You should download nghttp2-v1.60.0.tar.gz.  Do not download from "Source code (zip)".
