### ISSUE TITLE
Use nghttp2 to decode response only

### ISSUE THREAD

**Issue by ganeshmurthy** [nghttp2/nghttp2#2139]
Is there a way to use nghttp2 to only look at the response to find response headers ?
I have the response data in my buffers that I want to feed into nghttp2 so it can make callbacks to the callback set via nghttp2_session_callbacks_set_on_header_callback
nghttp2 is *not* used to send the http2 request, I want to use it to only look at the response to look at response headers like :status

**Comment by ganeshmurthy** [comment]
Hear me out here. As mentioned above, I want to use nghttp2 to only look at the response headers from nginx, I am not using nghttp2 to generate the requests. I cleverly thought I could use a "server" session (created using nghttp2_session_server_new()) and call nghttp2_option_set_no_recv_client_magic() to not have nghttp2 look for a client magic. I received the following sequence of frames from the nginx server:

Initial SETTINGS frame
WINDOW_UPDATE frame
SETTINGS frame (this is the ACK SETTINGS frame)
HEADERS (response headers)

Since I did not use nghttp2 to originate the request, on seeing the ACK SETTINGS frame, nghttp2 exits with error "SETTINGS: unexpected ACK" which is correct but unfortunate for me. All I want is to get all the response headers but nghttp2 errors out before getting to the headers and making those header callbacks.

**Comment by tatsuhiro-t** [comment]
Because the traffic is coming from server, nghttp2_session_client_new should be used.
That said, nghttp2 does not support this kind of usage.
