### ISSUE TITLE
FTBFS/Regression in nghttp2 1.61.0 => 1.62.0 with gcc 11

### ISSUE THREAD

**Issue by moonlitbugs** [nghttp2/nghttp2#2194]
Compiling nghttp2 **1.62.0** fails on stable Linux distros that use **gcc 11** as their compiler, such as the stable *Slackware 15.0* which uses *gcc 11.2.0*.  Compiling against gcc-*13* works fine.  The previous versions of nghttp2, **1.61.0** and below, are not affected.

## Example:

```
# make V=1
make  all-recursive
make[3]: Entering directory 'nghttp2-1.62.0/src'
depbase=`echo util.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -std=gnu++20 -DHAVE_CONFIG_H -I. -I..  -DPKGDATADIR='"/usr/share/nghttp2"' -DPKGLIBDIR='"/usr/lib64/nghttp2"' -I../lib/includes -I../lib/includes -I../lib -I../third-party -I../third-party/llhttp/include -I/usr/include/libxml2 -DHAVE_CONFIG_H    -g -O2 -fPIC -march=opteron -MT util.o -MD -MP -MF $depbase.Tpo -c -o util.o util.cc &&\
mv -f $depbase.Tpo $depbase.Po
In file included from util.h:57,
                 from util.cc:25:
template.h: In constructor ‘constexpr nghttp2::ImmutableString::ImmutableString(const string&)’:
template.h:233:19: error: call to non-‘constexpr’ function ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size() const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
  233 |       : len(s.size()), base(copystr(std::begin(s), std::end(s))) {}
      |             ~~~~~~^~
In file included from /usr/include/c++/11.2.0/string:55,
                 from util.h:42,
                 from util.cc:25:
/usr/include/c++/11.2.0/bits/basic_string.h:919:7: note: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size() const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’ declared here
  919 |       size() const _GLIBCXX_NOEXCEPT
      |       ^~~~
```

As a possible workaround, I tried switching between *std=c++20* and *std=gnu++20* and *std=c++17*, optionally with  ```HAVE_CXX20=0```,  but all of those failed with more errors.

**Comment by xl32** [comment]
GCC 12 (latest version available for EL7) also fails with the same error. GCC 13 is ok.

**Comment by tatsuhiro-t** [comment]
gcc-11 probably does not work anymore due to C++20 requirement.  gcc-12 works on our GithHub Actions workflow.

**Comment by moonlitbugs** [comment]
According to the config.log, *gcc-11* was tested and found to comply with **c++20** features when either of ```-std=c++20``` or ```-std=gnu++20``` were specified.  Here's a snippet of the output:

```
configure:20266: checking whether g++ supports C++20 features with -std=gnu++20
configure:21093: g++ -std=gnu++20 -c   conftest.cpp >&5
conftest.cpp:140:36: warning: 'volatile'-qualified parameter is deprecated [-Wvolatile]
configure:21093: $? = 0
configure:21103: result: yes
```
According to the report from @xl32, and despite the Github Actions cited above, gcc-12 also fails, and with the same error messages.

While this may be gcc's bug, the fact that it affects gcc-12 in **RHEL7** (and likely many other similar GNU/Linux distros) suggests this FTBFS will be a problem of more widespread interest.  If any further updates to *nghttp2* contain fixes for 0-day security vulnerabilities and the like, those distributions will want to roll out patches ASAP; and they will have only gcc-11 or gcc-12 available for the compile.

Is it the intention of the *nghttp2* developers to roll out *nghttp2-1.61.1* and *-1.61.2*, etc etc., for the foreseeable future, for those distributions which are locked into gcc-11 or gcc-12?  Should this **c++20** requirement be backed out and moved to *nghttp2-2.x* as it is not present in *nghttp2-1.61*?  Or add appropriate ```#ifdef``` feature-check blocks to avoid the FTBFS?

**Comment by tatsuhiro-t** [comment]
Even though gcc says it supports -std=c++20, the actual implementation status of C++ features varies across versions.  Also the linux distribution vendors package compilers with their own patches, so it is kind a hard to check the minimum version of gcc.

We only support the latest version of nghttp2.  It is very hard to support distributions that do have no effort to bring newer compilers to backport to LTS  or older releases.   Adding ifdef just complicates the source code and we just tired and lose interest in this project, and will eventually abandon its development, that is not what we want.

**Comment by cmeister2** [comment]
Saw this in curl also.  https://github.com/curl/curl/pull/13650

**Comment by BrianInglis** [comment]
Ditto Cygwin `g++` 11.4. 
While `g++` 12 and 13 are in test, there are issues with some other *GCC* components, so are not considered stable enough for promotion. 
Other distros with many users and even more packages need to be able to be recompiled with newer compiler versions, including backports and LTS releases, extending the testing required, and even longer lead times to promotion. 
Distros with latest compilers and packages are those with fewer users and packages and variants; some I've never heard of! ;^> 
You should check which g++ version supports the features you need, check that and fail during configure, rather than fail during make.

**Comment by moonlitbugs** [comment]
The "solution" I used to make *nghttp2 1.62* work is, well, not ideal:
- I put together a distribution build script for gcc-14 and built packages for it.
- Replace the packages for gcc-11 with gcc-14
- Manually delete ```libgcc_s.so.1``` **!!!**
- Compile nghttp2, which now links statically against ```libgcc_s.a```
- Revert the packages for *gcc-14* with the original *gcc-11* ones.
  N.B.: nghttp2 will not load due to missing features in gcc-11's libgcc_s.so, necessitating a static link.
- Recompile anything else under gcc-11 that needs to link with the new libnghttp2, if necessary.

While this is a nice SysAdmin tabletop exercise, it does not lend itself well to a distribution's automation, which may see several non-conflicting packages being updated/compiled in parallel.  Replacing gcc from underneath another build process while that build process is actively compiling source files is not what I had wished to accompany my morning coffee.  :smile:

To be fair, the reverse issue of building packages under gcc-14 that were engineered for earlier standards has been even more "fun" than this one.  And this is, in turn, *so* much nicer than yet another ABI change in  libpoppler; but I digress.  :wink:

**Comment by tatsuhiro-t** [comment]
I hope that slackware updates its compilers so that this kind of issues go away.
libnghttp2 itself is plain C, which can be compiled with any modern compilers.  C++ part is tricky like this, so you can pass CC=gcc-11 CXX=g++-14 and build nghttp2, which workarounds the non-ideal part of build issue?

**Comment by oerdnj** [comment]
> Even though gcc says it supports -std=c++20, the actual implementation status of C++ features varies across versions. Also the linux distribution vendors package compilers with their own patches, so it is kind a hard to check the minimum version of gcc.
> 
> We only support the latest version of nghttp2. It is very hard to support distributions that do have no effort to bring newer compilers to backport to LTS or older releases. Adding ifdef just complicates the source code and we just tired and lose interest in this project, and will eventually abandon its development, that is not what we want.

While this is true, I am not sure if it's that helpful to the open-source ecosystem to require compilers that are not present in the LTS distributions. GCC 11 was released in 2021 (GCC 10 in Debian bullseye was released in 2020) and while I absolutely agree that from maintainer's perspective it's a PITA to maintain backward-compatibility with older compilers, this leads to a situation where you can't use nghttp2 on reasonably supported distributions. And I am not speaking about the long-term support distros, just the regular stable releases of Debian and Ubuntu (supported for roughly 4 years).

I wish you would reconsider the changes between 1.61.0 => 1.62.0; not everyone is at the liberty of upgrading the latest-greatest and this is also making the lives of the distro maintainers much harder than it should be.

I am not a C++ programmer, but my guess is that errors like the OP reported and this (Debian Buster with gcc-10) could be circumvented by rewriting the code to a compatible form (there might be a need for #ifdef, but perhaps not?):

```
15:22:39 /usr/include/c++/10/tuple:1375:33: error: no match for 'operator<' (operand types are 'std::__tuple_element_t<1, std::tuple<nghttp2::StringRef, nghttp2::StringRef, nghttp2::StringRef, long unsigned int, long unsigned int, shrpx::Proto, unsigned int, unsigned int, unsigned int, bool, bool, bool, bool> >' {aka 'const nghttp2::StringRef'} and 'std::__tuple_element_t<1, std::tuple<nghttp2::StringRef, nghttp2::StringRef, nghttp2::StringRef, long unsigned int, long unsigned int, shrpx::Proto, unsigned int, unsigned int, unsigned int, bool, bool, bool, bool> >' {aka 'const nghttp2::StringRef'})
```

So, I am kindly asking you to reconsider.

**Comment by BrianInglis** [comment]
You should also note downstreams, such as curl, had to revert using 1.62, referencing this issue, as it broke their CI jobs, which probably run on mainstream server distro builds, and are unlikely to have the latest compiler releases, in the interests of stability. 
Also Ubuntu bases their gcc on Linaro, which develops mainly for embedded ARM, so major enterprise and server distros, such as RHEL and SuSE, probably have to do a lot of QA and fixes on their major platforms like amd64; rebuilding, testing, and triaging kernels and thousands of their packages for new warnings generated, and new issues encountered, before they can move to a new compiler. And these are commercial distros. 
It is likely more challenging and takes longer for non-commercial organization distros with more volunteer manpower, like Debian, Fedora, etc. to commit to a newer compiler. 
If you look at GCC https://gcc.gnu.org/develop.html#timeline it makes more sense for distros to target GCC versions #.4 for stable release, after 1-2 years effort in test from #.1 or #.2, and 12.4 has just been released, so it is likely to be months before that is promoted to current stable.

**Comment by tatsuhiro-t** [comment]
Curl CI uses nghttp2 v1.62.1 without an issue.

**Comment by moonlitbugs** [comment]
Hello @tatsuhiro-t et al,

I have not bisected or investigated much, but `nghttp2 1.66.0` compiles successfully under GCC-11.2; the regression appears fixed.  I am blindly guessing this is thanks to PR #2444 (and maybe commit 1440e883),  fixing compilation against GCC 16.

😄

**Comment by cbrownAkamai** [comment]
Even though there does not seem to be any will to resolve compilation problems with older compilers, I wanted to note for others that "nghttp2 1.67.1" fails with GCC 11.4.0 due to the use of consteval in a single header.  "Downgrading" to constexpr fixed the issue.
