### ISSUE TITLE
Unable to compile tests for release nghttp2-1.62.1. munit.h file is missing

### ISSUE THREAD

**Issue by eitlane** [nghttp2/nghttp2#2199]
Hello,

While I tried to compile nghttp2 from the source (nghttp2-1.62.1.tar.gz) I have the followin error:

```
 make[3]: Entering directory '/root/nghttp2/SOURCES/nghttp2-1.62.1/tests'
  CC       main.o
main.c:29:10: fatal error: munit.h: No such file or directory
   29 | #include "munit.h"
      |          ^~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:831: main.o] Error 1
make[3]: Leaving directory '/root/nghttp2/SOURCES/nghttp2-1.62.1/tests'
make[2]: *** [Makefile:1187: check-am] Error 2
make[2]: Leaving directory '/root/nghttp2/SOURCES/nghttp2-1.62.1/tests'
make[1]: *** [Makefile:867: check-recursive] Error 1
make[1]: Leaving directory '/root/nghttp2/SOURCES/nghttp2-1.62.1/tests'
make: *** [Makefile:571: check-recursive] Error 1
```

The file is in a separte [project](https://github.com/ngtcp2/munit/tree/7f53fea8901089d46233302b3af35bf8be93cfc5) which is *NOT* included in the tarball 

Compilation env:

Ubuntu 22.04.3 LTS (Jammy Jellyfish)
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

with the following options:
`configure --prefix=install-folder/pic --enable-lib-only --with-libxml2 --disable-shared --with-pic`

I expect the compilation to fail (as the file is missing) no matter the OS/compiler version

Thanks,
V

**Comment by tatsuhiro-t** [comment]
https://github.com/nghttp2/nghttp2/releases/download/v1.62.1/nghttp2-1.62.1.tar.gz should include all files necessary to build nghttp2.

**Comment by BadganchiP1234** [comment]
Could you please help here, i am also facing the same issue, not able to build tests.

| main.c:29:10: fatal error: munit.h: No such file or directory
|    29 | #include "munit.h"
|       |          ^~~~~~~~~
| compilation terminated.
| make: *** [<builtin>: main] Error 1

**Comment by devkdas** [comment]
git submodule update --init --recursive worked for me.
