### ISSUE TITLE
Compiler version numbers in readme

### ISSUE THREAD

**Issue by ryandesign** [nghttp2/nghttp2#2202]
I'm confused by the compiler version numbers shown in the readme:

https://github.com/nghttp2/nghttp2/blob/5db776c725ff4af951f5d4d1185a5b0250ccade9/README.rst?plain=1#L151-L154

Was that intended to read "g++ >= 12 and clang++ >= 15"?

**Comment by tatsuhiro-t** [comment]
A PR is welcome if you can make it better.
