### ISSUE TITLE
Regression: Global "check" target causes build failure with other libraries

### ISSUE THREAD

**Issue by anthonyalayo** [nghttp2/nghttp2#2204]
Abseil is also using the target "check", which causes a build with nghttp2 and abseil to fail:
```
CMake Error at build/_deps/absl-src/CMake/AbseilHelpers.cmake:306 (add_library):
  add_library cannot create target "check" because another target with the
  same name already exists.  The existing target is a custom target created
  in source directory
  "/home/anthony.alayo/test/build/_deps/nghttp2-src".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  build/_deps/absl-src/absl/log/CMakeLists.txt:423 (absl_cc_library)
```

It is due to this change:
https://github.com/nghttp2/nghttp2/commit/be8a32725873d83107c769df1811caf9f9cc0d27#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR171

Where before the target `check` would only be exposed if `HAVE_CUNIT` was enabled. Can we have a option/flag surrounding this?

**Comment by tatsuhiro-t** [comment]
This is not a regression.  The ability to run tests without resorting the external project is a huge win for us.
Obviously, a project has the liberty to add arbitrary named targets.  Then I am under impression that crashing targets means that cmake does not really support your use case.

**Comment by anthonyalayo** [comment]
> This is not a regression. The ability to run tests without resorting the external project is a huge win for us. Obviously, a project has the liberty to add arbitrary named targets. Then I am under impression that crashing targets means that cmake does not really support your use case.

Cmake does support the use case, its listed inside Craig Scott's book "Professional CMake". The main issue is that `check` should be a namespaced target. A namespaced target will have no collisions.

**Comment by anthonyalayo** [comment]
I linked this above, but the same bug was filed on abseil for the same problem:
https://github.com/abseil/abseil-cpp/issues/1641

**Comment by tatsuhiro-t** [comment]
The book author raised https://gitlab.kitware.com/cmake/cmake/-/issues/22687 and it seems no "namespace" thing in custom target, it needs to be unique name.  Non-exported internal target is fine, but target like "check", invoked by person, is really annoying when it needs to be "nghttp2-check" like that.

Adding check target only when it is not added already might be a workaround just like https://github.com/opencv/opencv/pull/17010/files did, and https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake is suggested for uninstall command.

**Comment by anthonyalayo** [comment]
I'm up for submitting a change to help fix the conflict, is there any option you prefer? Otherwise I can also do some research and see if there's a optimal way of doing it.
