### ISSUE TITLE
How to respond for the first upgrade message

### ISSUE THREAD

**Issue by ArkadyRudenko** [nghttp2/nghttp2#2221]
I write a http2 server. I want to curl this such as `curl -k --http2 http://localhost:8080/hello -v`
Version of nghttp2 1.43.0
Curl client sends a such request:
```
my_dir> curl -k --http2 http://localhost:8080/hello -v
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /hello HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA
> 
```
As I understand with RFC 7540(this version is on your main docs page) [section 3.2](https://datatracker.ietf.org/doc/html/rfc7540#section-3.1:~:text=After%20the%20empty%20line%20that%20terminates%0A%20%20%20the%20101%20response%2C%20the%20server%20can%20begin%20sending%20HTTP/2%20frames.%20%20These%0A%20%20%20frames%20MUST%20include%20a%20response%20to%20the%20request%20that%20initiated%20the%0A%20%20%20upgrade) server should sends `HTTP/1.1 101 Switching Protocols` first and then sends a response to the request that initiated the upgrade. Ok, I handle first and send to the client a switch protocol response. Then client accepts it and switches protocol to HTTP/2(everything seems good):
```
* Mark bundle as not supporting multiuse
< HTTP/1.1 101 Switching Protocols
< Connection: Upgrade
< Upgrade: h2c
* Received 101
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
```
**And then I have a problem**. How can my server to parse HTTP/1.1 request? Do I need to support HTTP/1.1 parser only for a init request? Before I manually find a `HTTP2-Settings` in request string to understood that this is first upgrade request 

So, I can hardcode a 200 response with correct `HTTP2-Settings`(that decode with base64url etc.) and I call `nghttp2_session_upgrade2`. And then client sends me a correct HTTP/2 requests and all good(if client and server keep this connection) . But I can not to reply for a first request because it in HTTP/1.1 version so I can not response to curl client for his request.

My attempts: I saw [your docs](https://nghttp2.org/documentation/package_README.html#:~:text=The%20HTTP%20Upgrade%20is%20performed%20like%20so) with HTTP upgrade but there is not about reponse to init request

**Question**: What is the correct order of actions to correct upgrade client protocl version and respond it? And witch stream_id should be when we call `nghttp2_submit_response`?
(So, I saw docs and can write http2 responses to socket and interact with client, the question in the first message to which there is no correct response)

**Comment by tatsuhiro-t** [comment]
You need to parse HTTP/1 request on your own.  You can write a parser or use the existing ones like llhttp or picohttpparser.
After you call nghttp2_session_upgrade2, it opens stream 1 as described in the documentation of the function.  You can send response using stream ID 1.

**Comment by ArkadyRudenko** [comment]
@tatsuhiro-t thanks!
