### ISSUE TITLE
Does nghttp2_submit_data2 automatically generate two or more DATA_FRAMES if it exceeds the client MAX_FRAME_SIZE?

### ISSUE THREAD

**Issue by harieamjari** [nghttp2/nghttp2#2223]
Hi,

I'm writing a server and I want to submit a data using, `nghttp2_submit_data2()`.

As I've read in the docs, only one DATA or HEADERS is allowed for a stream at a time. Does `nghttp2_submit_data2()` generates two or more DATA frames at its will if MAX_FRAME_SIZE is exceeded? (does nghttp2 keep track of that setting?). Or I will have to make sure it doesn't exceed that so it can be guaranteed only one DATA frame is generated?

I need to know so that when `nghttp2_on_frame_send_callback` is called, no DATA frame is actually in the outgoing queue as the docs required when calling again, `nghttp2_submit_data2()`.

--harieamjari

**Comment by tatsuhiro-t** [comment]
nghttp2 segments supplied data if it exceed max frame size because it only asks that amount of data from the callback.  As far as I know, you need to completely send off data submitted via nghttp2_submit_data2, and then call it again with another.
