### ISSUE TITLE
nghttp2 fails to detect c-ares 1.34.0 and newer

### ISSUE THREAD

**Issue by diizzyy** [nghttp2/nghttp2#2253]
This due to how the CMake framework is setup to determine available version as this broke in c-ares 1.34.0 and newer due to layout changes.
https://github.com/nghttp2/nghttp2/blob/master/cmake/FindLibcares.cmake#L19
This should probably be changed to make use of the internal logic in CMake using PkgConfig and/or CMake itself as upstream provides .cmake helpers.

**Comment by diizzyy** [comment]
Related, https://github.com/wireshark/wireshark/commit/7c1418625d2ba5095ef5393abdb2141c990a662c

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.  #2256 fixes it.
