### ISSUE TITLE
Compile failed: nghttp2 1.64.0 + wolfssl 5.7.2

### ISSUE THREAD

**Issue by designinlife** [nghttp2/nghttp2#2269]
**The compilation environment is as follows:**
OS: _AlmaLinux 8.10_
GCC: _gcc-toolset-13_
ngtcp2: _1.8.1_
wolfssl: _5.7.2_

./configure --prefix=/usr/local/nghttp2 --with-libbrotlienc --with-libbrotlidec --with-libxml2 --with-jansson --with-jemalloc --with-libngtcp2 --with-libnghttp3 --with-libbpf --with-wolfssl --enable-http3
make

**The following error occurs when executing the make command:**

make[2]: Entering directory '/spec/nghttp2-1.64.0/third-party'
  CC       url-parser/url_parser.lo
  CCLD     liburl-parser.la
  CC       llhttp/src/libllhttp_la-api.lo
  CC       llhttp/src/libllhttp_la-http.lo
  CC       llhttp/src/libllhttp_la-llhttp.lo
  CCLD     libllhttp.la
make[2]: Leaving directory '/spec/nghttp2-1.64.0/third-party'
Making all in src
make[2]: Entering directory '/spec/nghttp2-1.64.0/src'
Making all in testdata
make[3]: Entering directory '/spec/nghttp2-1.64.0/src/testdata'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/spec/nghttp2-1.64.0/src/testdata'
make[3]: Entering directory '/spec/nghttp2-1.64.0/src'
  CXX      util.o
  CXX      http2.o
  CC       timegm.o
  CXX      app_helper.o
  CC       nghttp2_gzip.o
  CXX      nghttp.o
  CXX      HtmlParser.o
  CXX      tls.o
  CXXLD    nghttp
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: nghttp.o: in function `nghttp2::HttpClient::initiate_connection()':
nghttp.cc:(.text+0x30f8): undefined reference to `wolfSSL_set_tlsext_host_name'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:1304: nghttp] Error 1
make[3]: Leaving directory '/spec/nghttp2-1.64.0/src'
make[2]: *** [Makefile:2456: all-recursive] Error 1
make[2]: Leaving directory '/spec/nghttp2-1.64.0/src'
make[1]: *** [Makefile:574: all-recursive] Error 1
make[1]: Leaving directory '/spec/nghttp2-1.64.0'
make: *** [Makefile:483: all] Error 2

**Comment by tatsuhiro-t** [comment]
Did you enable SNI in wolfssl?
