### ISSUE TITLE
Windows / MSVC14 support in nghttp2_asio.

### ISSUE THREAD

**Issue by fxb** [nghttp2/nghttp2#363]
I was trying to build nghttp2 and nghttp2_asio using MSVC14 and a simple CMake configuration.

nghttp2 builds fine apart from some integer truncation warnings (e.g. conversion from 'size_t' to 'uint8_t', possible loss of data). I prefer to treat all warnings as errors, though.

nghttp2_asio is another story, since lots of the code seems to use UNIX only functionality (e.g. different "sys/*.h" headers as well as "getopt.h" in "util.h"). Are there any plans to fix nghttp_asio to compile with MSVC14 as well?

Short list of things that I identified, and which would need to be done:
- Fix warnings by introducing explicit casts.
- Add Windows implementation for "memchunk.h", which doesn't use vectored I/O.
- Split up "util.h/cpp" into separate utility files, meaning common utility functions in one file and UNIX specific utility functions for the command line tools in another file. Also porting the command line utilities would be another big task.

**Comment by tatsuhiro-t** [comment]
I think it is a good idea to make libnghttp2_asio windows compatible.

As a first step, could you share warnings you encountered, so that we can fix them as a first step.
memchunk.h is not used in libnghttp2_asio code, but it is included by header file (http2.h) it uses.
It would be better to split it up just like util, or at least ifdef guard for windows build.

I don't have MSVC14 build environment, and the work is not probably going fast.

**Comment by 0x64616E69656C** [comment]
Not entirely on topic, but I encountered a few conversion warnings on linux / clang too they are not per se errors, but could under circumstances lead to crashes during fuzzing, a list of valuable flags would be (for clang, not all of them apply to gcc):

> -Wcast-align
> -Wconversion
> -Wextended-offsetof
> -Wformat-nonliteral
> -Wlanguage-extension-token
> -Wmissing-field-initializers
> -Wmissing-noreturn
> -Wmissing-variable-declarations
> -Wpadded
> -Wshorten-64-to-32
> -Wsign-conversion
> -Wswitch-enum
> -Wunreachable-code-break
> -Wunreachable-code
> -Wunused-macros
> -Wunused-parameter

I wanted to do more tests with -fsanitize besides address,undefined,signed-integer-overflow (espacially the new safe-stack and memory options), unfortionatly there are still no working pre-build llvm/clang 3.8 packages for debian available, the sanitizer is currently broken  (see debian bug 779785).

**Comment by tatsuhiro-t** [comment]
Thank you.  I'll consider to add additional warning flags mentioned in the previous post.
It seems "-Wpadded" shows warning for struct in public API, but we cannot change that struct because changing it will certainly breaks ABI, which we have to avoid at this time.  So probably, we don't include it.

**Comment by tatsuhiro-t** [comment]
With 28fe3e7e891a, I've enabled more warning flags, which are a subset @0x64616E69656C mentioned.

**Comment by josmad** [comment]
Was any progress made on this / what is left to be done?

**Comment by tatsuhiro-t** [comment]
As far as I know, except for the added warning flags, no progress has been made so far.

**Comment by haismail** [comment]
Hi tatsuhiro-t, I guess the situation is still the same e.g. nghttp_asio not compiling underMSVC14?

**Comment by tatsuhiro-t** [comment]
Yes.

**Comment by haismail** [comment]
Thanks tatsuhiro, any rough estimate of how long it could take if someone will start to make it work in Windows environment?

**Comment by tatsuhiro-t** [comment]
I haven't done any preliminary work, but we need to some work stated in https://github.com/nghttp2/nghttp2/issues/363#issuecomment-142271181
In my personal opinion, using extensive if-def dance for Windows makes our maintenance work very hard.

**Comment by alagoutte** [comment]
a first time will be add a Windows build ?

**Comment by tatsuhiro-t** [comment]
libnghttp2 can be compiled with MSVC using cmake just fine.
Some attempts was made to compile bundled applications here https://github.com/nghttp2/nghttp2/pull/544#issuecomment-198143704 but we use some header files which are not in Windows.

**Comment by alagoutte** [comment]
a automated build(bot) with appveyor(.yml) for example

**Comment by saravannah** [comment]
Hi fxb,
      I am also facing the getopt.h file missing error.
nghttp2-master\src\util.h(33): fatal error C1083: Cannot open include file: 'getopt.h': No such file or directory
network.h(36): fatal error C1083: Cannot open include file: 'sys/un.h': No such file or directory

Were you able to fix the above errors?

**Comment by dermojo** [comment]
Hi all,
I needed nghttp2 to compile with MinGW under Linux (the library + ASIO support). Feedback to the pull request is highly welcome.
