### ISSUE TITLE
nghttp2 and libnghttp2ASIO on Android

### ISSUE THREAD

**Issue by josmad** [nghttp2/nghttp2#450]
I am attempting to cross-compile nghttp2 and libnghttp2asio for Android, using Ubuntu 14.04 64-bit as the host system. 
After fixing the Dockerfile.android file; 
OpenSSL link is broken because a newer version was released and the libev homepage is down so I found a mirror, I was able to build nghttp2. 
However if I add --enable-asio-lib to the dockerfile, the option is ignored and only nghttp (and nghttpx & nghttpd) is being built. Any clue what fails? Is one of the other options specified in the dockerfile overriding --enable-asio-lib?

**Comment by tatsuhiro-t** [comment]
You need boost asio and its dependencies.

**Comment by josmad** [comment]
Do they have to be explicitly enabled using eg. --with-boost-asio?

**Comment by tatsuhiro-t** [comment]
Boost detection in configure script might be limited, especially for search path.
Adding CPPFLAGS and LDFLAGS for cross-compiled boost may help.

**Comment by josmad** [comment]
--with-boost-libdir for configure seems to be broken. No matter what I give to it, it will complain that it expects a directory name.
As for CPPFLAGS and LDFLAGS, do you mean the general ones or BOOST_CPPFLAGS and BOOST_LDFLAGS?

**Comment by tatsuhiro-t** [comment]
This is the boost base detection code: https://github.com/tatsuhiro-t/nghttp2/blob/86505b1c548b5aaae4e0230cc243ea027f13d8dd/m4/ax_boost_base.m4#L68

So --with-boost-libdir shows error if the given directory is not directory?

> As for CPPFLAGS and LDFLAGS, do you mean the general ones or BOOST_CPPFLAGS and BOOST_LDFLAGS?

I meant former.  Reading source code, it looks like the latter also works, but I'm not sure.

**Comment by josmad** [comment]
I am guessing that "test -d" checks if the given string points to a directory? Full path or relative to the working dir? Sorry, I am not familiar with autoconf syntax. I specified the full path to a folder in --with-boost-libdir

As for my Dockerfile.android, the nghttp2 part looks like this:

WORKDIR /root/build/nghttp2
RUN autoreconf -i && \
    ./configure \
    --disable-shared \
    --host=arm-linux-androideabi \
    --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
    --with-xml-prefix="$PREFIX" \
    --without-libxml2 \
    --enable-asio-lib \
    --disable-python-bindings \
    --disable-examples \
    --disable-threads \
    --with-boost-asio \
    --with-boost-system \
    --with-boost-thread \
    LIBSPDYLAY_CFLAGS=-I$PREFIX/usr/local/include \
    LIBSPDYLAY_LIBS="-L$PREFIX/usr/local/lib -lspdylay" \
    CPPFLAGS="-fPIE -I$PREFIX/include -I/home/buntu/boost_1_59_0" \
    CXXFLAGS="-fno-strict-aliasing" \
    PKG_CONFIG_LIBDIR="$PREFIX/lib/pkgconfig" \
    LDFLAGS="-fPIE -pie -L$PREFIX/lib -L/home/buntu/armeabi/lib" \
    LDLIBS="-lboost_system_gcc-mt-sd-1_59 -lboost_thread_pthread_gcc-mt-sd-1_59" && \
    make && \
    arm-linux-androideabi-strip src/nghttpx src/nghttpd src/nghttp

It still does not recognise boost, nor does it enable compilation of libnghttp2_asio. I tried running the entire build again with using the cache, but it made no difference.

**Comment by tatsuhiro-t** [comment]
> I am guessing that "test -d" checks if the given string points to a directory? Full path or relative to the working dir? Sorry, I am not familiar with autoconf syntax. I specified the full path to a folder in --with-boost-libdir

It behaves like a shell, and `test -d "$a"` checks that $a is an existing directory.  I think full path is safer and reliable in this case.
It looks like it is working when I set a directory to that option.  At least, I did not get "expects a directory name" error.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
