### ISSUE TITLE
Is there a way to configure the read/write timeouts ? 

### ISSUE THREAD

**Issue by rameshrajagopal** [nghttp2/nghttp2#455]
Hi, 

When my server gets the request, it just uploads the work to worker threads, response may come at any time later, but I do want to force the TIMEOUT behaviour, within a specified time, I don't get back from worker threads, I want to send a time-out error back to client, is there a way to achieve this via nghttp2 apis by changing the configuration/settings ? 

Regards,
Ramesh

**Comment by tatsuhiro-t** [comment]
Are you using libnghttp2_asio library?
If so, there is no timer in library, but you can create your own timer, and if timer is fired, use response::cancel() to cancel stream.

**Comment by tatsuhiro-t** [comment]
I mean boost::asio:deadline_timer

**Comment by rameshrajagopal** [comment]
Hi Tatsuhiro,

Yes, I am using libnghttp2_asio library. This means I need to take care of
creating timers for each request and handling it accordingly. Isn't it ?
With the C-library is it possible ?


Regards,
Ramesh.

**Comment by tatsuhiro-t** [comment]
I think timeout in this case is application specific, so it would be more handy for application to do it for its own.
If I were implement timeout, it would be I/O timeouts only.

**Comment by rameshrajagopal** [comment]
what do you mean by I/0 timeouts ?
Do you mean the below code would suffice ?
{
   auto timer = std::make_shared<boost::asio::deadline_timer>(
          res.io_service(), boost::posix_time::seconds(3));
      auto closed = std::make_shared<bool>();

      res.on_close([timer, closed](uint32_t error_code) {
        timer->cancel();
        *closed = true;
      });

      timer->async_wait([&res, closed](const boost::system::error_code &ec)
{
        if (ec || *closed) {
          return;
        }
         res.cance();
      });
}
is there any other way to configure io_service to handle this or equivalent
of setsockopt possible via asio library ?

Thanks for your help.
Ramesh

**Comment by tatsuhiro-t** [comment]
I/O timeout is 2 timeouts:  one for reading from client, one for writing data to client.

I think your timer code should work.
Does setsockopt have timer related option?

**Comment by rameshrajagopal** [comment]
Something like below can be used for setting timeout, but haven't tested much on this.
tv.tv_sec = 1;
tv.tv_usec = 0;  // Not init'ing this can cause strange errors
setsockopt(sockfd, SOL_SOCKET, SO_RCVTIMEO, (char *)&tv,sizeof(struct timeval));

Btw, I don't get a connection failure / request close in the following case. My client is keep firing the requests to the server and server is responding back. During this, I pull out a network cable on the server side. I don't get any notification from nghttp2 that something like this happened. Any idea ? 
Though my server is not reachable now, client is keep firing the request.

**Comment by tatsuhiro-t** [comment]
As far as I know, SO_RCVTIMEO is for blocking operation.
We use non-blocking socket for HTTP/2, and we cannot use this.

Pulling off the cable may not immediately report connection error.  That is how TCP works.  I'm not sure what you are trying to achieve.

**Comment by rameshrajagopal** [comment]
Ok. got it why we can not use setsockopt..

Regarding the network cable pulling, At sometime, the client should get a connection error but it my case it never. All the requests are keeping getting filled without a error being reported. 
I am trying to simulate a scenario where client and server is proper but the network connection in b/w interrupted/gone down or the whole server machine itself crashed. Trying to analyse what sort of problems can come and see how can I handle it.

**Comment by tatsuhiro-t** [comment]
What client software are you using? nghttp?

**Comment by rameshrajagopal** [comment]
Yes, nghttp2_asio client. 

class Client: public std::enable_shared_from_this<Client> {
public:
    Client(string h, string p, boost::asio::io_service & ios):
           host(h), port(p), ios(ios)
           {
               sess = make_shared<session>(ios, host, port);
               cout << "constructed" << endl;
           }
    ~Client() {
        cout << "Destructor called" << endl;
        req_map.clear();
    }
    void connect(session_connect_cb client_connect_cb) {
        /* we can not access sess out of io service
         * hence post method is needed
         */
        auto self = shared_from_this();
        ios.post(
           [self, client_connect_cb]() {
           self->sess->on_connect([self, client_connect_cb](tcp::resolver::iterator endpoint_it) {
              cout << "session connected" << endl;
              client_connect_cb(self->host, self->port, 0);
           });
           self->sess->on_error([self, client_connect_cb](const boost::system::error_code & ec) {
              cout << "session error " << ec.message() << endl;
              //need to convert from error_code to our own mapping
              client_connect_cb(self->host, self->port, 1);
           });
        });
    }
If I kill the server alone, then I am getting session connect error but network card pulling case it doesn't

**Comment by tatsuhiro-t** [comment]
We use boost asio, and check the write error accordingly.  Unless error is propagated to socket level, client/server may not know this kind of physical error.

**Comment by tatsuhiro-t** [comment]
http://stackoverflow.com/questions/14227007/howto-detect-that-a-network-cable-has-been-unplugged-in-a-tcp-connection

**Comment by rameshrajagopal** [comment]
I never get any feedback from nghttp2 even after waiting for 1/2 hour or so. I am solving this by having a node monitor which polls to the server. 

Btw, I have a client which tries to connect to the server, say server is not yet up. I get a session connect error from client
/* pseudo code is here */
session sess(ioservice, host, port); 
sess.on_connect(connect_callback);
sess.on_error(error_callback); 

since server is not yet up, I get a error_callback saying "connection refused". Basically I want to re-try until I get connected. On this front, I have the following questions 

1) After sess "error_callback", is the variable sess still valid ?  Can I use this variable to re-submit the connect_callback ? 
2) Do I need to re-submit the "connect callback" or already submitted callback is still a valid callback ? 
3) Do I need to re-create session itself ? 


Thanks 
Ramesh.

**Comment by tatsuhiro-t** [comment]
> I never get any feedback from nghttp2 even after waiting for 1/2 hour or so. I am solving this by having a node monitor which polls to the server.

We need at least read timeout here, to properly drop connection in this abnormal case.

> 3) Do I need to re-create session itself ? 

Yes.

**Comment by tatsuhiro-t** [comment]
09bd9c94a3fdb6e74763f942b4bbec0459b6bc2b makes a bit easier now for client to detect connection drop.

**Comment by rameshrajagopal** [comment]
Thanks I will try it out and update.

**Comment by rameshrajagopal** [comment]
Is still libnghttp2_asio library experimental ? Could you please tell why do you say it is in experimental ? Is there anything which needs to be taken care if you want to use in a production code base ? 

Thanks
Ramesh

**Comment by tatsuhiro-t** [comment]
API has still not frozen yet.  I still not sure boost asio is a way to go.  It seems it is too much complicated than it offers.  libev is much easier, especially for timers.

BTW, we added configurable timeouts for client and server.  See 1ee1122d40a9ce8adebd62f81d33cc60e153ae89 and 7c5ef0613dc9f540021ea97f4a53ce2841d0866f.
7c5ef0613dc9f540021ea97f4a53ce2841d0866f introduced backward incompatible change, so it requires rebuild.

**Comment by rameshrajagopal** [comment]
Cool! Thanks for adding the configurable timeouts. It saves some extra to be added at the request handling at the application.
