### ISSUE TITLE
No h2load

### ISSUE THREAD

**Issue by Angristan** [nghttp2/nghttp2#478]
Hi,

I installed nghttp2 from Debian Sid repo : https://packages.debian.org/fr/sid/nghttp2

But I don't have any h2load, is it normal ?

**Comment by bagder** [comment]
Yes, it is normal. It seems they don't include h2load in that package (or in any package really).

**Comment by tatsuhiro-t** [comment]
You can ask for it Debian package maintainer by submitting bug there.

**Comment by Angristan** [comment]
Okay because in Arch it's in the package.
Any way to have h2load on Debian ?

**Comment by tatsuhiro-t** [comment]
It is very easy to compile h2load on Debian sid.  All necessary packages are available.  See https://nghttp2.org/documentation/package_README.html#requirements for detailed required packages listing.

**Comment by thinred** [comment]
@Angristan Please report such problems to Debian bugtracker (using reportbug tool). I'll include h2load in the next upload, either as part of nghttp-client or as a standalone nghttp-h2load. Here is a relevant bug: https://bugs.debian.org/853860.

**Comment by thinred** [comment]
I've just uploaded a new package that has h2load in nghttp2-client (so if you upgrade, you should get it). This should be available in unstable very soon (i.e., hours). I believe this bug can be closed now. Thank you for the report!

**Comment by tatsuhiro-t** [comment]
@thinred Thank you!

**Comment by Angristan** [comment]
Thanks !
