### ISSUE TITLE
Multiple domain 

### ISSUE THREAD

**Issue by mhf-ir** [nghttp2/nghttp2#498]
Is nghttpx support multiple domain method ? each domain (or subdomain) has special crt and pem file and etc config ...

**Comment by tatsuhiro-t** [comment]
nghttpx supports multiple server certificates, using [--subcert](https://nghttp2.org/documentation/nghttpx.1.html#cmdoption-nghttpx--subcert) option.
Other configurations are global in nghttpx.  You can specify backend server based on host and path using [--backend](https://nghttp2.org/documentation/nghttpx.1.html#cmdoption-nghttpx-b) options.
