### ISSUE TITLE
Only with http2 push, DOMContentLoaded and total Load time is much slower

### ISSUE THREAD

**Issue by dman777** [nghttp2/nghttp2#501]
This isn't really a http2 push issue, as the files are being pushed as they should be. In fact, their individual times are much shorter. However, only with http2 push, the DOMContentLoaded and Load times are much slower. Any suggestions on what could  be wrong and how I could fix this? 

Please see the graphs:

Here is http non-push. You can see the time on the files are longer. For instance, krunch.png is 150ms. The DOMContentLoaded is 584 ms and Load is 745 ms

![](https://lh3.googleusercontent.com/-E6MTJBJrxho/VrVbPE3DgEI/AAAAAAAAD9A/K9a04jqnWkU/s1600/non-http2push.jpg)

Here is http2 push. The time on the individual files are much shorter. For instance, krunch.png is 9ms. However, the DOMContentLoaded is 2.74s and Load is 2.75s. The DOMContentLoaded and load is much longer than the normal http(non http2 push). 

![](https://lh3.googleusercontent.com/-3yc-RRWOvJY/VrVcPQEZAOI/AAAAAAAAD9I/5cAU0Q5DM1w/s1600/http2push.jpg)

These graphs can also be seen on imagur:
http://imgur.com/u3TdzDG
http://imgur.com/d24hSTh

**Comment by tatsuhiro-t** [comment]
This is probably because critical assets delivery is delayed by non critical asset pushes (e.g., images). Not sure which server are you using (nghttpd?).  Have you tried this with Firefox?  It has better HTTP/2 resource prioritization, and it can improve the situation.

**Comment by dman777** [comment]
With Firefox it is significantly worse than chrome. I am using the nghttp init.d script, where I see `DAEMON_ARGS="--conf /etc/nghttpx/nghttpx.conf --pid-file=$PIDFILE --daemon"`. Here is my nghttp config:

```
one@ip-172-31-12-86:/etc/nginx$ cat /etc/nghttpx/nghttpx.conf
frontend=0.0.0.0,443
backend=127.0.0.1,8080
tls-proto-list=TLSv1.2
private-key-file=/etc/nginx/ssl/resume.key
certificate-file=/etc/nginx/ssl/resume.crt
accesslog-file=/var/log/nghttpx/access.log
errorlog-file=/var/log/nghttpx/error.log
add-x-forwarded-for=yes
max-header-fields=200
```

**Comment by tatsuhiro-t** [comment]
I'd like to reproduce your configuration in my own PC.
Can I access your site so that I can see what's going on in my browser?
I think you are using Link header fields to initiate push. Can you show us what they're like?
nghttpx v1.7.0 improved resource priority handling, so if you are using older version, try the latest version.

Since total time with HTTP/2 push is smaller than the one without push (4.99s vs 5.79s), I guess this could be contention inside one HTTP/2 connection, and resources chrome considers critical are pushed back because of pushed non-critical images.

**Comment by dman777** [comment]
Sure, the [site link headers file is here](https://github.com/dman777/resume/blob/master/nginx_config/sites/resume_headers)

I will need to move a website off of the server to use http2 push because it also listens on port 443. I will get this done tonight and let you know when it's ready. Thanks!

**Comment by dman777** [comment]
Ok, I wasn't sure if you wanted to clone the site manually or wanted to load the site from my browser....I switched it to http2 push at www.darinhensley.com. If you need anything else, please let me know. Thanks!

**Comment by tatsuhiro-t** [comment]
Thank you.  I accessed to your site with chrome, and found that pushed version is 2 times faster than HTTP/1 (https) version.  Currently, we only consider js and css to interleave them to the parent resource.  It looks like polymer uses HTML files to do some styling.  If pushing HTML is common usecase in plymer, then we'd like to consider to interleave HTML as well as js and css.

This is not a cause of this issue, but it would be better not to set Link preload header to pushed resources.  Possibly, consider to set them in main (landing) html or something.

**Comment by dman777** [comment]
Thank you very much for your help. I'm novice in this discipline, if I may ask please....  HTML is the most common use case in polymer....it would be 90% of the web app. When you say say:

> we only consider js and css to interleave them to the parent resource

1. Does that mean nghttpx push is built to utilize js and css but not html? 
2. Is the parent resource index.html which requests the files? 
3. What is `interleave` when you say `consider to interleave HTML as well as js and css.`?

>  it would be better not to set Link preload header to pushed resources. Possibly, consider to set them in main (landing) html or something

I am under the impression to push resources they need to have the link preload header in nginx. Do you mean not to push html files but push  only the js and css files?

**Comment by tatsuhiro-t** [comment]
> 1. Does that mean nghttpx push is built to utilize js and css but not html?

nghttpx pushes all kind of resources.  js and css resources that are pushed just get higher priority.
Pushed HTML resources is normal priority, which is lower than js and css initially.

> 2. Is the parent resource index.html which requests the files?

Yes, we call index.html which initiates bunch of pushes parent.  We also call it associated resource.

> 3. What is interleave when you say consider to interleave HTML as well as js and css.?

It means we send parent HTML and pushed js and css in the same priority.

> I am under the impression to push resources they need to have the link preload header in nginx. Do you mean not to push html files but push only the js and css files?

No.  Attach Link header fields to only index.html, and don't set them in pushed resources.

**Comment by dman777** [comment]
Closing issue as it could be many variables. Thank you for the extraordinary information!
