### ISSUE TITLE
ASIO integration

### ISSUE THREAD

**Issue by clemahieu** [nghttp2/nghttp2#506]
Thanks for making this library, so far it's been very easy to use.  I use ASIO a lot in my own programs and I was wondering if I submitted some pull requests if they'd be accepted.

I'm using another HTTP library right now and one thing I wanted to get away from was incorrect usage of ASIO specifically around threadpools.  I'm finding this server implementation also uses threadpools internally as well, removing my reason to switch to this library.

When using ASIO if thread pools are needed it's left up to the user to dispatch to their own threadpool instead of the library itself making the pool; this is the same reason io_service doesn't have a thread pool.

There seem to also be some possible race conditions between initiating a connection and setting up handlers like session/on_connect/on_error.  If an error or connection completes before setting up the handlers it visually appears as if those events would be lost.

**Comment by tatsuhiro-t** [comment]
Contribution is always welcome.  I got similar voice before about current threadpool design.
If you have patches, feel free to submit PR.  We can discuss there.  libnghttp2_asio is still in experimental, so we can take incompatible changes if it improves usability a lot.

**Comment by martijnotto** [comment]
I have a similar issue. I wish to use this library, but not only does it create a threadpool (which is really not necessary in my application), I also do not see a way to attach it to my existing io_service.

Is anybody working on this already?

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
