### ISSUE TITLE
ASIO client performance

### ISSUE THREAD

**Issue by rmongia** [nghttp2/nghttp2#525]
I am trying to try a C++ based load generator client using nghttp's asio client library. I noticed a significant difference in the RPC my tool generates when using:
- io_service.run() 
  vs
- while(1) { io_service.poll() }

Now the second one obviously spins the CPU so is not very desirable. I am using a single session to send multiple requests. 

What do you think could be the issue with io_service.run()?

**Comment by tatsuhiro-t** [comment]
This is boost asio specific question, and I'm not expert about boost io_service performance.
I imagine that io_service.poll() will calling boost library very often, so some kind of overhead is expected.  On the other hand, io_service.run() is completely boost territory, and they can freely schedule their callback, and could be low overhead.

**Comment by rmongia** [comment]
Thanks for a quick response.

What I have observed is that there is a delay in the event (socket read/write) being signaled to the io_serivce. Could it be that even though the socket is read-ready (or write-ready), io_service is not informed about it immediately? 

Ideally there shouldn't be any difference in polling the io_service Vs calling run() on it.

**Comment by tatsuhiro-t** [comment]
I agree.  The thing is io_service is boost asio module, and not something we can change easily.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
