### ISSUE TITLE
Using nghttp2 with Apache 2.4 and ProxyPass

### ISSUE THREAD

**Issue by smirkybg** [nghttp2/nghttp2#531]
Hello,

Here's my environment's details:
OS: Archlinux x86_64
HTTP Server: Apache (httpd)
nghttp2 info:

```
 0 « root » ~ » pacman -Q nghttp2
nghttp2 1.8.0-2
```

httpd.conf definition:

```
LoadModule http2_module modules/mod_http2.so
..
Protocols h2 http/1.1
```

httpd-ssl.conf definition:
`ProxyPass /mpd.ogg http://localhost:8000/`

The problem is that I'm using mpd (the music player daemon server) to stream music.
Since it's important for me to be under https:// I use ProxyPass to redirect the stream through HTTPS.
If I use HTTP2 and play the stream, no more connections are able to be handled by the apache for that particular IP until I close the player which plays the stream. However, another IP can reach the Apache server normally.

EDIT:

I got it all wrong, it's not per IP, it's per some weird browser session.
For example, if I open up a second tab and try to access any of the vhosts (same or different one), they all seem to take forever in attempt to load anything.
However, if I open up another browser, it works!
Tested with Chromium and Firefox.
If I open Chromium with Incognito mode as a second instance, it will work too.
This is a very weird problem.

**Comment by tatsuhiro-t** [comment]
Are you using nghttpx?  Could you tell us its command-line or configuration?

**Comment by smirkybg** [comment]
I'm not that familiar but I assume I do use it? The config file is most likely this:
```
  0 « root » /home/smirky » ll /etc/nghttpx/nghttpx.conf 
-rw-r--r-- 1 root root 911  2 мар 20,14 /etc/nghttpx/nghttpx.conf
```
It's empty:
```
 0 « root » /home/smirky » cat /etc/nghttpx/nghttpx.conf 
#
# Sample configuration file for nghttpx.
#
# * Line staring '#' is treated as comment.
#
# * The option name in the configuration file is the long command-line
#   option name with leading '--' stripped (e.g., frontend). Put '='
#   between option name and value. Don't put extra leading or trailing
#   spaces.
#
# * The options which do not take argument in the command-line *take*
#   argument in the configuration file. Specify 'yes' as argument
#   (e.g., http2-proxy=yes). If other string is given, it disables the
#   option.
#
# * To specify private key and certificate file, use private-key-file
#   and certificate-file. See the examples below.
#
# * conf option cannot be used in the configuration file. It will be
#   ignored.
#
# Examples:
#
# frontend=0.0.0.0,3000
# backend=127.0.0.1,80
# private-key-file=/path/to/server.key
# certificate-file=/path/to/server.crt
# http2-proxy=no
# workers=1
```

**Comment by smirkybg** [comment]
Just to mention, this is still present even in the latest apache and nghttp2 versions:
apache 2.4.23-1
nghttp2 1.13.0-1

The problem can be reproduced every single time.
Example:
1) Setup a mpd server and set it to stream something over http on a particular port
2) Setup apache with mod_http2.so
3) Setup a ProxyPass in the httpd.conf to Proxy over https:// on a hardcoded path. Let's say https://mywebsite/mpd.ogg
4) Open up a browser, start listening on https://mywebsite/mpd.ogg
5) Open up a new tab on the same browser (NOTE same!) and try to connect to the webserver in any form and experience a never ending connection attempt.

Weird side effects:
If I open up another browser or just curl or wget a webpage (counts as a different client), the content is reachable.
This only happens with browsers though. This narrows it down in a weird way, perhaps they share some resources between tabs and connections just can't get through if I do this.
Tested on Firefox and Chrome (Chromium).

**Comment by tatsuhiro-t** [comment]
It could be an issue on Apache side.  Could you raise an issue in Apache bug tracker?

**Comment by smirkybg** [comment]
There wont be a point in doing that because:
1) Apache 2.5 isn't yet released
2) I haven't still haven't tested in any other webserver, such as nginx.
