### ISSUE TITLE
Nothing Happens with basic example with high level C++ api

### ISSUE THREAD

**Issue by wdavilaneto** [nghttp2/nghttp2#532]
```
#include <iostream>
#include <nghttp2/asio_http2_server.h>
using namespace nghttp2::asio_http2;
using namespace nghttp2::asio_http2::server;
int main(int arg, char *argv[]) {
    http2 server;
    server.num_threads(12);
    server.handle("/", [](const request &req, const response &res) {
        res.write_head(200);
        res.end("hello, world\n");
    });
    try {
        boost::system::error_code ec;
        if (server.listen_and_serve(ec, "localhost", "8000")) {
            std::cerr << "error: " << ec.message() << std::endl;
        }
    } catch (const std::exception &e) {
        std::cout << e.what() << std::endl;
    }
};
```

On ubuntu I've first tryed to link only nghttp2_asio and the LD reported  undefined reference to symbol 'SSL_load_error_strings@@OPENSSL_1.0.0'. 

Then I've added  ssl and crypto on target_link_libraries. Then everything compiles ok and run with no Erros.. But.. Servers give's me no response at all. Even hit break point on server.handle.

**Comment by wdavilaneto** [comment]
Was this tested on ubuntu ? Is origin/master supporting high level api ?

**Comment by tatsuhiro-t** [comment]
I normally develop nghttp2 on Debian, and so ubuntu should work too.
Have you tried examples/asio-sv and examples/asio-sv2? They are asio examples.
It looks like Debian/ubuntu boost is very sensitive to compiler chain.  As far as I know, it only works when it is compiled with gcc + libstdc++.

**Comment by wdavilaneto** [comment]
I'm using boost 1.59.
nither examples have any response too. I"ve compile nghttp2 with gcc + libstdc++.

`configure: summary of build options:

    Package version: 1.9.0-DEV
    Library version: 19:0:5
    Install prefix:  /usr/local
    System types:
      Build:         x86_64-unknown-linux-gnu
      Host:          x86_64-unknown-linux-gnu
      Target:        x86_64-unknown-linux-gnu
    Compiler:
      C compiler:     gcc
      CFLAGS:         -g -O2
      LDFLAGS:        
      C++ compiler:   g++
      CXXFLAGS:       -g -O2
      CXXCPP:         g++ -E
      C preprocessor: gcc -E
      CPPFLAGS:       
      WARNCFLAGS:     
      CXX1XCXXFLAGS:   -std=c++11
      EXTRACFLAG:     -fvisibility=hidden
      LIBS:           
    Library:
      Shared:         yes
      Static:         yes
    Python:
      Python:         /usr/bin/python
      PYTHON_VERSION: 2.7
      pyexecdir:      ${exec_prefix}/lib/python2.7/dist-packages
      Python-dev:     yes
      PYTHON_CPPFLAGS:-I/usr/include/python2.7
      PYTHON_LDFLAGS: -L/usr/lib -lpython2.7
      Cython:         cython
    Test:
      CUnit:          yes (CFLAGS='' LIBS='-lcunit')
      Failmalloc:     yes
    Libs:
      OpenSSL:        yes (CFLAGS=' ' LIBS='-lssl -lcrypto  ')
      Libxml2:        yes (CFLAGS='-I/usr/include/libxml2' LIBS='-lxml2')
      Libev:          yes (CFLAGS='' LIBS='-lev')
      Libevent(SSL):  yes (CFLAGS=' ' LIBS='-levent_openssl -levent  ')
      Spdylay:        yes (CFLAGS='-I/usr/local/include  ' LIBS='-L/usr/local/lib -lspdylay  ')
      Jansson:        yes (CFLAGS=' ' LIBS='-ljansson  ')
      Jemalloc:       yes (LIBS='-ljemalloc')
      Zlib:           yes (CFLAGS=' ' LIBS='-lz  ')
      Boost CPPFLAGS: -pthread -I/usr/include
      Boost LDFLAGS:  -L/usr/lib/x86_64-linux-gnu
      Boost::ASIO:    -lboost_system
      Boost::System:  -lboost_system
      Boost::Thread:  -lboost_thread
    Third-party:
      http-parser:    yes
      MRuby:          no (CFLAGS='' LIBS='')
      Neverbleed:     no
    Features:
      Applications:   yes
      HPACK tools:    yes
      Libnghttp2_asio:yes
      Examples:       yes
      Python bindings:yes
      Threading:      yes
`

**Comment by minaevmike** [comment]
Did you try to get your page via browser? you should notice that browsers supprots only tls http2.

**Comment by wdavilaneto** [comment]
I was trying via Postman and with curl...

**Comment by tatsuhiro-t** [comment]
curl only supports HTTP/2 over cleartext TCP via HTTP Upgrade which libnghttp2_asio does not support.

Try TLS in libnghttp2_asio, and access it with https URI.

**Comment by cmorse** [comment]
@tatsuhiro-t Are there any plans to add support for HTTP/1.1 to libnghttp2_asio?

**Comment by tatsuhiro-t** [comment]
@cmorse No, there is no plan to add HTTP/1.1 to libnghttp2_asio library.

**Comment by pkoretic** [comment]
@tatsuhiro-t can you maybe share what else      is missing from libnghttp2_asio? 

Seems like a very nice abstraction that took time and I was under impression that it has same feature set as underlying C library. 
I'm curious if this is something that is properly supported and could be used as a base for C++ frameworks? Thanks

**Comment by msinev** [comment]
Same issue - empty reply - connection closed with 0 byte reply.
Ubuntu 16.04. Compiled and installed as described in manual.  
Boost 1.58 from ubuntu. I have had issues with ubuntu's bundled boost some time in the past with different project. Have had no time to check yet thought.

**Comment by sunsided** [comment]
For curl, you can use the `--http2-prior-knowledge` option, e.g. using

```bash
curl --http2-prior-knowledge http://localhost:8000/
```

This way, curl won't attempt to upgrade the connection.

**Comment by JohnGalbraith** [comment]
So I am tooling around way out of my expertise here, and floundered around for an hour on this issue as well.  I am on Arch.  I fixed this (I think) by studying the nghttp2_asio example for long enough: `asio_sv.cc` and discovered that the documentation example appears to configure TLS, but does not actually *use* it.  This is probably a typo in the documentation, but my level of understanding here is still superficial at best.

This, for me, made a big difference.  Change:

```if (server.listen_and_serve(ec, "localhost", "3000")) {...}```

to 

```if (server.listen_and_serve(ec, tls, "localhost", "3000")) {...}```

and new things start to happen.   Good things.

**Comment by op-Valar-Morghulis** [comment]
> So I am tooling around way out of my expertise here, and floundered around for an hour on this issue as well. I am on Arch. I fixed this (I think) by studying the nghttp2_asio example for long enough: `asio_sv.cc` and discovered that the documentation example has a subtle difference between the first "bare bones" example and the second, TLS example. It is easy to miss this change, I and sure did.
> 
> This, for me, made a big difference. Change:
> 
> `if (server.listen_and_serve(ec, "localhost", "3000")) {...}`
> 
> which is from the top example, to
> 
> `if (server.listen_and_serve(ec, tls, "localhost", "3000")) {...}`
> 
> from the second and new things start to happen. Good things.

I could not deploy the bare example neither on my local server nor my cloud server. 
But if I add tls verification, it does work!
However, I could not figure out what made change to this.So if the bare example does not work, add tls parameter.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
