### ISSUE TITLE
Implement ALT-SVC

### ISSUE THREAD

**Issue by tatsuhiro-t** [nghttp2/nghttp2#535]
[ALT-SVC](http://httpwg.org/http-extensions/alt-svc.html) has been approved by IESG for publication as a Proposed Standard.
nghttp2 previously implemented ALT-SVC when it was in HTTP/2 specification, but we dropped it from nghttp2 source code when it was removed from HTTP/2 spec.  Now its frame payload is quite simplified, and we don't reuse the old code.

We only support ALT-SVC via HTTP/2 frame.  We don't parse alt-svc header field.

We have enabled user-defined extension mechanism already.  Since nghttp2 has no knowledge about user-defined frame, it just calls a callback provided by application to decode the frame.  To enable this, application has to set the frame type using `nghttp2_option_set_user_recv_extension_type()`.

So if we just enable ALT-SVC, and steals its handling from application while application provides its implementation through above mechanism, it is not backward compatible.  Therefore, we disables ALT-SVC (and future extension frame) by default.  To enable them, application has to tell the library so using new option call similar to `nghttp2_option_set_user_recv_extension_type()`.  User defined extension always takes precedence.

The question is that we should parse `Alt-Svc-Field-Value` in ALTSVC frame.  It is essentially the header field value of alt-svc header field.  Currently, I'm leaning toward not to parse them because application typically has its own parser for alt-svc (since it may support HTTP/1.1 as well).

**Comment by LPardue** [comment]
> The question is that we should parse Alt-Svc-Field-Value in ALTSVC frame. It is essentially the header field value of alt-svc header field. Currently, I'm leaning toward not to parse them because application typically has its own parser for alt-svc (since it may support HTTP/1.1 as well).

I tend to agree, leave this out of nghttp2 and allow the applications to handle what to do with the value.

Are you considering how nghttp and nghttpx might support Alt-Svc yet? The client-side seems to be more difficult than the server-side from my investigations.

**Comment by tatsuhiro-t** [comment]
For nghttpx, we have already alt-svc related options, and we can send ALTSVC frame when they are set.
For nghttp, yes, it is a bit complicated in client side, but nghttp is mostly used as debugging purpose, and ALTSVC is sent from server only, so it will just show the frame debug output.

**Comment by LPardue** [comment]
Ok thanks for the clarification

**Comment by tatsuhiro-t** [comment]
I'd wait for the publication of RFC, so this might be rescheduled v1.11.0 or later.
The actual work has begun already.

**Comment by tatsuhiro-t** [comment]
ALTSVC support was landed as of 9028512a5fad765ff3d4da8f45f6411ab931a4b9.
nghttp2's ALTSVC support is just send and receive frames.  Most of the interesting work should be done by the application.

To send ALTSVC, use `nghttp2_submit_altsvc()`.
To receive ALTSVC, use `nghttp2_option_set_builtin_recv_extension_type(option, NGHTTP2_ALTSVC)`, and use that option to initialize `nghttp2_session` with `nghttp2_session_client_new2()` or `nghttp2_session_client_new3()`.

nghttp client will print out the content of ALTSVC frame with -v option.
