### ISSUE TITLE
Query String not passed to backend from nghttpx

### ISSUE THREAD

**Issue by webeau** [nghttp2/nghttp2#540]
I pulled the latest from github, built and ran tests.  Everything passed but I am using nghttpx to proxy to nginx and Wordpress.  Wordpress was not seeing and incoming query string.

I rebuilt using 1.8.0 release, ran tests, and installed and now he query strings are reaching the backend server.

Appears to be a problem passing query strings to backend with current github pull.

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this bug.  This was fixed in 0140820.

**Comment by tatsuhiro-t** [comment]
v1.9.1 has this fix.

**Comment by kaziqta** [comment]
not working in 1.27.0,

see: https://www.djentmag.com/webmail <- doesn't work
