### ISSUE TITLE
long poll connection

### ISSUE THREAD

**Issue by minaevmike** [nghttp2/nghttp2#545]
is it possible to implement a long polling connection to http2 server via asio_client(with auto reconnects ans so on)? Mb it should be a part of lib?

**Comment by tatsuhiro-t** [comment]
In HTTP/2 context, TCP connection itself is long lived.  I'm not sure about long polling in the context of HTTP/2.  Could you describe a bit more of "long polling connection"?

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
