### ISSUE TITLE
Can't find python model,ImportError: No module named 'nghttp2'

### ISSUE THREAD

**Issue by sunzhaoyang** [nghttp2/nghttp2#546]
` nghttp2 git:(master) sudo ./configure --disable-threads  PYTHON=/usr/local/Cellar/python3/3.5.1/bin/python3 
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define **EXTENSIONS**... yes
checking build system type... x86_64-apple-darwin15.3.0
checking host system type... x86_64-apple-darwin15.3.0
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm
checking the name lister (/usr/bin/nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin15.3.0 file names to x86_64-apple-darwin15.3.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin15.3.0 file names to toolchain format... func_convert_file_noop
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking command to parse /usr/bin/nm output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.3.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking target system type... x86_64-apple-darwin15.3.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common -DPIC
checking if g++ PIC flag -fno-common -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.3.0 dyld
checking how to hardcode library paths into programs... immediate
checking dependency style of g++... gcc3
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.20... yes
checking whether /usr/local/Cellar/python3/3.5.1/bin/python3 version is >= 2.7... yes
checking for /usr/local/Cellar/python3/3.5.1/bin/python3 version... 3.5
checking for /usr/local/Cellar/python3/3.5.1/bin/python3 platform... darwin
checking for /usr/local/Cellar/python3/3.5.1/bin/python3 script directory... ${prefix}/lib/python3.5/site-packages
checking for /usr/local/Cellar/python3/3.5.1/bin/python3 extension module directory... ${exec_prefix}/lib/python3.5/site-packages
checking for python3.5... /usr/local/Cellar/python3/3.5.1/bin/python3
checking for a version of Python >= '2.1.0'... yes
checking for a version of Python >= '2.7'... yes
checking for the distutils Python package... yes
checking for Python include path... -I/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/include/python3.5m
checking for Python library path... -lpython3.5m
checking for Python site-packages path... /usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages
checking python extra libraries... -ldl  -framework CoreFoundation
checking python extra linking flags... -u _PyMac_Error /usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/Python
checking consistency of all components of python development environment... no
configure: WARNING:
  Could not link test program to Python. Maybe the main Python library has been
  installed in some non-standard library path. If so, pass it to configure,
  via the LDFLAGS environment variable.
  Example: ./configure LDFLAGS="-L/usr/non-standard-path/python/lib"
  ============================================================================
   ERROR!
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.
  ============================================================================

checking for cython.py... no
checking for cython... no
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=c++11... yes
checking whether std::future is available... yes
checking whether std::map::emplace is available... yes
checking for ZLIB... yes
checking for library containing dlopen... none required
checking for CUNIT... yes
checking for ev_time in -lev... yes
checking ev.h usability... yes
checking ev.h presence... yes
checking for ev.h... yes
checking for OPENSSL... no
configure: Requested 'openssl >= 1.0.1' but version of OpenSSL is 0.9.8zg
checking for LIBEVENT_OPENSSL... yes
checking for JANSSON... yes
checking for xml2-config... /usr/local/bin/xml2-config
checking for libxml - version >= 2.7.7... yes (version 2.9.3)
checking for library containing malloc_stats_print... no
checking for library containing je_malloc_stats_print... no
checking for LIBSPDYLAY... yes
checking whether to enable assertions... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking pwd.h usability... yes
checking pwd.h presence... yes
checking for pwd.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking for unistd.h... (cached) yes
checking for size_t... yes
checking for ssize_t... yes
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for int8_t... yes
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for off_t... yes
checking for pid_t... yes
checking for uid_t in sys/types.h... yes
checking for ptrdiff_t... yes
checking whether byte ordering is bigendian... no
checking for inline... inline
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for struct tm.tm_gmtoff... yes
checking size of int *... 8
checking size of time_t... 8
checking for unistd.h... (cached) yes
checking for working chown... yes
checking for error_at_line... no
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking whether strerror_r is declared... yes
checking for strerror_r... yes
checking whether strerror_r returns char *... no
checking for working strnlen... yes
checking for _Exit... yes
checking for accept4... no
checking for dup2... yes
checking for getcwd... yes
checking for getpwnam... yes
checking for localtime_r... yes
checking for memchr... yes
checking for memmove... yes
checking for memset... yes
checking for socket... yes
checking for sqrt... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strndup... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoul... yes
checking for timegm... yes
checking for timerfd_create... no
checking whether initgroups is declared... yes
checking linux/version.h usability... no
checking linux/version.h presence... no
checking for linux/version.h... no
checking for Linux epoll(7) interface... no
checking whether C compiler accepts -fvisibility=hidden... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating lib/Makefile
config.status: creating lib/libnghttp2.pc
config.status: creating lib/includes/Makefile
config.status: creating lib/includes/nghttp2/nghttp2ver.h
config.status: creating tests/Makefile
config.status: creating tests/testdata/Makefile
config.status: creating third-party/Makefile
config.status: creating src/Makefile
config.status: creating src/includes/Makefile
config.status: creating src/libnghttp2_asio.pc
config.status: creating examples/Makefile
config.status: creating python/Makefile
config.status: creating python/setup.py
config.status: creating integration-tests/Makefile
config.status: creating integration-tests/config.go
config.status: creating integration-tests/setenv
config.status: creating doc/Makefile
config.status: creating doc/conf.py
config.status: creating doc/index.rst
config.status: creating doc/package_README.rst
config.status: creating doc/tutorial-client.rst
config.status: creating doc/tutorial-server.rst
config.status: creating doc/tutorial-hpack.rst
config.status: creating doc/nghttpx-howto.rst
config.status: creating doc/h2load-howto.rst
config.status: creating doc/libnghttp2_asio.rst
config.status: creating doc/python-apiref.rst
config.status: creating doc/building-android-binary.rst
config.status: creating doc/nghttp2.h.rst
config.status: creating doc/nghttp2ver.h.rst
config.status: creating doc/asio_http2.h.rst
config.status: creating doc/asio_http2_server.h.rst
config.status: creating doc/asio_http2_client.h.rst
config.status: creating doc/contribute.rst
config.status: creating contrib/Makefile
config.status: creating script/Makefile
config.status: creating config.h
config.status: executing libtool commands
config.status: executing depfiles commands
configure: summary of build options:

```
Package version: 1.9.0-DEV
Library version: 19:0:5
Install prefix:  /usr/local
System types:
  Build:         x86_64-apple-darwin15.3.0
  Host:          x86_64-apple-darwin15.3.0
  Target:        x86_64-apple-darwin15.3.0
Compiler:
  C compiler:     gcc
  CFLAGS:         -g -O2
  LDFLAGS:
  C++ compiler:   g++
  CXXFLAGS:       -g -O2
  CXXCPP:         g++ -E
  C preprocessor: gcc -E
  CPPFLAGS:
  WARNCFLAGS:
  CXX1XCXXFLAGS:   -std=c++11
  EXTRACFLAG:     -fvisibility=hidden
  LIBS:
Library:
  Shared:         yes
  Static:         yes
Python:
  Python:         /usr/local/Cellar/python3/3.5.1/bin/python3
  PYTHON_VERSION:
  pyexecdir:      ${exec_prefix}/lib/python3.5/site-packages
  Python-dev:     no
  PYTHON_CPPFLAGS:-I/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/include/python3.5m
  PYTHON_LDFLAGS: -lpython3.5m
  Cython:
Test:
  CUnit:          yes (CFLAGS='-I/usr/local/Cellar/cunit/2.1-3/include' LIBS='-L/usr/local/Cellar/cunit/2.1-3/lib -lcunit -lncurses')
  Failmalloc:     yes
Libs:
  OpenSSL:        no (CFLAGS='' LIBS='')
  Libxml2:        yes (CFLAGS='-I/usr/local/Cellar/libxml2/2.9.3/include/libxml2' LIBS='-L/usr/local/Cellar/libxml2/2.9.3/lib -lxml2 -lz -lpthread -liconv -lm')
  Libev:          yes (CFLAGS='' LIBS='-lev')
  Libevent(SSL):  yes (CFLAGS='-I/usr/local/Cellar/libevent/2.0.22/include' LIBS='-L/usr/local/Cellar/libevent/2.0.22/lib -levent_openssl -levent')
  Spdylay:        yes (CFLAGS='-I/usr/local/Cellar/spdylay/1.3.2/include' LIBS='-L/usr/local/Cellar/spdylay/1.3.2/lib -lspdylay')
  Jansson:        yes (CFLAGS='-I/usr/local/Cellar/jansson/2.7/include' LIBS='-L/usr/local/Cellar/jansson/2.7/lib -ljansson')
  Jemalloc:       no (LIBS='')
  Zlib:           yes (CFLAGS='' LIBS='-lz')
  Boost CPPFLAGS:
  Boost LDFLAGS:
  Boost::ASIO:
  Boost::System:
  Boost::Thread:
Third-party:
  http-parser:    yes
  MRuby:          no (CFLAGS='' LIBS='')
  Neverbleed:     no
Features:
  Applications:   no
  HPACK tools:    yes
  Libnghttp2_asio:no
  Examples:       no
  Python bindings:no
  Threading:      no`
```

make and make install successes .

but can't import 

ImportError: No module named 'nghttp2'

**Comment by tatsuhiro-t** [comment]
This is because configure script failed to find python development library
```
Example: ./configure LDFLAGS="-L/usr/non-standard-path/python/lib"
============================================================================
ERROR!
You probably have to install the development version of the Python package
for your distribution. The exact name of this package varies among them.
============================================================================
```

**Comment by tatsuhiro-t** [comment]
Closed since python module has been removed.
