### ISSUE TITLE
The user callback function failed!

### ISSUE THREAD

**Issue by fatjimmy** [nghttp2/nghttp2#552]
I came across this error when I call nghttp2_session_mem_send. And following calls all failed with the same reason. So when I came across this error, should I terminate the session? By the way, what caused this error?

**Comment by tatsuhiro-t** [comment]
Generally, it means that application defined callback function returned NGHTTP2_ERR_CALLBACK_FAILURE or something not defined in nghttp2 API, and treated as error.
NGHTTP2_ERR_CALLBACK_FAILURE is used when application encountered fatal error, and would like to close HTTP/2 session immediately.  If that is not your case, it is probably programming error in your application.

**Comment by fatjimmy** [comment]
Here I didn't write any callback that would return NGHTTP2_ERR_CALLBACK_FAILURE. So if I had programming errors, how did nghttp2 know about that? Can you give me some examples to explain what kind of programming error it is ?

**Comment by tatsuhiro-t** [comment]
nghttp2 callback functions define their own return value semantics.  For example, nghttp2_on_frame_recv_callback only accepts return value 0 as success.  Returning nonzero value is treated as NGHTTP2_ERR_CALLBACK_FAILURE.  Another example, nghttp2_on_begin_headers_callback can accept  0, NGHTTP2_ERR_TEMPORAL_CALLBACK_FAILURE, and NGHTTP2_ERR_CALLBACK_FAILURE.  Returning any other value is treated as NGHTTP2_ERR_CALLBACK_FAILURE.
These return values are described in API reference manual.
So could you check your implementation about these return values?

**Comment by fatjimmy** [comment]
I finally found the problem. It's the read_callback function of nghttp2_data_provider struct. I didn't check the data size, which should be smaller than "length". If not, nghttp2_session_mem_send would return NGHTTP2_ERR_CALLBACK_FAILURE.
