### ISSUE TITLE
creating session

### ISSUE THREAD

**Issue by minaevmike** [nghttp2/nghttp2#560]
```
m_session.reset(new nghttp2::asio_http2::client::session(m_service, tls, m_host, m_port, m_timeout));
m_session->on_error(...);
m_session->on_connect(...);
```

when i am creating session in constructor it automatically starting connecting to endpoint(with resolving). If it happens to fast there is chance that on_connect() setter would be called after connect and i would never known that i am already connected to server.
So mb add additional parameter to session constructor or add method to session like `init`

**Comment by tatsuhiro-t** [comment]
My assumption is that m_service is not running when we create session.  After setting callbacks, we call m_service.run(), which actually will call callbacks.  Do you think this assumption is wrong?

**Comment by minaevmike** [comment]
In my case it's wrong. I have server(not http2). And this server, sometimes, must send request to http2 server. So i can't create io_service for each request.

**Comment by tatsuhiro-t** [comment]
Thank you for the reply.  I think we can use running io_service in the existing interface as long as the creation and on_error and on_connect are called in the same thread io_service is running (probably we can use post method of io_service).  Since we are same thread with io_service, callback functions never be invoked.

**Comment by minaevmike** [comment]
But even if we are in same thread of io_service callback of async_resolve could be called in other thread of io_service(if we run it in more then 1 thread) so possible result
so this code could be run like this
```
m_session.reset(new nghttp2::asio_http2::client::session(m_service, tls, m_host, m_port, m_timeout));
m_session->on_error(...);
m_session->on_connect(...);
```
```
 Thread 1                                                        Thread 2
new session
       |                                                              |
       |                                                              |
       v                                                              |
async_resolve(async_cb)                                               |
       |                                                          async_cb()
       |                                                          on_connect()
       v
session.on_connect()
```
I know that it is unlikely that it will work like that, but there is a little chance.

**Comment by tatsuhiro-t** [comment]
I meant the following code:

```
io_service.post([&io_service]() {
    auto sess = new session(io_service, ...);
    sess->on_connect(...);
});
```
post method guarantees that the callback is executed in the same thread that io_service is running.
If I understand correctly, callback of async_resolve is executed in the same thread of io_service.
Is it really true that async_resolve callback is executed by another unrelated thread?
If so, entire nghttp2 asio library is broken.

**Comment by minaevmike** [comment]
As i know if you run io_service in `n` thrads, callback will be executed in one of the `n` threads, where you call `io_service.run()`. http://www.boost.org/doc/libs/1_56_0/doc/html/boost_asio/reference/io_service/run/overload2.html
`Multiple threads may call the run() function to set up a pool of threads from which the io_service may execute handlers. All threads that are waiting in the pool are equivalent and the io_service may choose any one of them to invoke a handler.`

**Comment by tatsuhiro-t** [comment]
Thanks.  libnghttp2_asio is not compatible with boost thread pool.  It expects that its callbacks are called in one specific thread.

**Comment by minaevmike** [comment]
Please, can you explain your answer more detailed?

**Comment by tatsuhiro-t** [comment]
I'm not sure how to explain everything, but in essence, all callbacks must be invoked in the same thread in which session is created.  Creating session in one thread, and its async_resolve callback is called in the another thread is not acceptable in libnghttp2_asio lib.   They must be executed in the same thread, while they are invoked, its underlying io_service should be blocked.

**Comment by advservice** [comment]
I have some issue!

**Comment by Gerz-inc** [comment]
I have some issue!

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
