### ISSUE TITLE
nghttpx: Detect backend's online and offline status

### ISSUE THREAD

**Issue by tatsuhiro-t** [nghttp2/nghttp2#566]
nghttpx supports multiple backend addresses per routing pattern, and they are used as load balancing.  When nghttpx failed to connect one of the backend address, it marks it as bad, and don't use it for a while (we use exponential backoff timeout scheme here).

Using this existing mechanism, we can say that backend is offline if we observed that backend is failing constantly in a row.  It is usually difficult to say this in confidence.  We will add an option to specify how many times we can retry the failing backend, and if the threshold is exceeded, it is considered offline.  It is also hard to detect that it is back to online.  We will periodically attempt to connect to the offline backend.  If we can connect to it, we assume that it is back to online.

**Comment by fcicq** [comment]
it would be nice if you use haproxy style rise / fall config.

**Comment by tatsuhiro-t** [comment]
Thank you for the suggestion.  It looks good.

**Comment by proteneer** [comment]
This is really exciting for us! We're looking forward to seeing it work. As a starting point, gRPC has published its canonical algorithm for detection and reconnection, and has worked quite well for us.

https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md

The jittering presumably is to allow an even, randomly distributed re-connections so as to not to overwhelm the backend servers all at once.

**Comment by tatsuhiro-t** [comment]
Thanks.  We have already use exponential backoff, but the gRPC version looks very nice.

**Comment by tatsuhiro-t** [comment]
Should we need to consider the HTTP status code from backend when we decide that they are offline or online?  For example, if backend returns 5xx repeatedly, they are considered as offline, and we need non-5xx response from backend to consider they are online again.

For the sake of the completeness, probably they are required, or nice to have.  So the question is whether we can just get it done without HTTP status code.

**Comment by proteneer** [comment]
Hm, for us we only ever return 2xx and 4xx error codes. However that
denotes that the backend is still up. When the backend is down, the
connections are simply refused. But I'm not sure what other people are
doing.

On Wednesday, April 6, 2016, Tatsuhiro Tsujikawa <notifications@github.com>
wrote:

> Should we need to consider the HTTP status code from backend when we
> decide that they are offline or online? For example, if backend returns 5xx
> repeatedly, they are considered as offline, and we need non-5xx response
> from backend to consider they are online again.
>
> For the sake of the completeness, probably they are required, or nice to
> have. So the question is whether we can just get it done without HTTP
> status code.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/nghttp2/nghttp2/issues/566#issuecomment-206365961>
>


-- 
Yutong Zhao

**Comment by tatsuhiro-t** [comment]
Thank you for quick reply.  Probably we can first do connection based online/offline detection first, since this is the immediate use case for us.  We may expand this feature so that it can use HTTP status code to adopt more broad use case (if any)

**Comment by proteneer** [comment]
We should be thanking you for looking into this :)

On Wed, Apr 6, 2016 at 11:25 AM, Tatsuhiro Tsujikawa <
notifications@github.com> wrote:

> Thank you for quick reply. Probably we can first do connection based
> online/offline detection first, since this is the immediate use case for
> us. We may expand this feature so that it can use HTTP status code to adopt
> more broad use case (if any)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/nghttp2/nghttp2/issues/566#issuecomment-206426258>
>



-- 
Yutong Zhao

**Comment by tatsuhiro-t** [comment]
We have implemented connection based online/offline detection.  We added 2 options: --backend-fall and --backend-raise, they are analogous to fall and rise parameter found in haproxy.

**Comment by fcicq** [comment]
@tatsuhiro-t it is best if rise / fall are per-backend properties, but I see it is a little hard to write the configurations as command line parameters, it is acceptable that some settings will be only available in the config file. I should point out that global rise / fall settings will only suit for same-workload groups.

Ah. rise and fall is not a "X in a row" setting.
First, set the initial state as UP and a score of 0. a successful attempt add one to the score, while a failed try do a minus one.

if the state is UP, the score is capped at 0 as max and -fall as min, if -fall is reached, set the state as DOWN and the score to 0.
if the state is DOWN, the score is capped at 0 as min and +rise as max, if +rise is reached, set the state as UP and the score to 0.

**Comment by tatsuhiro-t** [comment]
Thank you for the comment.
We will make rise/fall parameters configurable in --backend option.

As for the behaviour of rise and fall, I think "X in a row" is more suitable to detect offline/online state since we would like to be sure that they are really working good or not.  Just increment/ decrement could be flaky in some situation.  We'd like to keep the current behaviour, but it is a bit internal specification, so we may adopt haproxy style in the future if the current semantics is really bad.

**Comment by tatsuhiro-t** [comment]
Now rise/fall are parameters in --backend option.

**Comment by fcicq** [comment]
@tatsuhiro-t FYI. the original rise and fall idea is able to mark the backends with long term success rate > 50% as UP and < 50% as DOWN (should use binomial distribution to calculate the actual value?). a much shorter window is used in "X in a row" style and probability calculation would be quite different. assume a fall value of 10, a backend with ~6.3% success rate (1-0.5^1/10) will be falsely marked as UP for 50% probability.

**Comment by fcicq** [comment]
@tatsuhiro-t Ah. X in a row is geometric distribution.

**Comment by tatsuhiro-t** [comment]
fall check will be done using exponential backoff, which is the mostly the same in gRPC in the above.
rise will be done 1.6 seconds +/- random millisecond offset.

I read haproxy configuration guide (http://www.haproxy.org/download/1.7/doc/configuration.txt), and they also use "consecutive" count for rise and fall:

```
fall <count>
  The "fall" parameter states that a server will be considered as dead after
  <count> consecutive unsuccessful health checks. This value defaults to 3 if
  unspecified. See also the "check", "inter" and "rise" parameters.

rise <count>
  The "rise" parameter states that a server will be considered as operational
  after <count> consecutive successful health checks. This value defaults to 2
  if unspecified. See also the "check", "inter" and "fall" parameters.
```

I thought that consecutive means "X in a row", but my understanding is wrong, or is it implemented otherwise?

**Comment by fcicq** [comment]
@tatsuhiro-t I'm sorry! it is me that wrongly understood the rise and fall logic. so the current implementation is right.

but anyway, I found the fact that using a large fall value (more than 5?) would be a bad idea for handling wonky backends, so the algorithm in my mind would become an alternate method with explicit expected prob value.

Sorry for the troubles.

**Comment by tatsuhiro-t** [comment]
The best value probably depends on the nature of the backend.  haproxy's  3 could be good default.
Please keep in touch with us, and create new issue if the current method does not work in practice.

**Comment by ManAgainstCode** [comment]
--backend-fall && --backend-rise not mentioned in the document: https://nghttp2.org/documentation/nghttpx.1.html

**Comment by tatsuhiro-t** [comment]
--backend-fall and --backend-rise options do not exist.
See rise and fall parameter in https://nghttp2.org/documentation/nghttpx.1.html#cmdoption-nghttpx-b
