### ISSUE TITLE
--backend-http-proxy-uri for h1 backends as well?

### ISSUE THREAD

**Issue by devlearner** [nghttp2/nghttp2#567]
> **--backend-http-proxy-uri=\<URI\>**
> Specify proxy URI in the form http://[\<USER\>:\<PASS\>@]\<PROXY\>:\<PORT\>. ...
> *This proxy is used when the backend connection is HTTP/2.* First, make a CONNECT request to the proxy and it connects to the backend on behalf of nghttpx. This forms tunnel. After that, nghttpx performs SSL/TLS handshake with the downstream through the tunnel. ...

now that the `--backend` option is unified with the `;proto=` keyword, shall we, perhaps, apply the http-proxy setting to h1 backends as well?

(which might be useful in some settings; and provide a more uniform experience across backends)

thanks a lot

**Comment by tatsuhiro-t** [comment]
The uniformity is nice.  I think this option is rather out of the place, and it is only useful in special case (and most likely people use HTTP/2 in this case).  So I'd rather leave this HTTP/2 only.

**Comment by devlearner** [comment]
Well i think it's a useful option and am currently using it with h2 backends :)
anyway thanks for considering it :)

**Comment by anup19** [comment]
This definitely is a very useful option. However, restricting it to h2 only backends appears to be a limitation in the use-case I am working on.

I am using nghttpx proxy to be the "edge" for a variety of backends that may or may not support HTTP/2. The "edge" nghttpx has to pass requests through a forward-proxy (squid) to be able to connect to the backends. Only squid has connectivity to the backends. (This is a security requirement). 

`--backend-http-proxy-uri` lets me get this setup work for backends that support HTTP/2. However, it does not work when the backend is HTTP/1.1 only. 

@tatsuhiro-t may I request this feature to be enabled for HTTP/1.1 as well? It would also bring uniformity as discussed before.
