### ISSUE TITLE
Building on Cygwin

### ISSUE THREAD

**Issue by bc-lee** [nghttp2/nghttp2#569]
With latest Cygwin environment(gcc=5.3.0), -std=C++11 option is not suitable for building nghttp2 and tools.
With -std=C++11 or C++0x options, Cygwin GCC defines `__STRICT_ANSI__`  and `_REENT_ONLY` macro and it affects some C functions that are not in ANSI standard. In https://github.com/ajaxorg/cygwin-builds/blob/master/usr/include/stdlib.h , one can check that several functions like `mkstemp` cannot be used with -std=C++11 options.
Changing ax_cxx_compile_stdcxx_11.m4 or some headers code can solve this problem.

**Comment by tatsuhiro-t** [comment]
Is this decision made by Cygwin? I could not find any reason why we cannot use mkstemp with C++11 compiler.

**Comment by bc-lee** [comment]
It is mainly due to cygwin uses newlib, not glibc. https://www.cygwin.com/ml/cygwin/2015-12/msg00167.html http://stackoverflow.com/questions/15944051/error-fdopen-was-not-declared-found-with-g-4-that-compiled-with-g3/15945702#15945702

**Comment by tatsuhiro-t** [comment]
Looks like newlib is doing something not right, isn't it?  It is absolutely no relation between __STRICT_ANSI__ and -std=c++11.  I don't understand why cygwin switched to that newlib in that kind of maturity.
