### ISSUE TITLE
should default next proto to h2,h2-14

### ISSUE THREAD

**Issue by jeffallen** [nghttp2/nghttp2#572]
Cloudflare supports only h2, not h2-14:

$ nghttp https://nella.org/
[ERROR] HTTP/2 protocol was not selected. (nghttp2 expects h2-14)
[ERROR] Could not connect to the host

nghttp does not allow me to set the next proto, so I cannot talk to servers that support only "h2".

**Comment by Micdu70** [comment]
Hello,

No issue for me:

$ nghttp -v https://nella.org/
[  0.002] Connected
The negotiated protocol: h2
[...]

Which version of nghttp2 do you have?

**Comment by jeffallen** [comment]
I have Debian's 0.6.4-2 package. It must be old. Sorry for the noise.

(It still would be nice to be able to set the next proto, but I can do that with h2i.)
