### ISSUE TITLE
Binaries should goto "bin" directory

### ISSUE THREAD

**Issue by raeesbhatti** [nghttp2/nghttp2#576]
Hey there, thanks for such an awesome project. But while building it on Cygwin, I noticed that the binaries were placed under the `src` directory. Which I think, is not right. The project binaries should go to a `bin` directory along with any DLLs, so that, we can easily move them somewhere else if we want to.

**Comment by tatsuhiro-t** [comment]
Thank you for the suggestion.  Are you using cmake build?  If so, due to my lack of knowledge of cmake, PR is appreciated to fix this issue.

**Comment by tatsuhiro-t** [comment]
Not sure about standard practice of cmake, but doesn't `make install` install binaries to /usr/local/bin?
