### ISSUE TITLE
nghttpx with 2 backend domains

### ISSUE THREAD

**Issue by Winzigweich** [nghttp2/nghttp2#580]
hello,
i have a problem with my nghttpx config.  when i call in browser the second domain (affilie.de) it redirect to my first domain (fruchthof24.de).

here is my config file:
user=root
workers=4
frontend=*,443
backend=212.227.252.236,4444;;proto=h2;tls
backend=2001:8d8:91e:aa00::1c:f946,4444;;proto=h2;tls
backend=217.160.108.85,4444;;proto=h2;tls
subcert=/opt/psa/var/certificates/cert-FhvkAw:/opt/psa/var/certificates/cert-FhvkAw
tls-proto-list=TLSv1.2,TLSv1.1,TLSv1.0
ciphers=ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
dh-param-file=/etc/ssl/certs/dhparam.pem
private-key-file=/opt/psa/var/certificates/cert-YX6ymS
certificate-file=/opt/psa/var/certificates/cert-YX6ymS
#accesslog-file=/var/log/nghttpx/access.log
#errorlog-file=/var/log/nghttpx/error.log
add-x-forwarded-for=yes
insecure=yes

in nginx directive the listen entry for my first domain is 212.227.252.236:4444 and 2001:8d8:91e:aa00::1c:f946:4444. for the second domain is 217.160.108.85:4444.

here is the start protokoll:
root@fruchthof24:~# service nghttpx restart
 * Restarting HTTP/2 reverse proxy nghttpx                                                                                                                      16/Apr/2016:13:29:28 +0200 PID7706 [FATAL] shrpx_worker_process.cc:154 IPC socket is closed.  Perform immediate shutdown.
16/Apr/2016:13:29:28 +0200 PID7741 [NOTICE] Resolved backend address: 212.227.252.236:4444 -> 212.227.252.236:4444
16/Apr/2016:13:29:28 +0200 PID7741 [NOTICE] Resolved backend address: [2001:8d8:91e:aa00::1c:f946]:4444 -> [2001:8d8:91e:aa00::1c:f946]:4444
16/Apr/2016:13:29:28 +0200 PID7741 [NOTICE] Resolved backend address: 217.160.108.85:4444 -> 217.160.108.85:4444
16/Apr/2016:13:29:28 +0200 PID7742 [NOTICE] Listening on 0.0.0.0, tls
16/Apr/2016:13:29:28 +0200 PID7742 [NOTICE] Listening on [::], tls
                                                                                                                                                         [ OK ]
root@fruchthof24:~# 16/Apr/2016:13:29:28 +0200 PID7742 [NOTICE] Worker process [7745] spawned
16/Apr/2016:13:29:28 +0200 PID7742 [NOTICE] Renew new ticket keys
16/Apr/2016:13:29:28 +0200 PID7742 [NOTICE] [LISTEN:0x7ffe162339e0] Created worker thread #0
16/Apr/2016:13:29:28 +0200 PID7742 [NOTICE] [LISTEN:0x7ffe162339e0] Created worker thread #1
16/Apr/2016:13:29:28 +0200 PID7742 [NOTICE] [LISTEN:0x7ffe162339e0] Created worker thread #2
16/Apr/2016:13:29:28 +0200 PID7742 [NOTICE] [LISTEN:0x7ffe162339e0] Created worker thread #3
fetch-ocsp-response (using OpenSSL 1.0.2f  28 Jan 2016)
sending OCSP request to http://gu.symcd.com
/opt/psa/var/certificates/cert-YX6ymS: good
        This Update: Apr 14 16:20:11 2016 GMT
        Next Update: Apr 21 16:20:11 2016 GMT

verifying the response signature
verify OK (used: [u'-VAfile', u'/tmp/tmpOx6FfD/issuer.crt'])
fetch-ocsp-response (using OpenSSL 1.0.2f  28 Jan 2016)
sending OCSP request to http://gu.symcd.com
/opt/psa/var/certificates/cert-FhvkAw: good
        This Update: Apr 16 08:49:53 2016 GMT
        Next Update: Apr 23 08:49:53 2016 GMT

verifying the response signature
verify OK (used: [u'-VAfile', u'/tmp/tmpcHhtOi/issuer.crt'])

have anyone a idea?

**Comment by tatsuhiro-t** [comment]
To route specific backend based on request host, do something like this:

```
backend=212.227.252.236,4444;;proto=h2;tls
backend=212.227.252.236,4444;fruchthof24.de/;proto=h2;tls
backend=2001:8d8:91e:aa00::1c:f946,4444;fruchthof24.de/;proto=h2;tls
backend=217.160.108.85,4444;affilie.de/;proto=h2;tls
```

Notice the first entry which does not have no request pattern.  This is called catch-all pattern that nghttpx needs to route the request which does not match any patterns.

**Comment by Winzigweich** [comment]
hi tatsuhiro-t,
thanks, i have change the config file with this 
backend=212.227.252.236,4444;;proto=h2;tls
backend=212.227.252.236,4444;fruchthof24.de/;proto=h2;tls
backend=2001:8d8:91e:aa00::1c:f946,4444;fruchthof24.de/;proto=h2;tls
backend=217.160.108.85,4444;affilie.de/;proto=h2;tls

but the result is the same. the second domain redirect to the first domain.

**Comment by tatsuhiro-t** [comment]
What does the HTTP request to second domain look like ?

**Comment by Winzigweich** [comment]
Resolving www.affilie.de (www.affilie.de)... 217.160.108.85
Connecting to www.affilie.de (www.affilie.de)|217.160.108.85|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.fruchthof24.de/ [following]
--2016-04-16 14:11:12--  https://www.fruchthof24.de/
Resolving www.fruchthof24.de (www.fruchthof24.de)... 2001:8d8:91e:aa00::1c:f946, 212.227.252.236
Connecting to www.fruchthof24.de (www.fruchthof24.de)|2001:8d8:91e:aa00::1c:f946|:443... connected.
HTTP request sent, awaiting response... 200 OK

**Comment by tatsuhiro-t** [comment]
Ah, you use www.affilie.de not affilie.de.  The pattern match in nghttpx is exact match.  To allow required subdomain, do this:

```
backend=212.227.252.236,4444;;proto=h2;tls
backend=212.227.252.236,4444;*.fruchthof24.de/;proto=h2;tls
backend=2001:8d8:91e:aa00::1c:f946,4444;*.fruchthof24.de/;proto=h2;tls
backend=217.160.108.85,4444;*.affilie.de/;proto=h2;tls
```

**Comment by Winzigweich** [comment]
ah okay. ;-)
but now tell affilie.de ---> No input file specified. 
hmmm... error file is clear.

**Comment by tatsuhiro-t** [comment]
Not sure about the error message.   Where did it come from?  nginx?  Then it is a nginx issue.

If you'd like to route affilie.de (without subdomain), do this:

```
backend=212.227.252.236,4444;;proto=h2;tls
backend=212.227.252.236,4444;*.fruchthof24.de/;proto=h2;tls
backend=2001:8d8:91e:aa00::1c:f946,4444;*.fruchthof24.de/;proto=h2;tls
backend=217.160.108.85,4444;*.affilie.de/:affilie.de/;proto=h2;tls
```

**Comment by Winzigweich** [comment]
thanks :-)
<No input file specified.> <---- this was an nginx error. fcgi pass was not correct. 
for affilie.de i have two backend options configured
backend=217.160.108.85,4444;*.affilie.de/:affilie.de/;proto=h2;tls
backend=217.160.108.85,4444;*.affilie.de/;proto=h2;tls
this work perferkt. it redirect with and without www.* to the domain.

**Comment by tatsuhiro-t** [comment]
For the record, the second row is redundant, because first row covers it.

```
backend=217.160.108.85,4444;*.affilie.de/:affilie.de/;proto=h2;tls
```

is equivalent to

```
backend=217.160.108.85,4444;*.affilie.de/;proto=h2;tls
backend=217.160.108.85,4444;affilie.de/;proto=h2;tls
```

**Comment by tatsuhiro-t** [comment]
Anyway, good to hear that it works.  Closing.
