### ISSUE TITLE
Use libev kqueue backend on BSD system if possible

### ISSUE THREAD

**Issue by tatsuhiro-t** [nghttp2/nghttp2#586]
From libev manual (http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod):

> Kqueue deserves special mention, as at the time of this writing, it was broken on all BSDs except NetBSD (usually it doesn't work reliably with anything but sockets and pipes, except on Darwin, where of course it's completely useless). Unlike epoll, however, whose brokenness is by design, these kqueue bugs can (and eventually will) be fixed without API changes to existing programs. For this reason it's not being "auto-detected" unless you explicitly specify it in the flags (i.e. using EVBACKEND_KQUEUE) or libev was compiled on a known-to-be-good (-enough) system like NetBSD.

So if libev is installed without modification, it is not used automatically on BSD family except for NetBSD.  See if we can enable this on free BSD OSes, such as FreeBSD.

**Comment by bsuh** [comment]
FreeBSD already has a patch for this.
```
vagrant@:~ % cd /usr/ports/devel/libev
vagrant@:/usr/ports/devel/libev % cat files/patch-ev.c
--- ev.c.orig	2015-12-20 21:12:53 UTC
+++ ev.c
@@ -2736,7 +2736,7 @@ ev_recommended_backends (void) EV_THROW
 {
   unsigned int flags = ev_supported_backends ();

-#ifndef __NetBSD__
+#if !defined(__NetBSD__) && !defined(__FreeBSD__)
   /* kqueue is borked on everything but netbsd apparently */
   /* it usually doesn't work correctly on anything but sockets and pipes */
   flags &= ~EVBACKEND_KQUEUE;
```

**Comment by tatsuhiro-t** [comment]
Thank you. Perhaps it would be even better to enable it in our code for the other platforms.

**Comment by tatsuhiro-t** [comment]
kqueue is now enabled on h2load, nghttpx and nghttpd.  nghttp does not use lots of connections, so it is not patched.
