### ISSUE TITLE
End stream flag in trailers sent as separate, DATA frame

### ISSUE THREAD

**Issue by vlad-alexandru-ionescu** [nghttp2/nghttp2#588]
I'm using nghttpx to reverse-proxy gRPC traffic. Unfortunately gRPC client gets confused because when server sends back header frame (trailers) with flag `End Stream = True`, nghttpx translates that into the same header frame, but with `End Stream = False` and then adds a separate, empty data frame, with `End Stream = True`. This causes an error in the gRPC client as it no longer expects a data frame at that point (after trailers).

So nghttpx should not create a new data frame, but rather keep the `End Stream = True` in the header frame (the same it has received it from the backend).

For reference, the error I get from gRPC in go is `rpc error: code = 13 desc = server closed the stream without sending trailers`.

**Comment by vlad-alexandru-ionescu** [comment]
[HTTP/2 spec reference](https://http2.github.io/http2-spec/#rfc.section.8.1).

I'd be happy to get my hands dirty to fix this one, but I'd need some code pointers as to where the trailers and handled.

**Comment by vlad-alexandru-ionescu** [comment]
After some more investigation, it seems that this is due to a special case in gRPC where if there's no data, then the trailers are actually sent as headers (and no data frame is sent at all). So I can see why nghttpx adds an empty data frame in this case - but I would argue that it's unnecessary.

**Comment by tatsuhiro-t** [comment]
Current implementation of nghttpx only forwards trailer fields if there is response body.  As far as I know, nghttpx does not mix trailer fields to header fields.  Did you see trailer fields were appended to header fields?  If so, it might mean that gRPC does that.
Could you tell us how to reproduce this situation?

**Comment by vlad-alexandru-ionescu** [comment]
Yes, you're right, gRPC mixes headers and trailers. So it seems like a gRPC bug more than anything. I've opened [this issue with gRPC](https://github.com/grpc/grpc-go/issues/658).

Still, the only remaining complaint I have is that header-only responses get an empty data frame appended to them by nghttpx. I would argue that that data frame is unnecessary and should not be appended. But I don't have a strong opinion on this.

**Comment by tatsuhiro-t** [comment]
Thanks.  HTTP/2 standard allows empty body response, and gRPC should accept that.
Usually, we can omit empty DATA if possible, but it requires that backend server should add content-length: 0 to indicate that there is no body.  gRPC does not do that, therefore we cannot add END_STREAM to HEADERS reliably.

**Comment by tatsuhiro-t** [comment]
Right, we don't utilize END_STREAM in HEADERS from backend.  With that, nghttpx can avoid empty body.  I still think gRPC should accept empty body, but we'll do this fix anyway.

**Comment by tatsuhiro-t** [comment]
Fix committed via 2d2b72d4eb2611c02fcaa9cbdb25bc95cd7e5671

**Comment by vlad-alexandru-ionescu** [comment]
Many thanks for very fast fix!

**Comment by tatsuhiro-t** [comment]
Great to hear that.
FYI, we did a bit more optimization in libnghttp2 to avoid 0-length DATA in general if possible.
Closing the issue.
