### ISSUE TITLE
FreeBSD can't find python for OCSP stapling

### ISSUE THREAD

**Issue by bsuh** [nghttp2/nghttp2#590]
env: python: No such file or directory

It looks like execve is getting called with no environment variables and PATH is not set?

**Comment by tatsuhiro-t** [comment]
Thank you for telling us.  We did not pass envrion to execve when executing ocsp update command.

70e8dc3 will fix this issue.

**Comment by tatsuhiro-t** [comment]
Please reopen this issue, if this issue still happens to you.

**Comment by bsuh** [comment]
Verified working in v1.11.0. Was waiting for FreeBSD port to be updated with this fix.
