### ISSUE TITLE
Unused flags variable in nghttp2_submit_ping() at nghttp2_submit.c:216

### ISSUE THREAD

**Issue by angarkuscha** [nghttp2/nghttp2#593]
nghttp2_submit.c:216:3: warning: Value stored to 'flags' is never read
  flags &= NGHTTP2_FLAG_ACK;
  ^        ~~~~~~~~~~~~~~~~

Caught by static analyzer.

Current implementation:

int nghttp2_submit_ping(nghttp2_session *session, uint8_t flags,
                        const uint8_t *opaque_data) {
  flags &= NGHTTP2_FLAG_ACK;
  return nghttp2_session_add_ping(session, NGHTTP2_FLAG_NONE, opaque_data);
}

The flags parameter is unused and not being passed further to nghttp2_session_add_ping()

**Comment by tatsuhiro-t** [comment]
Thank you for telling us.  The fix was committed via 5d4f3f36e36718309f357140f8208b25a13eedba
