### ISSUE TITLE
C++ asio backend scalability windows IOCP/select ?

### ISSUE THREAD

**Issue by kangjoni76** [nghttp2/nghttp2#594]
I need to run blocking function on new connection server.  My application is minimal website. The blocking function that could be my worry  are fetching data from db and run generate custom HTML template. I do understand nghttp2 c++ asio does threading job, so I don't need any async nor multi thread computation overhead. Could you confirm that my assumption was true ? 
And I have a question regarding windows c++ asio backend, whether nghttp2 use IOCP or select with usual per thread scheduling?
Thanks

**Comment by tatsuhiro-t** [comment]
You can use threading with c++ asio lib, but please note that asio APIs for a single HTTP/2 session must be called from one single thread at a time, so you have to utilize boost io_service post to schedule the synchronization point, and it is not so easy.  If you have good knowledge of multi threading programming in c++ and boost, I'm sure you can do that.

As for Windows IOCP, it depends on how boost asio support it.  nghttp2 c++ asio lib itself just uses boost asio library.
