### ISSUE TITLE
API type comments

### ISSUE THREAD

**Issue by ddennerline** [nghttp2/nghttp2#595]
I would like to thank you for building a great library. I am have used the test tools for conformance testing my own clean room HTTP/2 implement. I have some comments on the API in regards to parameter typing that I thought might be beneficial.

1) Why isn't input data not defined as const correct. The fourth parameter of nghttp2_hd_inflate_hd() is a HPACK buffer fragment that should not be modified
2) Why is uint8_t being used instead of unsigned char, uchar_t, or u_char. uint8_t is reserved for counting. A google of uint8_t vs unsigned char (http://stackoverflow.com/questions/1725855/uint8-t-vs-unsigned-char) provides insight into usage pattern. 

In my opinion, these is patterns are problematic for integrating with HTTP server products – many casts will be required. I quick inspection of ngx_http_parse.c confirms that nginx uses either a ngx_str_t* or u_char*. 

 ssize_t nghttp2_hd_inflate_hd(nghttp2_hd_inflater*, nghttp2_nv*, int*, uint8_t*, size_t, int);

I suspect it's too late to make any changes even if some agreement is reached. But if at some point a major revision is planned, then improving portability and code security is good idea (in my opinion).

The reason that I wrote this post is that I am integrating the nghttp2 library with some C++ code that I have written. I am having to add too many C casts which I personal hate adding.

**Comment by tatsuhiro-t** [comment]
It is my mistake to not add const.  As you know, we cannot change signature since it is a part of our stable API.  But we can add new function, say, nghttp2_hd_inflate_hd2, to fix this issue if it makes the application developers happier.

**Comment by tatsuhiro-t** [comment]
Usually, uint8_t is an alias of unsigned char, and no cast is required.  Of course, there may be some platforms which isn't.

**Comment by tatsuhiro-t** [comment]
2a96d43 fixes missing const qualifier issue in nghttp2_hd_inflate_hd().  The commit added nghttp2_hd_inflate_hd2() which has const qualifier for `in` parameter.

**Comment by tatsuhiro-t** [comment]
Replacing uint8_t with unsigned char is WONTFIX here, and constness issue was fixed as in the previous comment, let's close this issue.
