### ISSUE TITLE
Buffers can't really be contagious

### ISSUE THREAD

**Issue by mustrumr** [nghttp2/nghttp2#598]
They can be contiguous

**Comment by tatsuhiro-t** [comment]
Could you explain in more detail about this issue?  I'm not sure what you are referring to.

**Comment by mustrumr** [comment]
contagious - adjective

1. (of a disease) spread from one person or organism to another, typically by direct contact.
    "a contagious disease"
2. (of a person) having a disease that can be transmitted by contact with other people.
    "precautions are taken with anyone who seems contagious"
3. (of an emotion, feeling, or attitude) likely to spread to and affect others

contiguous - adjective

1. sharing a common border; touching.
    "the Southern Ocean is contiguous with the Atlantic"
2. next or together in sequence.
    "five hundred contiguous dictionary entries"

**Comment by tatsuhiro-t** [comment]
Ah, it is typo. Thank you for tellng us.

**Comment by tatsuhiro-t** [comment]
Fix committed via 863fbff
