### ISSUE TITLE
nghttpx session affinity

### ISSUE THREAD

**Issue by bobbymicroby** [nghttp2/nghttp2#608]
Hello @tatsuhiro-t 

I was wondering if nghttpx supports any kind of session afinity, or are there any plans for this in the future ? We are thinking of using it for a kubernetes ingress loadbalancer, but some of our services are stateful and they do require that the client hits only one the of backends after the handshake. 

Regards, B.

**Comment by tatsuhiro-t** [comment]
nghttpx does not support session affinity at the moment.  Backend connection is reused or shared by different frontend connections for efficiency.
It is not hard to implement session affinity using, say, client IP hashing.  We will determine the routing pattern using host/path, and choose the backend using hash value.
The difficulty part is that affinity breaks when one of the backend pod is gone, or added, and nghttpx is reloaded.  In kubernetes, pod is ephemeral resource, and deleted or created anytime.  For simplest ingress controller, it will reload nghttpx process, and if the number of pod is changed, client connection may reach difference backend pod.  Not sure how other reverse proxy deals with this issue.

**Comment by tatsuhiro-t** [comment]
Similar issue #604

**Comment by bobymicroby** [comment]
Hello @tatsuhiro-t ,thank you for your reply. 

I like to think that every service is ephemeral in a way. After all, you can never be sure about it's welfare:)
The backend service can restore it's state and the client will pay the latency cost, but having some form of affinity is better than nothing. 

Fore sure having  something like [Client IP affinity & Generated cookie affinity](https://cloud.google.com/compute/docs/load-balancing/http/backend-service#setting_session_affinity) features that the Google Cloud Platform is offering, will make nghttpx a great candidate for implementing a custom ingress specially designed to handle the http2 services out there.

Regards, Bobby.

**Comment by tatsuhiro-t** [comment]
Thank you for the pointer to GCE.  We can start with simple IP hashing method.  Probably, cookie method is more ideal considering large deployment of corporate proxy, and some embedded information in cookie might help us to stick to the session in a more robust way.

**Comment by tatsuhiro-t** [comment]
As of d36afb7cdb0e1c08580f4918e013a8f659dc4ac6, client IP based session affinity has been added.  To enable it, use affinity=ip parameter in --backend option.

**Comment by bobymicroby** [comment]
Awsome ! We will give it a spin as soon as possible and will update you with the results ... Thank you .

**Comment by bobymicroby** [comment]
Hi @tatsuhiro-t,

We have experienced issues when we brought one of the load balanced nodes then **everyone** was redirected to a new node, causing all the nodes to recreate their state, which can be very expensive.

This problem is solved can be solved by consistent hashing, and there there is a C implementation here if you want to have a look https://github.com/RJ/ketama. 

Regards, Bobby.

**Comment by tatsuhiro-t** [comment]
The current implementation is what ketama describes naive.  Will look into the details of the better method.

**Comment by tatsuhiro-t** [comment]
Fix committed via 2bbe4422d2c694b6cd50976352b5f1347bebe3d1

**Comment by bobymicroby** [comment]
どうもありがとうございます :)

**Comment by tatsuhiro-t** [comment]
Cookie based affinity is now being discussed at https://github.com/nghttp2/nghttp2/issues/1024
And we have a working patch.
