### ISSUE TITLE
HTTP  POST request question!

### ISSUE THREAD

**Issue by moransina** [nghttp2/nghttp2#611]
Hi,

I have been trying to get POST to work but I am still confused on how it should work. No matter what way I try to do it, it throws some error or it doesn't send the POST body content.
Obviously the command line argument is  ``-d`` (which simply changes GET to POST, at least that is what it shows in the code line 2194)  
The documentation is a bit confusing though ``-d, --data=<PATH>   Post FILE to  server.``. What does Post FILE to server mean, does it mean we need to pass a file similar to input-file with following format ``hostname:portnumber/uri`` or what? Or is ``-d`` just  a flag that will flip GET to POST and we still need to pass ``-i``.  
My question evolves on what does go after ``-d``? Is it a file? If yes, what does it have as content? Also do I need to pass ``-i`` with it or not?

Here are few examples I run:

- ``h2load -p HTTP/1.1 -r1 -n3 -c1 -i ~/input.txt``  - **DID NOT WORK** (I made a minor change in the code by hardcoding the value of ``config.data_fd = 0;`` so I can **enforce the POST method** usage) however I am getting a **411 Status Code**.

- ``h2load -p HTTP/1.1 -r1 -n3 -c1 -d ~/post.txt -i ~/input.txt`` - **DID NOT WORK**. The post.txt content (POST bodies) hasn't been sent to the server. When I dumped the incoming requests on the server side, I see only the POST /uri but no POST body. I am also getting a **411 Status Code**, also the request body length=0 and the request header length doesn't seem to be correct. 

How does h2load send POST body content (aka payload)?? I couldn't find any indication in the h2load.cc on how to do that?

Assuming I need to send POST body content (aka payload) along with the request uri itself. For instance, I might have a file having requests such as:
``http:hostname:portnumber/test1?p1=xyz&p2=abc<TAB>{POST BODY Content}``
``http:hostname:portnumber/test2?p3=xyz&p4=abc<TAB>{POST BODY Content}`` 
Essentially each request has JSON POST Body that needs to be sent with. 

Does h2load actually support that? Where in the code are we sending the POST body content (aka payload)?
Do I need to have a special format for the POST body and the uri? Do I need to pass the POST body with the uri? Do I need to specific Param for the post body? I am sorry but it has gotten me confused and have been trying to get it to work for quite a bit but no luck.

Do you have a concrete example on how to use h2load to send POST requests with POST body?

Thanks

**Comment by tatsuhiro-t** [comment]
It turns out that h2load does not implement to send body when HTTP/1.1 is used.  HTTP/2 and SPDY work fine with request body.

-d takes file path, and h2load reads the content, and sends it to the remote server.  The content of the file is opaque to h2load, and it is up to the client and server what is the expected format they expect.

h2load's POST only supports single file, and one cannot change the request body per URI at the moment.

**Comment by tatsuhiro-t** [comment]
Implemented -d option for http/1.1 connection (HTTP/1.1 POST) in the recent commits.

**Comment by softwaregee** [comment]
Thanks @tatsuhiro-t .

So the new version **v1.12.0** is supposed to support the POST body feature for HTTP/1.1?
Also, does the -d option for http/1.1 support changing the request body per URI or not? i.e reading and sending a body per URI or not?

**Comment by softwaregee** [comment]
Thanks @tatsuhiro-t . 
I actually had the same question as well sometimes back. This is fantastic!

So the new version **v1.12.0** is supposed to support the POST body feature for HTTP/1.1?
Also, does the -d option for http/1.1 support changing the request body per URI or not? i.e reading and sending a body per URI or not?

**Comment by moransina** [comment]
@tatsuhiro-t 
Thanks for the update!
As mentioned above by @softwaregee , would the implementation of POST (HTTP/1.1) support changing the body per URI, i.e reading different bodies from a file and send a different body with each URI?

**Comment by tatsuhiro-t** [comment]
> So the new version v1.12.0 is supposed to support the POST body feature for HTTP/1.1?

Yes

> Also, does the -d option for http/1.1 support changing the request body per URI or not? i.e reading and sending a body per URI or not?

No.

**Comment by tatsuhiro-t** [comment]
I will close this issue since HTTP/1.1 POST has been implemented.

**Comment by Pratikhyadav** [comment]
HOW can i send File in POST request in command line on Linux?

**Comment by lubinson** [comment]
@tatsuhiro-t 

Thanks for the h2load tools. Now I can use it to send h2c traffic. Can it send different request body for each request? e.g. read each eol of the file refrerred by -d. 

Thanks.

**Comment by tatsuhiro-t** [comment]
At the moment, you cannot specify different request body for each request.

**Comment by lubinson** [comment]
@tatsuhiro-t 

Thank you. Do you have suggestion about how to achieve this by other way?
