### ISSUE TITLE
NGHTTP2_MAX_HEADERSLEN question

### ISSUE THREAD

**Issue by mattklein123** [nghttp2/nghttp2#613]
Hi,

Just wondering what the reason is behind the hard coded max headers length for transmitting frames. I agree this is a reasonable size, but it would be useful to allow a larger/configurable size so that I can more easily test what a sever does when it receives large headers.

https://github.com/nghttp2/nghttp2/blob/master/lib/nghttp2_frame.h#L63

I don't think there is anything in the spec that limits this, but I could be wrong.

Thanks,
Matt

**Comment by tatsuhiro-t** [comment]
You are correct.  The RFC does not limit the maximum size of header block.  On the other hand, implementation has a liberty to protect itself from overloading memory usage.  The limit is placed for this purpose, and not be abused by accidents.

But I agree that this value should be configurable.  We will add new option to nghttp2_option object to configure this setting.

**Comment by mattklein123** [comment]
Awesome, thanks. FWIW it would be really nice if this configurable value were also used on the decompression side so that users don't have to implement checking in headers complete callbacks for large headers. I understand however that is a larger change. Just having the sending side be configurable would help me a lot with my testing of the server.

**Comment by tatsuhiro-t** [comment]
I'd like to make limiting the size of receiving header fields another issue.  As far as I know, application has a specific counting policy for incoming header fields, and it may limit not only the number of bytes, but the number of header field name/value pair.  Perhaps, we can utilize SETTINGS_MAX_HEADER_LIST_SIZE defined in RFC 7540.  Currently we don't enforce it.  It just slipped into RFC in the last minutes change.
