### ISSUE TITLE
io_service unable to create session 

### ISSUE THREAD

**Issue by SMostaf** [nghttp2/nghttp2#621]
I'm unable to create a session, this line blocks the code and never returns:

`auto sess = session(io_service, "localhost", "3000");`

I'm seeing that issue only on ubuntu, same code works fine on OSX, how can I debug this issue?

**Comment by tatsuhiro-t** [comment]
We only starts asynchronous name resolver from there.
Which version of boost library are you using?  Stock version of ubuntu?  Which version of ubuntu?

**Comment by SMostaf** [comment]
using boost 1.61.0, Ubuntu 14.04 LTS
If there is a network issue, I receive a timeout error on OSX, I don't receive any thing in the session.on_error callback on ubuntu.

**Comment by tatsuhiro-t** [comment]
According to http://packages.ubuntu.com, boost which comes with 14.04 is boost version 1.54 or 1.55.  Did you compile boost 1.61 or PPA?  Is that compiled successfully?
on_error callback will run after session() returns. In your case, session never return.  We only start boost asynchronous operation from there, so probably boost issue.

**Comment by SMostaf** [comment]
I went back to boost1.54, now I'm seeing the on_error handler getting called with error message: tls: no application protocol negotiated

```
boost::asio::ssl::context tls_ctx(boost::asio::ssl::context::sslv23);
tls_ctx.set_default_verify_paths();
configure_tls_context(ec, tls_ctx);
    
```

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
