### ISSUE TITLE
Server Push at nghttp2.org

### ISSUE THREAD

**Issue by JimmyRittenborg** [nghttp2/nghttp2#622]
For some reason screen.css isn't pushed for me in Chrome Stable and Chrome Canary.
But assets on blog.cloudflare.com is.

![Push Promise](https://www.dropbox.com/s/jmr7izp02jhcpke/push-promise.jpg?dl=1)
And from the sessions I can also only find PUSH_PROMISE from blog.cloudflare.com

**Comment by tatsuhiro-t** [comment]
It turns out that nghttp2.org pushes resource only when client accesses "/" or "/index.html".
Please try https://nghttp2.org/  and see the push is working.

**Comment by JimmyRittenborg** [comment]
That works and also Canary gives it Initiator: Push / (index):26 👍
