### ISSUE TITLE
Compilation error with LibreSSL 2.4.1 (nghttp2 v1.12.0)

### ISSUE THREAD

**Issue by Micdu70** [nghttp2/nghttp2#623]
Hello,

I've got this error when compiling the latest version with LibreSSL 2.4.1:

`CXX      libnghttpx_a-shrpx_ssl.o
shrpx_ssl.cc: In function ‘SSL_CTX* shrpx::ssl::setup_server_ssl_context(std::ve                                                                                                                               ctor<ssl_ctx_st*>&, shrpx::ssl::CertLookupTree*)’:
shrpx_ssl.cc:1375:47: error: ‘SSL_CTX_get0_certificate’ was not declared in this                                                                                                                                scope
   auto cert = SSL_CTX_get0_certificate(ssl_ctx);`

I fixed this error by adding a conditional check of "LIBRESSL_VERSION_NUMBER" (in 'src/shrpx_ssl.cc'), line 1374 and 1400:

`#if !defined(LIBRESSL_VERSION_NUMBER) && OPENSSL_VERSION_NUMBER >= 0x10002000L`

I think it's a nice solution, isn't it?

**Comment by tatsuhiro-t** [comment]
Yes, it will fix the issue.

**Comment by tatsuhiro-t** [comment]
Fixed in 903e007

**Comment by Micdu70** [comment]
Great!

**Comment by tatsuhiro-t** [comment]
@Micdu70 you reopened this issue.  Do you still see compilation failure?

**Comment by Micdu70** [comment]
@tatsuhiro-t No... everything is ok ^^, but I tought It was nice to keep the issue open until the next release. ;) You can close it.

**Comment by tatsuhiro-t** [comment]
Thank you for reply.  Let's close this issue, because the issue was fixed for upcoming release (I will try to build libressl just before the release to make sure that we really fixed it).
Please raise a new issue if we break again in the new development.
