### ISSUE TITLE
complie problem for decided pow function of float or integer  at nghttp2.12.0  and Solaris 11

### ISSUE THREAD

**Issue by ken1no** [nghttp2/nghttp2#624]
I complie nghttp2 g++48 with Solairs 11 with some errors.
I have a solution, please add (double) cast for ... 

src/shrpx_connect_blocker.cc
[line:83]
auto base_backoff = pow(MULTIPLIER, (double)std::min(MAX_BACKOFF_EXP,fail_count_));

src/shrpx_shrpx_live_check.cc
[line:160]
auto base_backoff = pow(MULTIPLIER, (double)std::min(fail_count_, MAX_BACKOFF_EXP));

**Comment by tatsuhiro-t** [comment]
Thank you for suggestion.
Fix committed via 179561e

**Comment by tatsuhiro-t** [comment]
I believe the above commit fixes this issue.
