### ISSUE TITLE
nghttp2 does not build on armel architecture

### ISSUE THREAD

**Issue by thinred** [nghttp2/nghttp2#627]
Hi,
I noticed that for some strange reason nghttp2 1.12.0 does not build on the armel architecture. The error thrown by the compiler is "'mutex' in namespace 'std' does not name a type" in the file src/shrpx_connection_handler.h. I fixed it by explicitly including mutex header (see https://anonscm.debian.org/cgit/collab-maint/nghttp2.git/tree/debian/patches/0002-Fix-FTBFS-on-armel-by-explicitly-including-the-mutex.patch).

Hope it helps!

**Comment by tatsuhiro-t** [comment]
Thank you!  The patch was merged as 5d35351
