### ISSUE TITLE
Building nghttp2 in windows x64

### ISSUE THREAD

**Issue by Elavarasan83** [nghttp2/nghttp2#628]
I have to build nghttp2 in windows x64 machine. Apache has dependency with nghttp2.
I tried compiling nghttp2 using 'Makefile.msvc' using nmake command in VS2013 but it failed.
Can any one tell me the steps to compile nghttp2 in windows x64 machine?

**Comment by tatsuhiro-t** [comment]
It would be better to share the error message here so that interested people can offer help easily.

**Comment by Elavarasan83** [comment]
Now I have installed cygwin and used VS2013 x64 Native Tools Command Prompt.
Using make(package of cygwin) command i'm able to compile nghttp2. 
_c:\httpd-2.4.20\srclib\nghttp2\lib>make -f Makefile.msvc_

In nghttp2 documentation: [https://github.com/nghttp2/nghttp2](url) the following steps are mentioned:
_$ export CFLAGS="-U__STRICT_ANSI__ -I$libev_PREFIX/include -L$libev_PREFIX/lib"
$ export CXXFLAGS=$CFLAGS
$ ./configure
$ make_

Only make command is working for me. The other commands(export, ./configure) are not recognized. Any cygwin-package I have to install for these commands to work? I'm not sure how& where the variable(libev_PREFIX) is defined/set. 
Please clarify.

**Comment by tatsuhiro-t** [comment]
I think "export" is built-in command of bash shell.

I think using cmake is a lot simpler to build libnghttp2.  I just did the following and it worked very well:

1. install cmake for windows
2. inside nghttp2 directly, run `cmake .`
3. then run `cmake --build .` to build library.
4. The nghttp2.dll, nghttp2.lib, nghttp2.exp are placed under lib directory.

I used http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by Elavarasan83** [comment]
I had run the below commands. It works.
c:\httpd-2.4.20\srclib\nghttp2>
_cmake CMakeLists.txt -G "Visual Studio 12 2013" and then - cmake --build ._
_cmake --build . --config Release_

Another way of compiling is, using make package of cygwinf(with  VS2013 x64 native tools commands prompt)
c:\httpd-2.4.20\srclib\nghttp2\lib>make -f Makefile.msvc then lib file is generared
in '\lib\MSVC_obj'.

I will prefer compilation nghttp2 using make command. I want to use the nghttp2 library for Apache compilation. Apache looks for the library in '\lib\MSVC_obj'. 

I hope both these approaches generate same output.

**Comment by tatsuhiro-t** [comment]
You will use some scripts to do this automatically, so perhaps, you can move around the compiled library where you want?

**Comment by Elavarasan83** [comment]
Thanks for all the support.
