### ISSUE TITLE
Is there a nghttpx (forward proxy) client?

### ISSUE THREAD

**Issue by nubela** [nghttp2/nghttp2#629]
Hi,

I have a forward (Secure SSL) proxy server setuped. And I need a CLI client to access this proxy setup (nghttpx + backend).

Apart from the browser, do you have a CLI client (sth like `curl`) to make url requests?

**Comment by tatsuhiro-t** [comment]
nghttp can be used to access HTTP/2 proxy, but it only works with http URI.  https URI does not work.
To work with http URI, use the following trick.  To access nghttp2.org via HTTP/2 proxy:

```
$ nghttp -nv https://<PROXY> -H ':authority: nghttp2.org' -H ':scheme: http'
```

**Comment by nubela** [comment]
Thanks!
ᐧ
