### ISSUE TITLE
Nghttp http/2 client as library

### ISSUE THREAD

**Issue by ragavendrapec** [nghttp2/nghttp2#633]
Hi,

Is there any Nghttp2 client code which can be compiled as library so that it can be used in other source code? (something like libcurl, since the nghttp is generated as a binary now and is in C++, I'm looking for something in C)

**Comment by tatsuhiro-t** [comment]
The nghttp client specific code is only available as executable.  Its core HTTP/2 handling code uses libnghttp2.
If you want to more application code than libnghttp2 offers, you have to write them yourself.  We have tutorial how to write HTTP/2 client: https://nghttp2.org/documentation/tutorial-client.html

Another option is use libcurl, which integrates libnghttp2, and do multiplexing stuff.

**Comment by ragavendrapec** [comment]
Yes sure tatsuhiro-t. Many thanks for the prompt reply.
