### ISSUE TITLE
nghttp: use of multiple weights in command line 

### ISSUE THREAD

**Issue by cconcolato** [nghttp2/nghttp2#636]
Is it possible to use multiple weights, one per URL, when using nghttp? I would like to do something like:
```nghttp -nv URL1 -p 256 URL2 -p 128 URL3 -p 1 --no-dep```
But it seems that only the last `p` is taken into account. Is there another way to do it?

**Comment by tatsuhiro-t** [comment]
Currently, we don't do this, but we can define the semantics of multiple -p option so that N-th -p option specifies N-th URIs.  Personally, it would be better to set dependency as well, but we don't know the stream ID in advance, so it would be another issue.

**Comment by cconcolato** [comment]
Thanks for the response. I agree setting dependencies would be nice too. 
You could imagine something like:
```nghttp -nv URL1 -d 1:0 -p 256 URL2 -p 128 -d 2:1 URL3 -p 1 -d 3:1 --no-dep```
where `-d a:b` would define a temporary identifier 'a' for the preceding URL with a dependency on 'b'.

**Comment by tatsuhiro-t** [comment]
Thank you for suggestion.  For multiple -p option, we have implemented it in 3c1c2c4aadb3b91a271dbfcbdaca556dd9e41bdb

**Comment by cconcolato** [comment]
Great. Thank you for the quick fix !

**Comment by tatsuhiro-t** [comment]
For specifying dependency, we would like to discuss in the separate issue.
