### ISSUE TITLE
Error when using libnghttp2_asio.so: undefined reference to `nghttp2_session_set_local_window_size'

### ISSUE THREAD

**Issue by hnkien** [nghttp2/nghttp2#637]
I got issue when using libnghttp2 with boost asio:
/usr/local/lib64/libnghttp2_asio.so: undefined reference to `nghttp2_session_set_local_window_size'
My linux kernel: 4.5.7-202.fc23.x86_64
Boost library version: 1.58

**Comment by tatsuhiro-t** [comment]
nghttp2_session_set_local_window_size has been added since v1.12.0.  The chances are that you have multiple versions of nghttp2 library installed, and on runtime, somehow the asio executable refers to the older version of library.

**Comment by hnkien** [comment]
Thank you very much.
After checking, my linux box had already installed older version of Nghttp2.
