### ISSUE TITLE
ALPN support in nghttpx

### ISSUE THREAD

**Issue by bluecmd** [nghttp2/nghttp2#638]
Hi,

Is ALPN supported in nghttpx?

I'm using nghttp2 1.13.0 and the commands I'm using are:
```
sudo src/nghttpx --frontend=*,443 '--backend=172.17.0.2,8080' /etc/ssl/private/ssl-cert-snakeoil.key /etc/ssl/certs/ssl-cert-snakeoil.pem
```
and
```
sudo src/nghttpx --frontend=*,443 '--backend=172.17.0.2,443;;proto=h2;tls' /etc/ssl/private/ssl-cert-snakeoil.key /etc/ssl/certs/ssl-cert-snakeoil.pem --insecure
```

Chrome does not switch to h2. Reading https://www.nginx.com/blog/supporting-http2-google-chrome-users/ it appears  that ALPN is the only way to have recent Chrome use h2, so I'm assuming this is what's missing.

I'm using OpenSSL 1.0.1t which according to the same article does not include ALPN support. I have not tried to update to OpenSSL 1.0.2. If this is the problem, I would like to request a note in the documentation that this is needed for ALPN support / Chrome.

Thanks!

**Comment by tatsuhiro-t** [comment]
nghttpx supports ALPN, and it requires openssl >= 1.0.2.  Our README already states about this:
> ALPN support requires OpenSSL >= 1.0.2 (released 22 January 2015).

**Comment by bluecmd** [comment]
Indeed your right! I don't know why I missed that. I guess I assumed it would be on https://nghttp2.org/documentation/nghttpx-howto.html or otherwise more visible. Would it be OK to list it as a thing in the output from ./configure?

**Comment by tatsuhiro-t** [comment]
Sounds nice.
ALPN mention added in nghttpx how to in c9559b5c0d18d2039e75a06f8c009544cfcc05a9, and configure output for ALPN added in f4a4abd180485c9c62a7301b1330ab4db087709c

**Comment by bluecmd** [comment]
Fast response as always! Thanks a lot! FWIW, when I had OpenSSL 1.0.2 present and rebuilt nghttpx2, Chrome gladly switched to h2.

I confirmed that ./configure lists ALPN yes/no correctly if built with OpenSSL < or >= 1.0.2

Thanks!

**Comment by kestereverts** [comment]
I have built nghttp2 with a custom-built OpenSSL 1.0.2h on both Ubuntu 16.04.1 and 14.04.4, and in both cases it lists ALPN incorrectly as "no" in the ./configure output. After running nghttpx, I confirmed that it was in fact using ALPN.

I also built nghttp2 with the stock OpenSSL version (1.0.2g-fips) in Ubuntu 16.04.1, and it also listed ALPN as "no". I did not test if nghttpx used ALPN, as this was what I attempted first and was left confused, prompting me to custom-build OpenSSL.

**Comment by tatsuhiro-t** [comment]
I tested with Ubuntu 16.04, it shows "ALPN: yes".
Compiler options may affect the result.  Could you show us config.log file?

**Comment by kestereverts** [comment]
Here is is:
[config.log.txt](https://github.com/nghttp2/nghttp2/files/394025/config.log.txt)

**Comment by tatsuhiro-t** [comment]
I saw -L/root/openssl/lib used for testing ALPN support.  Can you make sure that the directory, /root/openssl/lib, contains libssl.so which includes ALPN support?

**Comment by kestereverts** [comment]
I only built the static library, so it is not there.

**Comment by tatsuhiro-t** [comment]
So you mean that /root/openssl/lib contains libssl.a?

What will happen if you just run "./configure" without any options?  Does it still report that ALPN is "no"?

**Comment by kestereverts** [comment]
Yes, it contains libssl.a.
If I ./configure without any options, it will still say "no": [config.log.txt](https://github.com/nghttp2/nghttp2/files/394152/config.log.txt)

**Comment by tatsuhiro-t** [comment]
Interesting.  The same compiler flag, and we got different result.

Could you do `./configure LIBS=-lrt`?  In some cases, "-lrt" is required for libssl.

**Comment by kestereverts** [comment]
It still says "no".

**Comment by tatsuhiro-t** [comment]
Thank you.
Since I have no idea why it does not work for you, and it could confuse users, I will revert the change.

**Comment by bluecmd** [comment]
Could you, just to be 100% certain here, do:
```
cat << _EOF_ > test.c
#include <openssl/opensslv.h>

int main() {
  puts(OPENSSL_VERSION_TEXT);
}
_EOF_
gcc test.c
./a.out
```
Just to make sure that the GCC is really seeing the new OpenSSL version and not some older one.

**Comment by kestereverts** [comment]
That shouldn't be a problem, as my nghttpx build actually runs with ALPN enabled.

Here's the output:
```
root@christopher:~/nghttp-dev# ./a.out
OpenSSL 1.0.2g  1 Mar 2016
```

It correctly identifies the globally installed OpenSSL lib.

**Comment by tatsuhiro-t** [comment]
f4a4abd180485c9c62a7301b1330ab4db087709c has been reverted for now.
