### ISSUE TITLE
Reloading nghttpx is too hard

### ISSUE THREAD

**Issue by bluecmd** [nghttp2/nghttp2#639]
Hi,

I need to reload nghttpx when replacing certificates - for example when using Let's Encrypt. I do not wish to drop existing connections.

From the documentation I gather I should be able to use SIGUSR2 followed by SIGQUIT. This however seems quite messy to implement. The caveat listed for SIGUSR2 is that I have to wait until the new nghttpx is healthy, and as far as I know I have no easy way of knowing that.

Secondly, this forks the process and my original caller will not be able to wait() on the process, losing track of which process is actually the main process.

I would like to request to be able to send SIGHUP (for example) causing nghttpx to reevaluate the configuration (config files if provided --conf / --include) as well as certificates provided on command line. 
I.e. effectively SIGUSR2 / SIGQUIT but not terminating the main process and in a "fire-and-forget" manner.

**Comment by tatsuhiro-t** [comment]
There are some workarounds for this issue.
We do reload nghttpx quite often, and we run nghttpx as daemon, and make it write its master PID using --pid-file option.  When we do SIGUSR2, new nghttpx process overwrites PID file.  nghttpx writes PID file after it started listening socket.  So the creating of new PID file is a good indication of availability of new nghttpx process. If we want to keep the older process ID, we can copy the existing file to somewhere before doing SIGUSR2.



  To check nghttpx is really online, one solution is actually access nghttpx.  For example, we can create frontend address with health monitor mode turned on, and make it only accessible from loop back interface.  We can use curl or whatever tool to access that endpoint to make sure that nghttpx is responsive.

**Comment by bluecmd** [comment]
We're using cgroups so I would really like to not have to track processes using PIDs.
I understand that it's perfectly technically doable to write health checking to do the failover, that however must be recognized as non-trivial work. nghttpx has all the internal state to say that it's ready or not for serving, this should really be something the daemon just does (and does well) for the operator.

It's a really common use-case, and forcing people to do PID juggling will make people misconfigure it. You have the opportunity to create something that's more or less foolproof, I strongly think you should consider it.

**Comment by tatsuhiro-t** [comment]
Fair enough, certainly it could simplify the deployment.  I will explore the possibility of reloading configuration without losing master process.

**Comment by tatsuhiro-t** [comment]
Reloading with SIGHUP has been implemented as of fb3d6f68a801866a0d049a53c0db4d086a8a4bf6
@bluecmd Could you test it out?

**Comment by bluecmd** [comment]
Incredibly fast fix! Thanks a million!

Tested:
- Looping SIGHUP (watch -n0.1 pkill -SIGHUP nghttpx) to see that the termination is graceful. Everything works just fine as far as I can tell
- Replacing SSL certificate to make sure the new one is picked up - works like a charm.

Great!
