### ISSUE TITLE
Where can i see the log messages of nghttp2 library, is it /var/log/syslog ?

### ISSUE THREAD

**Issue by rameshrajagopal** [nghttp2/nghttp2#643]
We use nghttp2 asio library for our service. At times, we do see that connection is getting queued at the load balancers and eventually times out. Our lb's connections is getting dropped at server side. 
For further debugging on this, 

1) Where does nghttp2 logs goes to ? (error/warning level) 
2) Is there any log message we print for connection drops and refuses ?

**Comment by tatsuhiro-t** [comment]
We have no logging in nghttp2 asio library.
For connection drops, do you mean that lb tried to connect to server which includes nghttp2 asio, and eventually timed out?  Have you increased backlog using http2::backlog()?  Also have you increased system's somaxconn?

**Comment by rameshrajagopal** [comment]
We see occasionally our client's request is not reaching our server. During
that time, we do see that LB is having a surge queue(connections). We are
assuming the LB is not able to make a connection with our server.
Apparently we don't have any logs at nghttp2 side to confirm whether there
was a connection drop.

Our backlog at server side is 1024. Our client use a single connection(long
lived) for making multiple requests(streams). AWS lb doesn't have support
for http2 and we are using TCP port forwarding to talk to server. I am not
sure whether AWS lb is making connection for each requests.

If I wanted to enable logs only for debugging this problem, what would be
the ideal place ? I don't want to enable debug mode nghttp2 which is having
huge logs. Please advise.

**Comment by tatsuhiro-t** [comment]
When connection is accepted by server, the following lambda functions are called:

For TLS: https://github.com/nghttp2/nghttp2/blob/d8822f2a8e0b576b7a77ebe07b5ad857050e2d70/src/asio_server.cc#L133

For TCP: https://github.com/nghttp2/nghttp2/blob/d8822f2a8e0b576b7a77ebe07b5ad857050e2d70/src/asio_server.cc#L166

If you want to log when the connection is made, these are the places.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
