### ISSUE TITLE
Stream 1 skipped in http mode without -u

### ISSUE THREAD

**Issue by bsdphk** [nghttp2/nghttp2#649]
Running nghttp2/1.11.1

nghttp -v http://someurl

skips stream number 1 

```
[  0.001] Connected
[  0.001] send SETTINGS frame <length=12, flags=0x00, stream_id=0>
          (niv=2)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
[  0.001] send PRIORITY frame <length=5, flags=0x00, stream_id=3>
          (dep_stream_id=0, weight=201, exclusive=0)
[  0.001] send PRIORITY frame <length=5, flags=0x00, stream_id=5>
          (dep_stream_id=0, weight=101, exclusive=0)
[  0.001] send PRIORITY frame <length=5, flags=0x00, stream_id=7>
```

That is probably correct behaviour if -u had been specified, but not without -u

**Comment by tatsuhiro-t** [comment]
RFC 7540 permits this skipping stream 1 in this case too.
We deliberately use the same dependency tree and starting stream 13 to make debugging easier.
If you want stream 1, use --no-dep option.

**Comment by bsdphk** [comment]
Ok, I agree that you can read RFC7540 that way
