### ISSUE TITLE
HPACK API question

### ISSUE THREAD

**Issue by weliu** [nghttp2/nghttp2#652]
In the tutorial of HPACK API, about nghttp2_hd_inflate_hd(), it says:

"It is important to note that the function may produce one or more header fields even if inlen is 0 when in_final is nonzero, due to differential encoding."

This may not be true in latest implementation. I looked up the code, if inlen is 0, and the in_final is nonzero, it at most set the flag NGHTTP2_HD_INFLATE_FINAL instead of producing any header fields. Please help to confirm.

**Comment by tatsuhiro-t** [comment]
You are right.  That part of document is a legacy of HTTP/2 draft development.  We will remove that note.  Thank you.

**Comment by tatsuhiro-t** [comment]
Fix committed via 4eb7f98
