### ISSUE TITLE
Should HPACK deflating API support multiple bufs?

### ISSUE THREAD

**Issue by weliu** [nghttp2/nghttp2#654]
Currently nghttp2 have nghttp2_hd_deflate_hd() to encode headers, however it only support one buffer input. Should we support mutiple bufs input like writev()? It will be very convenient under some conditions.

**Comment by tatsuhiro-t** [comment]
nghttp2_hd_deflate_hd() uses nghttp2_hd_deflate_hd_bufs(), which uses nghttp2_bufs that supports multiple buffers to support CONTINUATION frames.
The reason we have not expose this interface is that nghttp2_bufs is private.
Perhaps, we can define struct iovec compatible struct to pass to HPACK API, and wraps it in nghttp2_bufs.  But I'm not sure we can do this without changing nghttp2_bufs internals.  Personally, I don't want to add additional complexity to nghttp2_bufs not to sacrifice performance.

**Comment by weliu** [comment]
I looked up the struct of nghttp2_bufs. Maybe we could add such a API under one condition: every buf must have the same size, so we won't need to change nghttp2_bufs struct.
Is that acceptable?

**Comment by tatsuhiro-t** [comment]
If I understand it correctly, it first creates nghttp2_bufs with nghttp2_buf_chain for given buffers, so it does not allocate extra buffers, and does not change nghttp2_bufs at all.
Then I think it is reasonable.  The use case of HPACK encoding API is emit HEADERS frame, and each frame size is usually 16KiB, and assuming same size of buffer makes sense.

**Comment by tatsuhiro-t** [comment]
Fixed by #658
