### ISSUE TITLE
Receiving empty PUSH_PROMISE frame in on_frame_recv_callback

### ISSUE THREAD

**Issue by ctwd** [nghttp2/nghttp2#659]
I'm trying to handle pushed response from HTTP/2.0 server using nghttp2.
It seems I got an empty PUSH_PROMISE frame(with nvlen = 0 and nva=NULL) in call back function _on_frame_recv_callback_.
Also I can see HEADERS frame of the pushed response triggers the  _on_frame_recv_callback_  function, but it never triggers the _on_header_callback_  function. 
The result is I can't use the pushed response.
Is nghttp2 opened by me  in a wrong way?
Or is there a recommended solution dealing with pushed response using nghttp2?

**Comment by tatsuhiro-t** [comment]
As we documented in https://nghttp2.org/documentation/types.html#c.nghttp2_on_frame_recv_callback, Header fields are not available in nghttp2_on_frame_recv_callback.  They are emitted via nghttp2_on_header_callback.
Please make sure that nghttp2_on_header_callback is correctly set using nghttp2_session_callbacks_set_on_header_callback().

**Comment by ctwd** [comment]
I think I've find out what's wrong.
I followed the provided libevent_clinet demo,where  function _on_header_callback_ only deals with response header fields in HEADERS frame.
Not so familiar with HTTP/2.0 and the library, got confused when project did't run as I expected.

Thanks for your time!
