### ISSUE TITLE
nghttpx: healthmon frontend option doesn't works with --http2-proxy option

### ISSUE THREAD

**Issue by tsing** [nghttp2/nghttp2#661]
nghttpx always response with 400 when started with options like: 

`
-f '127.0.0.1,4000;healthmon;no-tls' --http2-proxy
`

**Comment by tatsuhiro-t** [comment]
Confirmed.  It looks like HTTP/1 frontend is affected by this bug.  HTTP/2 is OK.

**Comment by tatsuhiro-t** [comment]
Fix committed via 4807e71
