### ISSUE TITLE
Hiding the version number from the server header

### ISSUE THREAD

**Issue by timk95** [nghttp2/nghttp2#667]
For security purposes I would like to hide the version number of nghttp2. I've searched in the documentation but couldn't find any option related to disabling the version number.

I'm coming from NginX and they have a "server_token" option to disable the version number from the server header.

This would be a great feature, unfortunately I don't have any C knowledge and don't even know where to start to find the code related to the server header, if someone would be so kind to point me in the right direction I can edit it for now.

**Comment by tatsuhiro-t** [comment]
Currently, server header field is hard coded in https://github.com/nghttp2/nghttp2/blob/cf7f87c2adb9118ad3409b02b9590f2c58cb22d2/src/shrpx.cc#L1321

We will add an option to change this in the next release.

**Comment by tatsuhiro-t** [comment]
--server-name option has been added as of 0d4d1a63d45fb880ada93c78df7aa52779640632

**Comment by lutoma** [comment]
Is there also a way to not alter the Server header at all? i.e. to just pass through whatever the backend sent?

**Comment by tatsuhiro-t** [comment]
--no-server-rewrite option was added as of 136aae725f8c8415ea5cd51c18011d7334ba1c22

**Comment by tatsuhiro-t** [comment]
Closing, all required options have been implemented.

**Comment by timk95** [comment]
I've been using the --server-name option for some time now. Because I want to support nghttpx I kept the original value minus the version number for security purpose and that made me thinking, why not add a  --hide-version flag?

I think there are more people who like to promote nghttpx in their headers but like to hide the version number for security purpose.

**Comment by tatsuhiro-t** [comment]
The reason to choose --server-name instead of --hide-version is avoid additional flag.  If we add --hide-version, then some people still want to --server-name like option to completely rewrite the header field.
