### ISSUE TITLE
nghttp as the client to receive request 

### ISSUE THREAD

**Issue by yaung** [nghttp2/nghttp2#676]
I want to use nghttp (the client) to receive requests continually from another server, where does the requests should place in the code ? `add_requests()` or from the begining `main()` ?

```
for (auto req : requests) {

      for (int i = 0; i < config.multiply; ++i) {

        client.add_request(std::get<0>(req), std::get<1>(req), std::get<2>(req),
                           pri_spec);

      }

    }
```
should  I insert my request into the vector requests ? and it would be  processed ?

**Comment by tatsuhiro-t** [comment]
I'm not sure I understand the phrase "to receive requests continually from another server".
Server cannot send request.  Are you saying server push?
