### ISSUE TITLE
Loadbalancing after server error (50x)

### ISSUE THREAD

**Issue by akamos** [nghttp2/nghttp2#682]
Hi,
I use nghttpx and have defined several different backends matching on the same pattern, like load balancing. Lets call this here main gateway. On each backend I run again nghttpx for correct routing with pattern. (I use gRPC) 

Looks like following (I have several routing gateways)

`grpc client -> main gateway (nghttpx) -> routing gateway 1 (or 2, 3, 4..., nghttpx) -> grpc server`

Sometimes the routing gateway on these backends is not available, but the service (in my case the grpc Server) works fine. So the main gateway switch to another routing gateway! All fine. 

**BUT**

Sometimes, and quite more often, the grpc server is offline. The routing gatway so sends a 503 back to the main gateway. The main gateway interpretate this as a successful answer and redirect it to the client. I get an error in the grpc client. But I would like that now the main gateway resend the request again, but to another routing gateway which match the pattern.

How this is possible or can be added in nghttpx?

**Comment by tatsuhiro-t** [comment]
Currently, we don't keep request body after nghttpx sends them to backend, so retrying POST is not possible at the moment.

It would be good for gRPC client to send request again, but I'm not sure it is possible.
Another option is add multiple grpc server, and load balance them with nghttpx.  You can do rolling update them for instance.
