### ISSUE TITLE
Install nghttp2 on centOS 6.5/6.8 problem

### ISSUE THREAD

**Issue by yaung** [nghttp2/nghttp2#686]
I download the source from github:https://github.com/nghttp2/nghttp2. and install with step :

```
$ autoreconf -i
$ automake
$ autoconf
$ ./configure
$ make
```
My computer environment . 
CentOS release 6.8 (Final)、 gcc version 5.4.0 (GCC) 

Every step is OK and with no error , but I can not use it。

nghttp

-bash: nghttp: command not found

But ,I install nghttp2 on Ubuntu 14.04 /16.04 successfull !

**Comment by tatsuhiro-t** [comment]
`make` does not install executables and library files.  Have you issue `make install`?
If you still cannot find nghttp binary, run `./configure --enable-app` option, and see what's missing as prerequisites.

**Comment by yaung** [comment]
Yes , I have execute `make install` ,Iwant to know are there any requirements for linux kernel version ?
Thank you !

**Comment by yaung** [comment]
I finally install the nghttp2 successfully ! however , I do not sure the key step !
I was updated the linux kernel to 3.10 and solved some dependencies and it works !

By the way , In the [https://nghttp2.org/documentation/nghttpx-howto.html](url) ,to make nghttpx listen to encrypted HTTP/2 requests at port 8443, and a backend Web server is configured to listen to HTTP request at port 8080 in the same host, run nghttpx command-line like this:

`$ nghttpx -f0.0.0.0,8443 -b127.0.0.1,8080 /path/to/server.key /path/to/server.crt`

But I wan to make nghttpx listen http1.1 request at port 8080, and  backend Web server is configured to listen to HTTP request at port 8443 in the same host 


`workers=4
no-ocsp=yes
frontend=*,8080;no-tls
backend=www.mytest.com,443;;proto=h2;tls
#http2-proxy=yes

tls-proto-list=TLSv1.2,TLSv1.1,TLSv1.0
ciphers=ECDHE-RSA-AES128..........
private-key-file=/pathto/mytest.key
certificate-file=/pathto/mytest.cert

log-level=INFO
#insecure=yes
accesslog-file=/usr/local/nghttpx/log/access.log
errorlog-file=/usr/local/nghttpx/log/error.log
add-x-forwarded-for=yes`

I want to kown the is this configure right ?
When I execute `nghttpx --conf=conf/nghttpx.conf` , it's exit without any tips .
