### ISSUE TITLE
nghttpx configure question 

### ISSUE THREAD

**Issue by yaung** [nghttp2/nghttp2#688]
nghttpx ,by default, frontend connection is encrypted using SSL/TLS. and the backend is http1.1 .
I want to implement the following process：
 **client --http1.1--> nghttpx -- http2-->nginx**
In other words，I use the nghttpx convert frontend( http1.1) to backend (http2). I follow the **nghttpx - HTTP/2 proxy - HOW-TO** guide and the configuration is :

`
user=root
workers=1
frontend=*,8080;no-tls
backend=127.0.0.1,8443;;proto=h2;tls
http2-proxy=yes
tls-proto-list=TLSv1.2,TLSv1.1,TLSv1.0
ciphers=ECDHE-RSA-AES128-G.................
client-cert-file=/usr/local/nghttpx/cert/mytest.cert
client-private-key-file=/usr/local/nghttpx/cert/mytest.key
no-ocsp=yes
npn-list=h2
#log-level=INFO
insecure=yes
accesslog-file=/usr/local/nghttpx/log/access.log
errorlog-file=/usr/local/nghttpx/log/error.log

`
The Nginx server configure:
 `listen 8443 ssl http2`

Then I use curl to send request : curl http://127.0.0.1:8080   (client, nghttpx ,nginx are in same machine)

The result is :400 bad request
and the access log is :127.0.0.1 - - [14/Sep/2016:19:51:15 +0800] "GET / HTTP/1.1" 400 144 "-" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2"

I use command `strace -p 12257 -ff`to test(12257 is nghttpx's pid), The result is 

`
epoll_wait(6, {{EPOLLIN, {u32=4, u64=4294967300}}}, 64, 59743) = 1
clock_gettime(CLOCK_MONOTONIC, {87065, 954985275}) = 0
accept4(4, {sa_family=AF_INET, sin_port=htons(41332), sin_addr=inet_addr("127.0.0.1")}, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 7
setsockopt(7, SOL_TCP, TCP_NODELAY, [1], 4) = 0
setsockopt(7, SOL_TCP, TCP_NODELAY, [1], 4) = 0
epoll_ctl(6, EPOLL_CTL_ADD, 7, {EPOLLIN, {u32=7, u64=17179869191}}) = 0
clock_gettime(CLOCK_MONOTONIC, {87065, 972897918}) = 0
epoll_wait(6, {{EPOLLIN, {u32=7, u64=17179869191}}}, 64, 59743) = 1
clock_gettime(CLOCK_MONOTONIC, {87065, 975888700}) = 0
read(7, "GET / HTTP/1.1\r\nUser-Agent: curl"..., 16384) = 175
clock_gettime(CLOCK_REALTIME, {1473853670, 390536000}) = 0
clock_gettime(CLOCK_REALTIME, {1473853670, 392716065}) = 0
read(7, 0x1e6883f, 16209)               = -1 EAGAIN (Resource temporarily unavailable)
writev(7, [{"HTTP/1.1 400 Bad Request\r\nServer"..., 321}], 1) = 321
clock_gettime(CLOCK_REALTIME, {1473853670, 397032463}) = 0
clock_gettime(CLOCK_REALTIME, {1473853670, 397410701}) = 0
write(11, "127.0.0.1 - - [14/Sep/2016:19:47"..., 183) = 183
shutdown(7, SHUT_WR)                    = 0
close(7)                                = 0
clock_gettime(CLOCK_MONOTONIC, {87065, 989660213}) = 0
epoll_wait(6, {}, 64, 1)                = 0
clock_gettime(CLOCK_MONOTONIC, {87065, 993528866}) = 0
clock_gettime(CLOCK_MONOTONIC, {87065, 994497699}) = 0
epoll_wait(6, {}, 64, 59743)            = 0
clock_gettime(CLOCK_MONOTONIC, {87125, 782355027}) = 0
clock_gettime(CLOCK_MONOTONIC, {87125, 782944578}) = 0
epoll_wait(6, {}, 64, 59743)            = 0
clock_gettime(CLOCK_MONOTONIC, {87185, 587682565}) = 0
clock_gettime(CLOCK_MONOTONIC, {87185, 588003887}) = 0
epoll_wait(6, {}, 64, 59743)            = 0
clock_gettime(CLOCK_MONOTONIC, {87245, 393073797}) = 0
clock_gettime(CLOCK_MONOTONIC, {87245, 394613167}) = 0

`
Is there any mistakes in nghttpx.conf ? Thank you !

**Comment by tatsuhiro-t** [comment]
If you are using nghttpx as reverse proxy, remove "http2-proxy=yes" from configuration.

**Comment by yaung** [comment]
Thanks for your reply !

It works When I remove the "http2-proxy=yes"  . Thanke you !

And another Question is about the `--cacert `, the certificate I used in the configuration is signed by myself ,  and I used `insecure=yes` ,when I remove `insecure=yes` and `use cacert=pathto/ca.pem` ,  It returns 503  error code . 
Did I forgot something ?

**Comment by tatsuhiro-t** [comment]
When insecure is no, it also checks host name we are connecting against the host name described in the certificate from remote server.  Perhaps, this does not match in your case.

With '-b127.0.0.1,8443;;proto=h2;tls", nghttpx expects '127.0.0.1' is in Subject Alt Name extension as IP address object.  By default, nghttpx use the host specified in -b option, but we can override it using sni parameter.  If the certificate is for the host 'example.com', for, example, using sni parameter works like this:  `-b127.0.0.1,8443;;proto=h2;tls;sni=example.com`

**Comment by yaung** [comment]
Thanks for your reply ! 
Can nghttpx load multi-configuration from path? 
The  multiple backend addresses configure Puzzled me , and if I have hundreds of remote server , the single configuration is too complex !

**Comment by tatsuhiro-t** [comment]
We have `include` option to read from another file.

**Comment by yaung** [comment]
Another puzzeled me is that the same configuration when I used , it works random ! It happens a few days ago , today it was recurrence. I did nothing and don't know why !
`  [FATAL] shrpx.cc:2413 Too few arguments`    version:nghttpx nghttp2/1.14.1

**Comment by yaung** [comment]
Thanks !
