### ISSUE TITLE
Conditional RST_STREAM in nghttpx 

### ISSUE THREAD

**Issue by rodrigobdz** [nghttp2/nghttp2#689]
I'm using `nghttpx` between a server and a client and depending on the path requested from the client I would like to `RST_STREAM` from `nghttpx` all push promises that were not sent yet by the server. 

From #675 I know that I have to call `nghttp2_submit_rst_stream` with  `nghttp2_frame.push_promise.promised_stream_id` as an argument to achieve that. 

The questions are: 
1. From which function should I get the request path from the client and call `nghttp2_submit_rst_stream`?
2. How do I get all `nghttp2_frame.push_promise.promised_stream_id`?

**Comment by tatsuhiro-t** [comment]
So you'd like to cancel push from backend server if client has certain request path.  Is that right?
If that is correct, then you can get request path from `downstream->request().path`, and if it matches the path, call `nghttp2_submit_rst_stream(session, NGHTTP2_FLAG_NONE, frame->push_promise.promised_stream_id, NGHTTP2_CANCEL)` in https://github.com/nghttp2/nghttp2/blob/3e1cfa8e99d8764a62efc8f071d087c04d69de27/src/shrpx_http2_session.cc#L975

**Comment by rodrigobdz** [comment]
I tried that out but unfortunately it is not working. Maybe the callback is not getting called. I tried logging to the console from `on_begin_headers_callback ` without success.

Without checking the path I'm calling `nghttp2_submit_rst_stream(session, NGHTTP2_FLAG_NONE, frame->push_promise.promised_stream_id, NGHTTP2_CANCEL)` to cancel all push promises from the server. Although the client should not receive anything pushed, he is receiving everything. 

I inserted the `nghttp2_submit_rst_stream` call between line 974 and 976 in **shrpx_http2_session.cc** as you suggested: 

```
assert(downstream->get_downstream_stream_id() == frame->hd.stream_id);

nghttp2_submit_rst_stream(session, NGHTTP2_FLAG_NONE, frame->push_promise.promised_stream_id, NGHTTP2_CANCEL)

if (http2session->handle_downstream_push_promise(downstream, promised_stream_id) != 0) {
  http2session->submit_rst_stream(promised_stream_id, NGHTTP2_CANCEL);
}
```

**Comment by tatsuhiro-t** [comment]
I assumed that backend performed push.  But it sounds like it doesn't.  How do you push resource to the client?  Are you using "link rel=preload"?

**Comment by rodrigobdz** [comment]
Yes, I'm using `link rel=preload` to push to the client.

**Comment by tatsuhiro-t** [comment]
Thanks.  Then you should look at this https://github.com/nghttp2/nghttp2/blob/3e1cfa8e99d8764a62efc8f071d087c04d69de27/src/shrpx_http2_upstream.cc#L1569

In this case, you don't have to use nghttp2_submit_rst_stream at all.  Here, you just check the request path, and if it matches, don't execute `prepare_push_promise(downstream)`.  That's all.

**Comment by rodrigobdz** [comment]
Thank you for your quick replies. I'll look into it and let you know how it went

**Comment by rodrigobdz** [comment]
It worked as intended! Thanks again

**Comment by rodrigobdz** [comment]
There was a misunderstanding regarding what the proxy should cancel.
With the last proposed solution, the proxy does not push any content for certain request paths.

What I want to achieve is the following:
For certain client request paths the proxy should RST_STREAM (`nghttp2_submit_rst_stream`) all **pending** `PUSH_PROMISES` from *previous* requests but still push content for the *current* request.

How do I get all pending `PUSH_PROMISES` from *previous* requests?

**Comment by tatsuhiro-t** [comment]
Sorry for silence, but I have really no idea how to achieve this in nghttpx code base.  This is because nghttpx does not store any relationship between requests.
If you are concerned about wasted bandwidth for server push, don't use push, or reduce the amount of the resource to push.  This is the state of server push right now.

**Comment by rodrigobdz** [comment]
Could you please tell me which function sends the pushed content to the client? I'm having trouble finding it.

**Comment by rodrigobdz** [comment]
I found already the `on_frame_send_callback` which takes care of pushing among other things
