### ISSUE TITLE
nghttp2_submit_request success but nghttp2_session_mem_send return total length is zero!

### ISSUE THREAD

**Issue by niceshell** [nghttp2/nghttp2#691]
call nghttp2_submit_request successfully(return stream id)，but call nghttp2_session_mem_send return zero, submit data was lost !

**Comment by tatsuhiro-t** [comment]
Normally, it shouldn't happen.  Could you share the source code to reproduce this issue?

**Comment by niceshell** [comment]
`        int stream_id = nghttp2_submit_request(m_session, NULL, nva, h_cnt, &data_prd, pstApnNode);
        pstApnNode->stream_id = m_stream_id;
        if ( stream_id < 0 )
        {
            JPSLOG_FATAL("["<<__FUNCTION__<<"] " << "SendEnhancedApn nghttp2_submit_request err " << stream_id << ", apnsid:" << pstApnNode->uiApnId
                 << ", uid:" << pstApnNode->uiApnId << ", touid:" << pstApnNode->uiToUid << ", platform:" << (int)pstApnNode->stPload()->_ucPlatform
                 << ", appkey:" << pstApnNode->stPload()->_strAppKey << ", msgId:" << pstApnNode->stPload()->_msgid);
            return 1;
        }
        JPSLOG_DEBUG("["<<__FUNCTION__<<"] For sslid: "<< m_uiSslId << " apnid: " << pstApnNode->uiApnId << " uid:" << pstApnNode->uiToUid <<" stream-id " <<stream_id << " last send stream id " << m_stream_id);
        string sdata;
        for(;;)
        {
            ssize_t n;
            const uint8_t *b;
            n = nghttp2_session_mem_send(m_session, &b);
            if(n == 0)
            {
                JPSLOG_INFO("["<<__FUNCTION__<<"] " <<"data over, total length: " << sdata.length());
                break;
            }
            else if(n < 0)
            {
                int rt = nghttp2_submit_rst_stream(m_session, NGHTTP2_FLAG_NONE,stream_id,NGHTTP2_CANCEL);
                JPSLOG_FATAL("["<<__FUNCTION__<<"] For sslid: "<< m_uiSslId << " apnid: " << pstApnNode->uiApnId << " uid:" << pstApnNode->uiToUid <<"Impossible error NO MEMORY total length: " << sdata.length() << " reset : " << rt);
                m_can_used = false;
                return 2; 
            }
            sdata.append((const char*)b, n);
        }`

**Comment by niceshell** [comment]
the code is very large, main line:
 int stream_id = nghttp2_submit_request(m_session, NULL, nva,...);
if(stream_id < 0)
{
    //log error
    return -1;
}
string sdata;
for(;;)
{
    ssize_t n;
            const uint8_t *b;
            n = nghttp2_session_mem_send(m_session, &b);
            if(n == 0)
            {
                JPSLOG_INFO("["<<__FUNCTION__<<"] " <<"data over, total length: " << sdata.length());
                break;
            }
            else if(n < 0)
            {
                //log error
                return -1;
            }
            sdata.append((const char*)b, n);
}
if(sdata.length() == 0)
{
    //error here
}

I think the bug i said is produced while send a lot of data, but don't read response! then the memory of nghttp2_session exhuast!

**Comment by niceshell** [comment]
No, it's not sdata caused issue. I‘m pretty sure about it, and you can test it with before code!
You can send lot of data, the issue can happend!

**Comment by tatsuhiro-t** [comment]
I tried to send one million of requests, but never got an issue.

**Comment by niceshell** [comment]
Can you show your code to me?

**Comment by tatsuhiro-t** [comment]
https://github.com/nghttp2/nghttp2/blob/e1dfff89296283f97e7b9141a5e2b5df5792c9c2/src/shrpx_http2_session.cc#L1660

**Comment by tatsuhiro-t** [comment]
I'd like to know how you know that nghttp2_session consumes too much memory.
Have you performed heap memory analysis?

**Comment by niceshell** [comment]
I found why  nghttp2_session_mem_send will return 0 while send data reach max_concurrent_streams!

**Comment by mars9180** [comment]
Hello.i have met same problem.Have you solved it?

**Comment by ackpengyao** [comment]
Hello, i have a question that execution nghttp2_session_mem_send  some  times  later  nghttp2_session_mem_send  return zero  ,accord to debug i found return zero place where nghttp2_session_pop_next_ob_item  return NULL lead to nghttp2_session_mem_send recevie zero,  here is my code flow:


/*
**  pack session data callback function
*/
ssize_t data_prd_read_callback(
    nghttp2_session *session, int32_t stream_id, uint8_t *buf, size_t length,
    uint32_t *data_flags, nghttp2_data_source *source, void *user_data) 
{
	static int iCount = 0;
	static char byFlag = 0;

	if (nread > length)
	{
	 	nread = length;		  
	}

	ft_fifo_seek(g_CaptureFifo, (char *)buf, 0, nread);

	ft_fifo_setoffset(g_CaptureFifo, nread);

	if (1 == byReadCallBackFlag)
	{
		*data_flags = NGHTTP2_DATA_FLAG_EOF;
		printf(YELLOW "data_flags = NGHTTP2_DATA_FLAG_EOF\n" NONE);
		byReadCallBackFlag = 0;
	}

	DEBUG_PRINTF("stream_id:%d, nread:%zu, length:%zu\r\n", stream_id, nread, length);

	return nread;
}

/* Send HTTP request to the remote peer */
static void submit_postAudiorequest(http2_session_data *session_data) 
{
	int32_t stream_id;
	char byTemp[128] = {0};
	//http2_stream_data *stream_data = session_data->stream_data[STREAM_ID_REQUESTAUDIO];
	http2_stream_data *stream_data = find_IDLEStream(MSGTEXT_PLAYBACKCONTROLLER);

	if (NULL == stream_data)
	{
		DEBUG_PRINTF("---Create idle stream failed..---");
	    return ;
	}

	const char *uri = stream_data->uri;
	const struct http_parser_url *u = stream_data->u;
	char byLength = 0;

	byLength = strlen(EVENTS_PATH);
	stream_data->path = malloc(byLength);
	memset(stream_data->path, 0, byLength);
	strcpy(stream_data->path, EVENTS_PATH);
	stream_data->pathlen = byLength;
	DEBUG_PRINTF("req->path length:%d, %s", byLength, stream_data->path);

	getToken();

	// Boundary
	strcpy(byTemp, "multipart/form-data; boundary=");
	strcat(byTemp, &g_boundary.m_postaudioBoundary);

	const nghttp2_nv hdrs[] = {
		MAKE_NV(":method", "POST"), 	MAKE_NV_CS(":path", stream_data->path),
		MAKE_NV(":scheme", "https"), MAKE_NV("accept", "*/*"),    
		MAKE_NV_CS("authorization", g_bysubmitToken),
		MAKE_NV_CS("content-type", byTemp),
	};


	nghttp2_data_provider data_prd;
	data_prd.source.ptr = NULL;
	data_prd.read_callback = data_prd_read_callback;
	DEBUG_PRINTF("data_prd_read_callback...");
	stream_id = nghttp2_submit_request(session_data->session, NULL, hdrs,
	                                 ARRLEN(hdrs), &data_prd, stream_data);
	if (stream_id < 0) {
	errx(1, "Could not submit HTTP request: %s", nghttp2_strerror(stream_id));
	}

	stream_data->stream_id = stream_id;

	g_iAudioStreamID = stream_data->stream_id;
}

void *Http2DataRequestPthread(void)
{

      submit_postAudiorequest(session_data);

      while(1)
      {
                        datalen = nghttp2_session_mem_send(session_data->session, &datap);
			if (0 == datalen)
			{
				break;
			}else 
                        {
			        iRet = bufferevent_write(bev, datap, datalen);
                        }
      }
}

**Comment by niceshell** [comment]
you need to care about 'left-window' size, if it was enough then nghttp2_session_mem_send will be return zero!

**Comment by ackpengyao** [comment]
first my libnghttp  version(2-1.18.1)  , in my libnghttp project have no 'left-window' size  so  i don't understand  'left-windown'  ,can u explain it.
second why left-window size enough then nghttp2_session_mem_send size, can we clean left-window size?

**Comment by niceshell** [comment]
Sliding Window

**Comment by ackpengyao** [comment]
which version do u used libnghttp2

**Comment by niceshell** [comment]
Usually, server has max stream limit, you need to assure your client's stream can't exceed it!
One way is you can keep tow value what are local stream and remote stream, you need to assure sum of them not exceed server max stream limit!
I use nghttp2 version is 1.11.1

**Comment by ackpengyao** [comment]
1.i debug found that  local stream and remote stream of sum( 3 stream )   server max stream 10, so i think client stream is ok，print as follows 
{
    ########session->remote_settings.max_concurrent_streams==10,line==2326
    ########session->num_outgoing_streams==3,line==2327
    ########session->local_settings.max_concurrent_streams==10,line==2328
    ########session->num_incoming_streams==0,line==2329
}

2.i issus is that nghttp2_session_mem_send some timer later return zero before pack session data,i am sure data size>0 , print as follows:
{
Client:[data_prd_read_callback:3242]"[INFO] C ----------------------------> S (DATA post body), stream_id:11 length:1369\n"
Client:[data_prd_read_callback:3260]"stream_id:11, nread:1369, length:1369\r\n"
send: padlen = 0, nothing to do
stream: stream=11 obq resched cycle=1469344
#########send: next frame: DATA
####send: start transmitting frame type=0, length=1378
####NGHTTP2_OB_SEND_DATA  line==3072
####NGHTTP2_OB_SEND_DATA  line==3079
####session_after_frame_sent2  line==3107
Client:[Http2DataRequestPthread:3515]"#########after nghttp2_session_mem_send function==Http2DataRequestPthread,datalen==1378,line==3515\n"
Client:[Http2DataRequestPthread:3516]"#########after nghttp2_session_mem_send function==Http2DataRequestPthread,datalen==1378,line==3516\n"
Client:[Http2DataRequestPthread:3530]"#########nghttp2_session_mem_send datalen:1378, bufferevent_write iRet:0"
####NGHTTP2_OB_SEND_DATA  line==3079
send: end transmission of a frame
####session_after_frame_sent2  line==3088
send: reset nghttp2_active_outbound_item
send: aob->item = (nil)
########session->remote_settings.max_concurrent_streams==10,line==2326
########session->num_outgoing_streams==2,line==2327
########session->local_settings.max_concurrent_streams==10,line==2328
########session->num_incoming_streams==0,line==2329
################nghttp2_session_pop_next_ob_item        line==2361
Client:[Http2DataRequestPthread:3515]"#########after nghttp2_session_mem_send function==Http2DataRequestPthread,datalen==0,line==3515\n"
Client:[Http2DataRequestPthread:3516]"#########after nghttp2_session_mem_send function==Http2DataRequestPthread,datalen==0,line==3516\n"
########session->remote_settings.max_concurrent_streams==10,line==2326
########session->num_outgoing_streams==2,line==2327
########session->local_settings.max_concurrent_streams==10,line==2328
########session->num_incoming_streams==0,line==2329
################nghttp2_session_pop_next_ob_item        line==2361
Client:[Http2DataRequestPthread:3515]"#########after nghttp2_session_mem_send function==Http2DataRequestPthread,datalen==0,line==3515\n"
Client:[Http2DataRequestPthread:3516]"#########after nghttp2_session_mem_send function==Http2DataRequestPthread,datalen==0,line==3516\n"
########session->remote_settings.max_concurrent_streams==10,line==2326
########session->num_outgoing_streams==2,line==2327
########session->local_settings.max_concurrent_streams==10,line==2328
########session->num_incoming_streams==0,line==2329
################nghttp2_session_pop_next_ob_item        line==2361
Client:[Http2DataRequestPthread:3515]"#########after nghttp2_session_mem_send function==Http2DataRequestPthread,datalen==0,line==3515\n"
Client:[Http2DataRequestPthread:3516]"#########after nghttp2_session_mem_send function==Http2DataRequestPthread,datalen==0,line==3516\n"
}

**Comment by ackpengyao** [comment]
1. i found my issue that session remote_window_size= 0 ,my client don't receive data to  update window size from amazon server machine when send data>65535, whether have some api or method repeat init window size  in nghttp2 lib before remote_window_size close equal zero ,i hope u could give me some advice thanks so much,by the way  my client just new one session to communicate with amazon server machine  my issue debug as print follows:

send: end transmission of a frame
####session_after_frame_sent2  line==3101
send: reset nghttp2_active_outbound_item
send: aob->item = (nil)
########session->remote_settings.max_concurrent_streams==10,line==2331
########session->num_outgoing_streams==2,line==2332
########session->local_settings.max_concurrent_streams==10,line==2333
########session->num_incoming_streams==0,line==2334
########session->recv_window_size==6145,line==2338
########session->local_window_size==65535,line==2339
########session->remote_window_size==0,line==2340
########session->window_update_queued==0,line==2341

**Comment by ranjithpp** [comment]
i am facing similar issue, if the data is high around 21K. client application is jmeter in asynchronous mode, nghttp2_session_mem_send returned zero.
