### ISSUE TITLE
"301 Moved Permanently" and "200 OK" Alternating occurs (nghttpx)

### ISSUE THREAD

**Issue by yaung** [nghttp2/nghttp2#693]
When I use nghttpx（nghttp2-1.14.1） as proxy, I send http1.1 request to nghttpx and want nghttpx send http2 request to server.
```
frontend=*,8080;no-tls
backend=nghttp2.org,443;/;proto=h2;tls
```
curl -v -o /dev/null nghttp2.org:8080 -x 127.1:8080
and the response "301 Moved Permanently" and "200 OK" Alternating occurs!

and I fond the nghttpx send `http `request ,not the `https ` request. 
The pakage captured：**the error log** :
```
27/Sep/2016:19:44:18 +0800 PID8263 [INFO] shrpx_http2_session.cc:1920 [DHTTP2:0x111be560] SSL/TLS handshake completed

27/Sep/2016:19:44:18 +0800 PID8263 [INFO] shrpx_ssl.cc:1478 Update cache entry for SSL_SESSION=0x111d0f10, addr=106.186.112.116:443, timestamp=1474976658.093753

27/Sep/2016:19:44:18 +0800 PID8263 [INFO] shrpx_http2_session.cc:1526 [DHTTP2:0x111be560] Negotiated next protocol: h2

27/Sep/2016:19:44:18 +0800 PID8263 [INFO] shrpx_http2_downstream_connection.cc:419 [DCONN:0x111b84f0] HTTP request headers

:method: GET

:scheme: **http**

:path: /

:authority: nghttp2.org:8080

user-agent: curl/7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5
pragma: no-cache

accept: */*

x-forwarded-proto: **http**

via: **1.1 nghttpx**

```
**the access file log** :
```
127.0.0.1 - - [27/Sep/2016:19:44:18 +0800] "GET / HTTP/1.1" 200 6625 "-" "curl/7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5"

127.0.0.1 - - [27/Sep/2016:19:45:10 +0800] "GET / HTTP/1.1" 301 178 "-" "curl/7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5"

127.0.0.1 - - [27/Sep/2016:20:40:59 +0800] "GET / HTTP/1.1" 200 6625 "-" "curl/7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5"

127.0.0.1 - - [27/Sep/2016:20:41:50 +0800] "GET / HTTP/1.1" 301 178 "-" "curl/7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5"
```

**Comment by tatsuhiro-t** [comment]
I could not reproduce this alternating HTTP codes.

> and I fond the nghttpx send httprequest ,not the https request.

Because you send HTTP request.  nghttp2.org:8080 is equivalent to `http://nghttp2.org:8080` in curl.

**Comment by tatsuhiro-t** [comment]
Could you give us the HTTP request header fields to backend for both 200 and 301 response?

And as far as I know, it is wrong to use nghttp2.org as proxy backend.  The backend should be HTTP/1.1 proxy, such as squid.

**Comment by yaung** [comment]
200 and 301 problem is due to the multi-backend , I used two host name as backend . 

backend=nghttp2.org,443;/;proto=h2;tls
backend=mytest.com,443;;proto=h2;tls

When I delete the second one , the problem is  gone !

But ,Why nghttp2.org  can not used as proxy backend ?  Does the nghttpx cannot convert http1.1 over tls (https) to http2 ? my origin server is support http2.

**Comment by tatsuhiro-t** [comment]
> my backend is nginx and support http2，I want nghttpx send http2 request to nginx directly , and don't use squid, did this ok ?

I think this use case is reverse proxy.

The way you use nghttpx with curl's -x option is forward proxy.  There is huge difference between them.
To use nghttpx as forward proxy, the backend must be HTTP/1.1 forward proxy.  nghttp2.org is a web site, not forward proxy.

Please refer to https://nghttp2.org/documentation/nghttpx-howto.html especially for default mode and HTTP/2 proxy mode.

**Comment by yaung** [comment]
OK，Thanks for your reply !

when I test the request as follow: the second response 400 ,the first with host in url ,and second has no host in url.
```
GET http://nghttp2.org/ HTTP/1.1
User-Agent: curl/7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/1.0.2h zlib/1.2.3 libidn/0.6.5
Host: nghttp2.org
Pragma: no-cache
Accept: */*
Proxy-Connection: Keep-Alive
```
response : HTTP/1.1 200 OK

```
GET / HTTP/1.1
User-Agent: curl/7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/1.0.2h zlib/1.2.3 libidn/0.6.5
Host: nghttp2.org
Pragma: no-cache
Accept: */*
Proxy-Connection: Keep-Alive
```
response: HTTP/1.1 400 Bad Request

is this a imperfection ?
