### ISSUE TITLE
nghttpx: Can't work as reverse proxy for specified purpose

### ISSUE THREAD

**Issue by antsn** [nghttp2/nghttp2#695]
Sorry, It's me again!
I'm a total noob in this field, and I just want to use nghttpx for connect to googlezip and skyzip, (etc).
I use old presto Opera and some light-weighted browsers, which are not supported by those extensions, and my ISP blocked some pages, which can access via these proxies.

**shrpx** worked perfectly in the past, but current version, which googlezip require specify header, and I were suggested to use nghttpx, and get some problem:

1. ~~At first, I installed old version `1.4` (in distro repository). It worked not as expected:~~
 * ~~sometimes, it worked, but mostly not~~
 * ~~by using `-LINFO`, **shrpx** and **nghttpx** send identical request headers, but only **shrpx** worked without problem. It seems that the extra header I added, is not sent (I think so, because the error page in the browser, with googlezip, and the quality of image with skyzip)~~
2. I installed the latest version `1.15`, but:
 * can't figure out to work with it, when the older version did not require private key, and certify (with `-p` option).

**Comment by antsn** [comment]
I updated comment,
1. My mistake, sorry.
2.
 * After following a tutorial: `https://blog.apar.jp/linux/2584`, then it shows `tls: handshake libssl error`
 * If added `no-tls`, I get `502 Bad Gateway`

**Comment by tatsuhiro-t** [comment]
There is large changes in command-line usage after v1.9.0.  Please refer to https://nghttp2.org/documentation/nghttpx-howto.html#migration-from-nghttpx-v1-8-0-or-earlier

**Comment by antsn** [comment]
This command worked with version 1.8.0:
`nghttpx -k -p -b default.px.skyzip.de,443 -f 127.0.0.1,8080 --add-request-header="X-Skyzip-Mode: medium"`

In version 1.15.0:
`nghttpx -k -b default.px.skyzip.de,443 -f localhost,8080 --add-request-header="X-Skyzip-Mode: medium" client.key client.crt -LINFO`

It showed error like this:
`01/Oct/2016:22:10:32 +0700 PID7927 [INFO] shrpx_connection.cc:397 tls: handshake libssl error: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
01/Oct/2016:22:10:32 +0700 PID7927 [INFO] shrpx_client_handler.cc:454 [CLIENT_HANDLER:0x7f9bb5516000] Deleting
01/Oct/2016:22:10:32 +0700 PID7927 [INFO] shrpx_client_handler.cc:477 [CLIENT_HANDLER:0x7f9bb5516000] Deleted
01/Oct/2016:22:10:32 +0700 PID7927 [INFO] shrpx_connection_handler.cc:361 [LISTEN:0x7ffeb372c5a0] Accepted connection from 127.0.0.1, fd=12`

**Comment by antsn** [comment]
It works now. Thanks for your patience!
