### ISSUE TITLE
Any plan on support signed_certificate_timestamp tls extension?

### ISSUE THREAD

**Issue by palxex** [nghttp2/nghttp2#696]
To support [Certificate Transparency](https://www.certificate-transparency.org/) in nghttpd/nghttpx, like [nginx-ct](https://github.com/grahamedgecombe/nginx-ct).

**Comment by tatsuhiro-t** [comment]
Will look into it.  Is that widely used?

**Comment by tatsuhiro-t** [comment]
As of 412c8f9e679455209ce9e8bcc8ba1966e92cf128, signed_certificate_timestamp support has been added to nghttpx.  We use the same binary format with nginx-ct and mod_ssl_ct.

**Comment by palxex** [comment]
Great efficient:) Tested with my letsencrypt cert, no any problem.
