### ISSUE TITLE
Chrome hangs when browsing some web pages.

### ISSUE THREAD

**Issue by joeshae** [nghttp2/nghttp2#697]
I'm using nghttpx(1.15.0 or below) as H2 frontend of squid(v3.5.21).
When I tried to browse some pages in Chrome (v53.0.2785.116), for example:
http://www.voachinese.com/p/6317.html

The chrome hangs for waiting for many pending requests.

![sc](https://cloud.githubusercontent.com/assets/6749515/19019633/ad3db02e-88c0-11e6-9417-06da4b45c796.png)

When the browser hung, I cannot even open a new tab for google.com.
Once I changed `npn-list=h2` to `npn-list=http/1.1` in nghttpx.conf, the problem disappeared.

```daemon=yes
http2-proxy=yes
frontend=0.0.0.0,443
backend=127.0.0.1,20
private-key-file=/usr/etc/certs/xxx.key
certificate-file=/usr/etc/certs/xxx.crt
npn-list=h2
```

Can you please take a look at this issue?
Thank you!

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.
Could you submit this issue to chromium bug tracker as well?  At the moment, we don't know which side (or both side) cause this issue.

**Comment by joeshae** [comment]
Hi Tatsuhiro, have you reproduced this issue in your environment?

**Comment by tatsuhiro-t** [comment]
No, I haven't tried it yet.

**Comment by tatsuhiro-t** [comment]
I could not reproduce this issue.

**Comment by joeshae** [comment]
This issue should be from a chrome's bug from my test.
So I close this now.
