### ISSUE TITLE
examples for multi-thread

### ISSUE THREAD

**Issue by grassdeveloper** [nghttp2/nghttp2#700]
I need to develop HTTP2 client in C language with multi-thread.
Do you have any examples for it?
I'm so grateful to provide　wonderful nghttp2.

Thanks

**Comment by tatsuhiro-t** [comment]
We have multi threaded client h2load and server nghttpd/nghttpx.  They are under src directory.
The rule of sum is that single nghttp2_session instance must only be used from one thread at any moment.
If you want to use it from multiple threads, you have to use locks.

**Comment by grassdeveloper** [comment]
Thank you for quick response. I will check it.
Please let me ask a question about one more thing.

For example, there are a main thread, and 3 child threads.
Then, each child thread has own session instance(nghttp2_session_client_new) 
and user_data.
If I set callback(nghttp2_session_callbacks_set_on_frame_recv_callback, etc...)
on each child thread. Is the callback executed by each child thread?

I would appreciate your cooperation.

**Comment by tatsuhiro-t** [comment]
Yes.  These callbacks are executed by the thread where nghttp2_session_*_{send,recv} are called.
As long as you call these functions in a particular thread, no lock is required.  This is how we are doing in our all applications.

**Comment by grassdeveloper** [comment]
Thank you for quick response. I get it now.
 Thank you again
