### ISSUE TITLE
Specifies a curve for ECDHE ciphers. 

### ISSUE THREAD

**Issue by dalf** [nghttp2/nghttp2#701]
Is there an equivalent of the [ssl_ecdh_curve](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_ecdh_curve) directive of nginx ?

To use something like ```ssl_ecdh_curve secp384r1;```

Is it related to https://github.com/nghttp2/nghttp2/blob/35594e09df1a589b301cdb364a814e0175c3c0ac/src/shrpx_ssl.cc#L572 ?

**Comment by tatsuhiro-t** [comment]
Previously, it was hard coded.
I just added --ecdh-curves option to nghttpx to specify list of named curves in the preference order.
See 8babaac

**Comment by dalf** [comment]
Thank's a lot!
