### ISSUE TITLE
nghttpx as the forward proxy

### ISSUE THREAD

**Issue by yaung** [nghttp2/nghttp2#709]
hello ! 
As I know, the nghttpx works as forword proxy should set `http2-proxy=yes`,  and I have several questions:

- does forword proxy (HTTP/2 proxy mode) supported multi-backend configuration ?

- why the backend must be http1.1 proxy (eg.squid) ? , I want configure it as http server.

- when I configure like `backend=nghttp2.org,443;proto=h2;tls` , It resolved `addr=106.186.112.116:443,`   and also works well. Does nghttpx resolved it ? 

or the case that  I send request `curl -svo /dev/null www.cloudflare.com:780 -x 127.1:8080` and resolve the IP address with local DNS ?

**Comment by tatsuhiro-t** [comment]
nghttpx has 2 modes.  The one mode is default mode, which is suitable for reverse proxy.  The second mode, which is enabled with --http2-proxy, is forward proxy mode, which is suitable for, well, forward proxy.

With --http2-proxy, it acts as frontend of HTTP forward proxy.  Thus it requires HTTP proxy, like squid, as backend.  You can configure to use h2 protocol for backend connection if you wish, but squid does not support h2 yet.

> does forword proxy (HTTP/2 proxy mode) supported multi-backend configuration ?

Yes

>  why the backend must be http1.1 proxy (eg.squid) ? , I want configure it as http server.

If you use web server as backend, nghttpx must be configured as default mode (reverse proxy).
You can configure nghttpx to use h2 for backend connection even with --http2-proxy, but squid does not support h2 yet.

>  when I configure like backend=nghttp2.org,443;proto=h2;tls , It resolved 
addr=106.186.112.116:443, and also works well. Does nghttpx resolved it ?

The difference is subtle, and it seems work, but there are several differences.  Use default mode for this purpose.

> the case that I send request curl -svo /dev/null www.cloudflare.com:780 -x 127.1:8080 and resolve the IP address with local DNS ?

If you are talking about name resolution of www.cloudflare.com, it is done by forward proxy 127.0.0.1:8080.  If it is nghttpx, it just forwards request to the host given in -b option, and nghttpx itself does not resolve www.cloudflare.com.

**Comment by yaung** [comment]
Thanks for your reply ！
