### ISSUE TITLE
libevent-server.c example not working

### ISSUE THREAD

**Issue by Meeuwisse** [nghttp2/nghttp2#710]
Took the code as given and put it in a 'test.c' file. I got it running after adding to the top;
```
#define _U_ __attribute__((unused))
#define HAVE_UNISTD_H
#define HAVE_FCNTL_H
```
Then compile with;
> gcc test.c -lnghttp2 -levent -lcrypto -lssl -levent_openssl -Wl,-rpath,/usr/local/lib -o serf

Connecting using chrome gives me security warnings, but this was to be expected as it's a simple locally created key/cert for testing using the instructions from [server fault](http://serverfault.com/a/224127). Clicking through to trust & load anyway gives me on the command line;
> $ ./serf 3000 server.key server.crt
> 127.0.0.1 connected
> 127.0.0.1 network error
> 127.0.0.1 disconnected
> 127.0.0.1 connected
> 127.0.0.1 network error
> 127.0.0.1 disconnected
> 127.0.0.1 connected

And then... nothing. Chrome appears to be waiting forever, the server doesn't do anything either. Doesn't matter if I load "https://localhost:3000/" or append index.html (this file is in the current directory alongside the executable). Refreshing or doing other requests result in nothing.

curl requests do still seem to be replied to with a 'connected' (and then followed by nothing);
> $ curl -v --http2 https://localhost:3000/index.html --insecure
> *   Trying 127.0.0.1...
> * Connected to localhost (127.0.0.1) port 3000 (#0)
> * Initializing NSS with certpath: sql:/etc/pki/nssdb
> * skipping SSL peer certificate verification
> * ALPN, server accepted to use h2
> * SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
> * Server certificate:
> * 	subject: O=Default Company Ltd,L=Default City,C=XX
> * 	start date: Oct 15 08:35:14 2016 GMT
> * 	expire date: Oct 15 08:35:14 2017 GMT
> * 	common name: (nil)
> * 	issuer: O=Default Company Ltd,L=Default City,C=XX
> * Using HTTP2, server supports multi-use
> * Connection state changed (HTTP/2 confirmed)
> * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
> * Using Stream ID: 1 (easy handle 0x558a386d2260)
> > GET /index.html HTTP/1.1
> > Host: localhost:3000
> > User-Agent: curl/7.43.0
> > Accept: */*
> > 
> * http2_recv: 16384 bytes buffer at 0x558a386d2ba8 (stream 1)
> 

In total, I get the impression that a connection is established (ignoring for the moment the consistent 2 failed attempts for Chrome connections, which curl doesn't do) and then the connection is simply dropped. Suggestions?

**Comment by tatsuhiro-t** [comment]
libevent-server works for me.  Have you tried to compile libevent-server with our standard toolchain?  If it is built in that way, doesn't that still work?

**Comment by Meeuwisse** [comment]
I'm wondering if my actual problem is not being able to figure out what the standard toolchain is, and/or missing how to use it. I did follow the configure/make steps to produce and install the libraries to the point that I can actually compile and link examples, obviously. But the instructions then seem to make a jump to 'just having' the nghttpd tool, for example.

How would you recommend I compile the examples? Perhaps I can then narrow down the differences if that turns out to result in a functional build. Thanks!

**Comment by tatsuhiro-t** [comment]
Well, I mean that if you run `make`, then applications under examples directory are compiled.  You can find binaries under examples directory.

**Comment by Meeuwisse** [comment]
I expected as much but it doesn't seem to happen - make is just telling me that nothing needs to be done. I just hit `make clean`, `autoconf`, `./configure`, and `make` again but there's still nothing showing up.

Just to double-check I haven't broken anything spectacularly, I `git clone` from github in a new folder, do [these instructions](https://github.com/nghttp2/nghttp2#building-from-git) (all versions are also fine, automake & autoconf give no output) and still end up with no binaries in the examples folder. `sudo make install` does seem to work fine.

**Comment by tatsuhiro-t** [comment]
./configure displays configuration summary, and it includes examples are going to be built or not:
```
    Features:
      ...
      Examples:       yes
```

If it shows "Examples: no", then examples is not going to be built.
Perhaps, some of prerequisites are missing.  The required third party libraries are OpenSSL and Libevent with OpenSSL enabled.   If you are using Linux distribution which uses its own package system, you'd to install development packages.
By default, these checks for prerequisites are done automatically, and if they are not met, examples are disabled silently.  If you give --enable-examples explicitly to ./configure script, it stops when it knows that examples cannot be built.  Could you try that?

Finally, programs under examples are not going to be installed with `make install`.

**Comment by Meeuwisse** [comment]
Right, so I had the same thought process after your hint that `make` should've done everything. Turns out that before I started playing with all this I didn't have libevent-openssl and installed it from source. But for some reason the `configure` still thought it wasn't there - still not sure what package to install to convince it otherwise - and I overlooked the configure output giving me the summary. For the moment this does the trick;
> ./configure LIBEVENT_OPENSSL_CFLAGS=-I/usr/local/include LIBEVENT_OPENSSL_LIBS="-L/usr/local/lib -levent_openssl -levent"

And I end up with the actual tools to install etc as well. Unfortunately, the behavior of the example remains the same as observed earlier. But now at least I can have nghttp shed some light on it;
> [  0.001] Connected
> The negotiated protocol: h2
> [  0.003] recv SETTINGS frame <length=6, flags=0x00, stream_id=0>
>           (niv=1)
>           [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
> [  0.003] send SETTINGS frame <length=12, flags=0x00, stream_id=0>
>           (niv=2)
>           [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
>           [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
> [  0.003] send SETTINGS frame <length=0, flags=0x01, stream_id=0>
>           ; ACK
>           (niv=0)
> [  0.004] send PRIORITY frame <length=5, flags=0x00, stream_id=3>
>           (dep_stream_id=0, weight=201, exclusive=0)
> [  0.004] send PRIORITY frame <length=5, flags=0x00, stream_id=5>
>           (dep_stream_id=0, weight=101, exclusive=0)
> [  0.004] send PRIORITY frame <length=5, flags=0x00, stream_id=7>
>           (dep_stream_id=0, weight=1, exclusive=0)
> [  0.004] send PRIORITY frame <length=5, flags=0x00, stream_id=9>
>           (dep_stream_id=7, weight=1, exclusive=0)
> [  0.004] send PRIORITY frame <length=5, flags=0x00, stream_id=11>
>           (dep_stream_id=3, weight=1, exclusive=0)
> [  0.004] send HEADERS frame <length=42, flags=0x25, stream_id=13>
>           ; END_STREAM | END_HEADERS | PRIORITY
>           (padlen=0, dep_stream_id=11, weight=16, exclusive=0)
>           ; Open new stream
>           :method: GET
>           :path: /index.html
>           :scheme: https
>           :authority: localhost:3000
>           accept: */*
>           accept-encoding: gzip, deflate
>           user-agent: nghttp2/1.16.0-DEV
> [ 10.013] send GOAWAY frame <length=8, flags=0x00, stream_id=0>
>           (last_stream_id=0, error_code=SETTINGS_TIMEOUT(0x04), opaque_data(0)=[])
> Some requests were not processed. total=1, processed=0

Doesn't matter if I ask for a (non-)existing file or just `https://localhost:3000/`, the result remains the same.

**Comment by tatsuhiro-t** [comment]
Given the fact that nghttpd works, and you built libevent for your own, it is probably related to libevent.
nghttpd does not use libevent.

I think libevent is quite popular, and most of the distributions have packaged it.  Why don't you use packaged version of libevent?  Does the distribution you are using lack libevent package?

libevent may be used by the other program, and its runtime library may be already installed under /usr.
And if you run an example, it may use system default libevent, rather than the on you compiled.
Try `LD_LIBRARY_PATH=/usr/local/lib examples/libevent-server` to load libevent from /usr/local/lib.
Or try to use system default one to compile nghttp2 again.

**Comment by Meeuwisse** [comment]
Right! Got it working. Still not entirely sure what the effect was of my attempts, but the cause was not so much missing libevent, but libevent-devel. No more additional magic was required after installing that package and the examples are functional. I'm putting this under progressing the learning curve.

Thanks for helping out!

**Comment by 0xsky** [comment]
I get the same problem.
`[xsky@vm libnghttp2]$ ldd httpd2 
	linux-vdso.so.1 =>  (0x00007fffa6772000)
	libssl.so.1.1 => /usr/local/openssl/lib/libssl.so.1.1 (0x00007f72ac2ef000)
	libcrypto.so.1.1 => /usr/local/openssl/lib/libcrypto.so.1.1 (0x00007f72abe87000)
	libnghttp2.so.14 (0x00007f72abc62000)
	libevent-2.1.so.6 => /usr/local/lib/libevent-2.1.so.6 (0x00007f72aba10000)
	libevent_openssl-2.1.so.6 => /usr/local/lib/libevent_openssl-2.1.so.6 (0x00007f72ab809000)
	libm.so.6 => /lib64/libm.so.6 (0x0000003d3c600000)
	librt.so.1 => /lib64/librt.so.1 (0x0000003d3ca00000)
	libdl.so.2 => /lib64/libdl.so.2 (0x0000003d3be00000)
	libc.so.6 => /lib64/libc.so.6 (0x0000003d3ba00000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003d3c200000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003d3b600000)
`
