### ISSUE TITLE
Preodiecally pushing frames to update a certain object

### ISSUE THREAD

**Issue by Typhoon1089** [nghttp2/nghttp2#712]
Hi Tatsuhiro,

How does the server push new frames to update a certain object (an image or the server clock, for example) every second. I already modified the asio-sv.cc as the following part but it returns in "segmentation fault (core dumped)". Please take a look and give me some advice.

```cpp
server.handle("/push", [&style_css](const request &req, const response &res) {

      boost::system::error_code ec;

      res.write_head(200);

      auto push3 = res.push(ec, "GET", "/push.png");
      push3->write_head(200);

      auto timer = std::make_shared<boost::asio::deadline_timer>(
          res.io_service(), boost::posix_time::seconds(1));
      auto closed = std::make_shared<bool>();

      res.on_close([timer, closed](uint32_t error_code) {
          timer->cancel();
          *closed = true;
      });

      auto key = std::make_shared<int>();
      *key = 0;
      timer->async_wait([&res, closed, key, &push3](const boost::system::error_code &ec) {
          if (ec || *closed) {
              return;
          }
          *key = *key + 1;  
          if (*key > 5) 
              res.end(file_generator("push.html"));
          else 
              push3->end(file_generator("push.png"));
     });

  });
```

[server_push.txt](https://github.com/nghttp2/nghttp2/files/537961/server_push.txt)

**Comment by tatsuhiro-t** [comment]
It looks like a bug of libnghttp2_asio.  Fix committed via 08a9a2e

**Comment by Typhoon1089** [comment]
Thank you for your quick reply.  I have just fixed this bug. 

The code line
`timer->async_wait([&res, closed, key, &push3](const boost::system::error_code &ec) {`
should be 
`timer->async_wait([&res, closed, key, push3](const boost::system::error_code &ec) {`

However, this is not a good solution for the issue because I have to define `push3` before `async_wait`. Thus, the image is sent only one time through out `push3.end()`, when the function defined by `async_wait` is called in the first time. Do you have any suggestion?

**Comment by tatsuhiro-t** [comment]
As far as I know, deadline_timer is one shot, I mean, once it fired, it never fire again.
If you expect repeated timer, you have to use another kind of timer or something else.  I don't know which timer you should use here.

**Comment by Typhoon1089** [comment]
Yep, you are right and it can be solved by use `expires_at`.
However, even the function called by `timer->async_wait` is invoked every second, I cannot push the object very seconds. It is because the `push3` is defined outside of `timer->async_wait()`.

My question is that, how the `push3` is created inside the function that is called by `async_wait`?
For example, in our source code, I expected the object image.png is sent twice, the latter is after 1 second, but only one object is sent.


      auto push3 = res.push(ec, "GET", "/push.png");
      push3->write_head(200);
      push3->end(file_generator("push.png"));

      timer->async_wait([&res, closed, key, push3](const boost::system::error_code &ec) {
          if (ec || *closed) {
              return;
          }
         push3->end(file_generator("push.png"));
     });

**Comment by tatsuhiro-t** [comment]
There are several ways to achieve this, but the rule is push stream is just like regular stream, and end() will close the stream.  If you'd like to push 3 streams, you have to create 3 independent push streams using res.push().

**Comment by Typhoon1089** [comment]
I have understood the rule and already fixed the bug. 
Thank you very much for your replies and for your time.
