### ISSUE TITLE
It takes nghttpx server long time to transfer response to nghttpx client occasionally.

### ISSUE THREAD

**Issue by joeshae** [nghttp2/nghttp2#713]
I have a dedicate server, on which is running nghttpx as a forwarded proxy server, and squid as its backend. Then I used another nghttpx on my PC as a forwarded proxy client. The connection between nghttpx client on my PC and nghttpx server on my server is h2 on public internet, which is fast and stable.
When I browse web pages, a few of the requests are extremely slow ( even up to 50s ) occasionally between the nghttpx server and the nghttpx client. But if I refresh the page, the issue disappears.

From the squid logs, I can see squid is always running well without problems.

Take an example, there are two requests which are very slow between the nghttpx server and the nghttpx client.

squid logs:
It takes squid only 71 ms to finish each request.

```
1476906315.576 2016-10-20 03:45:15 +0800 127.0.0.1:54162->1.2.3.4:26 71,-,71,71 8603=1472+7131 TCP_MISS/GET/200 http://pics.dmm.co.jp/digital/video/h_102nsps00099/h_102nsps00099pt.jpg "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36" -
```

```
1476906315.797 2016-10-20 03:45:15 +0800 127.0.0.1:18187->1.2.3.4:26 71,-,71,71 8263=1462+6801 TCP_MISS/GET/200 http://pics.dmm.co.jp/digital/video/emab00006/emab00006pt.jpg "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36" -
```

nghttpx server's logs:

It takes nghttpx server 15.420 seconds to finish the request. Actually it's cost by sending the response.
```
[20/Oct/2016:03:45:30 +0800] :28764->:443 6802 15.420 200 23322 h2 ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 - . "GET http://pics.dmm.co.jp/digital/video/h_102nsps00099/h_102nsps00099pt.jpg HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36"
```

It takes nghttpx server 15.199 seconds to finish the request. Actually it's cost by sending the response.
```
[20/Oct/2016:03:45:30 +0800] :28764->:443 6472 15.199 200 23322 h2 ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 - . "GET http://pics.dmm.co.jp/digital/video/emab00006/emab00006pt.jpg HTTP/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36"
```

nghttpx client's logs:
Please see the attachment [client.zip](https://github.com/nghttp2/nghttp2/files/540130/client.zip)

Search for `h_102nsps00099pt.jpg` and `emab00006pt.jpg` to see the related logs.
I've already tried to do this, but unfortunately I'm not familiar with the internal logics in nghttpx, so I cannot figure out the issues.

I want to know what's happening indeed in this situation.
Thank you!

**Comment by tatsuhiro-t** [comment]
I can confirm that nghttpx somehow very slow to send response to its client.  It received response header from backend:

```
20/Oct/2016:03:45:15 +0800 PID15557 [INFO] shrpx_https_upstream.cc:1205 [UPSTREAM:0x7f424ee6e240] HTTP response headers
HTTP/1.1 200 OK
```

And it finished sending the response body at:

```
20/Oct/2016:03:45:30 +0800 PID15557 [INFO] shrpx_https_upstream.cc:1176 [DOWNSTREAM:0x7f424ec39c00] HTTP response completed
```

It looks like there is large video transfer in the same HTTP/2 connection.
Are you changing backend HTTP/2 connection flow control window?

**Comment by joeshae** [comment]
Thank you tatsuhiro for your reply!

Yes, I've changed the window size, because the max speed between nghttpx client and server is only 20mbps with the default windows size.

nghttpx as a client:

```
......
daemon=yes
http2-proxy=yes
cacert=/usr/etc/certs/foobar.com.crt
insecure=yes

frontend=127.0.0.1,101;no-tls

backend=1.foorbar.com,443;;proto=h2;tls
backend=1.foorbar.com,443;;proto=h2;tls
backend=1.foorbar.com,443;;proto=h2;tls
backend=1.foorbar.com,443;;proto=h2;tls
backend=1.foorbar.com,443;;proto=h2;tls
backend=1.foorbar.com,443;;proto=h2;tls

workers=8
backlog=10240
fastopen=10240

backend-http2-window-size=16777215
backend-http2-connection-window-size=16777215

listener-disable-timeout=0
backend-connections-per-host=1024
# backend-connect-timeout=5s

api-max-request-body=256K
backend-connections-per-host=1024
request-header-field-buffer=256K
max-request-header-fields=1000
response-header-field-buffer=256K
max-response-header-fields=1000

no-via=yes

accesslog-file=/dev/null
errorlog-file=/var/log/nghttpx/error-tunnel-client-a.log

# accesslog-file=/var/log/nghttpx/access-tunnel-client-a.log
# accesslog-format=[$time_local] $remote_addr:$remote_port->:$server_port $body_bytes_sent $request_time $status $pid $alpn $ssl_cipher $ssl_protocol $ssl_session_id $ssl_session_reused "$request" "$http_user_agent"
```

**Comment by tatsuhiro-t** [comment]
First thing first, I think the delay is caused by exhaustion of HTTP/2 window size of nghttpx client.
You specified:

```
backend-http2-window-size=16777215
backend-http2-connection-window-size=16777215
```

So that's both 16MiB.  backend-http2-window-size sets window size for each stream (request), and backend-http2-connection-window-size is for connection, and it is shared by all streams.
The thing is the one stream, which looks like video stream, completely occupies whole connection window.  But for some reason, it does not freed up its share.  This is probably because browser stops reading video stream, e.g., stop pause button.  From the log, once the video stream is closed, all other streams' transfer started again.  This caused 15 seconds mysterious delay.
My suggestion is that you shouldn't change backend-http2-connection-window-size from default value.  Actually, we intentionally use very large window size for connection because of the above reason.

By the way, backend-http2-window-size=16M means that one stream can occupy 16MiB memory.  Since most of the server allows 100 concurrent streams, nghttpx may consume 1.6GB per backend connection.  Whether this is acceptable or not depends on the specification of machine.  Perhaps, it would be good to choose smaller value, say, 256KiB or 1M, and measure the performance.

**Comment by joeshae** [comment]
I'm very appreciate your reply. 
Your explanation is very clear and really helped me.
After I changed the backend-http2-connection-window-size back to 2147483647, the issue didn't appear any more.

By the way, 
if the nghttpx client connects to nghttpx server, 
the client config is:
```
backend-http2-window-size=16777215
backend-http2-connection-window-size=2147483647
```

and the server config is:
```
frontend-http2-window-size=65535
frontend-http2-connection-window-size=65535
```

Then what is the window size of stream between them, 16777215 or 65535?
What is the window size of connection between them, 2147483647 or 65535?

Thank you tatsuhiro!

**Comment by tatsuhiro-t** [comment]
Well, stream is bidirectional.
The window size of the data flowing from server to client is specified by backend-http2-* options.
The window size of the data flowing from client to server is specified by frontend-http2-* options.

**Comment by joeshae** [comment]
Understand! Thank you tatsuhiro!
