### ISSUE TITLE
CMake build doesn't generate a shared library with a version

### ISSUE THREAD

**Issue by remoe** [nghttp2/nghttp2#718]
The shared library of nghttp2 on windows doesn't have a version in it after build with cmake.

On Windows one need a ".rc" file, like:

https://github.com/nghttp2/nghttp2/blob/master/lib/Makefile.msvc#L211

**Comment by tatsuhiro-t** [comment]
Thank you.  Do you know how to integrate .rc file into cmake?

**Comment by remoe** [comment]
yes, i hope: https://github.com/nghttp2/nghttp2/pull/719
