### ISSUE TITLE
How does the server handle CANCEL message?

### ISSUE THREAD

**Issue by Typhoon1089** [nghttp2/nghttp2#720]
Hello Tatsuhiro Tsujikawa-san, 
I used `libnghttp2_asio` to make a HTTP/2 server (e.g., `asio-sv2.cc`). And my question is how the server knows when CANCEL msg arrives, so that the server can keep the current cancelled object to re-push in another appropriate time instant? 
Furthermore, which function is responsible for handling CANCEL msg sent by the client?
Thank you very much for your time.

**Comment by tatsuhiro-t** [comment]
Assuming that CANCEL refers to RST_STREAM with error code CANCEL, you get the error code using a callback set by `nghttp2::asio_http2::server::response::on_close`.
The request and response objects are invalidated after on_close callback, so you should initiate new server push (if the canceled stream is server push, of course).

**Comment by Typhoon1089** [comment]
Thank you very much.

It is very helpful.
