### ISSUE TITLE
Is nghttpx bind to IP or address?

### ISSUE THREAD

**Issue by humiaozuzu** [nghttp2/nghttp2#721]
I'm using nghttpx as a client on my macbook and connecting to server using H2 tunnel.

It seems that nghttpx still bind to server old IP even when my domain dns record changed
```
backend=mydomain.com,443;;proto=h2;tls
```

Is this expected behavior? How can I make nghttpx bind to new address when domain record changed?

**Comment by tatsuhiro-t** [comment]
nghttpx resolves hostname at the startup, and continues to use IP address.
nghttpx must be restarted, or reloaded to resolve host name again.

**Comment by humiaozuzu** [comment]
@tatsuhiro-t Do you have plan to change this behavior?

**Comment by tatsuhiro-t** [comment]
I have no particular plan for this at the moment.   After all, nghttpx is reverse proxy, and we somehow assume that backend has stable IP address.
How often does your backend host name resolve to different IP address?

**Comment by humiaozuzu** [comment]
@tatsuhiro-t As a reverse proxy on server it's no need to support domain. but when using is as a client on computer, it quite useful.
My H2 tunnel host has many ip in different ISP pointing to the same domain just like CDN domains. When I carry my mac to my home. My ISP change to another. It will be quite convenient when I do not need to restart nghttpx

**Comment by yaung** [comment]
Restarted, or reloaded to resolve host name was unpractical in prodution environment , so It's really  a requisite function.

**Comment by yaung** [comment]
@tatsuhiro-t 
I am get error when reloading configure file (it's a IP address configure file, to solve the dynamic IP problem )
The file_stat_cb function monitor a file ,when it's changed ,the function will be invoked !
`
void file_stat_cb(struct ev_loop *loop, ev_stat *w, int revents){
  LOG(NOTICE) << "file anyhost changed ! ";
  auto wp = static_cast<WorkerProcess *>(w->data);
  if (wp->worker_pid == -1) {
  LOG(NOTICE) << "reload_config failed !! ";
    ev_break(loop);
    return;
  }
  reload_config(wp);
  LOG(NOTICE) << "reload_config success !! ";
  return;
}
`

and get error : It seems like reloading default configure ,not my own configuration file.

`17/Nov/2016:18:10:55 +0800 PID14177 [NOTICE] file anyhost changed ! 
17/Nov/2016:18:10:55 +0800 PID14177 [NOTICE] Reloading configuration
17/Nov/2016:18:10:55 +0800 PID14177 [INFO] shrpx_config.cc:3374 Resolving backend address
17/Nov/2016:18:10:55 +0800 PID14177 [INFO] shrpx_config.cc:3384 Host-path pattern: group 0: '/'
17/Nov/2016:18:10:55 +0800 PID14177 [INFO] shrpx_config.cc:3387 group 0 -> 127.0.0.1:80, proto=http/1.1
17/Nov/2016:18:10:55 +0800 PID14177 [INFO] shrpx_config.cc:3403 Catch-all pattern is group 0
17/Nov/2016:18:10:55 +0800 PID14177 [INFO] shrpx_config.cc:3515 Address resolution for 127.0.0.1 succeeded: 127.0.0.1
17/Nov/2016:18:10:55 +0800 PID14177 [INFO] shrpx_config.cc:3452 Resolved backend address: 127.0.0.1:80 -> 127.0.0.1:80
17/Nov/2016:18:10:55 +0800 PID14177 [NOTICE] Listening on 0.0.0.0:3000, tls
17/Nov/2016:18:10:55 +0800 PID14177 [NOTICE] Listening on [::]:3000, tls
17/Nov/2016:18:10:55 +0800 PID14177 [NOTICE] Worker process [14182] spawned
17/Nov/2016:18:10:55 +0800 PID14177 [NOTICE] reload_config success !! 
17/Nov/2016:18:10:55 +0800 PID14177 [NOTICE] Graceful shutdown signal received
17/Nov/2016:18:10:55 +0800 PID14177 [NOTICE] Worker process shutting down momentarily
17/Nov/2016:18:10:55 +0800 PID14177 [NOTICE] Worker process: [14178] exited normally with status 0; exit status 0
17/Nov/2016:18:10:55 +0800 PID14177 [NOTICE] Worker process: [14182] exited normally with status 100; exit status 1`


what is the problem ?

**Comment by tatsuhiro-t** [comment]
No idea since this is your modified code.
Perhaps, you are using wrong ev_loop?

**Comment by yaung** [comment]
When reload the configure file , I found that the master process is still alive and the work process is die because of recieve the  SHRPX_IPC_GRACEFUL_SHUTDOWN signal, I don't kown why ?

**Comment by tatsuhiro-t** [comment]
For the record, with the following patch, I saw that configuration is reloaded when it is modified:

```cpp
diff --git a/src/shrpx.cc b/src/shrpx.cc
index 8e1a727..1036795 100644
--- a/src/shrpx.cc
+++ b/src/shrpx.cc
@@ -174,6 +174,10 @@ namespace {
 void worker_process_child_cb(struct ev_loop *loop, ev_child *w, int revents);
 } // namespace
 
+namespace {
+void conf_path_cb(struct ev_loop *loop, ev_stat *w, int revents);
+} // namespace
+
 struct WorkerProcess {
   WorkerProcess(struct ev_loop *loop, pid_t worker_pid, int ipc_fd)
       : loop(loop), worker_pid(worker_pid), ipc_fd(ipc_fd) {
@@ -198,6 +202,11 @@ struct WorkerProcess {
                   0);
     worker_process_childev.data = this;
     ev_child_start(loop, &worker_process_childev);
+
+    auto config = get_config();
+    ev_stat_init(&conf_pathev, conf_path_cb, config->conf_path.c_str(), 0);
+    conf_pathev.data = this;
+    ev_stat_start(loop, &conf_pathev);
   }
 
   ~WorkerProcess() {
@@ -216,6 +225,7 @@ struct WorkerProcess {
     ev_signal_stop(loop, &exec_binary_signalev);
     ev_signal_stop(loop, &graceful_shutdown_signalev);
     ev_signal_stop(loop, &reload_signalev);
+    ev_stat_stop(loop, &conf_pathev);
   }
 
   ev_signal reopen_log_signalev;
@@ -223,6 +233,7 @@ struct WorkerProcess {
   ev_signal graceful_shutdown_signalev;
   ev_signal reload_signalev;
   ev_child worker_process_childev;
+  ev_stat conf_pathev;
   struct ev_loop *loop;
   pid_t worker_pid;
   int ipc_fd;
@@ -233,6 +244,19 @@ void reload_config(WorkerProcess *wp);
 } // namespace
 
 namespace {
+void conf_path_cb(struct ev_loop *loop, ev_stat *w, int revents) {
+  auto wp = static_cast<WorkerProcess *>(w->data);
+  LOG(NOTICE) << "Reloading configuration file";
+  if (!w->attr.st_nlink) {
+    LOG(NOTICE) << "conf path not found";
+    return;
+  }
+
+  reload_config(wp);
+}
+} // namespace
+
+namespace {
 std::deque<std::unique_ptr<WorkerProcess>> worker_processes;
 } // namespace
 
```

**Comment by humiaozuzu** [comment]
@tatsuhiro-t 
Like nginx when the value for app_servers changed, nginx will change to new backend app in realtime. Can nghttpx add a domain timeout (such as 1mins)?

```
location / {
    proxy_set_header   Host             $host;
    proxy_set_header   X-Real-IP        $remote_addr;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_pass         http://app_servers;
}
```

**Comment by tatsuhiro-t** [comment]
What is "domain timeout"?  How it works?

**Comment by humiaozuzu** [comment]
@tatsuhiro-t nghttpx get domain record every n mintutes(timeout)，when domain record changes, it connect to new backend next time.

**Comment by tatsuhiro-t** [comment]
Thank you.
work in progress.
