### ISSUE TITLE
Problem with zero length POST requests on Firefox with nghttpx

### ISSUE THREAD

**Issue by rraptorr** [nghttp2/nghttp2#726]
I've stumbled upon a weird issue with Firefox. Recently I've noticed that one of my legacy applications, stopped working in Firefox. Disabling HTTP/2 fixed the problem, so I've started debugging. Also, the problem was found only on Firefox, Chrome was working perfectly fine. Switching nghttpx to nginx also fixes the problem.

I am using nghttpx behind a haproxy, which does TLS. The application, makes several POST requests with no data (Content-Length: "0"). Those requests, when sent from Firefox, were constantly giving 502 errors from nghttpx. Traffic dumps showed that the request was never ever forwarded to a downstream.
After stripping the setup down to simplify it I was able to capture some traffic dumps and I've found a small difference between HTTP/2 frames generated by Firefox and Chrome. Firefox generates a HEADERS frame, followed by empty DATA frame. Chrome generates only HEADERS frame, with no DATA frame.

Unfortunately, the problem is not that easy to reproduce. When making such request from JS console everything works fine. However, the application makes many POST requests concurrently and this seems to trigger the problem. Changing all POST requests to send a single byte fixed the problem for me.

nghttpx version: 1.16.0, but 1.15.0 is also affected
Firefox HTTP/2 traffic dump: https://sky.nails.eu.org/files/fx-dump.pcapng
Firefox log: https://sky.nails.eu.org/files/fx.log
Chrome HTTP2 traffic dump: https://sky.nails.eu.org/files/ch-dump.pcapng
Chrome log: https://sky.nails.eu.org/files/ch.log

The problematic request is POST to URL /standalone/api/getSessionId

**Comment by tatsuhiro-t** [comment]
Thank you for telling us.
This is a regression introduced by the commit 231d739b1095d850552de434eb4818cb33cfb10d
The fix has been committed via 2b75aff32e529207175fb12fe05ed3d1dea27132

**Comment by rraptorr** [comment]
Thanks. I've rebuilt 1.16.0 with this patch and everything forks fine now.
