### ISSUE TITLE
Update backends via API with DNS entry/ non-numeric hostname

### ISSUE THREAD

**Issue by markbarks** [nghttp2/nghttp2#731]
I'd like to use the nghttpx api to update backend configuration as new services get created in my cluster. However, I ran into this limitation:

> The one limitation is that only numeric IP address is allowed in backend in request body while non numeric hostname is allowed in command-line or configuration file is read using --conf.

What is the reason for that? Would it be something easy to add? I can see about sending a PR if so.

If it's not straightforward - if I have a buddy service that will update the on disk config, and execute a SIGHUP, will the existing connections or request be preserved?

Thanks

**Comment by tatsuhiro-t** [comment]
#721 is the related topic.

> What is the reason for that? Would it be something easy to add? I can see about sending a PR if so.

Since we do API handling in a dedicated thread, we can do blocking name resolution, but in general, DNS is slow, it could hold up following API calls.
For better approach, we need to add non-blocking DNS query to nghttpx, or create a dedicated thread to do just DNS, which are not so straightforward.

> If it's not straightforward - if I have a buddy service that will update the on disk config, and execute a SIGHUP, will the existing connections or request be preserved?

Using SIGHUP keeps existing connections, yes.  nghttpx does the graceful shutdown.

**Comment by markbarks** [comment]
Thanks for the quick response.

Does the API server get busy enough that many requests would be queued whilst it was doing a DNS lookup though? That certainly wouldn't be the case in my use-case.

If the SIGHUP keeps existing connections, I will just go for the buddy-service for the time being however.  Cheers.

**Comment by tatsuhiro-t** [comment]
> Does the API server get busy enough that many requests would be queued whilst it was doing a DNS lookup though? That certainly wouldn't be the case in my use-case.

This probably depends on the site.  Currently, we only have one API, and it might no be frequently called.  But we may add new API in the future, then we are in trouble especially if new API needs faster response.  In general, nghttpx uses event based approach, and it never be a good idea to use blocking DNS there.

If you'd like to try blocking DNS, replace "true" with "false"
https://github.com/nghttp2/nghttp2/blob/d83949bc88c90866e705c588ca5233dd5192cf10/src/shrpx_api_downstream_connection.cc#L274

**Comment by tatsuhiro-t** [comment]
FYI, we are going to implement dynamic DNS support in backend.  If it is ever implemented, we will allow non-numeric hostname in api call.

**Comment by tatsuhiro-t** [comment]
Now nghttpx supports dynamic DNS support for backend servers.  With "dns" parameter in backend option, non-numeric host name is allowed in backend API call.
