### ISSUE TITLE
nghttpx proxy cause exception while invoke the gRPC service twice

### ISSUE THREAD

**Issue by sc-syf** [nghttp2/nghttp2#739]
I used the nghttpx as the proxy of my gRPC service.

while I invoke the gRPC method at the first time, it works well. However,  if I invoke the method after few minutes,  it will cause a exception:
> <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, {"created":"@1481021223.548072702","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235,"grpc_status":14})>

started the gRPC server with 'GRPC_TRACE=all GRPC_VERBOSITY=DEBUG', after I invoked a method and wait for few seconds(may 60 seconds), I saw the following info:

> D1206 10:41:36.947737420   24342 tcp_posix.c:168]            read: error={"created":"@1481020896.947716810","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235}
D1206 10:41:36.947769942   24342 parsing.c:98]               FLOW    parse: server stream[3] MOVE                                 parsing.incoming_window(65510) <-          global.unannounced_incoming_window_for_parse(65560) giving 131070
D1206 10:41:36.947783515   24342 chttp2_transport.c:459]     W:0x7fdb7c001240 close transport
D1206 10:41:36.947788092   24342 chttp2_transport.c:2127]    set connectivity_state=4
D1206 10:41:36.947798455   24342 connectivity_state.c:156]   SET: 0x7fdb7c003590 server_transport: READY --> SHUTDOWN [close_transport] error=0x7fdb7c006280 {"created":"@1481020896.947716810","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235,"grpc_status":14}
D1206 10:41:36.947804297   24342 connectivity_state.c:183]   NOTIFY: 0x7fdb7c003e50
D1206 10:41:36.947840406   24342 chttp2_transport.c:2096]    R:0x7fdb7c001240 -> 0 ws=INACTIVE

besides, I run the nghttpx with "--conf=/etc/nghttpx/proxy.conf -LINFO", there is no info printed.

However, while I removed the nghttpx and connect the gRPC server directly, it won't print that exception.

is it a bug of nghttpx?   or I didn't use the nghttpx with the right way?

here is my nghttpx config file:
>frontend=0.0.0.0,6000;no-tls
backend=10.10.10.9,30401;;proto=h2;no-tls;
backend=10.10.10.9,30402;;proto=h2;no-tls;
backend=10.10.10.9,30403;;proto=h2;no-tls;
backend=10.10.10.9,30404;;proto=h2;no-tls;
workers=8

python version: 2.7.6
grpcio version: 1.0.1
nghttpx version: nghttp2/1.17.0
system:  ubuntu 14.04

**Comment by tatsuhiro-t** [comment]
-LINFO should print logging messages, but if it doesn't, it is probably redirected to other files.
Could you share us content of /etc/nghttpx/proxy.conf?  It is most likely that errorlog-file is used somewhere.

**Comment by tatsuhiro-t** [comment]
I tested with greeter_server in examples directory of Go's grpc repository, and it works very much fine for me.

**Comment by sc-syf** [comment]
@tatsuhiro-t  I forget there exsits an error log .....
this is the bottom of error.log info:

>10/Dec/2016:20:00:46 +0800 PID31514 [INFO] shrpx_http2_upstream.cc:1739 [DOWNSTREAM:0x7fadc1494300] HTTP response completed
10/Dec/2016:20:00:46 +0800 PID31514 [INFO] shrpx_http2_downstream_connection.cc:115 [DCONN:0x7fadc14128c0] Detaching from DOWNSTREAM:0x7fadc1494300
10/Dec/2016:20:00:46 +0800 PID31514 [INFO] shrpx_http2_downstream_connection.cc:56 [DCONN:0x7fadc14128c0] Deleting
10/Dec/2016:20:00:46 +0800 PID31514 [INFO] shrpx_http2_session.cc:627 [DHTTP2:0x7fadc1423500] Remove downstream
10/Dec/2016:20:00:46 +0800 PID31514 [INFO] shrpx_http2_downstream_connection.cc:89 [DCONN:0x7fadc14128c0] Deleted
10/Dec/2016:20:00:46 +0800 PID31514 [INFO] shrpx_http2_session.cc:723 [DHTTP2:0x7fadc1423500] Stream stream_id=3 is being closed with error code 0
10/Dec/2016:20:00:46 +0800 PID31514 [INFO] shrpx_http2_upstream.cc:62 [UPSTREAM:0x7fadc1434140] Stream stream_id=3 is being closed
10/Dec/2016:20:00:46 +0800 PID31514 [INFO] shrpx_downstream.cc:162 [DOWNSTREAM:0x7fadc1494300] Deleting
10/Dec/2016:20:00:46 +0800 PID31514 [INFO] shrpx_downstream.cc:192 [DOWNSTREAM:0x7fadc1494300] Deleted
10/Dec/2016:20:00:46 +0800 PID31514 [INFO] shrpx_client_handler.cc:480 [CLIENT_HANDLER:0x7fadc141d000] Deleting
10/Dec/2016:20:00:46 +0800 PID31514 [INFO] shrpx_client_handler.cc:503 [CLIENT_HANDLER:0x7fadc141d000] Deleted
10/Dec/2016:20:00:47 +0800 PID31514 [INFO] shrpx_connect_blocker.cc:34 Unblock
10/Dec/2016:20:00:47 +0800 PID31514 [INFO] shrpx_connect_blocker.cc:34 Unblock
10/Dec/2016:20:00:47 +0800 PID31514 [INFO] shrpx_connect_blocker.cc:34 Unblock
10/Dec/2016:20:00:51 +0800 PID31514 [INFO] shrpx_http2_session.cc:82 [DHTTP2:0x7fadc1423500] connection check required
10/Dec/2016:20:01:46 +0800 PID31514 [INFO] shrpx_http2_session.cc:119 [DHTTP2:0x7fadc1423500] Timeout
10/Dec/2016:20:01:46 +0800 PID31514 [INFO] shrpx_http2_session.cc:2227 [DHTTP2:0x7fadc1423500] Remove from http2_avail_freelist, group=0x7fadc4417118, freelist.size=1
10/Dec/2016:20:01:46 +0800 PID31514 [INFO] shrpx_http2_session.cc:240 [DHTTP2:0x7fadc1423500] Disconnecting


I saw the exception of gRPC server in the same time, and I found that exception printed in the same time while nghttpx error.log printed last three lines.

**Comment by sc-syf** [comment]
p.s. I didn't use Go. I used Python.

**Comment by tatsuhiro-t** [comment]
Thank you.

> 10/Dec/2016:20:00:47 +0800 PID31514 [INFO] shrpx_connect_blocker.cc:34 Unblock
> 10/Dec/2016:20:00:47 +0800 PID31514 [INFO] shrpx_connect_blocker.cc:34 Unblock
> 10/Dec/2016:20:00:47 +0800 PID31514 [INFO] shrpx_connect_blocker.cc:34 Unblock

These lines of log indicates that nghttpx failed to connect to backend gRPC servers.
The error log when this happened should exist somewhere in the earlier part of the log, and does not appear in the above comment.
Could you show us more logs?  It would be better to give us complete log of nghttpx after sanitizing any confidential data.

**Comment by tatsuhiro-t** [comment]
I tried https://github.com/grpc/grpc/blob/v1.0.0/examples/python/route_guide/route_guide_server.py and it works very well with nghttpx.

**Comment by tatsuhiro-t** [comment]
Are all those backend gRPC services up and running?

**Comment by sc-syf** [comment]
@tatsuhiro-t no,  my nghttpx proxy to 4 backend, but I closed other three port to catch the exception info in case of  route to others server port which is not has the debug info.

this is the error.log file. Thanks.
[error.txt](https://github.com/nghttp2/nghttp2/files/644244/error.txt)

**Comment by sc-syf** [comment]
@tatsuhiro-t  and, even if I opened all of 4 backend, it will also cause that exception.

**Comment by tatsuhiro-t** [comment]
Thank you.
The availability of backends are no problem.  nghttpx can handle this kind of situation.
From error.txt, I see that there were 2 requests, but they both were successful.  No error is logged there.
Did the exception occur after this logging?

**Comment by tatsuhiro-t** [comment]
>>    [DHTTP2:0x7fadc1423500] Timeout
    10/Dec/2016:20:01:46 +0800 PID31514 [INFO] shrpx_http2_session.cc:2227 [DHTTP2:0x7fadc1423500] Remove from http2_avail_freelist, group=0x7fadc4417118, freelist.size=1
    10/Dec/2016:20:01:46 +0800 PID31514 [INFO] shrpx_http2_session.cc:240 [DHTTP2:0x7fadc1423500] Disconnecting

>I saw the exception of gRPC server in the same time, and I found that exception printed in the same time while nghttpx error.log printed last three lines.

I think this is not a problem. nghttpx just dropped connection because there is no request/response in predefined period of time.  What kind of exception does gRPC server throw?

**Comment by sc-syf** [comment]
@tatsuhiro-t   while nghttpx dropped that connection, in the mean time, the gRPC server printed:
>D1206 10:41:36.947737420   24342 tcp_posix.c:168]            read: error={"created":"@1481020896.947716810","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235}
D1206 10:41:36.947769942   24342 parsing.c:98]               FLOW    parse: server stream[3] MOVE                                 parsing.incoming_window(65510) <-          global.unannounced_incoming_window_for_parse(65560) giving 131070
D1206 10:41:36.947783515   24342 chttp2_transport.c:459]     W:0x7fdb7c001240 close transport
D1206 10:41:36.947788092   24342 chttp2_transport.c:2127]    set connectivity_state=4
D1206 10:41:36.947798455   24342 connectivity_state.c:156]   SET: 0x7fdb7c003590 server_transport: READY --> SHUTDOWN [close_transport] error=0x7fdb7c006280 {"created":"@1481020896.947716810","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235,"grpc_status":14}
D1206 10:41:36.947804297   24342 connectivity_state.c:183]   NOTIFY: 0x7fdb7c003e50
D1206 10:41:36.947840406   24342 chttp2_transport.c:2096]    R:0x7fdb7c001240 -> 0 ws=INACTIVE


and, I will not got exception if at this time I invoke the method again.

However, the client exception
><_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, {"created":"@1481021223.548072702","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235,"grpc_status":14})>
will raise if I wait for few minutes after the first time invocation and invoke it twice,  but I don't know what the exactly time I should wait to trigger this client exception.

**Comment by tatsuhiro-t** [comment]
So, exception from backend is not a problem.  Let's focus at client side connection.

What I think strange is that the request which causes client side exception is not logged in nghttpx error log.  It means that nghttpx does not get connection at all. Is there any other error log?
If nghttpx returned Unavailable (503) status code, then at least the log should contain the entry that nghttpx accpeted connection from client, but currently it is missing.

How do you send request to nghttpx?  Is that some kind of command-line program?  Is that configured to connect to the nghttpx?

**Comment by sc-syf** [comment]
oh. the error.log's content doesn't contains second invocation. Could you please wait for few minutes and I will reproduce the whole process.

**Comment by sc-syf** [comment]
@tatsuhiro-t I'm so sorry...... I can't reproduce the exception...... 
that exception doesn't happened at all......

but it is the truth that I got that error at many times.
I'll test it tomorrow......

thank you.

**Comment by sc-syf** [comment]
@tatsuhiro-t     
[error.txt](https://github.com/nghttp2/nghttp2/files/645271/error.txt)
this is the whole error.log. the last connection raised exception.

I may found what's goes wrong. I declared the  client like a singleton, and use it at everywhere:
gRPC client snippet:
```
class EventClient:                                                               
    def __init__(self, host=''10.10.64.15', port=50501):                                                      
        conn_str = '{}:{}'.format(host, port)                                    
        self.channel = grpc.insecure_channel(conn_str)                           
        self.stub = event_pb2.EventHandlerStub(self.channel)      

               
    def get_event(self, event_id):                                        
        event_resp = self.stub.get_event(event_pb2.EventRequest(event_id=event_id))
        return event_resp
```
and at my client side, I used Django. at views.py, the invocation snippet is :
```
ec  = EventClient()
def get_details(request):
     ec.get_event(request.GET.get('id', '0'))
```
rather than:  
```
def get_details(request):
     ec  = EventClient()
     ec.get_event(request.GET.get('id', '0'))
```
and the second method will not cause this problem.

namely， can't I  use a global gRPC connection?
Does the gRPC channel has a timeout and then it will be closed?

**Comment by tatsuhiro-t** [comment]
I check the last connection in the log, and there is no error there.

It looks like global client cannot handle connection lost gracefully.  If that is true, then this is not nghttpx issue.  I have no knowledge about Django or EventClient stuff, and have no idea about how to enable global gRPC connection if it is ever possible.
gRPC connection is still just a HTTP/2 connection over TCP in this case, and server has liberty to drop connection in any moment.  Client should handle this.

**Comment by sc-syf** [comment]
@tatsuhiro-t    
ok.all right.  thanks for your reply. thank you!  ^_^

**Comment by mojinxun** [comment]
@sc-syf  can you tell me: 

nghttp2 config with grpc, gRpc Server is based by csharp

how can I use the url

**Comment by sc-syf** [comment]
@mojinxun ???.jpg

**Comment by sc-syf** [comment]
At last, I found that maybe we should use a service discovery tool such as [consul](https://www.consul.io/) rather than use `nghttpx` or `nginx stream mode` as a load balancer.

---
Here is an article about python micro service stack:
http://flagzeta.org/blog/a-python-microservice-stack/

**Comment by mojinxun** [comment]
@sc-syf I do it, And everything is ok, Lan use Consul, Wan use nghttpx
