### ISSUE TITLE
fetch-ocsp-response doesn't work with openssl 1.1.0 (Debian SID)

### ISSUE THREAD

**Issue by dalf** [nghttp2/nghttp2#742]
When using the nghttp2-proxy package from debian sid version 1.17.0, I've this error :
```PID1 [NOTICE] Renew new ticket keys
fetch-ocsp-response (using OpenSSL 1.1.0c  10 Nov 2016)
sending OCSP request to http://ocsp.int-x3.letsencrypt.org/
Missing = in header key=value
ocsp: Use -help for summary
```

The syntax to add header seems to have changed (?). From ```openssl ocsp -help``` : 
```
 -header val             key=value header to add
```

Changing the [line 150](https://github.com/nghttp2/nghttp2/blob/master/script/fetch-ocsp-response#L150) solves the problem :
```python
	args.extend(['-header', 'Host=' + ocsp_host])
```
but, I don't know if it can be applied to LibreSSL.
In version LibreSSL version ```OpenSSL 1.0.2g  1 Mar 2016```, I don't see a ```header``` option with the ```ocsp``` command (test from the docker image ```evild/alpine-nginx:1.9.15-libressl``` )

For references :
https://www.openssl.org/docs/man1.1.0/apps/ocsp.html
https://www.openssl.org/docs/man1.0.2/apps/ocsp.html
https://www.openssl.org/docs/man1.0.1/apps/ocsp.html

The h2o version : https://github.com/h2o/h2o/blob/0d0075b87d0c62b14502728a55951462fa424ba9/share/h2o/fetch-ocsp-response#L91

**Comment by tatsuhiro-t** [comment]
Thank you for telling us.  You are right, syntax has been changed in OpenSSL 1.1.0.
Fortunately, OpenSSL 1.1.0 no longer requires -header option.  We just change the condition that -header is added for OpenSSL 1.0.x or LibreSSL.

cc: @kazuho

**Comment by dalf** [comment]
Hum, I think there is no header option for OpenSSL 1.0.x or LibreSSL according to the man pages.

**Comment by tatsuhiro-t** [comment]
I heard that it was non-documented option.

**Comment by dalf** [comment]
Okay ! Thank you for your quick answers.
