### ISSUE TITLE
CORS - Preflight OPTIONS response not returned

### ISSUE THREAD

**Issue by Gericop** [nghttp2/nghttp2#746]
I have a 1.17.0-DEV version of nghttp2, behind that is an nginx 1.10.0. The nginx is configured to return with 204 and no content (except for the CORS headers needed) when a CORS preflight request is made to it. The problem is that it pretty much seems like that the nghttpx somehow just drops this response and the client gets a status code 0, so the following PUT / DELETE request doesn't happen.
This problem seems to occur only if there's nghttpx in the way, so if I setup the backend by taking out nghttpx and leaving just nginx, the preflight request-response happens and everything works just fine. Both nginx and nghttpx uses HTTP/2. What's more interesting is that if I return an error code, such as 401, instead of 204, it gets through. Am I doing something wrong or is it a bug?

**Comment by Gericop** [comment]
Okay, so I think I found the problem, though I don't know whether it's a bug or an intentional behavior of nghttpx.
My nginx config was like when an OPTIONS request arrived, it responded with all the necessary CORS headers + Content-Type set to `text/plain` and Content-Length to 0. This seems to confuse nghttpx. Removing these two headers solved the problem.
Please note that my original config was based on [this enable-cors.org](http://enable-cors.org/server_nginx.html) sample.

**Comment by tatsuhiro-t** [comment]
For the record, sending Content-Length: 0 with 204 status code is a violation against RFC 7230 (See https://tools.ietf.org/html/rfc7230#section-3.3.2).  We implemented this in nghttp2 v1.17.0.  But user reported that some widely used service sends Content-Length:0 with 204 code (#735).
We workaround this by simply discarding such header field in upcoming nghttp2 v1.18.0.
