### ISSUE TITLE
nghttp2 client doesn't accept "Content-Length" header

### ISSUE THREAD

**Issue by birendra-keshari** [nghttp2/nghttp2#753]
The rfc says:
 "A request or response that includes a payload body can include a content-length header field."

But nghttp2 client seems to error out when it receives "Content-Length" header. Is there any reason for not allowing "Content-Length" ? I would assume this header to be useful in general for clients/intermediaries that can show download/upload progress. Thanks!

**Comment by tatsuhiro-t** [comment]
nghttp client generally accepts content-length.  But it refuses to do so for certain status code, such as 1xx, and 204 (see https://tools.ietf.org/html/rfc7230#section-3.3.2).  HTTP/2 is still subject to the HTTP semantics.
Could you check HTTP status code?

**Comment by birendra-keshari** [comment]
I checked it and that seems to be the case. I am closing it. Thanks!
