### ISSUE TITLE
nghttpx route request based on domaine name (like nginx server_name)

### ISSUE THREAD

**Issue by sulliwane** [nghttp2/nghttp2#760]
Hello,

Here is what I'd like to have:
```
client request: domainName1:same_IP:443  <------>  NGHTTPX <-------> grpcServer:50051          
client request: domainName2:same_IP:443  <------>  NGHTTPX <-------> grpcServer:50052
```
Is NGHTTPX Proxy able to route the request to the backend **depending on the domain name** in the request header of the request ?

Many thanks for your answer!

**Comment by tatsuhiro-t** [comment]
Yes.  See backend option.

**Comment by sulliwane** [comment]
My grpc server loads a certificate (from [letsencrypt](https://letsencrypt.org/) CA) called **domainName1.key**/**domainName1.crt**. My grpc client loads the default OS **CA.bundle** (so it can verify my server certificates CA signature). 

After looking at the [documentation](https://nghttp2.org/documentation/nghttpx-howto.html), I have a few questions:
1. Should I be running nghttpx in **default mode**, or **proxy mode** ```http2-proxy=yes```?
2. How adding nghttpx in the middle will impact the certificates setup?
3. I'd like to have nghttpx to just route the call (so it doesn't need itself certificate), is that possible?
4. Or do I need to load the same certificates in nghttpx than in my grpc server ?
5. In this case, can I load multiple certificates in nghttpx ?

Many thanks for your insights!

**Comment by tatsuhiro-t** [comment]
> 1. Should I be running nghttpx in default mode, or proxy mode http2-proxy=yes?

The default mode.

> 2. How adding nghttpx in the middle will impact the certificates setup?

If my understanding is correct, clients expect that nghttpx have domain previously gRPC services had.  If it is correct, nghttpx should load the certificate issued by lets encrypt.

> 3. I'd like to have nghttpx to just route the call (so it doesn't need itself certificate), is that possible?

Assuming that client uses TLS, it is not possible at the moment since nghttpx is L7 load balancer, and it has to first decrypt packets from client.

> 4. Or do I need to load the same certificates in nghttpx than in my grpc server ?

Yes

> 5. In this case, can I load multiple certificates in nghttpx ?

Yes.  The primary certificate and private key are loaded by certificate-file and private-key-file options respectively.  The other key pairs can be added using subcert option.  The certificate used by the connection is chosen based on TLS SNI extension.  If there is no match, primary certificate is used.

**Comment by sulliwane** [comment]
It makes sense now. I tried again today following your explanations (and the [documentation](https://nghttp2.org/documentation/nghttpx.1.html)) and it's working perfectly. Many thanks for your help!

Before closing the issue, I have three more questions:
1. On the performance side, how nginx ```proxy_pass``` and nghttpx compare? (They are basically doing the same thing, except that nghttpx supports http2, am I correct?).
2. What is the default load balancing pattern used by nghttpx? Is load balancing considered a major feature of nghttpx, or a side feature?
3. Do you consider nghttpx more like a "nghttp2 implementation example" or really like a product in its own that is going to compete with other established products (like nginx reverse proxy feature/load balancing) ? (because right now I feel it's presented more like a "tool" in the nghttp2 toolbox. I might be wrong)

I can open another issue for these questions If you prefer. Again, many thanks!

**Comment by tatsuhiro-t** [comment]
> 1. On the performance side, how nginx proxy_pass and nghttpx compare? (They are basically doing the same thing, except that nghttpx supports http2, am I correct?).

I think they are basically the same.  While I am not an expert of nginx configuration, it seems that nginx has more features than nghttpx.  Whether that is important or not depends on the use case.

> 2. What is the default load balancing pattern used by nghttpx? Is load balancing considered a major feature of nghttpx, or a side feature?

The default and only load balancing algorithm is round robin at the moment, and rise/fall health check similar to haproxy.  It also has session affinity based on client IP.

> 3. Do you consider nghttpx more like a "nghttp2 implementation example" or really like a product in its own that is going to compete with other established products (like nginx reverse proxy feature/load balancing) ? (because right now I feel it's presented more like a "tool" in the nghttp2 toolbox. I might be wrong)

Well, initially, it was written to ensure that the underlying library (nghttp2, formally spdylay) has sufficient APIs to create proxy.  At that time, it could be called as example.  But in recent years, nghttpx has been updated to make it stable, fast, and get top notch TLS support, and I consider it a complete proxy product. It might be better to get its own project if we emphasizes it, but currently it would be in one repository, to make the build easier.

**Comment by sulliwane** [comment]
Nice! Thanks a lot :)
