### ISSUE TITLE
TLS 1.3 support

### ISSUE THREAD

**Issue by nutinshell** [nghttp2/nghttp2#764]
Since BoringSSL supports TLSv1.3 already, would you consider adopt TLS 1.3 soon?

**Comment by tatsuhiro-t** [comment]
I'm waiting for OpenSSL 1.1.1 to get TLSv1.3 support.  But apparently nghttp2 can compile with BoringSSL, I will do some tries to get 1.3 from it when I have spare time for it.

**Comment by tatsuhiro-t** [comment]
Here is experimental branch to enable TLSv1.3 with boringssl: https://github.com/nghttp2/nghttp2/tree/boringssl-tls13

**Comment by humiaozuzu** [comment]
The openssl official master branch has TLS 1.3 support now.

**Comment by tatsuhiro-t** [comment]
Good.
TLS 1.3 is still in WG Last Call state.  Strictly speaking, it is not finalized yet.

**Comment by tatsuhiro-t** [comment]
#816 enables TLSv1.3 support.
