### ISSUE TITLE
Unable to build v1.18.1 because unable to locate c-ares >= 1.7.5

### ISSUE THREAD

**Issue by GuillaumeRossolini** [nghttp2/nghttp2#771]
Hi,

Since nghttp2 v1.18.0, I have been unable to build the apps (--enable-app). Here is the message I get when I run `./configure`:
```
./configure --with-libxml2 --with-jemalloc --disable-examples --enable-app
[...]
checking for LIBCARES... no
configure: Requested 'libcares >= 1.7.5' but version of c-ares is -
```

However, I did build c-ares v1.12 from source with these commands:
`make clean 2>/dev/null ; ./buildconf && ./configure && make && make install`

Could you please help me specify the path to c-ares?

Thanks,

**Comment by tatsuhiro-t** [comment]
configure script uses pkg-config to find c-ares.  Do you have libcares.pc under /usr/local/lib/pkgconfig?
It should work, but if it does not, try to specify both LIBCARES_CFLAGS and LIBCARES_LIBS.

**Comment by GuillaumeRossolini** [comment]
Yes, here it is:
```
#***************************************************************************
# Project        ___       __ _ _ __ ___  ___
#               / __|____ / _` | '__/ _ \/ __|
#              | (_|_____| (_| | | |  __/\__ \
#               \___|     \__,_|_|  \___||___/
#
prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: c-ares
URL: http://daniel.haxx.se/projects/c-ares/
Description: asynchronous DNS lookup library
Version: -
Requires:
Requires.private:
Cflags: -I${includedir}
Libs: -L${libdir} -lcares
Libs.private:
```

The version number in there looked weird so I changed it to `1.12`, and now `./configure` passes for nghttp2.

I'll see about reporting that upstream.

Regards,
Thanks!

**Comment by tatsuhiro-t** [comment]
Indeed.  Something is wrong there.
