### ISSUE TITLE
Apache 2.4.25 - Segmention Fault

### ISSUE THREAD

**Issue by davidenco** [nghttp2/nghttp2#773]
Yesterday I upgraded from Apache 2.4.23 to 2.4.25. Nothing else has changed.

Since the upgrade, HTTP2 clients are randomly receiving the "Aborted" HTTP status and the webpage does not load. However HTTP1 clients such as IE11 are unaffected and can access the webpage when HTTP2 can't.

In the Apache error_log, "Segmention Fault (11)" is logged when an HTTP2 client tries to load the page.

Restarting the Apache service or rebooting the server resolves the issue for a few seconds.

Could this be a problem with Apache or nghttp2? Let me know if you need anything else, thanks.

**Comment by tatsuhiro-t** [comment]
I couldn't determine that cause without more information.  I suggest that this issue should be reported to Apache and [mod_h2](https://github.com/icing/mod_h2).

**Comment by davidenco** [comment]
Thanks. Turns out this is indeed a bug within Apache and that the bug was fixed just after 2.4.25 was released!

https://bz.apache.org/bugzilla/show_bug.cgi?id=60510

Applying the patch works for me! :)
