### ISSUE TITLE
logasap option support

### ISSUE THREAD

**Issue by humiaozuzu** [nghttp2/nghttp2#777]
just like haproxy's option:
https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4-option%20logasap

**Comment by tatsuhiro-t** [comment]
I understand how logasap works.  Could you tell me what kind of benefit this feature brings?  Use-case?

**Comment by humiaozuzu** [comment]
This feature helps a lot when debugging nghttpx client.
We use nghttpx as a proxy client here and logasap is convenient as we do not have to wait for the request end to see to the log. Especially for open large files.

**Comment by tatsuhiro-t** [comment]
Thank you.  #781 implements this feature.
