### ISSUE TITLE
 best practice to call "nghttp2_submit_data()" multiple times?

### ISSUE THREAD

**Issue by chen-wang** [nghttp2/nghttp2#78]
nghttp2_submit_data() returns NGHTTP2_ERR_DATA_EXIST when the previously submitted data has not been fully processed yet. I am wondering what is the right way to call nghttp2_submit_data() again if an application has new data to submit after the previously submitted data has been processed. I have thought the following approaches:
1. call "nghttp2_submit_data()" in  "nghttp2_data_source_read_callback()" when EOF is reached. It is too early since "nghttp2_stream_detach_data()" has not been called yet.
2. call "nghttp2_submit_data()" in "on_frame_send_callback()" if it is the last frame of the previous submission. Still too early for the same reason above.
3. call "nghttp2_submit_data()" after "nghttp2_session_mem_send()", then application needs to maintain a stream list to remember which stream is eligible to submit data again.

Please suggest the best practice to use "nghttp2_submit_data()".

Thanks
Chen

**Comment by octGitHub** [comment]
Hello, is there are demo of what you  dicussed ?  

I 'm trying make a demo with amazon's alexa.  
 It need to open a stream to upload many data,but I stuck on this

**Comment by roshanDD** [comment]
@octGitHub , I am curently facing with the same problem (demo with amazon's alexa), I am also stuck on uploading data, I am wondering if you got this solved? Please help1

**Comment by palak-volansys** [comment]
@roshanDD, @octGitHub , I am also facing the same problem with amazon's alexa. Have you found something to deal with this problem? Please help.
