### ISSUE TITLE
SNI and multiple key types

### ISSUE THREAD

**Issue by KirbyDE** [nghttp2/nghttp2#792]
Hi.

Assuming that there are 2 domains (example.com and example.org) with the following certificates

1) ECDSA certificate for example.com
2) RSA certificate for example.com
3) ECDSA certificate for example.org
4) RSA certificate for example.org
5) RSA certificate for example.com with SAN example.org

It it possible to configure nghttpx to use
- certificates 1) and 3) for clients supporting SNI and ECDSA 
- certificates 2) and 4) for clients supporting SNI and RSA
- certificate 5) for clients that do not support SNI
?

**Comment by tatsuhiro-t** [comment]
nghttpx supports multiple certificates, but one certificate is associated to one domain.  nghttpx cannot choose certificate based on client capability of RSA/ECDSA.  I'm wondering that openssl offers such a feature.
For non-SNI clients, nghttpx always uses default certificate, which is passed as certificate-file option.

**Comment by KirbyDE** [comment]
I think that this is possible with OpenSSL, as HAProxy 1.7 does it:
[https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#5.1-crt](url)

> There are cases where it is desirable to support multiple key types, e.g. RSA
and ECDSA in the cipher suites offered to the clients. This allows clients
that support EC certificates to be able to use EC ciphers, while
simultaneously supporting older, RSA only clients.

> In order to provide this functionality, multiple PEM files, each with a
different key type, are required.

It would be great if this could also be made possible in nghttpx.

**Comment by tatsuhiro-t** [comment]
Thank you.  Will look into it.

**Comment by tatsuhiro-t** [comment]
@KirbyDE #798 implements this feature.  Could you test it?

**Comment by tatsuhiro-t** [comment]
BTW, it requires OpenSSL >= 1.0.2.  BoringSSL and LibreSSL don't work.
