### ISSUE TITLE
Error when trying to write large chunks using NGHTTP2_DATA_FLAG_NO_COPY

### ISSUE THREAD

**Issue by bbfgelman1** [nghttp2/nghttp2#796]
In my data provider, which I submit to `nghttp2_submit_data`, I would like to be able to write data in very large chunks. My function looks like this:
```c++
ssize_t my_source_read_cb(
    nghttp2_session* session,
    int32_t stream_id,
    uint8_t* buf,
    size_t length,
    uint32_t* data_flags,
    nghttp2_data_source* source,
    void* user_data) {
  // length is normally about 16k
  // what if I want to write much more than this?
  *data_flags |= NGHTTP2_DATA_FLAG_NO_COPY;
  // I want to write 1 megabyte.
  return (1 << 20);
}
int my_send_data_cb( ... ) {
  // I expect this to be called with length = the value returned by my_source_read_cb
  // ... do stuff
  return 0;
}

// sometime later
nghttp2_submit_data(my_session, NGHTTP2_FLAG_NONE,  my_stream, &provider_with_my_source_read_cb);
```

When I try this, the next call to `nghttp2_session_mem_send(my_session, &data)` always produces an error. `my_source_read_cb` gets called, but `my_send_data_cb` (which I did put in the callbacks) does not.

Why does this not work? I specified a large initial window size (2^31 - 1) and frame size (2^24 - 1) in the server settings, so it should be possible to send such large frames.

**Comment by tatsuhiro-t** [comment]
See https://nghttp2.org/documentation/nghttp2_session_callbacks_set_data_source_read_length_callback.html

**Comment by bbfgelman1** [comment]
Excellent! This is exactly what I needed. Thank you so much for the reply!

It would be really great if the documentation for https://nghttp2.org/documentation/types.html#c.nghttp2_data_source_read_callback made some mention of the existence of this callback.

Now that I know about this, my use case can work!

Thanks again!

**Comment by tatsuhiro-t** [comment]
I updated the doc to mention about the callback.  See 5f31c094
