### ISSUE TITLE
nghttpx recv SIGHUP throws signal Segmentation fault(11)

### ISSUE THREAD

**Issue by ManAgainstCode** [nghttp2/nghttp2#801]
I use the latest code from the repository to build a nghttpx service.

When testing the reload configuration file function with command "kill -SIGHUP [pid]", I could always find the nghttpx output saying "NOTICE (shrpx_log.cc:520) Worker process: [pid] exited abnormally with status b; exit status 0; signal Segmentation fault(11)". 

And this error seemed to cause a termination of nghttpx service in a very short time interval, as the client reported a termination of connection.

**Comment by tatsuhiro-t** [comment]
It works fine for me.  OS, and compiler are helpful information.
Could you attach gdb debugger to nghttpx worker process, and check the backtrace when it crashes?

**Comment by tatsuhiro-t** [comment]
OK, I just reproduced it.

**Comment by tatsuhiro-t** [comment]
Fix committed via 4a06f968

**Comment by ManAgainstCode** [comment]
OK, problem solved.
