### ISSUE TITLE
How to call API /api/v1beta1/backendconfig ?

### ISSUE THREAD

**Issue by devil0118** [nghttp2/nghttp2#806]
![image](https://cloud.githubusercontent.com/assets/4556669/22820874/969c209e-efb3-11e6-8621-bbdbca69bd8d.png)
![image](https://cloud.githubusercontent.com/assets/4556669/22821078/8668fec6-efb4-11e6-8aa8-e00426bf6af8.png)
![image](https://cloud.githubusercontent.com/assets/4556669/22821095/97f59014-efb4-11e6-8cbf-9b0a6be54d2e.png)

Are there any examples?
Thank you!!!

**Comment by tatsuhiro-t** [comment]
Have you configured "api" parameter for the API endpoint?
https://nghttp2.org/documentation/nghttpx.1.html#cmdoption-nghttpx-f

In order to make nghttpx listen to the API request on 127.0.0.1:8080, do this in command line:

```
-f"127.0.0.1,8080;api"
```

or in configuration file:

```
frontend=127.0.0.1,8080;api
```

**Comment by devil0118** [comment]
configuration file:
![image](https://cloud.githubusercontent.com/assets/4556669/22821546/89c3df76-efb6-11e6-9b04-4320592e6262.png)

error log:
![image](https://cloud.githubusercontent.com/assets/4556669/22821648/07008908-efb7-11e6-8c54-01d9db4320c5.png)

**Comment by devil0118** [comment]
Thank you。
