### ISSUE TITLE
load balance policy

### ISSUE THREAD

**Issue by ManAgainstCode** [nghttp2/nghttp2#808]
any way to config the load balance policy?
is there a config like 'weight'?

**Comment by tatsuhiro-t** [comment]
The only balancing policy we implemented in nghttpx is round robin based load balancing.  Weight is not considered at the moment.

**Comment by truongdo** [comment]
It would be great if this feature is added to nghttpx

**Comment by tatsuhiro-t** [comment]
#1297 implements the "weight" configuration.
