### ISSUE TITLE
execution nghttp2_session_mem_send  some  times  later    send session data failed!!

### ISSUE THREAD

**Issue by ackpengyao** [nghttp2/nghttp2#817]
Hello, i have a question that execution nghttp2_session_mem_send  some  times  later  nghttp2_session_mem_send  return zero  ,accord to debug i found return zero place where nghttp2_session_pop_next_ob_item  return NULL lead to nghttp2_session_mem_send recevie zero,  here is my code flow:

```c
/*
**  pack session data callback function
*/
ssize_t data_prd_read_callback(
    nghttp2_session *session, int32_t stream_id, uint8_t *buf, size_t length,
    uint32_t *data_flags, nghttp2_data_source *source, void *user_data) 
{
	static int iCount = 0;
	static char byFlag = 0;

	if (nread > length)
	{
	 	nread = length;		  
	}

	ft_fifo_seek(g_CaptureFifo, (char *)buf, 0, nread);

	ft_fifo_setoffset(g_CaptureFifo, nread);

	if (1 == byReadCallBackFlag)
	{
		*data_flags = NGHTTP2_DATA_FLAG_EOF;
		printf(YELLOW "data_flags = NGHTTP2_DATA_FLAG_EOF\n" NONE);
		byReadCallBackFlag = 0;
	}

	DEBUG_PRINTF("stream_id:%d, nread:%zu, length:%zu\r\n", stream_id, nread, length);

	return nread;
}

/* Send HTTP request to the remote peer */
static void submit_postAudiorequest(http2_session_data *session_data) 
{
	int32_t stream_id;
	char byTemp[128] = {0};
	//http2_stream_data *stream_data = session_data->stream_data[STREAM_ID_REQUESTAUDIO];
	http2_stream_data *stream_data = find_IDLEStream(MSGTEXT_PLAYBACKCONTROLLER);

	if (NULL == stream_data)
	{
		DEBUG_PRINTF("---Create idle stream failed..---");
	    return ;
	}

	const char *uri = stream_data->uri;
	const struct http_parser_url *u = stream_data->u;
	char byLength = 0;

	byLength = strlen(EVENTS_PATH);
	stream_data->path = malloc(byLength);
	memset(stream_data->path, 0, byLength);
	strcpy(stream_data->path, EVENTS_PATH);
	stream_data->pathlen = byLength;
	DEBUG_PRINTF("req->path length:%d, %s", byLength, stream_data->path);

	getToken();

	// Boundary
	strcpy(byTemp, "multipart/form-data; boundary=");
	strcat(byTemp, &g_boundary.m_postaudioBoundary);

	const nghttp2_nv hdrs[] = {
		MAKE_NV(":method", "POST"), 	MAKE_NV_CS(":path", stream_data->path),
		MAKE_NV(":scheme", "https"), MAKE_NV("accept", "*/*"),    
		MAKE_NV_CS("authorization", g_bysubmitToken),
		MAKE_NV_CS("content-type", byTemp),
	};


	nghttp2_data_provider data_prd;
	data_prd.source.ptr = NULL;
	data_prd.read_callback = data_prd_read_callback;
	DEBUG_PRINTF("data_prd_read_callback...");
	stream_id = nghttp2_submit_request(session_data->session, NULL, hdrs,
	                                 ARRLEN(hdrs), &data_prd, stream_data);
	if (stream_id < 0) {
	errx(1, "Could not submit HTTP request: %s", nghttp2_strerror(stream_id));
	}

	stream_data->stream_id = stream_id;

	g_iAudioStreamID = stream_data->stream_id;
}

void *Http2DataRequestPthread(void)
{

      submit_postAudiorequest(session_data);

      while(1)
      {
                        datalen = nghttp2_session_mem_send(session_data->session, &datap);
			if (0 == datalen)
			{
				break;
			}else 
                        {
			        iRet = bufferevent_write(bev, datap, datalen);
                        }
      }
}
```

**Comment by tatsuhiro-t** [comment]
I'm not sure I understand the issue.
nghttp2_session_mem_send eventually returns 0 if there is no frame to send.

**Comment by ackpengyao** [comment]
in my opinion ,nghttp2_session_mem_send acctually just pack session data and responsible to reset session->aob. finally accord to bufferevent_write write session data to server machine.
my issue is that exection nghttp2_session_mem_send some timer later my client can't get data from server machine ,i debug found issue is where pack session data before  return zero (item == NULL).
    
case NGHTTP2_OB_POP_ITEM: {
      nghttp2_outbound_item *item;

      item = nghttp2_session_pop_next_ob_item(session);
      if (item == NULL) {
        DEBUGF("################nghttp2_session_pop_next_ob_item  line==%d\n",__LINE__);
        return 0;
      }

**Comment by tatsuhiro-t** [comment]
nghttp2_session_pop_next_ob_item is not a public API.  It is an internal thing, and an application should not use it.

Are you saying that nghttp2_session_mem_send should serialize HTTP/2 frame ignoring flow control window, and any priority stuff?  If yes, then it is not designed in that way.  In my opinion, ignoring them makes the function must less useful.

**Comment by ackpengyao** [comment]
1.i debug found that  local stream and remote stream of sum( 3 stream )   server max stream 10, so i think client stream is ok，print as follows 
{
    ########session->remote_settings.max_concurrent_streams==10,line==2326
    ########session->num_outgoing_streams==3,line==2327
    ########session->local_settings.max_concurrent_streams==10,line==2328
    ########session->num_incoming_streams==0,line==2329
}

2.i issus is that nghttp2_session_mem_send exection some timers later return zero where before pack session data,i debug in my project always datalen=0 (this value return from nghttp2_session_mem_send) print as follows :

{
Client:[data_prd_read_callback:3242]"[INFO] C ----------------------------> S (DATA post body), stream_id:11 length:1369\n"
Client:[data_prd_read_callback:3260]"stream_id:11, nread:1369, length:1369\r\n"
send: padlen = 0, nothing to do
stream: stream=11 obq resched cycle=1469344
#########send: next frame: DATA
####send: start transmitting frame type=0, length=1378
####NGHTTP2_OB_SEND_DATA  line==3072
####NGHTTP2_OB_SEND_DATA  line==3079
####session_after_frame_sent2  line==3107
nghttp2_session_mem_send  datalen:1378, bufferevent_write iRet:0"
####NGHTTP2_OB_SEND_DATA  line==3079
send: end transmission of a frame
####session_after_frame_sent2  line==3088
send: reset nghttp2_active_outbound_item
send: aob->item = (nil)
########session->remote_settings.max_concurrent_streams==10,line==2326
########session->num_outgoing_streams==2,line==2327
########session->local_settings.max_concurrent_streams==10,line==2328
########session->num_incoming_streams==0,line==2329
################nghttp2_session_pop_next_ob_item        line==2361
nghttp2_session_mem_send datalen==0,line==3516\n"
########session->remote_settings.max_concurrent_streams==10,line==2326
########session->num_outgoing_streams==2,line==2327
########session->local_settings.max_concurrent_streams==10,line==2328
########session->num_incoming_streams==0,line==2329
################nghttp2_session_pop_next_ob_item        line==2361
nghttp2_session_mem_send datalen==0,line==3516\n"
########session->remote_settings.max_concurrent_streams==10,line==2326
########session->num_outgoing_streams==2,line==2327
########session->local_settings.max_concurrent_streams==10,line==2328
########session->num_incoming_streams==0,line==2329
################nghttp2_session_pop_next_ob_item        line==2361
nghttp2_session_mem_send datalen==0,line==3516\n"
}

3.i debug in nghttp2 lib found that where return zero(exection this api finallly return NULL) ,print as follows:


nghttp2_outbound_item *nghttp2_session_pop_next_ob_item(nghttp2_session *session) 
{
  nghttp2_outbound_item *item;

  item = nghttp2_outbound_queue_top(&session->ob_urgent);
  if (item) 
 {
    DEBUGF("################nghttp2_session_pop_next_ob_item	line==%d\n",__LINE__);
    nghttp2_outbound_queue_pop(&session->ob_urgent);
    item->queued = 0;
    return item;
  }

  item = nghttp2_outbound_queue_top(&session->ob_reg);
  if (item) {
    nghttp2_outbound_queue_pop(&session->ob_reg);
    item->queued = 0;
	DEBUGF("################nghttp2_session_pop_next_ob_item  line==%d\n",__LINE__);
    return item;
  }

  if (!session_is_outgoing_concurrent_streams_max(session)) {
    item = nghttp2_outbound_queue_top(&session->ob_syn);
    if (item) {
      nghttp2_outbound_queue_pop(&session->ob_syn);
      item->queued = 0;
	  DEBUGF("################nghttp2_session_pop_next_ob_item	line==%d\n",__LINE__);
      return item;
    }
  }

  if (session->remote_window_size > 0) {
	  DEBUGF("################nghttp2_session_pop_next_ob_item	line==%d\n",__LINE__);
    return nghttp2_stream_next_outbound_item(&session->root);
  }
  DEBUGF("################nghttp2_session_pop_next_ob_item	line==%d\n",__LINE__);

  return NULL;
}

**Comment by tatsuhiro-t** [comment]
Perhaps, connection level or stream level flow control window get zero?  Notice that there are 2 levels of flow control window: connection (session) and stream.

**Comment by ackpengyao** [comment]
1. i found my issue that session remote_window_size= 0 ,my client don't receive data to  update window size from amazon server machine when send data>65535, whether have some api or method repeat init window size  in nghttp2 lib before remote_window_size close equal zero ,i hope u could give me some advice thanks so much,by the way  my client just new one session to communicate with amazon server machine  my issue debug as print follows:

send: end transmission of a frame
####session_after_frame_sent2  line==3101
send: reset nghttp2_active_outbound_item
send: aob->item = (nil)
########session->remote_settings.max_concurrent_streams==10,line==2331
########session->num_outgoing_streams==2,line==2332
########session->local_settings.max_concurrent_streams==10,line==2333
########session->num_incoming_streams==0,line==2334
########session->recv_window_size==6145,line==2338
########session->local_window_size==65535,line==2339
########session->remote_window_size==0,line==2340
########session->window_update_queued==0,line==2341

**Comment by tatsuhiro-t** [comment]
Server is responsible to send WINDOW_UPDATE to increase the flow control credit.  If server does not send any of it, then it is a server bug, or it does so intentionally because it does not want to read upload body?

To receive these incoming frames, nghttp2_session_mem_recv or nghttp2_session_recv is used.   Upon the reception of WINDOW_UPDATE, libnghttp2 will increase window size.
