### ISSUE TITLE
nghttpx: Remove SPDY

### ISSUE THREAD

**Issue by tatsuhiro-t** [nghttp2/nghttp2#821]
Both Firefox and Chromium have already dropped SPDY.
HTTP/2 is superior than SPDY in every aspect. We should remove it from nghttpx.
Perhaps, milestone v1.21.0.
We will stop serving SPDY requests at nghttp2.org as well.

**Comment by alagoutte** [comment]
Do you have some stats about SPDY request on nghttp2?

**Comment by tatsuhiro-t** [comment]
I have stats on nghttp2.org.
On particular period, among total 42,000 https requests, SPDY is only 0.005%.  h2 is 77%.

https://bugzilla.mozilla.org/show_bug.cgi?id=1248197 says that it is ~2% last July.

SPDY is maintenance burden for me now, so if it is allowed, I'd like to remove it.
Perhaps, first declare deprecation of SPDY, and don't recommend to build with it.
Also make configure script SPDY detection disabled by default.
Then few month later, remove it completely.

**Comment by tatsuhiro-t** [comment]
My SPDY deprecation plan is that:

v1.28.0: SPDY feature is officially deprecated; its feature could be incomplete compared to other supported protocols.
v1.29.0: SPDY functionality is completely removed from nghttp2.
