### ISSUE TITLE
Apache Compile Error :  checking for nghttp2 version >= 1.2.1... FAILED 

### ISSUE THREAD

**Issue by nik6018** [nghttp2/nghttp2#827]
I am trying to compile apache with nghttp2 to enable mod_http2 but i can't seem to figure out this configure command error 

> checking for nghttp2 version >= 1.2.1... FAILED configure: WARNING: nghttp2 version is too old configure: error: mod_http2 has been requested but can not be built due to prerequisite failures no

As i have downloaded the latest version so this doesn't seems to be the issue, so can anyone provide some info as how to resolve this issue.

Here is my apache configure  command:
```
--with-nghttp2=$PPS_PATH/lib \
--enable-http2 \
```

I have compiled nghttp2 on a Ubuntu machine and copied all the libnghttp2.* files to CentOS 6 as i have to build Apache on CentOS 6 _(I am going through this hassle because the autoconf version avaialable on CentOS 6  is 2.63 and nghttp2 requires 2.65 and up)_

I am doing anything wrong or i need to copy some other files which are required ?

**Comment by tatsuhiro-t** [comment]
I suggest to ask Apache developer about it.

**Comment by nik6018** [comment]
@tatsuhiro-t  thanks for your suggestion.

Can you provide any workaround for compiling nghttp2 on CentOS 6 as the build is not possible due to the version issue in CentOS6.

**Comment by tatsuhiro-t** [comment]
I think you can download tar ball from https://github.com/nghttp2/nghttp2/releases, then autoconf stuff does not bother you.  Also --enable-lib-only could help to reduce dependency.

**Comment by nik6018** [comment]
Yes I did the same but it still complains about the autoconf version 

> configure.ac:761: error: Autoconf version 2.64 or higher is required

**Comment by tatsuhiro-t** [comment]
For tar ball version, you don't have to run `autoreconf -i`.  Just run configure script.  Doesn't it still work for you?

**Comment by nik6018** [comment]
@tatsuhiro-t  Yay ! it did work , thanks i didn't knew that `autoreconf -i` is not required for tar ball.

One more thing , if you can help me out does the library libnghttp2 is required only at build time for the module mod_http2 or it is required at run-time as well ? as I didn't get any reference on Apache website.

**Comment by tatsuhiro-t** [comment]
I'm not mod_http2 developer, so I'm not certain.  In general, if mod_http2 dynamically links against libnghttp2, it is required at run-time.  If it is linked statically, it is not.  Again I suggest to ask Apache developer about it.

**Comment by nik6018** [comment]
@tatsuhiro-t  Thanks for the help, Compiled and ran the Apache binary and everything works as expected requests now serving over HTTP2.

**Comment by tatsuhiro-t** [comment]
Great.  Let's close the issue.
