### ISSUE TITLE
autoreconf error, and ./configure error

### ISSUE THREAD

**Issue by y123456yz** [nghttp2/nghttp2#828]
[root@s10-2-x-4 nghttp2-master]# autoconf -V
autoconf (GNU Autoconf) 2.69             
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by David J. MacKenzie and Akim Demaille.

[root@s10-2-x-4 nghttp2-master]# autoreconf -i
lib/Makefile.am:35: Libtool library used but `LIBTOOL' is undefined
lib/Makefile.am:35:   The usual way to define `LIBTOOL' is to add `AC_PROG_LIBTOOL'
lib/Makefile.am:35:   to `configure.ac' and run `aclocal' and `autoconf' again.
lib/Makefile.am:35:   If `AC_PROG_LIBTOOL' is in `configure.ac', make sure
lib/Makefile.am:35:   its definition is in aclocal's search path.
src/Makefile.am:164: library used but `RANLIB' is undefined
src/Makefile.am:164:   The usual way to define `RANLIB' is to add `AC_PROG_RANLIB'
src/Makefile.am:164:   to `configure.ac' and run `autoconf' again.
src/Makefile.am:239: Libtool library used but `LIBTOOL' is undefined
src/Makefile.am:239:   The usual way to define `LIBTOOL' is to add `AC_PROG_LIBTOOL'
src/Makefile.am:239:   to `configure.ac' and run `aclocal' and `autoconf' again.
src/Makefile.am:239:   If `AC_PROG_LIBTOOL' is in `configure.ac', make sure
src/Makefile.am:239:   its definition is in aclocal's search path.
third-party/Makefile.am:30: Libtool library used but `LIBTOOL' is undefined
third-party/Makefile.am:30:   The usual way to define `LIBTOOL' is to add `AC_PROG_LIBTOOL'
third-party/Makefile.am:30:   to `configure.ac' and run `aclocal' and `autoconf' again.
third-party/Makefile.am:30:   If `AC_PROG_LIBTOOL' is in `configure.ac', make sure
third-party/Makefile.am:30:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

[root@s10-2-x-4 nghttp2-master]# automake
lib/Makefile.am:35: Libtool library used but `LIBTOOL' is undefined
lib/Makefile.am:35:   The usual way to define `LIBTOOL' is to add `AC_PROG_LIBTOOL'
lib/Makefile.am:35:   to `configure.ac' and run `aclocal' and `autoconf' again.
lib/Makefile.am:35:   If `AC_PROG_LIBTOOL' is in `configure.ac', make sure
lib/Makefile.am:35:   its definition is in aclocal's search path.
src/Makefile.am:164: library used but `RANLIB' is undefined
src/Makefile.am:164:   The usual way to define `RANLIB' is to add `AC_PROG_RANLIB'
src/Makefile.am:164:   to `configure.ac' and run `autoconf' again.
src/Makefile.am:239: Libtool library used but `LIBTOOL' is undefined
src/Makefile.am:239:   The usual way to define `LIBTOOL' is to add `AC_PROG_LIBTOOL'
src/Makefile.am:239:   to `configure.ac' and run `aclocal' and `autoconf' again.
src/Makefile.am:239:   If `AC_PROG_LIBTOOL' is in `configure.ac', make sure
src/Makefile.am:239:   its definition is in aclocal's search path.
third-party/Makefile.am:30: Libtool library used but `LIBTOOL' is undefined
third-party/Makefile.am:30:   The usual way to define `LIBTOOL' is to add `AC_PROG_LIBTOOL'
third-party/Makefile.am:30:   to `configure.ac' and run `aclocal' and `autoconf' again.
third-party/Makefile.am:30:   If `AC_PROG_LIBTOOL' is in `configure.ac', make sure
third-party/Makefile.am:30:   its definition is in aclocal's search path.
[root@s10-2-x-4 nghttp2-master]# autoconf
[root@s10-2-x-4 nghttp2-master]# ./configure --prefix=/usr/local/nghttp2
checking for gcc... no
checking for cc... no
checking for cl.exe... no

[root@s10-2-x-x nghttp2-master]# ./configure --prefix=/usr/local/nghttp2
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
./configure: line 4170: syntax error near unexpected token `2.2.6'
./configure: line 4170: `LT_PREREQ(2.2.6)'

**Comment by tatsuhiro-t** [comment]
Make sure that the following packages are installed: autoconf automake autotools-dev libtool pkg-config

**Comment by y123456yz** [comment]
@tatsuhiro-t   
thanks，the reason is that pkg-config not install .

bug , now have new error, when I make the nghttp.


configure: summary of build options:

    Package version: 1.21.0-DEV
    Library version: 27:0:13
    Install prefix:  /usr/local
    System types:
      Build:         x86_64-unknown-linux-gnu
      Host:          x86_64-unknown-linux-gnu
      Target:        x86_64-unknown-linux-gnu
    Compiler:
      C compiler:     gcc
      CFLAGS:         -g -O2
      LDFLAGS:        
      C++ compiler:   g++
      CXXFLAGS:       -g -O2
      CXXCPP:         g++ -E
      C preprocessor: gcc -E
      CPPFLAGS:       
      WARNCFLAGS:     
      WARNCXXFLAGS:   
      CXX1XCXXFLAGS:   -std=c++11
      EXTRACFLAG:     -fvisibility=hidden
      LIBS:           
    Library:
      Shared:         yes
      Static:         yes
    Python:
      Python:         /usr/bin/python
      PYTHON_VERSION: 
      pyexecdir:      
      Python-dev:     no
      PYTHON_CPPFLAGS:
      PYTHON_LDFLAGS: 
      Cython:         
    Test:
      CUnit:          no (CFLAGS='' LIBS='')
      Failmalloc:     yes
    Libs:
      OpenSSL:        yes (CFLAGS=' ' LIBS='-lssl -lcrypto  ')
      Libxml2:        no (CFLAGS='' LIBS='')
      Libev:          yes (CFLAGS='' LIBS='-lev')
      Libc-ares       yes (CFLAGS='-I/usr/local/include  ' LIBS='-L/usr/local/lib -lcares  ')
      Libevent(SSL):  no (CFLAGS='' LIBS='')
      Spdylay:        no (CFLAGS='' LIBS='')
      Jansson:        no (CFLAGS='' LIBS='')
      Jemalloc:       no (LIBS='')
      Zlib:           yes (CFLAGS=' ' LIBS='-lz  ')
      Systemd:        no (CFLAGS='' LIBS='')
      Boost CPPFLAGS: 
      Boost LDFLAGS:  
      Boost::ASIO:    
      Boost::System:  
      Boost::Thread:  
    Third-party:
      http-parser:    yes
      MRuby:          no (CFLAGS='' LIBS='')
      Neverbleed:     no
    Features:
      Applications:   yes
      HPACK tools:    no
      Libnghttp2_asio:no
      Examples:       no
      Python bindings:no
      Threading:      yes


[root@s10-2-x-4 nghttp2-master]# make
make  all-recursive
make[1]: Entering directory `/home/yazhou.yang/test/nghttp2-master'
Making all in lib
make[2]: Entering directory `/home/yazhou.yang/test/nghttp2-master/lib'
Making all in includes
make[3]: Entering directory `/home/yazhou.yang/test/nghttp2-master/lib/includes'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/yazhou.yang/test/nghttp2-master/lib/includes'
make[3]: Entering directory `/home/yazhou.yang/test/nghttp2-master/lib'
  CC     nghttp2_pq.lo
  CC     nghttp2_map.lo
  CC     nghttp2_queue.lo
  CC     nghttp2_frame.lo
  CC     nghttp2_buf.lo
  CC     nghttp2_stream.lo
  CC     nghttp2_outbound_item.lo
  CC     nghttp2_session.lo
  CC     nghttp2_submit.lo
  CC     nghttp2_helper.lo
  CC     nghttp2_npn.lo
  CC     nghttp2_hd.lo
  CC     nghttp2_hd_huffman.lo
  CC     nghttp2_hd_huffman_data.lo
  CC     nghttp2_version.lo
  CC     nghttp2_priority_spec.lo
  CC     nghttp2_option.lo
  CC     nghttp2_callbacks.lo
  CC     nghttp2_mem.lo
  CC     nghttp2_http.lo
  CC     nghttp2_rcbuf.lo
  CC     nghttp2_debug.lo
  CCLD   libnghttp2.la
make[3]: Leaving directory `/home/yazhou.yang/test/nghttp2-master/lib'
make[2]: Leaving directory `/home/yazhou.yang/test/nghttp2-master/lib'
Making all in third-party
make[2]: Entering directory `/home/yazhou.yang/test/nghttp2-master/third-party'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/yazhou.yang/test/nghttp2-master/third-party'
Making all in src
make[2]: Entering directory `/home/yazhou.yang/test/nghttp2-master/src'
Making all in includes
make[3]: Entering directory `/home/yazhou.yang/test/nghttp2-master/src/includes'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/yazhou.yang/test/nghttp2-master/src/includes'
make[3]: Entering directory `/home/yazhou.yang/test/nghttp2-master/src'
  CXX    libnghttpx_a-util.o
  CXX    libnghttpx_a-http2.o
  CC     libnghttpx_a-timegm.o
  CXX    libnghttpx_a-app_helper.o
  CXX    libnghttpx_a-ssl.o
  CXX    libnghttpx_a-shrpx_config.o
  CXX    libnghttpx_a-shrpx_accept_handler.o
  CXX    libnghttpx_a-shrpx_connection_handler.o
shrpx_connection_handler.cc: In function 'void shrpx::{anonymous}::thread_join_async_cb(ev_loop*, ev_async*, int)':
shrpx_connection_handler.cc:102:16: error: 'ev_break' was not declared in this scope
   ev_break(loop);
                ^
make[3]: *** [libnghttpx_a-shrpx_connection_handler.o] Error 1
make[3]: Leaving directory `/home/yazhou.yang/test/nghttp2-master/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/yazhou.yang/test/nghttp2-master/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/yazhou.yang/test/nghttp2-master'
make: *** [all] Error 2

**Comment by y123456yz** [comment]
may be my libev lib is too old.

**Comment by y123456yz** [comment]
yes, I upgrade the libev, that's OK.
thanks

**Comment by tatsuhiro-t** [comment]
OK, let's close the issue.
