### ISSUE TITLE
nghttp2_session_want_write returns 0 after GOAWAY, even with active streams.

### ISSUE THREAD

**Issue by bbfgelman1** [nghttp2/nghttp2#832]
I'm trying to implement graceful shutdown in my server application. As described in your documentation and in the RFC, I do this by sending a GOAWAY frame with the last client-initiated stream ID I intend to process. At the moment, this is always done by calling

```c++
nghttp2_submit_goaway(my_session, NGHTTP2_FLAG_NONE,
                      nghttp2_session_get_last_proc_stream_id(my_session),
                      NGHTTP2_NO_ERROR, NULL, 0)
```

The problem is that after the GOAWAY frame gets sent (the on_frame_send_callback gets called), `nghttp2_session_want_write` returns 0, even if there are responses ready to be written. This is also true for the client session. After receiving a GOAWAY frame, `nghttp2_session_want_write` returns 0 even if there is more data to send for streams <= last stream id.

**I think this is very misleading, because even though want_write returns 0, calling mem_send will produce data to send.**

I have seen cases where want_write returns 1 but mem_send returns 0. I think this is ok because the very next call to want_write will return 0. In my opinion, the opposite (want_write = 0, mem_send > 0) should not be possible.

**Comment by tatsuhiro-t** [comment]
It looks like  3fd5d0af799852f0549a0af14b31c095bba2a6ea will remove the check against active streams.  Will check why I did it.

**Comment by tatsuhiro-t** [comment]
#835 fixes this issue.
