### ISSUE TITLE
stream getting closed after returning NGHTTP2_ERR_PAUE from send_data_callback

### ISSUE THREAD

**Issue by vgmahajanshetty** [nghttp2/nghttp2#833]
Hi Tatsuhiro,

I'm using nghttp2 library version nghttp2-1.16.0.

I have set the callback function of type nghttp2_send_data_callback, let's call it "Send_Data_Callback()" to avoid copying of data.

Inside Send_Data_Callback(), based on some condition, I will return "NGHTTP2_ERR_PAUSE". This will result in closing the stream, as the callback "nghttp2_on_stream_close_callback()" gets called with error code as 0. Later if I try to send data using nghttp2_session_send() then it's not sending any data.

I think when stream is closed then library will not be able to send any data on that stream, I think this is correct behavior, but I'm not understanding why is the stream getting closed when NGHTTP2_ERR_PAUSE is returned from Send_Data_Callback() ? My understanding is when I return NGHTTP2_ERR_PAUSE from Send_Data_Callback(), it pauses the stream from sending any data and it continues to send after calling nghttp2_session_send() later. Is this understanding correct? Correct me if it's wrong.

Thanks,
Vishwanath G M

**Comment by tatsuhiro-t** [comment]
I think your understanding is correct.  I can think that the reason why nghttp2_on_stream_close_callback is called is that application sets NGHTTP2_DATA_FLAG_EOF.  Is that the case?  Can you share the source code to reproduce this?

**Comment by vgmahajanshetty** [comment]
Hi,

Yes, NGHTTP2_DATA_FLAG_EOF was set, but that data was not sent because socket was not writable that moment and returned EWOULDBLOCK. Please go through below code snippet:

/*===============================================*/

nghttp2_data_provider data_prd;
data_prd.read_callback = read_callback;

static ssize_t read_callback(nghttp2_session *session,
                                  int32_t stream_id, uint8_t *buf,
                                  size_t length, uint32_t *data_flags,
                                  nghttp2_data_source *source,
                                  void *user_data)
{

    /*some code ..... */

    *data_flags |= NGHTTP2_DATA_FLAG_NO_COPY;

    if (server_sent_eof) {  //backend server sent EOF for this request
        *data_flags |= NGHTTP2_DATA_FLAG_EOF;
    }

    return ret_length; //this ret_length is always less than or equal to 'length' which is input param to this function
}


static size_t Send_Data_Callback(nghttp2_session *session,
                                 nghttp2_frame *frame,
                                 const uint8_t *framehd, size_t length,
                                 nghttp2_data_source *source,
                                 void *user_data)
{
    int32_t ret_val = 0, send_length = 0;
    unit8_t *buffer;

    /* send_length is calculated based on padding, frameheader (9 bytes) 
      and actual data length to send */
    buffer = calloc(1, send_length);

    /* here I will prepare the buffer as required for nghttp2_send_data_callback 
       considering frame->data.padlen
     */

    ret_val = send_data_to_client(buffer); //this may return EWOULDBLOCK

    if (ret_val == EWOULDBLOCK) {

        /* in this case, I will return NGHTTP2_ERR_PAUSE to nghttp2 library 
           and expecting it to NOT to close stream as data is not sent though 
           flag NGHTTP2_DATA_FLAG_EOF was set. I will save this buffer and try to 
           send it when socket becomes writable later, by calling nghttp2_session_send()
           which eventually calls read_callback() and Send_Data_Callback() */

        return NGHTTP2_ERR_PAUSE;
    }

    if (ret_val == 0) {
        return 0;
    } else {
        return NGHTTP2_ERR_CALLBACK_FAILURE;
    }

    /*  some code.... */
}
/*===============================================*/

As you can see, I'm returning NGHTTP2_ERR_PAUSE when send_data_to_client() returned EWOULDBLOCK. I should send same data again when it becomes writable, so I returned NGHTTP2_ERR_PAUSE, but soon after returning this, "on_stream_close_callback()" is getting called as stream got closed by library and subsequent nghttp2_session_send() will not send any data on this stream.
I'm expecting not to close stream when NGHTTP2_ERR_PAUSE is returned even though NGHTTP2_DATA_FLAG_EOF was set.

Please let me know whether this correct behavior? or is this bug?

Thanks,
Vishwanath G M

**Comment by tatsuhiro-t** [comment]
I think what you are looking for is NGHTTP2_ERR_WOULDBLOCK:

Quoted from manual:
> If it cannot send any data at all, just return NGHTTP2_ERR_WOULDBLOCK; the library will call this callback with the same parameters later (It is recommended to send complete DATA frame at once in this function to deal with error; if partial frame data has already sent, it is impossible to send another data in that state, and all we can do is tear down connection). 

Using NGHTTP2_ERR_PAUSE tells nghttp2 library that complete DATA frame has sent, and without sending sending further frames, just return to the application code.

**Comment by vgmahajanshetty** [comment]
Hi,

I tried returning NGHTTP2_ERR_WOULDBLOCK in above case instead of NGHTTP2_ERR_PAUSE, but Send_Data_Callback() OR read_callback() will not be called again by library. As per the manual it should call this callback later, but it's not happening. For this reason I started using NGHTTP2_ERR_PAUSE as return value and saving buffer in application and send it again when socket becomes writable.

Can you please let me know should I set any flags in stream or nghttp2_session structures before returning NGHTTP2_ERR_WOULDBLOCK from Send_Data_Callback() ?

Thanks,
Vishwanath G M

**Comment by tatsuhiro-t** [comment]
Not special flag is required except for NGHTTP2_DATA_FLAG_NO_COPY which you already specified.

It works for me; after returning NGHTTP2_ERR_WOULDBLOCK, the next invocation of nghttp2_session_mem_send calls send_data_callback.

**Comment by vgmahajanshetty** [comment]
Hi,

Thanks for you reply. I'm using "nghttp2_session_send()" instead of "nghttp2_session_mem_send()" throughout my application. I think this should not make any difference and ideally it should call send_data_callback() in next invocation after returning NGHTTP2_ERR_WOULDBLOCK, right? Please correct me if this understanding is wrong.

Thanks,
Vishwanath G M

**Comment by tatsuhiro-t** [comment]
Yes, it should work.  I verified it using modified version of examples/libevent-server.c.
