### ISSUE TITLE
nghttpx: dns resolv

### ISSUE THREAD

**Issue by aguilbau** [nghttp2/nghttp2#834]
Hello, I know that nghttpx has an option to resolv backends every X seconds, `dns`.

However, is their a way to make it resolv it every time it fails to contact the backend ?

**Comment by tatsuhiro-t** [comment]
Try --dns-cache-timeout=0

**Comment by aguilbau** [comment]
Thanks ! 
What will happend then ? the proxy will query the resolver for every request ?

**Comment by tatsuhiro-t** [comment]
Yes.
