### ISSUE TITLE
Q: nghttpx as a protocol translator?

### ISSUE THREAD

**Issue by kapekto1** [nghttp2/nghttp2#839]
```
Client <-- (HTTP/1.1) --> nghttpx <-- (HTTP/2) --> NGINX <--- (HTTP/1.1) ----> Web Server
                     [forward proxy]           [reverse proxy]
```

Hello, is it possible to setup a such environment as above?
I would like to have just a translator (nghttpx) from HTTP/1.1 to  HTTP/2.0 to create HTTP2.0 tunnel between nghttpx and NGINX.

**Comment by tatsuhiro-t** [comment]
So you just want to put nghttpx between client and particular NGINX web site, right?
If so, nghttpx can do this.  Use "proto=h2" keyword in `--backend `option.  If you want TLS, use "tls" keyword too.  And don't use `-s` option.

**Comment by kapekto1** [comment]
Thanks for answer. Yes, this is exactly what I want to. So, because I'm not sure if I fully understand "backend and frontend" idea used here, is NGINX acts here as a backned server? Is my following idea correct?

`nghttpx -f'*,80;no-tls' -b[my_nginx_ip_address],nginx_listen_port
`
HTTP/1.1 client connects to nghttpx:80 and nghttpx will forward traffic as HTTP/2 to NGINX?

**Comment by tatsuhiro-t** [comment]
I think your understanding is correct.  proto=h2 is also required to in -b option:

```
nghttpx -f'*,80;no-tls' -b'[my_nginx_ip_address],nginx_listen_port;;proto=h2'
```

**Comment by kapekto1** [comment]
Cool I used it that way and I cannot connect through nghttpx. I used command:

`nghttpx -f'*,443;' -b'nginx_server,443;;proto=h2;tls' ./nghttpx.key ./nghttpx.crt`

And I'm trying to connect through nghttpx machine from another host (from terminal console) using https_proxy="http://nghttpx_server:443".
Then I'm launching links webbrowser from console and get nothing (waiting for connection). No any traces in nginx logs... Is it possible in that way or maybe it is too complicated setup?

**Comment by tatsuhiro-t** [comment]
Is the certificate of nginx_server signed by know CA or self-signed?  If it is self-signed, provide its certificate to nghttpx using --cacert, or as a last resort, use -k to disable TLS server authentication.

With this setup, https_proxy=... does not work.  Client should point to the address of nghttpx.

**Comment by kapekto1** [comment]
It works ;)
Thanks for help :)
