### ISSUE TITLE
Unused variable warnings

### ISSUE THREAD

**Issue by hsleisink** [nghttp2/nghttp2#840]
Could you please replace all the unused warning prevention tricks by using (void) casts?

So, instead of
```
int function(int variable _U_) {
}
```
use this
```
int function(int variable) {
  (void)variable;
}
```
This way, it's more compiler independent and saves a lot of build system trickery.

**Comment by tatsuhiro-t** [comment]
Agreed.  We can save defining _U_ for compilers other than gcc or clang.

**Comment by hsleisink** [comment]
Thanks!
