### ISSUE TITLE
ERR_EMPTY_RESPONSE when using 'redirect-if-not-tls'

### ISSUE THREAD

**Issue by Ronsevet** [nghttp2/nghttp2#843]
Hi,

I've tried testing the redirect-if-not-tls param ,I added a port 80 frontend, added the param to the backend but I only get ERR_EMPTY_RESPONSE when browsing to it on port 80, is there something I am missing here?

Thanks,

Ron

**Comment by tatsuhiro-t** [comment]
First thing to check is that TLS frontend is enabled (e.g., `-f'*,443;tls'`).
The port in redirect URI host is 443 by default.  If the TLS port number is not 443, then use `--redirect-https-port` to specify the desired port.

**Comment by Ronsevet** [comment]
@tatsuhiro-t  thanks for the response...
my wish is basically to have nghttpx listen on port 80 and force these connections to redirect to 443, what would you say is the best approach? 

Thanks,

Ron

**Comment by tatsuhiro-t** [comment]
My working example is like this:

```
$ nghttpx server.key server.crt -f'*,443' -f'*,80;no-tls' -b'127.0.0.1,3001;;redirect-if-not-tls'
```

nghttpx listens both 443 (TLS) and 80 (no-TLS).  Accessing port 80 by curl results:

```
$ curl http://localhost/ -D-
HTTP/1.1 308 Permanent Redirect
Location: https://localhost/
Connection: close
Server: nghttpx

```

**Comment by Ronsevet** [comment]
@tatsuhiro-t 

here is my config updated with your suggestion - 

frontend=*,443
frontend=*,80;no-tls
backend=66.6.X.X,80;redirect-if-not-tls
http2-proxy=yes
#errorlog-syslog=yes
add-x-forwarded-for=yes
add-request-header=X-Forwarded-Proto: https
accesslog-file=/var/log/nghttpx/access.log
errorlog-file=/var/log/nghttpx/error.log

when trying to browse my site i get -

400 Bad Request

nghttpx nghttp2/1.19.0

Thank you for your help

Ron

**Comment by tatsuhiro-t** [comment]
`backend=66.6.X.X,80;redirect-if-not-tls` should be `backend=66.6.X.X,80;;redirect-if-not-tls`
(notice extra semicolon after 80)
But normally such error is caught by nghttpx, and it refuses to run.
Also remove "http2-proxy=yes" if you are using nghttpx as reverse proxy.
"X-Forwarded-Proto" header field is automatically added, so add-request-header=... is not required.

**Comment by Ronsevet** [comment]
@tatsuhiro-t 
when adding the second semicolon the service wont start (I am running nghttpx with it's upstart init as a service and with a conf file not line flags),
btw - why do you suggest not using http2-proxy?

**Comment by tatsuhiro-t** [comment]
The syntax of backend option is the same between command-line and config file, except for the fact that the quotation is not required in config file.
Please make sure that the init file points to the correct nghttpx configuration file.

http2-proxy is used to make nghttpx function as forward proxy (e.g.,  as a  HTTP/2 frontend for squid).
https://nghttp2.org/documentation/nghttpx-howto.html#http-2-proxy-mode
In this case, proxy URI is explicitly configured to client (browser) via flags or proxy.pac file.
I think the redirection does not work in this case.  Just listen on 443 port, and configure client to use https proxy URI.
