### ISSUE TITLE
libnghttp2_asio prevent timeouts when connecting to APN

### ISSUE THREAD

**Issue by mikealeonetti** [nghttp2/nghttp2#847]
This is pretty awesome. Quick question.

When connecting to APN, the Apple documentation says to keep the connexion open and check the quality of the connexion by sending PING frames. Is there a way to do this using the libnghttp2_asio library? When I open a connexion it usually times out after 60 seconds. Apple warns that continual connexions will look like DOS attacks, so I'd like to try and keep it open as best as possible.

Thanks.

**Comment by tatsuhiro-t** [comment]
There is no way to send PING with libnghttp2_asio.  The underlying library has the capability to send PING, so adding feature is possible.
I think 60 seconds timeout is not so small.  Have you got any warnings from Apple when you reconnect to the endpoint in every 60 seconds?

**Comment by mikealeonetti** [comment]
I have not gotten any warnings. Although I'd rather have it not time out. Could I program in to your code a timer using the nghttp2_submit_ping method on the session?

**Comment by tatsuhiro-t** [comment]
Yes.  I just did it in PR #848.  Could you test it?

**Comment by mikealeonetti** [comment]
Seems to work well. I had it running for a few hours connected to APN and I sent a Push Notification every 10 minutes. It works well. Thanks. I'm going to use this PR live for now.

**Comment by tatsuhiro-t** [comment]
Thank you.  Will merge the PR.
