### ISSUE TITLE
how to use nghttp to create mulit-streams to download from a server(the server have already support http2)

### ISSUE THREAD

**Issue by y123456yz** [nghttp2/nghttp2#852]
I use "nghttp -nv http://ip:port/xxx.tar.gz" to download xxx.tar.gz (it is a large file).  but it only create one stream to communicate with the http2 server.

I want to use multi-streams to communicate with the http2 server.

how to use nghttp ?

**Comment by y123456yz** [comment]
my http2 server is a file server that using nginx(already support http2). but I do not know how to use nghttp to communicate with nginx by using multi-streams

**Comment by y123456yz** [comment]
I Have another question, how to create 2 streams to download two diffrent file whith a connection at the same time.

if nghttp have the function, how to use nghttp to realize it.

**Comment by tatsuhiro-t** [comment]
To create 2 streams, give nghttp 2 URIs:  nghttp -nv https://example.com/foo https://example.com/bar

nghttp is not download tool.  Its -O option does not work, and if 2 streams are concurrently running, nghttp interleaves their response data in undefined manner.

**Comment by y123456yz** [comment]
@tatsuhiro-t  thanks

I want to see the multi-stream package through wireshark and debug nginx with multi-stream. 
your  answer is alread Meet my requirements.
thank you again.

**Comment by tatsuhiro-t** [comment]
Alright, let's close the issue.
