### ISSUE TITLE
example/client.c was failed

### ISSUE THREAD

**Issue by crinaZhao** [nghttp2/nghttp2#854]
Thank you for your great HTTP/2 library. I always use this software as a reference to develop trusterd.

I run the examples/client with below command to send request
./client "https://avs-alexa-na.amazon.com/v20160207/directives"

[INFO] C ----------------------------> S (HEADERS)
:method: GET
:scheme: https
:path: /v20160207/directives
authorization: Bearer {token}
[INFO] C <---------------------------- S (GOAWAY)
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF

My libnghttp version is v1.20.0
I do not know why server shut down the connection...

**Comment by tatsuhiro-t** [comment]
I also don't know why server closed the connection.  Server might not authorize the request or some sort.  If request is not right, server usually responds with 4xx status code.  But server has all the right to do some counter measure to protect itself.

**Comment by crinaZhao** [comment]
Thanks for your quick answer:) Where can I print response statues code? I send a GET request,  server responses information without body. Is that normal msg=EOF?

**Comment by crinaZhao** [comment]
Is that possible because of token too long?

**Comment by tatsuhiro-t** [comment]
It appears that server only sends GOAWAY, and no response. msg=EOF tells us that server closed connection.

**Comment by crinaZhao** [comment]
From wireshark log, I caught
601	242.290174160	client	server	TLSv1.2	180	Client Key Exchange, Change Cipher Spec, Encrypted Handshake Message
602	242.682593759	server	client	TLSv1.2	155	Change Cipher Spec, Hello Request, Hello Request, Application Data
Should I change configuration about SSL?

**Comment by crinaZhao** [comment]
How can I change Cipher Suit orders in nghttp2?

**Comment by tatsuhiro-t** [comment]
Assuming you are working with client.c, you should use SSL_CTX_set_cipher_list in fetch_uri function.

**Comment by crinaZhao** [comment]
Thanks a lot for your kindly reply:)  How can I print response status_code in client.c?

**Comment by tatsuhiro-t** [comment]
HTTP status code is shown when it is received.

**Comment by crinaZhao** [comment]
Thanks for your kindly reply. I will close this issue. Thanks very much.

**Comment by jtlkm** [comment]
Hi @crinaZhao 
Is your problem solved?  I have encountered a similar problem.
request:
request:
 nghttp2_nv hdrs[] = {
 MAKE_NV2(":method", "GET"),
 MAKE_NV2(":scheme","https"),
 MAKE_NV2(":path","/v20160207/directives"),
 MAKE_NV2("authorization","Bearer Atza|IwEBIO64ezexgTyd1jNfasksuW42slGru0CWGdv8vhDQG5RJdHf3ZPXj_6GCm73zPsln7miEc97z-jzrSskSOcjGiC-qwNdMF7yPRtwM_431Kk9VN7nSqHic1pv5wjiU-E7-pyHemAt0AFhRjkPKiPL4mMFW-UgIra_8gViyP9H6nR89mneeKMIu4NStwG5Pgr7qWxiKLU1FuM8BBTyYjNaQ_wsvO658Ry4t82C7_Z5TcPF9_fn-OHmwNyNT8bWv5mQiYCTrF6vtChOo_IGkgcqgGWRuPsWGpntUdAnU6-1-3p2YPL7dk7MsT5MmvgKr5NHqopEOmfEdtm-atneLiDMguyCWtUIr5SBeVBfGXtev03Q3oWULbZ7PU0EvPVzVU2bK5eChMCF_fe-EMqr9g94EyJylUdM9V0MDQx55rz9q9QYSRcZFUiW3UxvxQIaQjumm4X3Xx69k00ohdwCpucClgKh5azVcRVnPgzYvyWSv7OOsshLKTZ1SfANrUyW0G76M4N_Df-EbhA8TQ4ScynMRffMPnlCHkDVz4orfNd-8348-fgfmEnc0i-Y17bcUVxrD1Rw"),
 };
server  response:
 :status: 200
 access-control-allow-origin: *
 x-amzn-requestid: 0e0f55fffe053c3c-000070d9-000301e3-49948381c86f4659-d452715c-1
 content-type: multipart/related; boundary=------abcde123; type=application/json
 All headers received

But after a few seconds eventcb received BEV_EVENT_EOF （Disconnected from the remote host）。
Why the server will automatically disconnect, what needs to set up? Is it not a long connection?
