### ISSUE TITLE
Server push - dropped packets?

### ISSUE THREAD

**Issue by marwankhalili** [nghttp2/nghttp2#855]
I've been experimenting with server push using the libnghttp2_asio library. 

I noticed that only 200 messages are received by the client no matter how many resources I push from the server (see example code below). Is this a limit for the number of concurrent streams per connection?

<details>
<summary> Server pushing resources (800 x 11 bytes) </summary>

```
server.handle("/", [](const request &req, const response &res) {
    boost::system::error_code ec;
    for (size_t i = 0; i < 800; i++) {
        auto push = res.push(ec, "GET", "/" + std::to_string(i));
        push->write_head(200);
        push->end("Hello world");
        std::cerr << i << ": Pushed bytes " << std::endl; 
    }
    res.write_head(200);
    res.end();
});
```

</details>

</br>

<details>
<summary> Client receiving push stream (200 x 11 bytes) </summary>

```
auto count = std::make_shared<int>(0);
req->on_push([&count](const request &push) {
    push.on_response([&](const response &res) {
        res.on_data([&](const uint8_t *data, size_t len) {
            std::cerr << ++(*count) << ": Received bytes " << len << std::endl;
        });
    });
});
```

</details>

**Comment by tatsuhiro-t** [comment]
nghttp2 client session has the built-in mechanism to limit the number of reserved streams by the server, and the default value is 200.  https://nghttp2.org/documentation/nghttp2_option_set_max_reserved_remote_streams.html
The reason why we do this is that RFC 7540 does not impose the limit of reserved streams.  To protect the client session from the memory exhaustion with lots of reserved stream state, we added this feature.

**Comment by marwankhalili** [comment]
Ok, that's understandable. Thanks for clarifying!
