### ISSUE TITLE
what's means of PKG_PROG_PKG_CONFIG(0.20)  in configure

### ISSUE THREAD

**Issue by y123456yz** [nghttp2/nghttp2#859]
when I run configure, it error,
......................
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
./configure: line 6414: syntax error near unexpected token `0.20'
./configure: line 6414: `PKG_PROG_PKG_CONFIG(0.20)'

but I have install pkg-config
[root@xxx nghttp2]# pkg-config --version
0.23
[root@xxx nghttp2]#

**Comment by y123456yz** [comment]
[root@xxx nghttp2]# rpm -qa | grep libtool
libtool-2.2.6-15.5.el6.x86_64

[root@xxx nghttp2]# ./configure
.....................
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
./configure: line 4169: syntax error near unexpected token `2.2.6'
./configure: line 4169: `LT_PREREQ(2.2.6)'

**Comment by y123456yz** [comment]
@tatsuhiro-t 

I want to know want means of PKG_PROG_PKG_CONFIG(0.20) and LT_PREREQ(2.2.6).
whether nghttp2 need libtool >= 2.2.6 and pkg-config >= 0.20

but my version is already satisfy the requirement

**Comment by y123456yz** [comment]
run libtoolize can resolve this porblem, thanks

**Comment by y123456yz** [comment]
@tatsuhiro-t

please close the problem. thanks

**Comment by tatsuhiro-t** [comment]
Normally, libtoolize is not required.  README suggests required Ubuntu package.  They have slightly different name in RPM.
Anyway, good to here that problem was solved.

**Comment by whitekyo** [comment]
> libtoolize

how do you fix it?

I still don't work
