### ISSUE TITLE
generator_cb usage

### ISSUE THREAD

**Issue by jontom123** [nghttp2/nghttp2#860]
Hey I have a problem that I haven't been able to figure out, currently I'm using libnghttp2_asio to communicate with a server, I establish a session fine but when I want to submit a request I use generator_cb to generate the body, the data is coming from the microphone so I read 10 ms of audio and return them, everything is working ok until now but the problem comes when the len variable of generator_cb keeps decreasing until it reaches 0, it lasts about 1.5 seconds and then I can't send any more data.

My question is why is this happening? why does the len variable keep decreasing? 

Another important question is when I do 

`auto req3 = sessGlobal->submit(ec3, "POST", "https://example.com/",mic_audio(capture_handle),h3);`

mic_audio(handle) is a modified function based on the included file_generator_from_fd but instead of reading a file I read the microphone

Does it immediately submit the request and then slowly chunks the data generated by generator_cb as it is available or does it first completely load all the data and then submit the request?

Currently it will read about 1 second of microphone audio, then I will get the submitted successfully message, but I still want to continue sending data.

**Comment by tatsuhiro-t** [comment]
The answer to the first question is that HTTP/2 has flow control feature, and there are limit who much data can be sent at a time.  By default, it is 64KiB.  Peer will send WINDOW_UPDATE to recover the window.  There will be some delay between sending data, and receiving WINDOW_UPDATE form peer, thanks to RTT.

The second question is it depends on the implementation of mic_audio.  The specification of generator_cb does not require that all data must be assembled before hand.  It supports the transfer in away that data is streamed into the connection.

**Comment by jontom123** [comment]
Hey Tatsuhiro, thanks for the quick reply, currently I send 320 bytes every 10ms, and in total I send almost 64KiB, since len always reaches zero at about 2 seconds(64KiB is 2.048 seconds of audio) 

So is this the reason why len keeps decreasing, because I reached the total 64KiB limit? it takes me about 2 seconds to reach this limit shouldn't WINDOW_UPDATE be received by now? how can this problem be fixed in streaming scenarios?

here is my mic_audio implementation

`generator_cb mic_audio(snd_pcm_t* fd) {
  auto d = defer_shared(snd_pcm_close, fd);
  return [fd, d](uint8_t *buf, size_t len, uint32_t *data_flags)
      -> generator_cb::result_type {
        
	if (stopFlag) {
          memcpy( (void*)buf, (void*)reinterpret_cast<const uint8_t*>(endingVoice.data()) , endingVoice.length() );
	  slen=slen+endingVoice.length();
          *data_flags |= NGHTTP2_DATA_FLAG_EOF;
           return slen;
        }

	if (len<320 ) {
	 fprintf (stderr, "Error, can't send any more data");
         return 0;
        }

	if(first){
	 first=false;
         memcpy( (void*)buf, (void*)reinterpret_cast<const uint8_t*>(dataVoice.data()) ,dataVoice.length() );
         slen=dataVoice.length();
	}
        uint8_t *buf2=buf+slen;
        n = snd_pcm_readi (fd, buf2, 160);
        n=n*2;
        if (n != 320) {
          fprintf (stderr, "read from audio interface failed (%s)\n",snd_strerror (n));
          return NGHTTP2_ERR_TEMPORAL_CALLBACK_FAILURE;//this has never been returned
        }
	buf[n+slen]=0;
        return n+slen;
      };
}
`

I think the issue might be that mic_audio is not streaming data into the connection but actually just getting 64KiB of data and sending it, that's why the WINDOW_UPDATE isn't received in time. Is this the issue? and if so how can I make a generator_cb function that actually streams the data?

**Comment by tatsuhiro-t** [comment]
It depends on the server when WINDOW_UPDATE is sent;  client has to wait for it.
libnghttp2_asio will call generator_cb again when WINDOW_UPDATE is received, and window size is enlarged again.
In generator_cb, application can just write the len (which is passed as a parameter) bytes of data.
The application should write at most len bytes of data to buf, and no more.  If there are data left to send, don't worry.  The library will call generator_cb again, and you can write the part of remaining data there.

**Comment by jontom123** [comment]
mic_auido is continually called with values of 30 or 40 in len, which is useless for me so I just skip it like this

`if (len<320 ) {
	 fprintf (stderr, "Error, can't send any more data");
         return 0;
        }`

Is this the correct behavior while waiting for the WINDOW_UPDATE to be sent?

Looking at asio_common.cc

`generator_cb file_generator_from_fd(int fd) {
  auto d = defer_shared(close, fd);

  return [fd, d](uint8_t *buf, size_t len, uint32_t *data_flags)
      -> generator_cb::result_type {
        ssize_t n;
        while ((n = read(fd, buf, len)) == -1 && errno == EINTR)
          ;

        if (n == -1) {
          return NGHTTP2_ERR_TEMPORAL_CALLBACK_FAILURE;
        }

        if (n == 0) {
          *data_flags |= NGHTTP2_DATA_FLAG_EOF;
        }

        return n;
      };
}
`

This will set NGHTTP2_DATA_FLAG_EOF if n==0, and length might get to zero but just because the WINDOW_UPDATE frame hasnt't been received, in this case wouldn't this be an error since the file wasn't fully sent?

**Comment by tatsuhiro-t** [comment]
> Is this the correct behavior while waiting for the WINDOW_UPDATE to be sent?

No.  It is better to send data as much as possible.
libnghttp2 sends the written bytes in one DATA frame.  The boundary of DATA frame is not significant in HTTP/2 in general.  If it is required to keep boundary of chunk of data, application should first encode them to tell the receiver the data boundary, and write them without considering DATA frame boundary in streaming fashion.  Server should read incoming data, and concatenate/split them as necessary by decoding application specific encoding.

> This will set NGHTTP2_DATA_FLAG_EOF if n==0, and length might get to zero but just because the WINDOW_UPDATE frame hasnt't been received, in this case wouldn't this be an error since the file wasn't fully sent?

When generator callback is called, len must be greater than 0.
And the return value 0 from read() means EOF, which means it reads whole file.
So setting NGHTTP2_DATA_FLAG_EOF is correct in this case.

**Comment by jontom123** [comment]
I have been searching the source code and managed to "fix" the problem for now by modifying the initial window size set inside of nghttp2, as the server I'm connecting to never sends the initial windows size setting when the connection is established, I tried manually updating the remote window size with available functions in nghttp2 (submit_window_update) but it didn't work, is it possible the server just ignored them?

Currently I set the initial window size to 1MiB and everything seems to be working alright, although the server response is a little slow which leads me to another question

> libnghttp2 sends the written bytes in one DATA frame

You said they get sent in one DATA frame, but I want to send each 320 byte chunk in a separate data frame, to make it more responsive as the data keeps getting sent, does the generator_cb send a DATA frame each time the function is called, or does it concatenate a bunch of data(filled through many generator_cb calls) and sends it together in a DATA frame?

**Comment by tatsuhiro-t** [comment]
> I have been searching the source code and managed to "fix" the problem for now by modifying the initial window size set inside of nghttp2, as the server I'm connecting to never sends the initial windows size setting when the connection is established, I tried manually updating the remote window size with available functions in nghttp2 (submit_window_update) but it didn't work, is it possible the server just ignored them?

There is no public API to change peer's window size.  It must be updated by peer which is required by protocols spec.

> Currently I set the initial window size to 1MiB and everything seems to be working alright, although the server response is a little slow which leads me to another question

I'm not sure you are controlling server too, but it would be better to configure server to enlarge window size to 1MiB or so.

> You said they get sent in one DATA frame, but I want to send each 320 byte chunk in a separate data frame, to make it more responsive as the data keeps getting sent, does the generator_cb send a DATA frame each time the function is called, or does it concatenate a bunch of data(filled through many generator_cb calls) and sends it together in a DATA frame?

Responsive or not responsive depends on the server implementation.  As far as I know, depending on the DATA frame boundary in generic HTTP/2 is naive.
One call to generater_cb corresponds to single DATA frame.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
