### ISSUE TITLE
nghttpx: Single process mode?

### ISSUE THREAD

**Issue by devlearner** [nghttp2/nghttp2#869]
Hi Tatsuhiro,

Thank you for the continuous development of this useful library and the related utilities i.e. nghttpx, nghttp, nghttpd, h2load etc—these tools really made our lives easier and much better ;)

Recently, i just ran into a situation where i was trying to debug a weird behaviour on my system—which I suspect, nails down to ipc; but rest assured the culprit isn't on nghttpx per se ;) —but it would be quite useful if I could somehow run nghttpx in single process mode (aka, minus the master process) to aid in debugging and confirming my preposition ;)

I tried the `--disable-threads` compile option, as well as `-n 0` and the `--single-thread` runtime options, however it seems that at least 1 worker process is spawned by the master process.  Is it possible to run nghttpx in single process mode so that a single worker process would stand on its own without a master process?

I noticed that there seems to be a similar option in nginx: (from its [FAQ](http://nginx.org/en/docs/faq/daemon_master_process_off.html))
> In a development environment, using "master_process off", nginx can run in the foreground without the master process and can be terminated simply with ^C (SIGINT). This is somewhat similar to running Apache with an 'X' command-line option. However you should NEVER run nginx in production with "master_process off". 

And as it rightly observes, which i understand, it probably won't be used in a production environment.  Any help on having this as a developer/debugging option would be useful and greatly appreciated ;)

**Comment by tatsuhiro-t** [comment]
I agree that it is useful for development purpose.  Actually, I always do some changes to run nghttpx in a single process to produce correct profiling result.
It requires to give up some features (signal handling), but it is a reasonable compromise since they are not so much useful for debugging.

**Comment by tatsuhiro-t** [comment]
#875 implements "single process mode".

**Comment by devlearner** [comment]
Thank you!
