### ISSUE TITLE
O_CLOEXEC not defined

### ISSUE THREAD

**Issue by acesso** [nghttp2/nghttp2#87]
After few hours compiling all the tool chain to compile it on Centos 5.5 i´ve found out that util.cc uses O_CLOEXEC witch is not on this distro kernel since this function was added on  2.6.23 (centos5 still uses 2.6.18). I know this is old but may address builders on old boxes.

**Comment by barracuda156** [comment]
Missing `O_CLOEXEC ` supposed to be fixed here: https://www.gnu.org/software/gnulib/manual/html_node/fcntl_002eh.html
