### ISSUE TITLE
How to use nghttp2 send http1.1 request

### ISSUE THREAD

**Issue by howardguo** [nghttp2/nghttp2#880]
Hi 
1. How I can use nghttp2 to send http1.1 request? 
2. when I send http2 request to AVS(http2 service), I can not get the header data. How to get header data? ex: no status(200).

**Comment by tatsuhiro-t** [comment]
libnghttp2 cannot issue HTTP/1.1 request.
Assuming you are using libnghttp2 C API, response headers are received via [nghttp2_on_header_callback](https://nghttp2.org/documentation/types.html#c.nghttp2_on_header_callback).  See also https://nghttp2.org/documentation/nghttp2_session_callbacks_set_on_header_callback.html#c.nghttp2_session_callbacks_set_on_header_callback

**Comment by howardguo** [comment]
thanks, got it.
