### ISSUE TITLE
nghttp2 might not compile with gcc-7

### ISSUE THREAD

**Issue by tatsuhiro-t** [nghttp2/nghttp2#882]
gcc-7 combined with the upcoming C++17 might not compile nghttp2.
One of the reason behind that is http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0012r1.html

Since they are not released yet, and C++17 standardization is also still in progress, we use this issue to track their progress, and the compilation issue we currently have.

**Comment by zdzichu** [comment]
FYI, Fedora 26 and Fedora rawhide at the moment come with GCC 7.1. It just went in, previously both were shipping GCC 7.0.1. Both nghttp2 1.21.1 and 1.22.0 compiled fine with GCC 7.0.1:
https://koji.fedoraproject.org/koji/buildinfo?buildID=878111
https://koji.fedoraproject.org/koji/buildinfo?buildID=882825

**Comment by tatsuhiro-t** [comment]
Thank you for the info.  It may depend on the extra compiler flags. Will check.

**Comment by tatsuhiro-t** [comment]
Fix committed via 17c88d60c73c518512fef252989ce6ef5667ff67
