### ISSUE TITLE
Memory leak on error in lib/nghttp2_session.c

### ISSUE THREAD

**Issue by lstefani** [nghttp2/nghttp2#884]
In ```static int inflight_settings_new()``` in ```lib/nghttp2_session.c```, the second ```return NGHTTP2_ERR_NOMEM;``` call is missing a free of the memory allocated in ```*settings_ptr```.

The fix is to replace
```
  if (niv > 0) {
    (*settings_ptr)->iv = nghttp2_frame_iv_copy(iv, niv, mem);
    if (!(*settings_ptr)->iv) {
      return NGHTTP2_ERR_NOMEM;
    }
  } else {
    (*settings_ptr)->iv = NULL;
  }
```
with
```
  if (niv > 0) {
    (*settings_ptr)->iv = nghttp2_frame_iv_copy(iv, niv, mem);
    if (!(*settings_ptr)->iv) {
      nghttp2_mem_free(mem, *settings_ptr);
      return NGHTTP2_ERR_NOMEM;
    }
  } else {
    (*settings_ptr)->iv = NULL;
  }
```

**Comment by tatsuhiro-t** [comment]
It looks like a bug.  Could you make a PR for this?

**Comment by lstefani** [comment]
Created PR.

**Comment by tatsuhiro-t** [comment]
Thank you.  Looks like failmalloc test suite has been broken, and failed to catch this issue.

**Comment by tatsuhiro-t** [comment]
Hmm, travis does not pick the leak..  Anyway,  thank you very much for fixing this bug.
