### ISSUE TITLE
Ubuntu 14.04+boost 1.63 returns "tls: no application protocol negotiated" connecting to Apple APN

### ISSUE THREAD

**Issue by mikealeonetti** [nghttp2/nghttp2#893]
Hi again,

Thank you for all of your help so far. I've compiled the code on another machine running Ubuntu 14.04 and compiled my own boost 1.63 with the nghttp2 code (v1.21.1). The same boost 1.63 and nghttp2 v1.21.1 works fine connecting to APN on my Gentoo machine, however, on the ubuntu machine it complains:

> tls: no application protocol negotiated

However, running

> openssl s_client -connect api.development.push.apple.com:443 -cert certs/apn.crt -key certs/apn.key -debug -showcerts -CApath /etc/ssl/certs/

Seems to return no errors. The linking for boost and nghttp2 seems to be proper for the program:

> $ ldd bin/soundwave | grep -P '(nghttp2|boost|ssl|crypt)'
>         libboost_system.so.1.63.0 => /var/soundwave/bin/../lib/libboost_system.so.1.63.0 (0x00007fb7bc657000)
>         libboost_thread.so.1.63.0 => /var/soundwave/bin/../lib/libboost_thread.so.1.63.0 (0x00007fb7bc435000)
>         libboost_log.so.1.63.0 => /var/soundwave/bin/../lib/libboost_log.so.1.63.0 (0x00007fb7bc176000)
>         libboost_regex.so.1.63.0 => /var/soundwave/bin/../lib/libboost_regex.so.1.63.0 (0x00007fb7bbe8f000)
>         libnghttp2_asio.so.1 => /var/soundwave/bin/../lib/libnghttp2_asio.so.1 (0x00007fb7b8d42000)
>         libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fb7b8881000)
>         libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fb7b84a6000)
>         libboost_filesystem.so.1.63.0 => /var/soundwave/bin/../lib/libboost_filesystem.so.1.63.0 (0x00007fb7b7282000)
>         libnghttp2.so.14 => /var/soundwave/soundwave-cpp/out/lib/libnghttp2.so.14 (0x00007fb7b5b16000)
>         libgcrypt.so.11 => /lib/x86_64-linux-gnu/libgcrypt.so.11 (0x00007fb7b5449000)
>         libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007fb7b4d4d000)
>         libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007fb7b330a000)
>         libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fb7b237b000)

Where do you think the breakdown might be?

Thanks.

**Comment by tatsuhiro-t** [comment]
alpn support has been added to openssl since version 1.0.2.
Make sure that openssl version satisfies that condition.

**Comment by mikealeonetti** [comment]
Interesting. On another server I'm getting "Connection timed out" with it also. But the openssl client command I listed above works just fine. What would be the way to debug this?

**Comment by tatsuhiro-t** [comment]
Packet capture?  I want to know that whether TCP connection is established, and then TLS handshake has been started or not.  Or could be DNS?

**Comment by mikealeonetti** [comment]
Interesting. When I do a tcpdump and examine with wireshark, on the same server with the same user I do not see it trying to make any outbound connexions to any of the Apple IP addresses nor any DNS requests. However, I can dig and ping the IP address on the server. I also can use the openssl s_client, resolve, and successfully connect. That does appear on the wireshark.

**Comment by mikealeonetti** [comment]
Is there a debug mode for nghttp2 client so I can see where the failure is happening?

**Comment by tatsuhiro-t** [comment]
There is no debug mode for libnghttp2_asio.  Have you tried examples/asio-cl?

**Comment by mikealeonetti** [comment]
I haven't yet. I've created a sample piece of code that mimics yours that does work, however.

```
#include <iostream>

#include "boost/asio/io_service.hpp"
#include "boost/asio/ip/tcp.hpp"

int main( int argc, char *argv[] )
{

        const std::string host = "api.push.apple.com";
        const std::string service = "443";
        boost::asio::io_service io_service;
        boost::asio::ip::tcp::resolver resolver( io_service );

  resolver.async_resolve({host, service},
                          [](const boost::system::error_code &ec,
                                 boost::asio::ip::tcp::resolver::iterator endpoint_it) {

                                std::cout << "Error is: " << ec << std::endl;

                                    boost::asio::ip::tcp::endpoint ep = endpoint_it->endpoint();
                                std::cout << "IP resolved is: " << ep.address().to_string() << std::endl;
                          });

        io_service.run();


        return( EXIT_SUCCESS );
}
```

This works no problem with the same libs.

I've noticed an interesting issue giving this problem more depth. I've added some couts to your code to see where it's failing.

```
void session_impl::start_resolve(const std::string &host,
                                 const std::string &service) {
  deadline_.expires_from_now(connect_timeout_);

  std::cout << __PRETTY_FUNCTION__ << " start [" << host << ':' << service << ']' << std::endl;

  auto self = shared_from_this();

  resolver_.async_resolve({host, service},
                          [self](const boost::system::error_code &ec,
                                 tcp::resolver::iterator endpoint_it) {
				 std::cout << __PRETTY_FUNCTION__ << "Returned" << ec << std::endl;
                            if (ec) {
				 std::cout << "Resolver error." << ec << std::endl;
                              self->not_connected(ec);
                              return;
                            }

			    boost::asio::ip::tcp::endpoint ep = endpoint_it->endpoint();
			std::cout << "IP resolved is: " << ep.address().to_string() << std::endl;

                            self->start_connect(endpoint_it);
                          });

  deadline_.async_wait(std::bind(&session_impl::handle_deadline, self));
}
```

In this case, not only does async_resolve not return, but it seems to create a memory leak. I've put some loggers on the destructors.
```
session_impl::~session_impl() {
	std::cout << __PRETTY_FUNCTION__ << std::endl;
  // finish up all active stream
  for (auto &p : streams_) {
    auto &strm = p.second;
    auto &req = strm->request().impl();
    req.call_on_close(NGHTTP2_INTERNAL_ERROR);
  }
session::~session()
{
	std::cout << __PRETTY_FUNCTION__ << std::endl;
}
```
They never get called and my program just continues to increase in memory as it tries again and again to connect to the APN servers.

Just to see what would happen, I rewrote your connect function to the following:
```
void session_impl::start_resolve(const std::string &host,
                                 const std::string &service) {

  std::cout << __PRETTY_FUNCTION__ << " start [" << host << ':' << service << ']' << std::endl;

	auto self( shared_from_this() );

	io_service_.post( [ this, self, host, service ](){
		// Error code so boost is a no-throw
		boost::system::error_code error;
		boost::asio::ip::tcp::resolver::iterator iterator = resolver_.resolve( { host, service }, error );

		// Did we have a resolution error?
		if( error )
		{
			std::cout << "Error resolving " << error.message() <<std::endl;
			return;
		}

		start_connect( iterator );
	} );
}
```
And it resolves, connects, handshakes, and does everything no problem. The memory leak also disappears. I'm honestly not sure why this is. Any thoughts?

**Comment by tatsuhiro-t** [comment]
As far as I know, resolver_.resolve performs name resolution in blocking manner.  This is not the same as the original code, which does that asynchronously.

I tried boost 1.63 from Debian, and asio-cl works.  session_impl::~session_impl is also called.

**Comment by mikealeonetti** [comment]
That is indeed what is odd. It works on a Gentoo system of mine just fine with the same boost library. I'll have to do some digging in boost to and test to see how they implement their async_resolve and why their implementation is failing and mine isn't. It may take a couple of days since I'm trying to work on other things at the same time.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
