### ISSUE TITLE
expose tls_layer & tcp_layer socket_

### ISSUE THREAD

**Issue by yayo** [nghttp2/nghttp2#908]
"socket_" NOT exposed in
/usr/include/nghttp2/asio_http2_client.h

I need to GET  "socket_" when I implement
ASIO_HTTP2-PROXY_CLIENT -> http2_proxy_connect_server -> https1_server

I need to SET  "socket_" when I implement
ASIO_PROXY_HTTP2-CLIENT -> http1_proxy_connect_server -> https2_server

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
