### ISSUE TITLE
socks5 backend support

### ISSUE THREAD

**Issue by humiaozuzu** [nghttp2/nghttp2#909]
By default, nghttpx use http proxy (such as squid) as backend. Can you add support for socks5 as backend as we need to use shadowsocks(provide socks5 proxy) to receive the traffic.

**Comment by tatsuhiro-t** [comment]
It looks like squid has (limited) socks support: http://wiki.squid-cache.org/Features/Socks

**Comment by LPardue** [comment]
https://github.com/nghttp2/nghttp2/issues/313 is an old SOCKS ticket that may be of interest to @humiaozuzu. Are you trying to do something different?
