### ISSUE TITLE
libnghttp2_asio server request flow control

### ISSUE THREAD

**Issue by kevinmcm2** [nghttp2/nghttp2#911]
Right now the data_cb you can put on 'request' doesn't have an equivalent to NGHTTP2_ERR_DEFERRED if we want to put a hold on request data coming in. I could take a look at putting together a patch, but is it already happening?

**Comment by tatsuhiro-t** [comment]
Currently, flow control is managed by libnghttp2 automatically, and there is no workaround to turn it off.
Patch is welcome.  I think the proper way to handle flow control is disable automatic flow control using [nghttp2_option_set_no_auto_window_update](https://nghttp2.org/documentation/nghttp2_option_set_no_auto_window_update.html), and add wrapper function to call [nghttp2_session_consume](https://nghttp2.org/documentation/nghttp2_session_consume.html).

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
