### ISSUE TITLE
h2 CONNECT method request error in nghttpx

### ISSUE THREAD

**Issue by chengr28** [nghttp2/nghttp2#912]
Hi, I'm learning about HTTP/2 protocol and try to write a little tool to learn how HTTP/2 transmission. I downloaded the source of nghttp2 1.22.0 + squid 4.0.19 and compiled them follow the guide <https://github.com/nghttp2/nghttp2/blob/master/README.rst> in Debian 8.7.
Squid has been set to allow all transport and listen on default port `3128` and nghttpx has been set to:
```
$ nghttpx -f'*,8443;no-tls' -b127.0.0.1,3128
```

* h2c process:
    * TCP handshake
    * Me to nghttpx
        * PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n
        * SETTINGS frame [SETTINGS_MAX_CONCURRENT_STREAMS=100, SETTINGS_INITIAL_WINDOW_SIZE=65535, SETTINGS_ENABLE_PUSH=0, SETTINGS_HEADER_TABLE_SIZE=0]
        * HEADERS frame [:mehtod=CONNECT, :authority=xxx:xxx, proxy-authorization=Basic ..., +END_HEADERS]
    * nghttpx to me
        * SETTINGS frame [SETTINGS_MAX_CONCURRENT_STREAMS=100, SETTINGS_INITIAL_WINDOW_SIZE=65535]
        * SETTINGS frame [ACK to my SETTINGS frame]
        * HEADERS frame [:status=200, ..., +END_HEADERS]
    * Me to nghttpx
        * SETTINGS frame [ACK to nghttpx]
        * DATA frame [TCP proxy data ..., +END_STREAM]
    * nghttpx to me
        * DATA frame [TCP proxy data ...]
        * (May be followed a RST_STREAM frame or nothing)
    * Me to nghttpx
        * (May be followed a GOAWAY frame)
    * Shutdown connection

The h2c process works fine, but when I changed the configuration to try to enable encryption/use h2:
```
$ nghttpx -f'*,8443' -b127.0.0.1,3128 /xxx/server.key /xxx/server.crt
```
With the same data transmission stream, also I have specified TLS version to 1.2 + ALPN with `h2` enabled in the request(Cipher suite is `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384` I captured it below). However, I received an error message from nghttpx after I sent the first packet:
```
HTTP/1.1 501 Not Implemented.
```
I have captrued the packet with Wireshark `any` interface,  there is no any packets between nghttpx and squid. After that, I changed to use HTTP/1.1 CONNECT method, both cleartext and HTTPS are working good. Also I tried to add `--http2-proxy` parameter but it seems no effect, like:
```
$ nghttpx --http2-proxy -f'*,8443' -b127.0.0.1,3128 /xxx/server.key /xxx/server.crt
```
Is something wrong with this process when TLS enabled/h2?
Thanks.

**Comment by tatsuhiro-t** [comment]
--http2-proxy option is required if nghttpx is used as forward proxy (as a frontend of squid).  It changes certain behaviour of nghttpx.

From the error message, it looks like nghttpx and client do not negotiate h2. Have you checked the negotiated ALPN?  It is in ServerHello extensions, and it is visible in cleartext.

**Comment by chengr28** [comment]
Yes, ALPN seems does:
![2017-05-06-tls-alpn](https://cloud.githubusercontent.com/assets/1025140/25773780/77652c7a-32b6-11e7-9a18-44a9adec0134.png)

**Comment by chengr28** [comment]
I have upgraded OpenSSL to the latest version 1.1.0e. Also I get a warning message after running:
```
fetch-ocsp-response (using OpenSSL 1.1.0e  16 Feb 2017)
failed to extract ocsp URI from /xxx/server.crt
2017-05-07T00:09:24.585+08:00 1789 1789 xxxxxxxx WARN (shrpx_connection_handler.cc:600) ocsp query command for /xxx/server.crt failed: error=0, rstatus=ff00, status=255
```
I don't know if this is the reason, but there is no any information about OCSP in HTTP/2 RFC .

**Comment by tatsuhiro-t** [comment]
ClientHello contains ALPN, but ServerHello doesn't.  Which OpenSSL version is nghttpx linked?  To use ALPN, OpenSSL version >= 1.0.2 is required.

OCSP is TLS related stuff, and not HTTP/2.  fetch-ocsp-response script should work with the valid certificate which contains OCSP URI.  But it might not with the self signed one.  This is not related to the inability to enable h2.

**Comment by chengr28** [comment]
After I compiled nghttp2 again, it works! Nghttpx seems linked built-in OpenSSL 1.0.1 in Debian 8. There are 3 version series(1.0.1x/1.0.2x/1.1.0x) in my system and I thought that it will uses the 1.1.0x because it shows `using OpenSSL 1.1.0e 16 Feb 2017`, but it doesn't. Thanks for your help!

Also is there any ways to print the library versions which be linked in nghttp2?
