### ISSUE TITLE
OpenSSL 1.1.1 TLS v1.3 which draft supported ?

### ISSUE THREAD

**Issue by centminmod** [nghttp2/nghttp2#926]
Hi with regards to https://github.com/nghttp2/nghttp2/pull/816 which OpenSSL 1.1.0 TLS v1.3 draft is supported ? draft-18, draft-19 or draft-20 ?

thanks

**Comment by tatsuhiro-t** [comment]
It depends on which version of OpenSSL you are building with.
While I'm developing nghttp2, I only tests with OpenSSL git master, thus it is draft-20.

**Comment by centminmod** [comment]
thanks @tatsuhiro-t :)
