### ISSUE TITLE
libnghttp2_asio MSVC17

### ISSUE THREAD

**Issue by saravannah** [nghttp2/nghttp2#933]
I have just started working on this. I have few queries regarding libnghttp2_asio support in windows. Is libnghttp2_asio windows compatible or it has to be compiled in Cygwin environment only ?

"""Note that the above steps most likely produce nghttp2 library only. No bundled applications are compiled.

Notes for building on Windows (Mingw/Cygwin)

Under Mingw environment, you can only compile the library, it's libnghttp2-X.dll and libnghttp2.a.
If you want to compile the applications(h2load, nghttp, nghttpx, nghttpd), you need to use the Cygwin environment."""

**Comment by tatsuhiro-t** [comment]
I only tested libnghttp2_asio under Linux, and have no idea msvc can compile it or not.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
