### ISSUE TITLE
nghttpx.service fault to start

### ISSUE THREAD

**Issue by kalagxw** [nghttp2/nghttp2#934]
root@shrpx:/home/xxx# systemctl status nghttpx.service
● nghttpx.service - HTTP/2 proxy
   Loaded: loaded (/lib/systemd/system/nghttpx.service; linked; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Mon 2017-05-29 19:49:44 CST; 2s ago
     Docs: man:nghttpx
  Process: 1746 ExecStart=/usr/local/bin/nghttpx --conf=/etc/nghttpx/nghttpx.conf (code=exited, status=0/SUCCESS)
 Main PID: 1746 (code=exited, status=0/SUCCESS)
      CPU: 20ms

May 29 19:49:44 shrpx systemd[1]: nghttpx.service: Service hold-off time over, scheduling restart.
May 29 19:49:44 shrpx systemd[1]: Stopped HTTP/2 proxy.
May 29 19:49:44 shrpx systemd[1]: nghttpx.service: Start request repeated too quickly.
May 29 19:49:44 shrpx systemd[1]: Failed to start HTTP/2 proxy.
May 29 19:49:44 shrpx systemd[1]: nghttpx.service: Unit entered failed state.
May 29 19:49:44 shrpx systemd[1]: nghttpx.service: Failed with result 'start-limit-hit'.

==============================================================
xxx@shrpx:~$ cat /lib/systemd/system/nghttpx.service
[Unit]
Description=HTTP/2 proxy
Documentation=man:nghttpx
After=network.target

[Service]
Type=notify
ExecStart=/usr/local/bin/nghttpx --conf=/etc/nghttpx/nghttpx.conf
ExecReload=/bin/kill --signal HUP $MAINPID
KillSignal=SIGQUIT
PrivateTmp=yes
ProtectHome=yes
ProtectSystem=full
Restart=always

[Install]
WantedBy=multi-user.target

**Comment by tatsuhiro-t** [comment]
Could you provide nghttpx log?  Without that, it is hard for us to diagnose the issue.

**Comment by kalagxw** [comment]
Jul 31 18:57:04 localhost.localdomain systemd[1]: Starting HTTP/2 proxy...
Jul 31 18:57:04 localhost.localdomain nghttpx[1581]: 2017-07-31T18:57:04.171+08:00 1581 1581 bfbcc7ed NOTICE (shrpx.cc:2750) Loading configuration from /etc/nghttpx/nghttpx.conf
Jul 31 18:57:04 localhost.localdomain nghttpx[1581]: 2017-07-31T18:57:04.171+08:00 1581 1581 bfbcc7ed INFO (shrpx_config.cc:3711) Resolving backend address
Jul 31 18:57:04 localhost.localdomain nghttpx[1581]: 2017-07-31T18:57:04.171+08:00 1581 1581 bfbcc7ed INFO (shrpx_config.cc:3721) Host-path pattern: group 0: '/'
Jul 31 18:57:04 localhost.localdomain nghttpx[1581]: 2017-07-31T18:57:04.171+08:00 1581 1581 bfbcc7ed INFO (shrpx_config.cc:3724) group 0 -> 127.0.0.1:8089, proto=http/1.1
Jul 31 18:57:04 localhost.localdomain nghttpx[1581]: 2017-07-31T18:57:04.171+08:00 1581 1581 bfbcc7ed INFO (shrpx_config.cc:3740) Catch-all pattern is group 0
Jul 31 18:57:04 localhost.localdomain nghttpx[1581]: 2017-07-31T18:57:04.172+08:00 1581 1581 bfbcc7ed INFO (shrpx_config.cc:3873) Address resolution for 127.0.0.1 succeeded: 127.0.0.1
Jul 31 18:57:04 localhost.localdomain nghttpx[1581]: 2017-07-31T18:57:04.172+08:00 1581 1581 bfbcc7ed INFO (shrpx_config.cc:3790) Resolved backend address: 127.0.0.1:8089 -> 127.0.0.1:8089
Jul 31 18:57:04 localhost.localdomain nghttpx[1581]: 2017-07-31T18:57:04.172+08:00 1581 1581 bfbcc7ed NOTICE (shrpx.cc:1140) Daemonising disabled under systemd
Jul 31 18:57:04 localhost.localdomain nghttpx[1581]: 2017-07-31T18:57:04.173+08:00 1581 1581 bfbcc7ed WARN (shrpx.cc:816) bind() syscall failed: Address already in use
Jul 31 18:57:04 localhost.localdomain nghttpx[1581]: 2017-07-31T18:57:04.173+08:00 1581 1581 bfbcc7ed FATAL (shrpx.cc:844) Listening IPv4 socket failed
Jul 31 18:57:04 localhost.localdomain systemd[1]: nghttpx.service: Main process exited, code=exited, status=255/n/a
Jul 31 18:57:04 localhost.localdomain systemd[1]: Failed to start HTTP/2 proxy.
Jul 31 18:57:04 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=nghttpx comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Jul 31 18:57:04 localhost.localdomain systemd[1]: nghttpx.service: Unit entered failed state.
Jul 31 18:57:04 localhost.localdomain systemd[1]: nghttpx.service: Failed with result 'exit-code'.
Jul 31 18:57:04 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=nghttpx comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 31 18:57:04 localhost.localdomain audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=nghttpx comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 31 18:57:04 localhost.localdomain systemd[1]: nghttpx.service: Service hold-off time over, scheduling restart.
Jul 31 18:57:04 localhost.localdomain systemd[1]: Stopped HTTP/2 proxy.
Jul 31 18:57:04 localhost.localdomain systemd[1]: Starting HTTP/2 proxy...
Jul 31 18:57:04 localhost.localdomain nghttpx[1584]: 2017-07-31T18:57:04.538+08:00 1584 1584 d952f8c5 NOTICE (shrpx.cc:2750) Loading configuration from /etc/nghttpx/nghttpx.conf
Jul 31 18:57:04 localhost.localdomain nghttpx[1584]: 2017-07-31T18:57:04.538+08:00 1584 1584 d952f8c5 INFO (shrpx_config.cc:3711) Resolving backend address
Jul 31 18:57:04 localhost.localdomain nghttpx[1584]: 2017-07-31T18:57:04.538+08:00 1584 1584 d952f8c5 INFO (shrpx_config.cc:3721) Host-path pattern: group 0: '/'
Jul 31 18:57:04 localhost.localdomain nghttpx[1584]: 2017-07-31T18:57:04.538+08:00 1584 1584 d952f8c5 INFO (shrpx_config.cc:3724) group 0 -> 127.0.0.1:8089, proto=http/1.1
Jul 31 18:57:04 localhost.localdomain nghttpx[1584]: 2017-07-31T18:57:04.538+08:00 1584 1584 d952f8c5 INFO (shrpx_config.cc:3740) Catch-all pattern is group 0
Jul 31 18:57:04 localhost.localdomain nghttpx[1584]: 2017-07-31T18:57:04.538+08:00 1584 1584 d952f8c5 INFO (shrpx_config.cc:3873) Address resolution for 127.0.0.1 succeeded: 127.0.0.1
Jul 31 18:57:04 localhost.localdomain nghttpx[1584]: 2017-07-31T18:57:04.538+08:00 1584 1584 d952f8c5 INFO (shrpx_config.cc:3790) Resolved backend address: 127.0.0.1:8089 -> 127.0.0.1:8089
Jul 31 18:57:04 localhost.localdomain nghttpx[1584]: 2017-07-31T18:57:04.538+08:00 1584 1584 d952f8c5 NOTICE (shrpx.cc:1140) Daemonising disabled under systemd
Jul 31 18:57:04 localhost.localdomain nghttpx[1584]: 2017-07-31T18:57:04.538+08:00 1584 1584 d952f8c5 WARN (shrpx.cc:816) bind() syscall failed: Address already in use
Jul 31 18:57:04 localhost.localdomain nghttpx[1584]: 2017-07-31T18:57:04.538+08:00 1584 1584 d952f8c5 FATAL (shrpx.cc:844) Listening IPv4 socket failed
Jul 31 18:57:04 localhost.localdomain systemd[1]: nghttpx.service: Main process exited, code=exited, status=255/n/a
Jul 31 18:57:04 localhost.localdomain systemd[1]: Failed to start HTTP/2 proxy.
Jul 31 18:57:04 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=nghttpx comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Jul 31 18:57:04 localhost.localdomain systemd[1]: nghttpx.service: Unit entered failed state.
Jul 31 18:57:04 localhost.localdomain systemd[1]: nghttpx.service: Failed with result 'exit-code'.
Jul 31 18:57:04 localhost.localdomain systemd[1]: nghttpx.service: Service hold-off time over, scheduling restart.
Jul 31 18:57:04 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=nghttpx comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 31 18:57:04 localhost.localdomain audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=nghttpx comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 31 18:57:04 localhost.localdomain systemd[1]: Stopped HTTP/2 proxy.
Jul 31 18:57:04 localhost.localdomain systemd[1]: Starting HTTP/2 proxy...
Jul 31 18:57:04 localhost.localdomain nghttpx[1587]: 2017-07-31T18:57:04.798+08:00 1587 1587 747e818b NOTICE (shrpx.cc:2750) Loading configuration from /etc/nghttpx/nghttpx.conf
Jul 31 18:57:04 localhost.localdomain nghttpx[1587]: 2017-07-31T18:57:04.798+08:00 1587 1587 747e818b INFO (shrpx_config.cc:3711) Resolving backend address
Jul 31 18:57:04 localhost.localdomain nghttpx[1587]: 2017-07-31T18:57:04.798+08:00 1587 1587 747e818b INFO (shrpx_config.cc:3721) Host-path pattern: group 0: '/'
Jul 31 18:57:04 localhost.localdomain nghttpx[1587]: 2017-07-31T18:57:04.798+08:00 1587 1587 747e818b INFO (shrpx_config.cc:3724) group 0 -> 127.0.0.1:8089, proto=http/1.1
Jul 31 18:57:04 localhost.localdomain nghttpx[1587]: 2017-07-31T18:57:04.798+08:00 1587 1587 747e818b INFO (shrpx_config.cc:3740) Catch-all pattern is group 0
Jul 31 18:57:04 localhost.localdomain nghttpx[1587]: 2017-07-31T18:57:04.798+08:00 1587 1587 747e818b INFO (shrpx_config.cc:3873) Address resolution for 127.0.0.1 succeeded: 127.0.0.1
Jul 31 18:57:04 localhost.localdomain nghttpx[1587]: 2017-07-31T18:57:04.798+08:00 1587 1587 747e818b INFO (shrpx_config.cc:3790) Resolved backend address: 127.0.0.1:8089 -> 127.0.0.1:8089
Jul 31 18:57:04 localhost.localdomain nghttpx[1587]: 2017-07-31T18:57:04.798+08:00 1587 1587 747e818b NOTICE (shrpx.cc:1140) Daemonising disabled under systemd
Jul 31 18:57:04 localhost.localdomain nghttpx[1587]: 2017-07-31T18:57:04.798+08:00 1587 1587 747e818b WARN (shrpx.cc:816) bind() syscall failed: Address already in use
Jul 31 18:57:04 localhost.localdomain nghttpx[1587]: 2017-07-31T18:57:04.798+08:00 1587 1587 747e818b FATAL (shrpx.cc:844) Listening IPv4 socket failed
Jul 31 18:57:04 localhost.localdomain systemd[1]: nghttpx.service: Main process exited, code=exited, status=255/n/a
Jul 31 18:57:04 localhost.localdomain systemd[1]: Failed to start HTTP/2 proxy.
Jul 31 18:57:04 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=nghttpx comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Jul 31 18:57:04 localhost.localdomain systemd[1]: nghttpx.service: Unit entered failed state.
Jul 31 18:57:04 localhost.localdomain systemd[1]: nghttpx.service: Failed with result 'exit-code'.
Jul 31 18:57:05 localhost.localdomain systemd[1]: nghttpx.service: Service hold-off time over, scheduling restart.
Jul 31 18:57:05 localhost.localdomain systemd[1]: Stopped HTTP/2 proxy.
Jul 31 18:57:05 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=nghttpx comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 31 18:57:05 localhost.localdomain audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=nghttpx comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 31 18:57:05 localhost.localdomain systemd[1]: Starting HTTP/2 proxy...
Jul 31 18:57:05 localhost.localdomain nghttpx[1590]: 2017-07-31T18:57:05.042+08:00 1590 1590 cddebf51 NOTICE (shrpx.cc:2750) Loading configuration from /etc/nghttpx/nghttpx.conf
Jul 31 18:57:05 localhost.localdomain nghttpx[1590]: 2017-07-31T18:57:05.042+08:00 1590 1590 cddebf51 INFO (shrpx_config.cc:3711) Resolving backend address
Jul 31 18:57:05 localhost.localdomain nghttpx[1590]: 2017-07-31T18:57:05.042+08:00 1590 1590 cddebf51 INFO (shrpx_config.cc:3721) Host-path pattern: group 0: '/'
Jul 31 18:57:05 localhost.localdomain nghttpx[1590]: 2017-07-31T18:57:05.042+08:00 1590 1590 cddebf51 INFO (shrpx_config.cc:3724) group 0 -> 127.0.0.1:8089, proto=http/1.1
Jul 31 18:57:05 localhost.localdomain nghttpx[1590]: 2017-07-31T18:57:05.042+08:00 1590 1590 cddebf51 INFO (shrpx_config.cc:3740) Catch-all pattern is group 0
Jul 31 18:57:05 localhost.localdomain nghttpx[1590]: 2017-07-31T18:57:05.042+08:00 1590 1590 cddebf51 INFO (shrpx_config.cc:3873) Address resolution for 127.0.0.1 succeeded: 127.0.0.1
Jul 31 18:57:05 localhost.localdomain nghttpx[1590]: 2017-07-31T18:57:05.042+08:00 1590 1590 cddebf51 INFO (shrpx_config.cc:3790) Resolved backend address: 127.0.0.1:8089 -> 127.0.0.1:8089
Jul 31 18:57:05 localhost.localdomain nghttpx[1590]: 2017-07-31T18:57:05.042+08:00 1590 1590 cddebf51 NOTICE (shrpx.cc:1140) Daemonising disabled under systemd
Jul 31 18:57:05 localhost.localdomain nghttpx[1590]: 2017-07-31T18:57:05.042+08:00 1590 1590 cddebf51 WARN (shrpx.cc:816) bind() syscall failed: Address already in use
Jul 31 18:57:05 localhost.localdomain nghttpx[1590]: 2017-07-31T18:57:05.042+08:00 1590 1590 cddebf51 FATAL (shrpx.cc:844) Listening IPv4 socket failed
Jul 31 18:57:05 localhost.localdomain systemd[1]: nghttpx.service: Main process exited, code=exited, status=255/n/a
Jul 31 18:57:05 localhost.localdomain systemd[1]: Failed to start HTTP/2 proxy.
Jul 31 18:57:05 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=nghttpx comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Jul 31 18:57:05 localhost.localdomain systemd[1]: nghttpx.service: Unit entered failed state.
Jul 31 18:57:05 localhost.localdomain systemd[1]: nghttpx.service: Failed with result 'exit-code'.
Jul 31 18:57:05 localhost.localdomain systemd[1]: nghttpx.service: Service hold-off time over, scheduling restart.
Jul 31 18:57:05 localhost.localdomain systemd[1]: Stopped HTTP/2 proxy.
Jul 31 18:57:05 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=nghttpx comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 31 18:57:05 localhost.localdomain audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=nghttpx comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 31 18:57:05 localhost.localdomain systemd[1]: Starting HTTP/2 proxy...
Jul 31 18:57:05 localhost.localdomain nghttpx[1593]: 2017-07-31T18:57:05.292+08:00 1593 1593 15f43ee5 NOTICE (shrpx.cc:2750) Loading configuration from /etc/nghttpx/nghttpx.conf
Jul 31 18:57:05 localhost.localdomain nghttpx[1593]: 2017-07-31T18:57:05.292+08:00 1593 1593 15f43ee5 INFO (shrpx_config.cc:3711) Resolving backend address
Jul 31 18:57:05 localhost.localdomain nghttpx[1593]: 2017-07-31T18:57:05.292+08:00 1593 1593 15f43ee5 INFO (shrpx_config.cc:3721) Host-path pattern: group 0: '/'
Jul 31 18:57:05 localhost.localdomain nghttpx[1593]: 2017-07-31T18:57:05.292+08:00 1593 1593 15f43ee5 INFO (shrpx_config.cc:3724) group 0 -> 127.0.0.1:8089, proto=http/1.1
Jul 31 18:57:05 localhost.localdomain nghttpx[1593]: 2017-07-31T18:57:05.292+08:00 1593 1593 15f43ee5 INFO (shrpx_config.cc:3740) Catch-all pattern is group 0
Jul 31 18:57:05 localhost.localdomain nghttpx[1593]: 2017-07-31T18:57:05.292+08:00 1593 1593 15f43ee5 INFO (shrpx_config.cc:3873) Address resolution for 127.0.0.1 succeeded: 127.0.0.1
Jul 31 18:57:05 localhost.localdomain nghttpx[1593]: 2017-07-31T18:57:05.292+08:00 1593 1593 15f43ee5 INFO (shrpx_config.cc:3790) Resolved backend address: 127.0.0.1:8089 -> 127.0.0.1:8089
Jul 31 18:57:05 localhost.localdomain nghttpx[1593]: 2017-07-31T18:57:05.292+08:00 1593 1593 15f43ee5 NOTICE (shrpx.cc:1140) Daemonising disabled under systemd
Jul 31 18:57:05 localhost.localdomain nghttpx[1593]: 2017-07-31T18:57:05.292+08:00 1593 1593 15f43ee5 WARN (shrpx.cc:816) bind() syscall failed: Address already in use
Jul 31 18:57:05 localhost.localdomain nghttpx[1593]: 2017-07-31T18:57:05.292+08:00 1593 1593 15f43ee5 FATAL (shrpx.cc:844) Listening IPv4 socket failed
Jul 31 18:57:05 localhost.localdomain systemd[1]: nghttpx.service: Main process exited, code=exited, status=255/n/a
Jul 31 18:57:05 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=nghttpx comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Jul 31 18:57:05 localhost.localdomain systemd[1]: Failed to start HTTP/2 proxy.
Jul 31 18:57:05 localhost.localdomain systemd[1]: nghttpx.service: Unit entered failed state.
Jul 31 18:57:05 localhost.localdomain systemd[1]: nghttpx.service: Failed with result 'exit-code'.
Jul 31 18:57:05 localhost.localdomain systemd[1]: nghttpx.service: Service hold-off time over, scheduling restart.
Jul 31 18:57:05 localhost.localdomain systemd[1]: Stopped HTTP/2 proxy.
Jul 31 18:57:05 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=nghttpx comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 31 18:57:05 localhost.localdomain audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=nghttpx comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 31 18:57:05 localhost.localdomain systemd[1]: nghttpx.service: Start request repeated too quickly.
Jul 31 18:57:05 localhost.localdomain systemd[1]: Failed to start HTTP/2 proxy.
Jul 31 18:57:05 localhost.localdomain systemd[1]: nghttpx.service: Unit entered failed state.
Jul 31 18:57:05 localhost.localdomain systemd[1]: nghttpx.service: Failed with result 'exit-code'.

**Comment by kalagxw** [comment]
frontend=*,443
backend=localhost,8089
private-key-file=/root/.acme.sh/xxx.key
certificate-file=/root/.acme.sh/xxx/fullchain.cer
http2-proxy=yes
workers=8
no-via=yes
log-level=INFO
fastopen=3
daemon=yes

**Comment by zdzichu** [comment]
> frontend=*,9443

> WARN (shrpx.cc:816) bind() syscall failed: Address already in use

There's already something listening on port 9443. Use `ss --processes --listening 'sport = :443'` command to find out what it is.

**Comment by kalagxw** [comment]
**got somwthing wrong with the log above . it is actually the key/crt problem,i am sure the file path is right and maybe a file right issus?**
============================================
[root@localhost .acme.sh]# pwd
/root/.acme.sh
[root@localhost .acme.sh]# ll
total 172
-rw-r--r--. 1 root root    239 Jul 31 19:36 account.conf
-rwxr-xr-x. 1 root root 152415 Jul 31 16:49 acme.sh
-rw-r--r--. 1 root root     78 Jul 31 16:49 acme.sh.csh
-rw-r--r--. 1 root root     78 Jul 31 16:49 acme.sh.env
drwxr-xr-x. 3 root root     42 Jul 31 16:54 ca
drwxr-xr-x. 2 root root    247 Jul 31 16:49 deploy
drwxr-xr-x. 2 root root   4096 Jul 31 16:49 dnsapi
-rw-r--r--. 1 root root    448 Jul 31 19:36 http.header
drwxr-xr-x. 2 root root    167 Jul 31 19:36 xxxxx.org_ecc
===============================================
`ul 31 19:30:59 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=nghttpx comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 31 19:30:59 localhost.localdomain nghttpx[1465]: 2017-07-31T19:30:59.551+08:00 1465 1465 b9a520a1 NOTICE (shrpx.cc:1140) Daemonising disabled under systemd
Jul 31 19:30:59 localhost.localdomain nghttpx[1465]: 2017-07-31T19:30:59.551+08:00 1465 1465 b9a520a1 NOTICE (shrpx.cc:854) Listening on 0.0.0.0, tls
Jul 31 19:30:59 localhost.localdomain nghttpx[1465]: 2017-07-31T19:30:59.551+08:00 1465 1465 b9a520a1 NOTICE (shrpx.cc:854) Listening on [::], tls
Jul 31 19:30:59 localhost.localdomain nghttpx[1465]: 2017-07-31T19:30:59.552+08:00 1465 1465 b9a520a1 NOTICE (shrpx.cc:1297) Worker process [1466] spawned
Jul 31 19:30:59 localhost.localdomain systemd[1]: Started HTTP/2 proxy.
Jul 31 19:30:59 localhost.localdomain nghttpx[1465]: 2017-07-31T19:30:59.552+08:00 1465 1465 b9a520a1 NOTICE (shrpx_worker_process.cc:213) Renew new ticket keys
Jul 31 19:30:59 localhost.localdomain nghttpx[1465]: 2017-07-31T19:30:59.552+08:00 1465 1465 b9a520a1 INFO (shrpx_worker_process.cc:194) enc_keylen=16, hmac_keylen=32
Jul 31 19:30:59 localhost.localdomain nghttpx[1465]: 2017-07-31T19:30:59.552+08:00 1465 1465 b9a520a1 INFO (shrpx_worker_process.cc:254) ticket keys generation done
Jul 31 19:30:59 localhost.localdomain nghttpx[1465]: 2017-07-31T19:30:59.552+08:00 1465 1465 b9a520a1 INFO (shrpx_worker_process.cc:256) 0 enc+dec: 68f0ae2f7114623dae6cb2aad8e51583
Jul 31 19:30:59 localhost.localdomain nghttpx[1465]: 2017-07-31T19:30:59.565+08:00 1465 1465 b9a520a1 FATAL (shrpx_tls.cc:856) SSL_CTX_use_PrivateKey_file failed: error:02001002:system library:fopen:No such file or directory
Jul 31 19:30:59 localhost.localdomain nghttpx[1465]: 2017-07-31T19:30:59.565+08:00 1465 1465 b9a520a1 FATAL (shrpx_tls.cc:869) SSL_CTX_use_certificate_file failed: error:02001002:system library:fopen:No such file or directory
`

**Comment by tatsuhiro-t** [comment]
Make sure that paths to certificate and private key file are correctly specified in configuration file.

**Comment by kalagxw** [comment]
i am sure the key/cer file path is right cause if i run nghttpx --conf=/path/to/conf in console.
the program runs well

**Comment by kalagxw** [comment]
the certificate was genetated by acme.sh(let's encrypt shell) 
and all the  files had chown into root group

**Comment by tatsuhiro-t** [comment]
What happen if you change the permission of those files in a way that the user/group which runs nghttpx service can read them?

**Comment by kalagxw** [comment]
for example what user/group? and i will have try.
now the are in root:root and show the error above
