### ISSUE TITLE
asio client may not function properly

### ISSUE THREAD

**Issue by fifc** [nghttp2/nghttp2#936]
the typical usage of asio client is,
request = the_session.sumit(...);
request.on_response(...);
however, before on_respones(), the actual response may have already arrived and finished, and in such case, the call of on_response may crash.

can not figure out how to set on_respnse handler before submit.

**Comment by tatsuhiro-t** [comment]
Have you experienced crash with the actual code?

`submit()` just enqueues the request, and does not actually dispatch it to the remote server.
Therefore, if you call `request.on_response()` just after `submit()`, a response should not be arrived because a request is not sent.

**Comment by ustime** [comment]
if the dispatching thread is already running when you call submit, there is the possibility that an http response arrived before the call of on_response. i have make it happen by place a getchar() between submit and on_response.

**Comment by ustime** [comment]
void send_msg(const session& sess, const std::string& url, const std::string& msg) {
      boost::system::error_code ec;
      auto req = sess.submit(ec, "POST", url, msg, {{"content-type",{"application/octet-stream"}}});

      if (ec) {
        std::cerr << "error: " << ec.message() << std::endl;
        return;
      }

      printf("press enter to on_response ...\n");
      getchar();
      req->on_response([](const response &res) {
        std::cerr << "HTTP/2 " << res.status_code() << std::endl;
        for (auto &kv : res.header()) {
          std::cerr << kv.first << ": " << kv.second.value << "\n";
        }
        std::cerr << std::endl;
        res.on_data([](const uint8_t *data, std::size_t len) {
        });
      });

      req->on_close([](uint32_t error_code) {
        std::cerr << "request stream closed\n";
      });
}

**Comment by tatsuhiro-t** [comment]
So the thread which executes send_msg, and the other thread executes event loop?
I think this configuration does not work with libnghttp2_asio.
The assumption is that send_msg and event loop must be executed by the same thread.

**Comment by ustime** [comment]
but that may be a drawback of http/2 multi-stream and connection reuse

**Comment by ustime** [comment]
but that may be a drawback of http/2 multi-stream and connection reuse. and why not just use blocked io instead of event loop and callbacks in the same thread?

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
