### ISSUE TITLE
Can not activate TLSv1.0 and TLSv1.1 in nghttpx

### ISSUE THREAD

**Issue by maxwinkel** [nghttp2/nghttp2#937]
When running nghttpx, I'm not able to activate TLSv1.0 and TLSv1.1. The only active protocol is TLSv1.2.

I'm using the cmd line options

--tls-proto-list=TLSv1.0,TLSv1.1,TLSv1.2
--tls-min-proto-version=TLSv1.0
--tls-max-proto-version=TLSv1.2

and also tried using only one of proto-list/min|max-proto-version.

I'm currently running nghttpx 1.23.1 with openssl 1.1.0f, but also had the same situation with nghttpx 1.21.1 and openssl 1.0.1t and any combination of the above.

Both openssl versions support TLSv1.0 and TLSv1.1, but the handshaking with these protocols fails.

Thank you for your help!

**Comment by tatsuhiro-t** [comment]
It looks like the default cipher list does not include TLSv1.1 ciphers.
If I specify the Intermediate compatibility cipher list from https://wiki.mozilla.org/Security/Server_Side_TLS, TLSv1.1 works for me.

**Comment by tatsuhiro-t** [comment]
It might be better to set minimum TLS version to 1.2.

**Comment by maxwinkel** [comment]
> It might be better to set minimum TLS version to 1.2.

I totally agree, but unfortunately I may not just exclude all legacy browsers.

> It looks like the default cipher list does not include TLSv1.1 ciphers.

That was it. It's now running as expected. Thank you very much!

**Comment by tatsuhiro-t** [comment]
> I totally agree, but unfortunately I may not just exclude all legacy browsers.

I'd like to make default configuration consistent with TLS version and ciphers.  Currently, TLS version minimum is TLSv1.1 by default, but the cipher list does not include any ciphers compatible with that version.
It is completely fine to change these configuration for your deployments to support legacy clients.
