### ISSUE TITLE
nghttp2_session_send not calling read_callback

### ISSUE THREAD

**Issue by vgmahajanshetty** [nghttp2/nghttp2#940]
Hi Tatsuhiro,

I am implementing http2 server on reverse proxy (load balancer).

I am using 1.16.0 version of nghttp2 library and observing one strange behavior with Safari client on iphone 6s.

Please go through below sequence of events:

I'm calling:

1: nghttp2_submit_response(session, stream_id, nva, nvlen, &data_prd); to send headers and data to client

    A:    This calls "send_callback()" which is registered using nghttp2_session_callbacks_set_send_callback()
            This function will send headers.

    B:    Then on_frame_send_callback() will be invoked indicating http2 HEADERS are sent.

    C:    Then it invokes read_callback() which is set in data_prd as
            data_prd.read_callback = read_callback;

For this stream, I currently need to send 18918 bytes of data
In read_callback I am setting NGHTTP2_DATA_FLAG_NO_COPY to data_flags to avoid copying of data.
*data_flags |= NGHTTP2_DATA_FLAG_NO_COPY;

In read_callback, "length" parameter has value of 16384. Stream window is 65535 and session window is 60735.

I am calculating min_window as
min_window = min(remote_stream_window, remote_session_window);

then returning min of received "length" parameter and min_window.
return min (length, min_window);
Finally this will return 16384.

    D:        Then it will call send_data_callback() which is registered using nghttp2_session_callbacks_set_send_data_callback()

                in send_data_callback() I will send data of 16384 bytes. Then it will call on_frame_send_callback() indicating data frame is sent. Now, I have still few more bytes (2534 bytes) of data to send, so I will call nghttp2_submit_data().

    E:         Now, it will call read_callback(). This time it will return 2534 and I sent *data_flags with value of 0x07, which means NGHTTP2_DATA_FLAG_EOF, NGHTTP2_DATA_FLAG_NO_END_STREAM and NGHTTP2_DATA_FLAG_NO_COPY are set. Reason for setting NGHTTP2_DATA_FLAG_NO_END_STREAM is still this stream has to send more data as and when it receives from back end server.

    F:        Now send_data_callback() will be invoked again and I will send 2534 bytes of data now. Now, on_frame_send_callback() will be invoked indicating a data frame is sent.

2: Now, when backend server sends next chunk of data (this time it's 19200 bytes), I will call nghttp2_submit_data() followed by nghttp2_session_send()   [this time I am calling nghttp2_submit_data() since headers are already sent]. Now after calling nghttp2_session_send() I am expecting below invocations:
    a: read_callback()
    b: send_data_callback()
as it happened while sending first chunk of data (18918 bytes), in 1st step above.

but, nghttp2_session_send() is just returning 0 without calling any callbacks, and finally this session fails to send subsequent data chunks. (If I try to call nghttp2_submit_data() again it returns -529, which indicates data already submitted, not processed yet).

This behavior is happening always and it's seen only with safari browser in iphone 6s/6s plus. The same code works perfectly fine for mac book safari browser, windows 10 firefox, chrome etc.

Can you please let me know if something is wrong in the logic?

Thanks,
Vishwanath G M

**Comment by tatsuhiro-t** [comment]
I think you don't have to call nghttp2_submit_data.  If read_callback is passed to nghttp2_submit_response, nghttp2_session_send calls read_callback repeatedly if it has positive flow control window until you set NGHTTP2_DATA_FLAG_EOF.

**Comment by vgmahajanshetty** [comment]
Hi,

Thanks for your response.

In my case backend server sends chunks of data one after another. For example, if client made a request for 1MB of file, then server will send responses to load balancer in chunks of 20Kbytes every time.

So, first time http2 server of load balancer (which acts as client to the main backend server and as http2 server to the front end http2 client) receives 20KB of data from real server. Then it will prepare http2 headers; prepares an array of nghttp2_nv *nva of length "nvlen" and calls
rv = nghttp2_submit_response(session, stream_id, nva, nvlen, &data_prd);
So, this callback sends headers and 20KB of data by calling read_callback() which is supplied in data_prd above. read_callback() is called repeatedly until it sends 20KB of data (actually it calls read_callback() and send_data_callback() as I mentioned earlier).

So, while sending last data frame for this first 20KB of chunk, read_callback() will set NGHTTP2_DATA_FLAG_NO_COPY, NGHTTP2_DATA_FLAG_NO_END_STREAM and NGHTTP2_DATA_FLAG_EOF; combination of these flags will make sure it will not mark end of data in the data frame.

So, after sometime back end server will send next 20KB of data. Now I am calling nghttp2_submit_data() and nghttp2_session_send() to repeat the process, but as I mentioned nghttp2_session_send() is returning immediately without calling read_callback() and send_data_callback().

As you mentioned, I tried to avoid nghttp2_submit_data() for second 20KB of chunk by calling nghttp2_submit_response(session, stream_id, NULL, 0, &data_prd); nva and nvlen are 0 as this time I need to send only data frames (headers are already sent while sending first 20KB of data). This is resulting in submitting multiple frames of type HEADERS (which is not required as headers are already sent) with no actual headers in it and client is closing session.

IMP: The current code works fine for most of the browsers. Only safari and firefox in iphone 6s has problem, they are not loading page properly as callbacks are not being called.
[sorry for writing very lengthy explanation]

Thanks,
Vishwanath G M

**Comment by tatsuhiro-t** [comment]
The recommended use of nghttp2_submit_response is that it should be called once.  No need to call multiple times.
The key is that you should not set NGHTTP2_DATA_FLAG_NO_END_STREAM and NGHTTP2_DATA_FLAG_EOF if you expect that backend server may send more data.
If you find that there is no data to send in read_callback, but more data is expected to come from backend server, don't send any data flags. Just return NGHTTP2_ERR_DEFERRED.
This makes the library detach the stream from transmission queue, and read_callback is not called.
When you get data from backend server, call nghttp2_session_resume_data.  It is safe to call this function even if the stream is still in transmission queue.  The return value still shows error, but ignore it if the error is not NGHTTP2_ERR_NOMEM.  nghttp2_session_resume_data makes the library pushes the stream to the transmission queue again, and read_callback is called again via nghttp2_session_send.

**Comment by vgmahajanshetty** [comment]
Thank you for clarifying this. It's working fine now.
