### ISSUE TITLE
Is any support for TLS 1.3 draft 18?

### ISSUE THREAD

**Issue by yctung** [nghttp2/nghttp2#946]
I just compile nghttp2 (tls13-early-data) with the openssl master branch. It works perfectly with the openssl s_client. 

However, when I try to use some commercial browsers to connect to my nghttp2 server, TLS 1.2 is associated instead of TLS1.3.

I then notice the commercial browsers only support TLS1.3 draft 18 but the nghttp2 is using draft 20 (openssl).

Is there any way for nghttp to accept TLS1.3 draft18? something like nghttpd -**support_tls_min_draft_18** 8080 key.pem cert.pem will be super useful to my test.

BTW, is any other browser really supporting TLS1.3 draft 20 or 19? (based on my understanding, both Chrome and Firefix dev versions only have draft 18).

Is it a intended behavior that nghttp reject to associate TLS 1.3 draft 18 connections? or it is a bug?

(just curious what is the logic to have a server protocol that no browser can use it...)

Yu-Chih

**Comment by tatsuhiro-t** [comment]
OpenSSL has https://github.com/openssl/openssl/tree/tls1.3-draft-18 branch which speaks TLSv1.3 draft-18.
But currently, nghttp2 cannot be compiled with that branch because the branch is so outdated, and it does not have required functionality for TLSv1.3.

OpenSSL master branch is draft-20.  It is not compatible with draft-18.  It is a sad situation, but TLSv1.3 is not finalized yet, and if it does, it should be more like draft-20, not outdated draft-18.

**Comment by yctung** [comment]
Yeah, I noticed there is a OpenSSL draft 18 branch but (as you said) that is not compatible to nghttp2. 

I know it is not meaningful to support draft 18 now, but in such a case, how nghttp2 group knows their server implementation is correct? What client(browser) you are using to test your code? Specifically, I am working on adding the 0RTT resumption to my service, I didn't know if this function is enabled, will browser sends two separate GET requests (one in early data one in the normal SSL session) or not.

Yu-Chih

**Comment by tatsuhiro-t** [comment]
I used haskell TLSv1.3 client [1] and openssl s_client to verify that 0-RTT early data works.

[1] https://github.com/kazu-yamamoto/hs-tls/tree/tls13-20

**Comment by yctung** [comment]
Hi Tatshuiro,

Thank you for the reply. I am using Openssl s_client as well. But I notice Firefox has something special (different from s_client). For example, I noticed when my s_server didn't receive/speak early data, Firefox will send the same GET request again to make the browsing works. Anyway, I think it might still too early to know which behavior is correct because it seems the 0RTT protocol is optional and not finalized yet.

Yu-Chih
