### ISSUE TITLE
How to specify just compile the static library with cmake ?

### ISSUE THREAD

**Issue by pengweichu** [nghttp2/nghttp2#953]
I'm try to compile it with VS, first I used below command, but when I use VS open the .sln file, the project is for compile to DLL, how to specify just compile the static library only with cmake ?

`cmake .. -G "Visual Studio 14 2015 Win64" -DENABLE_ASIO_LIB=ON -DJANSSON_INCLUDE_DIR=D:\Stacks\jansson\src -DJANSSON_LIBRARY=D:\Stacks\jansson\build\lib\Release  -DZLIB_LIBRARY=D:\Stacks\lib64\release`

I've tried -DNGHTTP2_STATICLIB, but got below:

CMake Warning:
  Manually-specified variables were not used by the project:

    NGHTTP2_STATICLIB

Another question: does nghttp2_asio is support Windows(MSVC) ? I got the getopt.h and sys/un.h file can't find error.

Thanks

**Comment by svnpenn** [comment]
https://github.com/nghttp2/nghttp2/issues/1170
