### ISSUE TITLE
Patch for compile libnghttp2_asio for MSVC 15

### ISSUE THREAD

**Issue by pengweichu** [nghttp2/nghttp2#969]
I have a patch which created by my colleague for compile the libnghttp2_aiso for MSVC 15, how could I upload it ?

BR

**Comment by tatsuhiro-t** [comment]
The best way is create Pull request.
Please read https://github.com/nghttp2/nghttp2/blob/master/CONTRIBUTION and the patch author should agree on it.

**Comment by pengweichu** [comment]
Thanks, I have send the PR, plz review.

BR

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
