### ISSUE TITLE
nghttp2_asio client : getting stream id from request/response.

### ISSUE THREAD

**Issue by saravannah** [nghttp2/nghttp2#977]
I want to access stream id for each request and response
I checked asio_http2_client.h file, couldn't find much information regarding stream in that.
Snippet from examples code : 
 req->on_response([&sess](const response &res) {
        std::cerr << "HTTP/2 " << res.status_code() << std::endl;
        for (auto &kv : res.header()) {
          std::cerr << kv.first << ": " << kv.second.value << "\n";
        }
I want to get the stream id for respective headers.

**Comment by saravannah** [comment]
And also regarding session submit command with a particular stream id ?

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
