### ISSUE TITLE
nghttp2 does not set correct X-Forwarded-For when proxyproto used with ssl/sni

### ISSUE THREAD

**Issue by ademaria** [nghttp2/nghttp2#979]
Hello,

We have nghttpx to receive traffic from an upstream nginx using proxyproto.
`frontend=0.0.0.0,443;tls;proxyproto;sni-fwd`

We have added
```
add-x-forwarded-for=true
add-forwarded=for
forwarded-for=ip
```

We expect on the remote backend to find the `X-Forwarded-For` header

```
GET /endpoint
Host: XXXXXXX
Accept: */*
Content-Encoding: gzip
User-Agent: XXXXXXXXXXXXX
Accept-Language: en-gb
Accept-Encoding: gzip, deflate
Forwarded: for=10.240.52.0      <--- incorrect IP
X-Forwarded-Proto: https
Via: 2 nghttpx, 1.1 nghttpx
```

using an echo server, we get:

```
curl -v https://XXXX3/debug -k
* Hostname was NOT found in DNS cache
*   Trying XXXX...
* Connected to XXXX (XXXXX) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
[cut]
*        SSL certificate verify ok.
> GET /debug HTTP/1.1
> User-Agent: curl/7.35.0
> Host: ZZZZZZ
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 08 Aug 2017 16:32:55 GMT
< Content-Type: text/plain
< Transfer-Encoding: chunked
* Server "" is not blacklisted
< Server: ""
< Via: 1.1 nghttpx
< 
CLIENT VALUES:
client_address=127.0.0.1
command=GET
real path=/debug
query=nil
request_version=1.1
request_uri=http://XXXXX:8080/debug

SERVER VALUES:
server_version=nginx: 1.10.0 - lua: 10001

HEADERS RECEIVED:
accept=*/*
forwarded=for=10.240.33.0
x-forwarded-for=10.240.33.0  <- INCORRECT IP
host=ZZZZZZZ
user-agent=curl/7.35.0
via=1.1 nghttpx
x-forwarded-proto=https
BODY:
```

It used to work when there was no tls/sni-fwd involved
```
CLIENT VALUES:
client_address=127.0.0.1
command=GET
real path=/
query=nil
request_version=1.1
request_uri=http://XXXXXX:8080/

SERVER VALUES:
server_version=nginx: 1.10.0 - lua: 10001

HEADERS RECEIVED:
accept=*/*
host=XXXXXXXXXXXXX
user-agent=curl/7.35.0
via=1.1 nghttpx
x-forwarded-for=XXXXXXX  <- correct IP
x-forwarded-proto=http
BODY:
-no body in request-

```

**Comment by tatsuhiro-t** [comment]
I found a bug that forward header field has incorrect client IP with/without tls/sni-fwd.  But x-forwarded-for works fine.

**Comment by ademaria** [comment]
We seem to experience that, when using proxyproto:
1) the remote IP is correctly the remote client IP ($remote_ip)
2) the IP passed on as `x-forwarded-for` or `forward` header  has the incorrect IP (pod name rather than $remote_ip

possibly related to what you are fixing now.

**Comment by tatsuhiro-t** [comment]
x-forwarded-for, forwarded, and $remote_addr access log variable refer to the same value.
With #980, they should be the same.  Even without #980, x-forwarded-for, and $remote_addr should point to the same value.

**Comment by tatsuhiro-t** [comment]
Have you tried --strip-incoming-x-forwarded-for?

**Comment by ademaria** [comment]
This is not what we observed.
Yes I have tried all possible combinations. Will try 980 when you release it and will to replicate it.

**Comment by ademaria** [comment]
Thank you so much for looking into it.

**Comment by ademaria** [comment]
@tatsuhiro-t  I have found some time to replicate my issue:
I have compiled commit `788835c5fd2f60a716b6128521c9b3da458f2c13` and I am using `gcr.io/google_containers/echoserver:1.4` as backend to see what happens to the headers.


My configuration is:

```
frontend=0.0.0.0,443;tls;proxyproto;sni-fwd
backend=127.0.0.1,8080;/echo;no-tls

[cut]

tls-min-proto-version=TLSv1.2
strip-incoming-x-forwarded-for=true
strip-incoming-forwarded=true
add-x-forwarded-for=true
add-forwarded=for
forwarded-for=ip
server-name=""
```
`curl https://ZZZZZZZZ/echo`
```                                                                                                                                                                     
CLIENT VALUES:
client_address=127.0.0.1
command=GET
real path=/echo
query=nil
request_version=1.1
request_uri=http://ZZZZZZ:8080/echo

SERVER VALUES:
server_version=nginx: 1.10.0 - lua: 10001

HEADERS RECEIVED:
accept=*/*
forwarded=for=104.ZZZ.ZZZ.ZZ   <- correct IP 
host=ZZZZZZZZZZZZZZZZZZ
user-agent=curl/7.35.0
via=1.1 nghttpx
x-forwarded-proto=https
BODY:
-no body in request
```

as you can see, the x-forwarded-for header is missing. $remote_addr in the log is correct, as it is correct the forwarded=for ip

Regards
Alessandro

**Comment by tatsuhiro-t** [comment]
You should use `yes` instead of `true` in nghttpx configuration file.  `true` is evaluated as`no`, which disables XFF.
And, you don't have to use quotes in configuration file. server-name should look like this:

```
server-name=
```

This just set empty server header field instead of deleting server header field from response.

**Comment by ademaria** [comment]
That was it btw. thank you very much!
