### ISSUE TITLE
nghttp2-asio: bi-directional streams

### ISSUE THREAD

**Issue by redj3** [nghttp2/nghttp2#982]
I am writing a client program to do the following:
On receiving the data response from server(res.on_data), I want to analyse the data received from server and send some data back to server for the same stream id.
Is it possible ?

**Comment by tatsuhiro-t** [comment]
I think you can as long as you maintain stream ID relationship.  It requires the same maximum concurrent stream limit for front and backend connections.  It might requires more, but I cannot find any at the moment.

**Comment by redj3** [comment]
Sorry I understood the maximum concurrent stream limit but didn't get the part "Maintain stream ID relationship" ?

**Comment by tatsuhiro-t** [comment]
I mean that relationship of stream ID between frontend and backend connection, so in this case, they share the same number.

**Comment by redj3** [comment]
Sorry again. I want to send back data from client for the same connection(session), for the same stream received from server.  Didn't get the part "frontend and backend connection" ?

**Comment by tatsuhiro-t** [comment]
I said that because nghttp2 asio lib does not have exact feature you want.  You have to create separate sessions for frontend and backend, and maintain their relationship by yourself.

**Comment by redj3** [comment]
I am able to send bi-directional(server===client) data frames by following way
Client : 
        Using generator_cb argument in session::submit, I am able to defer by returning NGHTTP2_ERR_DEFERRED. When I got response from server,I call resume and copy the some data to buf inside generator_cb and return the total number of bytes copied and in the next cycle I make sure it returns NGHTTP2_ERR_DEFERRED again. By this way, I am able to send data frames for a stream from client to server.

Server:
     Using generator_cb in response::end, I am able to send data frames by following similar way as client.

Is there any problem in the above method?

Now the problem is that I am not able to achieve the same in PUSH PROMISE case.
I did the following similar to the above mentioned client steps
req.on_push ---> push.on_response ---> res.on_data --->push.resume.

Can you please help me out or suggest any other way w.r.t PUSH_PROMISE?

**Comment by redj3** [comment]
Hi,
      I went through the code flow little bit. Whenever a client receives a PUSH_PROMISE frame, nghttp2_session_open_stream is called with initial state as NGHTTP2_STREAM_RESERVED. In nghttp2_session_open_stream if the initial state is NGHTTP2_STREAM_RESERVED, we are are shutting down the stream by setting the flag NGHTTP2_SHUT_WR indicating the transmission is no more allowed for the stream.

As per the current implementation, I will not be able to send data from client on a push promise stream. Is my observation right?
Thanks, 
SJ.

**Comment by tatsuhiro-t** [comment]
Yes.  The reserved stream is effectively read-only for client.  It is how RFC 7540 defines server push.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
